### ISSUE TITLE
Mozilla Account icon

### ISSUE THREAD

**Issue by ai** [rafaelmardojai/firefox-gnome-theme#10]
I use Fedora 30, Firefox 67 and the latest `firefox-gnome-theme`. Mozilla account name is above the icon in the menu.

![20190704192724](https://user-images.githubusercontent.com/19343/60690008-cd1a2500-9e91-11e9-9569-75a44e6438f2.png)

(Thanks for the project, I am really happy to use it)

**Comment by rafaelmardojai** [comment]
It should be fixed.
