### ISSUE TITLE
Can no longer drag tabs to new window

### ISSUE THREAD

**Issue by ryanrms** [rafaelmardojai/firefox-gnome-theme#100]
Fedora 31
GNOME 3.34.2 Wayland session
firefox 71.0 OR firefox-wayland 71.0

Normally (without the theme) I'm able to drag a tab outside the window, and it will create a new window with the tab in it.  With the theme installed, I can only drag and drop tab order, not create new windows with it.

Workaround: Right click tab -> Move Tab -> Move to New Window

Is it possible to have both the theme and dragging and dropping for new windows?  Great theme, I really like it.

**Comment by rafaelmardojai** [comment]
I can't reproduce under X11. (Firefox 71 & Fedora 31)

**Comment by rafaelmardojai** [comment]
Looks like some upstream wayland related bug, See: https://bugzilla.mozilla.org/show_bug.cgi?id=1527976

**Comment by rafaelmardojai** [comment]
Looks like this was solved upstream.
