### ISSUE TITLE
Close/Maximize/Minimize in need of minor modification

### ISSUE THREAD

**Issue by ryanrms** [rafaelmardojai/firefox-gnome-theme#101]
In the new version of Adwaita on my system, when window decorations are in the background, they have a thin circle around them. 
![Screenshot from 2019-12-19 21-09-11](https://user-images.githubusercontent.com/2936638/71229711-e712bd00-22a3-11ea-81e9-49e8d6a4121b.png)

Looks like the theme just needs a minor tweak to the inactive styling to be in line with this new change from the GNOME team.  If you aren't prepared to update the theme quite yet because you don't see this change on  your system, would you give me a hint on how to achieve it on my system?  It will at the very least be useful for the future when you get the updated theme!

Here's how it looks now (inactive style):
![Screenshot from 2019-12-19 21-11-35](https://user-images.githubusercontent.com/2936638/71229815-3bb63800-22a4-11ea-9bd6-88ba9e912394.png)

**Comment by k-kirill** [comment]
Just removing the border around the button does not seem like a proper solution as native windows still have that round border. Moreover, on hover, one can see a square border with rounded corners.

**Comment by rafaelmardojai** [comment]
@k-kirill currently rounded title buttons are not default on this theme, you should enable `rounded-title-buttons.css`  optional-feature. See: https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features. 

Pd: soon it will be default.

**Comment by k-kirill** [comment]
Many thanks, enabling the ```rounded-title-buttons.css``` feature has solved my issue and now the Firefox header bar looks like native in Gnome :)
