### ISSUE TITLE
system-icons.css

### ISSUE THREAD

**Issue by shaneramone** [rafaelmardojai/firefox-gnome-theme#102]
@rafaelmardojai Hello, I know that system-icons.css is bugged on certain systems (mine being one of them) but I have been playing around with the papirus icon theme and have noticed that changing the system icon theme to papirus-light enables the "dark" icon theme within firefox (white icons) and changing the system theme to just regular papirus enables the "light" icon theme (black icons). The papirus-dark icon theme seems to be the middle of the road icon theme and generates a greyish icon theme in firefox which doesn't look good with either a light or dark Gtk theme.

Sorry to waffle on but my question is, can I set a specific icon theme with system-icons.css rather than having to mess with filters?

Setting the icon theme manually within firefox to papirus-light would solve my issue but I'm not sure how to do it.

**Comment by rafaelmardojai** [comment]
Sorry for late answer.

What you want is to use `system-icons.css`  with a different theme than the system one?

You could replace the icons from `firefox-gnome-theme/theme/icons/` with the papirus-light ones. This theme use the same icons name.
