### ISSUE TITLE
Firefox 72 Broke Overlay Scrollbars

### ISSUE THREAD

**Issue by 73** [rafaelmardojai/firefox-gnome-theme#103]
Since the update the scrollbar does not collapse anymore. It is always expanded, like when hovered. (Thanks for making Firefox look native, that should actually be done by a distributor, imho)

**Comment by rafaelmardojai** [comment]
Looks like the hack used it's not working any more. Nothing to do on my side.

Just wait for Mozilla to implement proper overlay scrollbars (https://bugzilla.mozilla.org/show_bug.cgi?id=1147847)

**Comment by 73** [comment]
It really did look awesome. Thanks.

**Comment by JaneSmith** [comment]
Is there any particular reason why it doesn't work anymore? Was some feature removed from Firefox that this relied on? Otherwise, wouldn't it be considered a regression in Firefox and could be reported to them as a bug?

**Comment by 73** [comment]
My understanding is, that [XBL](
https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XBL) was removed.
therefore there is no `-moz-binding` primitive to bind custom scripts to
the scrollbar, anymore. I hope I got that right.

I don't know how to make a voice heared at Mozilla, but ever since I know
how great it could look, I am hooked.

**Comment by rafaelmardojai** [comment]
@73 Correct, that's the reason.

**Comment by rafaelmardojai** [comment]
I just created a new project for scrollbars: https://github.com/rafaelmardojai/firefox-gnome-scrollbars

It requires some installation steps in Firefox installation folder, so i don't want to include it here for now.

**Comment by 73** [comment]
You Sir, just made my day!
