### ISSUE TITLE
Profile pic in Firefox Sync button too large

### ISSUE THREAD

**Issue by jurf** [rafaelmardojai/firefox-gnome-theme#104]
![obrázok](https://user-images.githubusercontent.com/7472425/73359366-fa507980-42a0-11ea-8bac-fae1670ec854.png)

As you can see, the profile pic icon is bigger than the others, and also a little bit blurry. If a custom pic is set, it’s even more visible.

**Comment by rafaelmardojai** [comment]
It's intentional, i thought `16px` was too small for an avatar.

https://github.com/rafaelmardojai/firefox-gnome-theme/blob/6a4eb9e4e49e38d3341305864085036ae4fd1ec3/theme/parts/buttons.css#L331-L341

But it's up to the users. What do you think?

**Comment by jurf** [comment]
I would be happy with a small avatar. I know my face, I don’t really like it standing out, it looks a bit out-of-place to me if it’s big. If think it’s smallish in regular Firefox too.

I added the snippet into `customChrome.css` with the size altered back to 16px and I’m happy now. :slightly_smiling_face: 

However, the thing _is_ blurry at 26px. That’s probably a bigger problem than the size.
