### ISSUE TITLE
Installation fails due to times.json

### ISSUE THREAD

**Issue by bellegarde-c** [rafaelmardojai/firefox-gnome-theme#106]
ArchLinux, installation fails because of this directory:
```
$ ls ~/.mozilla/firefox/4u6rph18.default
times.json
```

This directory is created by Firefox even after removing ~/.mozilla, it's not Firefox profile.

**Comment by rafaelmardojai** [comment]
Are you using the installation script? Try passing your Firefox profile folder with the `-p` flag.
`./scripts/install.sh -p <profile_folder>`

**Comment by bellegarde-c** [comment]
Tried but linking is broken:

![Capture d’écran du 2020-02-14 11-48-05](https://user-images.githubusercontent.com/57196916/74524722-e56e1a00-4f1f-11ea-95b3-8980c6bd2942.png)

**Comment by bellegarde-c** [comment]
Hmm, ok, due to gitbhub archive.
