### ISSUE TITLE
Sizing issues with mixed-DPI setups

### ISSUE THREAD

**Issue by fbruetting** [rafaelmardojai/firefox-gnome-theme#108]
I am on Fedora Silverblue 31 and Wayland and have a main UHD screen and an additional HD screen. There I have the following problems:

1. Sometimes the menus of the header bar don’t appear when being in full-screen on the UHD screen. When I resize the window to a smaller size and drag it around a bit, the menus work in most positions (but not in all positions).
2. Firefox doesn’t scale when dragged to another screen (UHD screen is scaled 200%). The scaling is usually set according to the screen the mouse pointer resides in, when I open Firefox (see the exceptions mentioned below).
3. Sometimes when I open Firefox on the UHD screen, it gets scaled to 400%, so that it’s effectively 200% too large.
4. Sometimes when I open Firefox on the HD screen, it gets scaled to 50%. But there, the window itself does not get scaled to that size, but instead just the upper left quadrant of the window gets used with the contents scaled to 50%, whereas the other three quadrants stay black.
5. The video player also makes strange effects when getting resized to sizes smaller than the default (larger is no problem). I made a screen cast:

[Peek 2020-02-23 23-23.zip](https://github.com/rafaelmardojai/firefox-gnome-theme/files/4242578/Peek.2020-02-23.23-23.zip)

**Comment by rafaelmardojai** [comment]
Those issues are reproducible in default Firefox?

**Comment by fbruetting** [comment]
Not at all, FF behaves nicely since they implemented the Wayland stuff some about two moths ago.

**Comment by fbruetting** [comment]
Do these CSS files somehow interfere with Firefox’s settings? After removing the `chrome` folder, I get really weird scaling issues which I have never seen since installing your scripts.

**Comment by rafaelmardojai** [comment]
Not at all, it only modify Firefox ui via the `userChrome.css` file.

The only user prefs modifications are in the `user.js` file, witch are very basic:
https://github.com/rafaelmardojai/firefox-gnome-theme/blob/56652507e0bfd15a39d68c1097dfa786f39f5f36/configuration/user.js#L1-L12

But, that file lives in the `chrome` folder.

Maybe try removing you profile cache (`~/.cache/mozilla/firefox/`). This won't erase your settings, sessions, etc.

**Comment by fbruetting** [comment]
By the way – this is how it sometimes looks when I un-maximize the window. But I also saw these effects in video programs (which seem to handle Wayland in some different manor, since they draw their surfaces by themselves or whatever). So at least it seem that something interferes with Wayland here… 🤔

![Bildschirmfoto von 2020-02-16 01-55-37](https://user-images.githubusercontent.com/10520767/74597422-8dd6c800-505f-11ea-9ac6-d35e7b5bc52a.png)

**Comment by rafaelmardojai** [comment]
I have tried but I couldn't reproduce the issues.

I only can scale my both screens to 200%.
Also i can't help with wayland related bugs, because I'm using NVIDIA drivers.

**Comment by fbruetting** [comment]
Doesn't NVidia by now work in Wayland? At least for Fedora, as far as I know.

**Comment by rafaelmardojai** [comment]
With proprietary drivers?

**Comment by fbruetting** [comment]
https://www.youtube.com/watch?v=F86egPk5-9I

**Comment by rafaelmardojai** [comment]
I will investigate, installing proprietary drivers on Fedora 31 resulted in Wayland disabled by default to me.

**Comment by fbruetting** [comment]
Here is what some windows produce (a new private window doesn’t do that, however):

[VID-20200223-WA0022.zip](https://github.com/rafaelmardojai/firefox-gnome-theme/files/4241460/VID-20200223-WA0022.zip)

**Comment by fbruetting** [comment]
While the above screen shot shows my UHD screen, here is a screen shot of full-screen-FF on my HD screen. Firefox gets scaled here to the upper-left quarter and a little bit distorted (which also some other Wayland-incapable(?) programs do). But in fact the controls are working from their theoretical places. For example when you want to click on the menu icon, you need to click on the quasi-correct spot in the black part of the window.


![](https://shelly.cloud/wp-content/uploads/2019/09/shelly_smoke_automation3.jpg)

**Comment by fbruetting** [comment]
> By the way – this is how it sometimes looks when I un-maximize the window. But I also saw these effects in video programs (which seem to handle Wayland in some different manor, since they draw their surfaces by themselves or whatever). So at least it seems that something interferes with Wayland or Mutter here… thinking
> 
> ![Bildschirmfoto von 2020-02-16 01-55-37](https://user-images.githubusercontent.com/10520767/74597422-8dd6c800-505f-11ea-9ac6-d35e7b5bc52a.png)

This has been fixed, presumably by Firefox or by Mutter/Shell.

**Comment by fbruetting** [comment]
In the meantime, all above mentioned issues got resolved. One thing however still occurs: The anchor points of all popovers of the left side are displaced, which seems to be due to the scaling factor not being considered – the popovers of the right-side headerbar buttons however are correct.

#### Left side button popovers

![Bildschirmfoto von 2020-06-12 18-48-59](https://user-images.githubusercontent.com/10520767/84527942-0c2a3a80-acdf-11ea-863e-14cd5cfee541.png)

![Bildschirmfoto von 2020-06-12 18-49-03](https://user-images.githubusercontent.com/10520767/84527958-13514880-acdf-11ea-9472-988553bd291b.png)


#### Right side button popover

![Bildschirmfoto von 2020-06-12 18-50-49](https://user-images.githubusercontent.com/10520767/84527971-18ae9300-acdf-11ea-9b1b-63caaa48b70c.png)

**Comment by rafaelmardojai** [comment]
I have been testing this and couldn't reproduce any of the issues (GNOME 47, Wayland, Fedora 41 and Firefox 133 wayland-native). If it's still reproducible feel free to re-open.
