### ISSUE TITLE
Close button is shown on the tab bar

### ISSUE THREAD

**Issue by amivaleo** [rafaelmardojai/firefox-gnome-theme#110]
Hi!

I installed this script some time ago. Everything was fine at that time. I don't usually use firefox, so I don't do much on it apart from keep it update as all other applications I have.

Lately, I've noticed that the close button is not drawn on the headerbar anymore, but on the tab bar:

![Schermata da 2020-02-14 08-48-36](https://user-images.githubusercontent.com/24316547/74511674-cfa02b00-4f06-11ea-893b-d9f4300821e3.png)

I've just reinstalled the script from anew, without success: issue is still there.

Tested on Mozilla Firefox 72.0.2, gnome-shell 3.34.3, Fedora 31.

**Comment by rafaelmardojai** [comment]
I cant reproduce the bug and I'm running the same system (FF 72.0.2, gnome-shell 3.34.3, Fedora 31).

Are you using wayland? If so try to reproduce the bug under X11.
Currently i can't help with wayland related bugs, because I'm using NVIDIA drivers.

**Comment by amivaleo** [comment]
I was in wayland before and in xorg now. I have the same issue also here.

Any hint on where I should check to spot some issue? What does your script need to run smoothly?

**Comment by rafaelmardojai** [comment]
Could you share a full screenshot of your FF? Also the tabbar looks too tall in your screenshot.

This issue remembers me to #85, but it should be fixed since [600ed1e]. Sure you are using the latest version? Checkout theme version in FF customization panel.

**Comment by amivaleo** [comment]
I've discovered that I had two profile-folders in ~/.mozilla/firefox and I reinstalled the script in wrong one...

I've deleted the "wrong one" and reinstalled che script in the other/"right" one. Now everything is fine. I guess I had an older version of the script and, hence the very same issue.

Apologies.
