### ISSUE TITLE
Can't click on entire top bar when not fullscreen

### ISSUE THREAD

**Issue by RaghavRao** [rafaelmardojai/firefox-gnome-theme#111]
After updating to the latest master, I cannot click on the address bar, the hamburger menu or any of my extensions. But I can when I am in fullscreen.

I did clear cache, restart, and reinstall the theme just as a sanity check, but no luck

**Comment by rafaelmardojai** [comment]
Firefox version?
Wayland?

**Comment by RaghavRao** [comment]
Wayland, correct

72.0.2

Fedora 31, Gnome 3.34

**Comment by rafaelmardojai** [comment]
Could you try to reproduce the issue in X11?

**Comment by RaghavRao** [comment]
Same behaviour in X11 as well.
What logs will help debug this?

**Comment by truongan** [comment]
I can confirm this error, weirdly enough checkout commit ~e9620b6 seem to be a work around.

**Comment by brandlos** [comment]
I had the same error--but only if my GNOME titlebar buttons are on the left side of the window. Choosing to have them on the right side makes the buttons clickable.

**Comment by rafaelmardojai** [comment]
Thanks @brandlos, i cat reproduce the issue setting titlebar buttons to left. Fix arriving soon.

**Comment by rafaelmardojai** [comment]
[f2d44e0] should fix the issue. Please test and confirm.

**Comment by truongan** [comment]
> [[f2d44e0](https://github.com/rafaelmardojai/firefox-gnome-theme/commit/f2d44e0d820534495761faa64a24605bf0dae363)] should fix the issue. Please test and confirm.

It's fixed for me. Nice work
