### ISSUE TITLE
Active tab hardly recognizable in dark mode

### ISSUE THREAD

**Issue by fbruetting** [rafaelmardojai/firefox-gnome-theme#112]
Could you please enhance the contrast of the active tab a bit? As you see in the screen shot, it’s not that obvious – especially if you have a large screen with a long tab bar. In reality it’s even less obvious than in this screen shot, because that’s enlarged by 200 %. ;)

![Bildschirmfoto von 2020-02-21 00-53-17](https://user-images.githubusercontent.com/10520767/74990874-c2be9280-5444-11ea-8e7d-de514a6efca8.png)

**Comment by rafaelmardojai** [comment]
Have you tried to enable the optional feature `active-tab-contrast.css`?

See https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features

**Comment by rafaelmardojai** [comment]
Duplicated of #48

**Comment by fbruetting** [comment]
Ah ok, sorry.
