### ISSUE TITLE
Displaced favorites menu

### ISSUE THREAD

**Issue by fbruetting** [rafaelmardojai/firefox-gnome-theme#114]
May happen only when the list is bigger than the screen height.

![Bildschirmfoto von 2020-02-23 15-50-57](https://user-images.githubusercontent.com/10520767/75114329-75fdd600-5655-11ea-8fdf-c7fba4e01400.png)

**Comment by rafaelmardojai** [comment]
[dda64b5] helps?

**Comment by fbruetting** [comment]
Yes!
