### ISSUE TITLE
Moving the search bar to the bottom?

### ISSUE THREAD

**Issue by fbruetting** [rafaelmardojai/firefox-gnome-theme#115]
While using your really nice theme, I sometimes noticed, that I forgot what I was about to do on some web pages (especially documentation tabs) when I was searching for some special things. After recognizing that there was an open search bar with some keywerd it reminded me of what I wanted to do. However, I often don’t notice that opened search bar immediately.

This may sound a bit silly, but if you have a bunch of documentation pages open, this can happen easily. What I noticed, is that the search bar gets easily overseen as there usually already are a bunch of bars at the top of the window – you have the headerbar, the tabs bar, the search bar, and often one or even two bars of the web page, plus sometimes cookie banners.

I think it would be helpful if the search bar could reside on the bottom of the page, because there it better reminds you what you were searching for, as you recognize the bar there immediately. And you always more directly see how many search results are found on the page, so that you also don’t digress to read larger blocks of text when you see that there are a lot of other search results, which you might check first, before going into a more-depth reading.

Guess that might also be a reason why Mozilla put the search bar at the bottom, whereas other bars like popup-blocker notifications etc. get shown at the top of the page. What do you think?

**Comment by rafaelmardojai** [comment]
You're right. 
Currently the searchbar is on top to match GNOME Web, but i think that can change for usability reasons.
