### ISSUE TITLE
GNOME right click menu on headerbar

### ISSUE THREAD

**Issue by meson11** [rafaelmardojai/firefox-gnome-theme#116]
is there a way to get to the GNOME right click headerbar with the options: minimize, maximize, ... ?
especially for the functions to pin the window in foreground or on visible workspace.

**Comment by bellegarde-c** [comment]
More a Firefox issue I guess.

**Comment by rafaelmardojai** [comment]
There is no way to archive that. No with CSS. 
You can open an issue in Firefox.
