### ISSUE TITLE
Uneven padding in urlbar dropdown entries

### ISSUE THREAD

**Issue by afraidofmusic** [rafaelmardojai/firefox-gnome-theme#118]
![Screenshot from 2020-02-29 21-39-10](https://user-images.githubusercontent.com/25895258/75613330-4f500b80-5b3d-11ea-90db-349c7a3e35a3.png)
Can be seen in the screenshot above. Entries aren't centered and bookmark star nearly touches the edge.

**Comment by rafaelmardojai** [comment]
How it looks with latest commit?

**Comment by afraidofmusic** [comment]
![Screenshot from 2020-03-01 06-40-36](https://user-images.githubusercontent.com/25895258/75619050-a975be80-5b87-11ea-86b9-2123062ec531.png)
Fixed. thanks.
