### ISSUE TITLE
Input bar style in Adwaita-dark

### ISSUE THREAD

**Issue by afraidofmusic** [rafaelmardojai/firefox-gnome-theme#119]
The input bar in the dark variety is different than the light variety
![Screenshot from 2020-03-09 18-13-25](https://user-images.githubusercontent.com/25895258/76228403-c0747a80-6231-11ea-9b89-9ed3125cb607.png)
![Screenshot from 2020-03-09 17-38-37](https://user-images.githubusercontent.com/25895258/76225865-265f0300-622e-11ea-9a5a-9756f676af85.png)
![Screenshot from 2020-03-09 17-40-30](https://user-images.githubusercontent.com/25895258/76226003-4ee6fd00-622e-11ea-9785-aab0cc795f30.png)

**Comment by rafaelmardojai** [comment]
I finally got to work on this. Fixed.
