### ISSUE TITLE
New tab page not dark

### ISSUE THREAD

**Issue by jurf** [rafaelmardojai/firefox-gnome-theme#120]
When changing my theme to Adwaita-dark, the whole browser follows suit, including settings, sidebar, etc., except for the new tab page, which continues to be light. Changing the browser theme to dark fixes it, but also changes colours of other elements.

Fedora 31/Firefox 74 (Wayland)

**Comment by rafaelmardojai** [comment]
This theme currently don't provide a `userContent.css` file, so there is no browser pages theming.

This is an upstream issue, see: https://bugzilla.mozilla.org/show_bug.cgi?id=1546540

**Comment by ByteEnable** [comment]
I created a firefox theme for this very reason.  Was difficult because the FF theme builder makes no reference to new tab background colors but it is available.  I had to go digging in the FF source code to find it.
https://addons.mozilla.org/en-US/firefox/addon/adwaita-dark-new-tab-fixed/

**Comment by rafaelmardojai** [comment]
Looks like this was fixed upstream.
