### ISSUE TITLE
Suggestion: Nicer-looking high contrast active tab

### ISSUE THREAD

**Issue by smichel17** [rafaelmardojai/firefox-gnome-theme#121]
I'm silly and made my own high-contrast active tab style before I realized there already was one. Obviously style is subjective, but I think mine is less jarring, while retaining similar contrast levels. So, I figured I'd share this and you can do whatever you'd like with it :)

The main difference is that I adjusted the background color less, and increased the size of the bottom border instead (3px -> 5px). The main reason this helps is that in dark-themed Firefox, the web page below the tab is often white, which causes the underline to get lost in the contrast with the dark tabs. This isn't a problem in gnome, because the whole application obeys the system theme.

I would have sent a PR directly, but I made it in the hacky, just-modify-the-general-styles way, and don't want to wrestle with the selectors any further because, well, it works for a personal tweak and it's not hard to rebase when needed.

Here's the diff: https://github.com/smichel17/firefox-gnome-theme/commit/158ebbef2f35e81c4f0bd586fa21d8e7430c1ff5?diff=unified

**Comment by rafaelmardojai** [comment]
I have included your suggestions to `active-tab-contrast.css`. How it looks now?

**Comment by smichel17** [comment]
Looks good to me!
