### ISSUE TITLE
Incognito window icon bugged

### ISSUE THREAD

**Issue by eh8** [rafaelmardojai/firefox-gnome-theme#123]
![image](https://user-images.githubusercontent.com/22990581/78810161-fd996d00-7995-11ea-8565-4d0c1236b15e.png)

**Comment by rafaelmardojai** [comment]
Looks fine to me, can you elaborate more?

**Comment by eh8** [comment]
![image](https://user-images.githubusercontent.com/22990581/78844459-d06baf80-79d3-11ea-9738-808333182a5a.png)

Was this icon placement intentional?

**Comment by rafaelmardojai** [comment]
Yeah, inspired by GNOME Web (Epiphany) incognito window.

**Comment by eh8** [comment]
Oh! I see now. That makes sense.

My Epiphany incognito looks quite strange now that I see it:

![image](https://user-images.githubusercontent.com/22990581/78846021-67d30180-79d8-11ea-8dca-cb0159e12a3f.png)
