### ISSUE TITLE
Firefox 75 breaks the URL bar of firefox-gnome-theme

### ISSUE THREAD

**Issue by JaneSmith** [rafaelmardojai/firefox-gnome-theme#128]
Firefox 75 changed the look of the URL bar when focused, and so it breaks firefox-gnome-theme.

As a temporary workaround, in `about:config` the key `browser.urlbar.update1` can be set to `false` to change it back to the old look, which is compatible with firefox-gnome-theme. I suppose the theme should be updated to support it though.

**Comment by rafaelmardojai** [comment]
This theme supports the new URL bar since it came to FF nightly. I'm running FF 75 with `browser.urlbar.update1` enabled and all looks fine.

Can you share a screenshot?

**Comment by JaneSmith** [comment]
My apologies for wasting your time. It appears that I was being stupid and still using an older version of the theme.
