### ISSUE TITLE
Switch to dark theme

### ISSUE THREAD

**Issue by ghost** [rafaelmardojai/firefox-gnome-theme#130]
The installation goes completely fine but the theme is in light mode. How can one switch it to dark mode shown on the picture?

**Comment by rafaelmardojai** [comment]
Theme variant changes based in your system theme.
But soon it will be possible to force dark/light variant using the theme preference present in the Firefox customization panel.

**Comment by PitcherTear22** [comment]
It is possible now, close this?

**Comment by parzivalsevenfivesixnine** [comment]
> Theme variant changes based in your system theme.
> But soon it will be possible to force dark/light variant using the theme preference present in the Firefox customization panel.

My system theme is dark but the installation installs light theme anyway. Any way I can either force dark mode or do it manually? It drives me kinda crazy as all of my other applications have dark mode and I work mostly at night so my eyes than hurt.

**Comment by PitcherTear22** [comment]
Add `@import theme/colors/dark.css` to `userChrome.css`.

**Comment by rafaelmardojai** [comment]
> Add @import theme/colors/dark.css to userChrome.css.

That will not work. That file is already imported by theme. The issue is that all is behind the `prefers-color-scheme: dark` media query. And for some reason Firefox isn't detecting @parzivalsevenfivesixnine dark theme.

I fix would be to copy the root variables part from `theme/colors/dark.css` to `userChrome.css`.

```css
:root {
	/* contents */
}
```

**Comment by rafaelmardojai** [comment]
@parzivalsevenfivesixnine Could you give me info about your setup? 

I have a similar issue with Firefox Flatpak, but it should work fine with host installations.

**Comment by rafaelmardojai** [comment]
There's some discussion upstream about making `prefers-color-scheme` respect the built-in Firefox themes. So we could use Firefox light/dark theme to manually choose theme variant.

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1529323
