### ISSUE TITLE
Emulate Gnome Web (Epiphany) behavior in small screens.

### ISSUE THREAD

**Issue by mgueji** [rafaelmardojai/firefox-gnome-theme#131]
In Gnome Web when the screens width is to small, the top(title) bar splits in two, leaving in the top just the url bar and the menu button and in the bottom of the screens makes a new bar with all the other buttons including a button that shows the number off tabs open with a contextual menu when you click on it.
I was wondering if this is possible to do in Firefox, I've been trying doing it by my own but it's far away from my programing skills.
With this, the theme will be really useful in mobile devices in portrait mode, the ones that support running Firefox (Librem 5 and Pinephone for example)

**Comment by rafaelmardojai** [comment]
It's an impossible task to do with just CSS, due to how Firefox UI is structured.

Pd: For your use case Epiphany is not enough?

**Comment by mgueji** [comment]
Gnome Web lacks from some fearures like extensions support, I will try to make the theme a bit more friendly for small screens.
Thanks for the reply.
