### ISSUE TITLE
Active Firefox window has a different color

### ISSUE THREAD

**Issue by rthery** [rafaelmardojai/firefox-gnome-theme#132]
In Gnome, the highlight for a selected window is only done on the buttons of the header bar, but with this Firefox theme, it seems to be applied to the whole header bar, making it much darker than it's supposed to be (and harder for the eyes with my theme)

For reference, I'm using Pop!_OS 20.04 with its default dark theme.

Here's an example, the right window is the currently active one:
![Screenshot from 2020-05-02 11-08-21](https://user-images.githubusercontent.com/430971/80860174-580cad00-8c66-11ea-9119-0ac7eb0f4048.png)

Is there a way to fix this ? If anyone can point me to the direction to what to look for and modify, I can probably do some some tests and a PR if I'm successful :)

**Comment by rafaelmardojai** [comment]
I don't get it, it's how is supposed to look. There's only a few small  GNOME 3.36 changes that i have to update. 

Here's an example of how looks GNOME Web active & inactive windows: 
![](https://user-images.githubusercontent.com/6210397/80873385-c27d1780-8c7d-11ea-9351-81d2f08cd0ca.png)
![](https://user-images.githubusercontent.com/6210397/80873382-bd1fcd00-8c7d-11ea-980f-718519f909b3.png)

Remember this theme is designed to follow latest GNOME Adwaita style.
I think Pop! OS theme is something based in Materia. So maybe this fork will work for you: https://github.com/MattKercher/firefox-materia-theme/.

**Comment by rthery** [comment]
Ah I see, thank you I'll try that Materia theme!
