### ISSUE TITLE
Support firefox colour themes

### ISSUE THREAD

**Issue by p00f** [rafaelmardojai/firefox-gnome-theme#134]
I love how this theme fits perfectly into GNOME.

Materialfox supports using colours from firefox colour themes like [dracula](https://addons.mozilla.org/en-US/firefox/addon/dracula-dark-colorscheme/) using a [helper extension](https://addons.mozilla.org/en-US/firefox/addon/materialfox-helper/), is it possible with this theme?

**Comment by rafaelmardojai** [comment]
Out of scope, this the is focused on GNOME Adwaita style. So no plan to support this for now.
