### ISSUE TITLE
Autocomplete popup is not themed

### ISSUE THREAD

**Issue by PitcherTear22** [rafaelmardojai/firefox-gnome-theme#135]
Title

![Screenshot from 2020-05-07 12-17-18](https://user-images.githubusercontent.com/36493671/81263289-08125980-905d-11ea-82c6-30aeaafd134d.png)

**Comment by PitcherTear22** [comment]
This dialog too
![Screenshot from 2020-05-07 12-28-16](https://user-images.githubusercontent.com/36493671/81264073-73106000-905e-11ea-9187-1259e3b53f12.png)

**Comment by rafaelmardojai** [comment]
I have added experimental theming support for JS prompt dialogs.

I have tried to mimic GtkMessageDialog:
![](https://user-images.githubusercontent.com/6210397/81845128-bb73c600-9515-11ea-8180-4de9a1f70158.png)

Please, test latest commits.

**Comment by folknor** [comment]
JS popup looks great!
![firefox-gnome-theme-popup](https://user-images.githubusercontent.com/233791/81855504-f6deb680-954e-11ea-8568-f1b99fcacbd4.jpg)

Here's how the URL bar popup looks using latest commits and firefox nightly for me
![firefox-gnome-theme-urlbar](https://user-images.githubusercontent.com/233791/81855507-f7774d00-954e-11ea-915f-a6aa363c1048.jpg)

**Comment by rafaelmardojai** [comment]
> Here's how the URL bar popup looks using latest commits and firefox nightly for me

@folknor I have not tested this theme lately in nightly. Please open a new issue, for me to remember check that.

**Comment by PitcherTear22** [comment]
Working perfectly!

![Screenshot from 2020-05-14 06-19-13](https://user-images.githubusercontent.com/36493671/81880316-df351b80-95aa-11ea-9550-c87997ee5367.png)
![Screenshot from 2020-05-14 06-19-05](https://user-images.githubusercontent.com/36493671/81880322-e0664880-95aa-11ea-80dd-944e7cab0b8d.png)
