### ISSUE TITLE
URL bar dropdown looks weird in Firefox Nightly

### ISSUE THREAD

**Issue by folknor** [rafaelmardojai/firefox-gnome-theme#138]
![81855507-f7774d00-954e-11ea-915f-a6aa363c1048](https://user-images.githubusercontent.com/233791/81897491-443a4280-95a6-11ea-9302-3fb9fba9171d.jpg)

I've ran nightly builds of Gecko browsers since long before Firefox existed, so I haven't tested your theme on any other kind of build. Please let me know if you want me to test on release/beta/dev! :-)

Thank you!

**Comment by rafaelmardojai** [comment]
I also used to ran nightly, but recently i just switch to release Flatpak.

Until i check this, I think you can restore the old URL bar with `browser.urlbar.update1`.

**Comment by rafaelmardojai** [comment]
I also used to run nightly, but recently i just switch to release Flatpak.

Until i check this, I think you can restore the old URL bar with `browser.urlbar.update1`.

**Comment by gsurkov** [comment]
I'm having the same issue on recently released Firefox 77.

**Comment by rafaelmardojai** [comment]
I'm having connection issues. So i haven't updated to 77 yet.

**Comment by NettoHikari** [comment]
> Until i check this, I think you can restore the old URL bar with `browser.urlbar.update1`.

There are some keys beginning with `browser.urlbar.update1`. Which one has to be toggled or is it necessary to create one?
![grafik](https://user-images.githubusercontent.com/8510368/83677582-e78dde80-a5cb-11ea-9c02-4f03dbf59ee4.png)

**Comment by rafaelmardojai** [comment]
> There are some keys beginning with browser.urlbar.update1. Which one has to be toggled or is it necessary to create one?

Looks like that pref isn't available any more.

**Comment by vredesbyyrd** [comment]
This helped get me everything right again. 

https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/urlbar_full_width.css

Had to remove:

```
#urlbar{
  /*position: static !important;
```
