### ISSUE TITLE
Dragging the headerbar buttons doesn't drag the window

### ISSUE THREAD

**Issue by ravila4** [rafaelmardojai/firefox-gnome-theme#14]
I don't know if this can be implemented in the theme, but in GNOME applications, click+dragging a button in the headerbar drags the window, thus providing a larger draggable area. With this theme, if Firefox has a small window, the UI elements pack closely together, and the draggable area becomes quite small.

**Comment by rafaelmardojai** [comment]
Fixed, if it introduces some bug let me know to revert.

**Comment by ravila4** [comment]
Thanks for the quick reply. It's working well, just the refresh button and the hamburger menu buttons have different behaviour.

**Comment by rafaelmardojai** [comment]
Now is working better, i think.

**Comment by rafaelmardojai** [comment]
Since [758a896] this feature is disabled by default.
https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features
