### ISSUE TITLE
Some icons are black on dark background

### ISSUE THREAD

**Issue by fbruetting** [rafaelmardojai/firefox-gnome-theme#142]
In the time of the last weeks, icons went dark-on-dark. However, this does not affect all icons:

![Bildschirmfoto von 2020-06-10 19-00-22](https://user-images.githubusercontent.com/10520767/84296889-fb49bf80-ab4c-11ea-9085-422500c3665c.png)

**Comment by snydox** [comment]
I got the same problem when I updated the theme. So I tried reinstalling it from scratch and I got the same problem. But after enabling: svg.context-properties.content.enabled it worked :)
