### ISSUE TITLE
one new tab showing.

### ISSUE THREAD

**Issue by Duckfeld-McJimmers** [rafaelmardojai/firefox-gnome-theme#143]
Hi, i am not sure if this is an issue, but I noticed that it used to hide the tab when there were only which I really liked. Now it doesnt hide anymore for some odd reason.
![Screenshot from 2020-06-10 21-12-17](https://user-images.githubusercontent.com/62215800/84344299-3f45c000-ab5f-11ea-85d6-52a4e8f5acc1.png)

**Comment by rafaelmardojai** [comment]
You should enable the optional feature following: https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features.

Also you can create a new boolean pref in `about:config` named `gnomeTheme.hideSingleTab`. (initial implementation of #137)

**Comment by Duckfeld-McJimmers** [comment]
Oh thank you very much! :D Last time I installed it my brother helped so I forgot to add in the the -g
