### ISSUE TITLE
make an AUR package

### ISSUE THREAD

**Issue by barfin** [rafaelmardojai/firefox-gnome-theme#146]

**Comment by ispanos** [comment]
Is that even possible?

**Comment by rafaelmardojai** [comment]
You can do the same as the Manjaro community fork.

https://gitlab.manjaro.org/packages/community/themes/firefox-gnome-theme-maia
https://gitlab.manjaro.org/Chrysostomus/firefox-gnome-theme-maia

But personally I don't have time nor interest.
