### ISSUE TITLE
Bookmarks and history sidebar text is unreadable in dark theme

### ISSUE THREAD

**Issue by ravila4** [rafaelmardojai/firefox-gnome-theme#15]
In dark theme, the background of the bookmarks sidebar is white, and text is unreadable:

![Screenshot from 2019-07-06 10-05-49](https://user-images.githubusercontent.com/9020496/60757529-06f64300-9fda-11e9-9266-b18b9f2c8da5.png)

**Comment by skewty** [comment]
My Firefox didn't seem to use my current gnome theme colors after switching to this; I had to manually set dark theme.  Perhaps these two issues are related.

**Comment by rafaelmardojai** [comment]
@skewty there is no way to know if host theme is dark or light.

**Comment by skewty** [comment]
But can you not just use the theme colors?
If the theme is light, it will have a light background and dark text.
If the theme is dark, it will have a dark background and light text.
As long as you refer to the theme colors you should be able to avoid color contrast issues.

**Comment by skewty** [comment]
Firefox, in default theme mode, will use whatever theme colors I have set in Gnome.  When you set either Firefox's built-in light or dark themes, you are overriding the gnome theme.  And if I change my theme, Firefox might be "out of sync".  Also the Firefox dark theme colors often do not match your gnome theme :)

**Comment by skewty** [comment]
Any chance you can improve the contrast of the current selected tab?

**Comment by rafaelmardojai** [comment]
@skewty about colors choices i'm following Adwaita ones.

**Comment by rafaelmardojai** [comment]
@skewty if i rely again in Firefox default theme colors, you will need too set theme variant manually.
