### ISSUE TITLE
Publish on addons.mozilla.org

### ISSUE THREAD

**Issue by afranke** [rafaelmardojai/firefox-gnome-theme#152]
Awesome work, but the installation instructions are too much of a hassle for a regular user. Please publish the theme on the Firefox theme website so it can be easily installed.

**Comment by rafaelmardojai** [comment]
This level of customization is non possible with current Firefox theming API. 
Theme makes use of `userChrome.css` "legacy" file. So there's no user friendly way to install it.

The easiest way to install is using the script.
