### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by lionirdeadman** [rafaelmardojai/firefox-gnome-theme#153]
With Firefox 79 (Flatpak), the search is detached and just completely broken. It's probably easy to reproduce but I'll give more information if needed.

**Comment by rafaelmardojai** [comment]
URL bar search? I can't see any search related element broken.

**Comment by lionirdeadman** [comment]
![Screenshot from 2020-08-06 13-54-09](https://user-images.githubusercontent.com/39467792/89565349-6b429200-d7ec-11ea-9198-2167bb3c7cab.png)

Here's what the broken element is.

**Comment by rafaelmardojai** [comment]
Sure you're using latest theme version? I'm also running Firefox 79 Flatpak

![Captura de pantalla de 2020-08-06 12-56-57](https://user-images.githubusercontent.com/6210397/89565580-5feb6880-d7e4-11ea-9158-b2764c3a1baf.png)

**Comment by lionirdeadman** [comment]
Yes, I just installed it from master before reporting. Maybe this is related to me taking the `-g` option?

**Comment by rafaelmardojai** [comment]
Latest install script only enables `hide-single-tab.css` with `-g` option. If you have `matching-autocomplete-width.css` enabled for some reason (on `userChrome.css ` or `customChrome.css`)  you should disabled it. It's FF 68 only and might cause incompatibilities.

**Comment by lionirdeadman** [comment]
It was enabled. Disabling however didn't fix the problem. Maybe this is Wayland related somehow?

**Comment by rafaelmardojai** [comment]
Looking your screenshot. In latest theme version the private window headerbar is tinted purple.

**Comment by lionirdeadman** [comment]
Okay, that is *very weird*. It appears that the script installed an old version of the theme? Maybe I already had it installed and the script didn't update?

**Comment by rafaelmardojai** [comment]
The script installs the theme files relative to its location. Easiest way to update is running `git pull origin master` from `yourfirefoxprofile/chorme/firefox-gnome-theme` as documented on [README](https://github.com/rafaelmardojai/firefox-gnome-theme#updating) .

**Comment by lionirdeadman** [comment]
Yeah, I know. I guess I just forgot I installed it at some point in time. Closing now.
