### ISSUE TITLE
Can't enable dark mode on flatpak Firefox 79

### ISSUE THREAD

**Issue by n0bra1n3r** [rafaelmardojai/firefox-gnome-theme#155]
Thank you for this beautiful theme.

I followed the instructions in the README for flatpak (`./scripts/install.sh -f ~/.var/app/org.mozilla.firefox/.mozilla/firefox/<profile-name>`), but it doesn't use the dark colors when I set a dark theme in `Firefox Menu > Customize > Themes > Dark`. I'm on Manjaro 20.1. Is there a way to enable dark colors for this setup?

**Comment by nikkehtine** [comment]
I'm on Firefox from Flatpak and dark theme didn't want to work for me. Uninstalling the Adwaita-dark theme on Flatpak and then installing it again fixed it. Just in case someone has a similar problem.
