### ISSUE TITLE
[wayland] Drop-down sections in address bar don't display

### ISSUE THREAD

**Issue by Dreamsorcerer** [rafaelmardojai/firefox-gnome-theme#156]
Most of the buttons in the address bar don't display anything when clicked. This includes the shield and padlock buttons on the left, plus Firefox recommendations and other extensions on the right (but, the bookmark button does work).

I'm running on Ubuntu 20.04 with Wayland.

**Comment by rafaelmardojai** [comment]
Firefox version? I can't reproduce with current stable `Firefox 80` (Fedora/Xorg). 

Can you reproduce with vanilla Firefox? (without the theme installed)

**Comment by Dreamsorcerer** [comment]
Yep, current 80.0.1. I'll try some different options tomorrow in order to confirm when it happens.

**Comment by Dreamsorcerer** [comment]
Definitely Wayland related. I only get the issue when running `MOZ_ENABLE_WAYLAND=1 firefox`.
No problems when disabling the theme.

**Comment by rafaelmardojai** [comment]
Probably related to #92.

Could you edit `theme/gnome-theme.css` in your installation and comment/remove this line where popups theming is imported, and see what happens?
https://github.com/rafaelmardojai/firefox-gnome-theme/blob/d56e1613d039a2b773549e495fcd205043088fca/theme/gnome-theme.css#L9

**Comment by Dreamsorcerer** [comment]
Actually, I disabled fractional scaling, and now they're back. So, maybe it's something with fractional scaling on Wayland...?
Fractional scaling was causing some other issues as well, so I'd say it's probably more a problem with that experimental feature. I'm just going to leave it disabled.

**Comment by rafaelmardojai** [comment]
Yeah, might be. #108 also describe other issues related to Wayland scaling.

**Comment by Dreamsorcerer** [comment]
Let's close in favour of that issue then.

**Comment by Dreamsorcerer** [comment]
Spoke too soon. Still getting the problem.
It seems that it depends which website I'm looking at, as to whether it's broken or not. This Github page, everything is working fine. But, this page the pops up break (except for the padlock this time): https://my.account.sony.com/central/signin/#/global_error?entry=ca

**Comment by Dreamsorcerer** [comment]
Removing the popups.css you mentioned does fix the problem.

**Comment by rafaelmardojai** [comment]
Could you now restore it and comment/remove from line 47 to 68?

https://github.com/rafaelmardojai/firefox-gnome-theme/blob/d56e1613d039a2b773549e495fcd205043088fca/theme/parts/popups.css#L47-L68

**Comment by Dreamsorcerer** [comment]
Seems that the transparent line is causing the issue: https://github.com/rafaelmardojai/firefox-gnome-theme/blob/master/theme/parts/popups.css#L53

Though, I have no idea why it only happens on some sites. Once that Sony website has finished loading, if I then try to open the popups, most are broken.

**Comment by rafaelmardojai** [comment]
Yeah, is very weird.

If you change the line to `background: var(--gnome-popover-background) !important;` the issue persist?

**Comment by Dreamsorcerer** [comment]
I was wrong about the transparent line. It just moved the issue around..
That last line you mentioned didn't change it either.
Seems that it's breaking with: `box-shadow: var(--gnome-popover-shadow) !important;`
I've removed that line, and checked 3 times to be sure, and it seems the popups are all working with it gone.

**Comment by rafaelmardojai** [comment]
Yeah, I think you got it. Is not the first time that shadow cause issues, but I thought it only could create artifacts.
