### ISSUE TITLE
Bold tab label

### ISSUE THREAD

**Issue by 73** [rafaelmardojai/firefox-gnome-theme#158]
It seem there is some inconsistency when it comes to tab labels font weight.
All apps except Firefox have bold tab labels. I found it was changed in #150.
I am on Ubuntu 20.04 and therefore gnome-shell 3.36.4 and GTK 3.24.20:

![image](https://user-images.githubusercontent.com/529346/94774131-84fff000-03bd-11eb-8df6-643a9238a26c.png)

It is unclear to me where this inconsistency originates from.

**Comment by rafaelmardojai** [comment]
I think it's a change in GTK `3.24.21`. I haven't update my system in a while, so I'm also still seeing bold tab labels.

**Comment by 73** [comment]
I see. Then I will will wait for my next distribution upgrade. I would like to propose to make these changes optional in the future (since all logic for optional features is already implemented) and ease them out by changing the default some time later.
