### ISSUE TITLE
Title bar close icon incosistent with pop os

### ISSUE THREAD

**Issue by dyegoaurelio** [rafaelmardojai/firefox-gnome-theme#164]
I'm really liking this extension, but the close button is inconsistent with my ui
![Captura de tela de 2020-10-22 22-31-02](https://user-images.githubusercontent.com/42411160/96946320-679edd00-14b6-11eb-897e-3e197dd6e340.png)
![Captura de tela de 2020-10-22 22-30-42](https://user-images.githubusercontent.com/42411160/96946328-6a99cd80-14b6-11eb-836c-b064b18e0b8f.png)
I was trying to figure out how to fix that on the css files and then create a theme using this option, so it can be choosed on the installer

**Comment by perin-lionshead** [comment]
Hi, 

Any progress with making a pop theme css file? If not, I can take a crack at it sometime soon! It would be great to have a pop theme for sure!

**Comment by dyegoaurelio** [comment]
Hello @perin-lionshead as a metter of fact I've just starting to working on this right now
And I could use some help.

- To change the colors we could simply create a new theme on theme/colors , simply changing the blue variables to orange

- To change the close button Im no so sure but I'm trying to do something like this https://github.com/rafaelmardojai/firefox-gnome-theme/issues/159#issuecomment-706721041](https://github.com/rafaelmardojai/firefox-gnome-theme/issues/159#issuecomment-706721041

**Comment by perin-lionshead** [comment]
@dyegoaurelio great! I was just tinkering with it myself as well, though I have to run out for a bit in a few minutes! When I get home I can work on it more! I am also a tad unclear on how to change the close button, but I will look at #159. What would be of most help to you? Should I focus on the colors or the close button? Or maybe I should focus on one ui element like tabs and then you don't have to do all the elements?

**Comment by dyegoaurelio** [comment]
I'm currently working on the window button, so if you could focus the colors would be better

**Comment by rafaelmardojai** [comment]
I had been working on using the system title buttons instead of the current hardcoded. 

The main issue is the spacing needed by the title buttons in the headerbar, since they vary between themes. The solution could be to have a variable for the spacing, so each theme can change it.

**Comment by rafaelmardojai** [comment]
But my main concern is that Firefox "native" title buttons are from a regular title bar and look inconsistent compared with the GtkHeaderbar ones.

**Comment by dyegoaurelio** [comment]
I'm only having trouble adjusting the overlay circle position 
![image](https://user-images.githubusercontent.com/42411160/99194128-4e5b1a80-275c-11eb-96ef-5df871362c04.png)

**Comment by rafaelmardojai** [comment]
Do you think is better to hardcode the title button styles for each theme?

Any way, I think a variable for the spacing is still useful, since it might vary when more buttons are enabled.

**Comment by dyegoaurelio** [comment]
I'm not sure, currently I'm enabling this as a optional feature. If we succeed on porting this feature seamless then I don't think there's need to hard code the buttons on themes.

**Comment by perin-lionshead** [comment]
Alright, I'm back and will work on colors! I am focusing on the dark theme for now, but can do the light later as well!
