### ISSUE TITLE
Rounded corners, when tiled

### ISSUE THREAD

**Issue by maymage** [rafaelmardojai/firefox-gnome-theme#167]
Hi, 

first thanks for this wonderful theme, which makes me almost forget, that firefox is not a gnome app :)

So I recently noticed, that firefox  with your theme applied has still rounded corners, when tiled

![Tiled_Firefox](https://user-images.githubusercontent.com/36572014/97089159-3fd68300-1636-11eb-9d0a-0f2831ec501e.png)

but that's neither gnomey nor the case, when running firefox without your theme.

**Comment by rafaelmardojai** [comment]
Just noticed that now exists the `gtktiledwindow` attribute. Fixing now!

**Comment by rafaelmardojai** [comment]
Should be fixed now in master.

**Comment by maymage** [comment]
I confirm, fixed!
