### ISSUE TITLE
Gap in Tab bar:  screen  border   <-->  left most tab

### ISSUE THREAD

**Issue by maymage** [rafaelmardojai/firefox-gnome-theme#169]
Hi, 

maybe a picture says it all..

![Firefox_Tab_Space](https://user-images.githubusercontent.com/36572014/97676595-29468680-1a91-11eb-9f2a-62ab69f9e9ef.png)

**Comment by maymage** [comment]
Also between tabs.. this is however less visible, but still is, when hovering over a tab next to the active one. Again, a pic..

![Gap_Between_Tabs](https://user-images.githubusercontent.com/36572014/97676925-b12c9080-1a91-11eb-84d9-0c352d3d1e97.png)

**Comment by rafaelmardojai** [comment]
That's the way GNOME tabs looks like.

**Comment by maymage** [comment]
Strange, I've never noticed before..
