### ISSUE TITLE
Browser shadow slightly visible on second screen when in fullscreen

### ISSUE THREAD

**Issue by christianfl** [rafaelmardojai/firefox-gnome-theme#17]
I'm using two monitors. When using Firefox in fullscreen the shadow of the browser is slightly visible on the second monitor. I have the "Hide Single Tabs" option enabled if that's important.

**Comment by rafaelmardojai** [comment]
Can you provide some screnshot? 
It don't happens with regular Firefox?

**Comment by christianfl** [comment]
In fact, it does still happen without your extension. Seems I just didn't recognise it in beforehand.
