### ISSUE TITLE
Faint corners on window using Wayland

### ISSUE THREAD

**Issue by shoveln** [rafaelmardojai/firefox-gnome-theme#171]
OS: `Fedora 33`
Firefox: `82.0.3`
Firefox Gnome: `v82`

With `layers.acceleration.force-enabled` set to true, there are faint corners on the Firefox window, but not native GTK3 applications.

![Screenshot from 2020-11-11 02-55-08](https://user-images.githubusercontent.com/58153076/98790909-ef974900-23c9-11eb-92de-d3ad759eb162.png)
This is a zoomed in view of the corner on Nautlius.

![Screenshot from 2020-11-11 02-54-56](https://user-images.githubusercontent.com/58153076/98790939-faea7480-23c9-11eb-8f7b-25f222dbf3aa.png)
This is a zoomed in view of the corner on Firefox.

![Screenshot from 2020-11-11 03-01-49](https://user-images.githubusercontent.com/58153076/98791209-50bf1c80-23ca-11eb-95f7-e385d12dc45e.png)
Using the Adwaita light theme, the corner appears more visible.

**Comment by rafaelmardojai** [comment]
Can you reproduce this without the theme?

**Comment by shoveln** [comment]
I can actually. Sorry for not troubleshooting this more thoroughly before posting the issue.
