### ISSUE TITLE
Support for Manjaro colors?

### ISSUE THREAD

**Issue by Chrysostomus** [rafaelmardojai/firefox-gnome-theme#172]
I noticed that yaru colorscheme has been added to this repo. I have been maintaining a fork of this firefox theme for Manjaro, with the only difference being changing the blues to greens. Would you be open to adding also the manjaro colorscheme here, as I would much prefer packaging the code from upstream?

**Comment by rafaelmardojai** [comment]
Yeah, I'm fine with new color schemes, so feel free to send a PR!
