### ISSUE TITLE
Issue dump 2

### ISSUE THREAD

**Issue by lionirdeadman** [rafaelmardojai/firefox-gnome-theme#18]
- [x] Sign/Account item in the hamburger menu is off-set when not logged in resulting in a blank space.
- [x] Container tab colors are no longer lines but instead circles
- [x] List all tabs has space on the left of the volume icon
- [x] Library and other items use black items on dark backgrounds
- [x] Broken back button functionality due to #14 (It normally can be dragged to show back history)
- [x] Block element item (From ublock origin) in context menu has more spacing than other items

I'll post screenshots if you need

**Comment by rafaelmardojai** [comment]
I think no screenshots needed.

About point 2, i have styled container identity colors as circles searching for a more "gnomish" way of it.  But i'm not really sure. Do you have a better way or just revert and keep it as a line?

About point 5, you can also right-click or long-press-click to show history. Or do you think that is enough to revert #14 fix?

**Comment by lionirdeadman** [comment]
>About point 2, i have styled container identity colors as circles searching for a more "gnomish" way of it. But i'm not really sure. Do you have a better way or just revert and keep it as a line?

I think lines looked more cohesive. Perhaps they could be moved to the bottom but then identication of which is being shown could be a little bit more confusing. (Although one could argue that the highlighted tab already does that job making it somewhat redundant)

>About point 5, you can also right-click or long-press-click to show history. Or do you think that is enough to revert #14 fix?

Yeah, you can but it's still breaking functionality, if possible, it could be made an exception for that specific button?

**Comment by rafaelmardojai** [comment]
Can you provide me a screenshot of "Library and other items use black items on dark backgrounds"?

**Comment by lionirdeadman** [comment]
The back buttons are black
![Screenshot from 2019-07-07 00-28-03](https://user-images.githubusercontent.com/39467792/60764006-73ab2500-a04e-11e9-8a50-f8739b7a8e97.png)

**Comment by rafaelmardojai** [comment]
I can't reproduce this "Sign/Account item in the hamburger menu is off-set when not logged in resulting in a blank space.", please provide a screenshot.

**Comment by lionirdeadman** [comment]
![Screenshot-20190707233013-1280x1024](https://user-images.githubusercontent.com/39467792/60781161-38bcf600-a10f-11e9-8fed-df4334a01bea.png)

**Comment by rafaelmardojai** [comment]
Please test last commit.

**Comment by lionirdeadman** [comment]
All of my issues seem to be fixed, closing. Thanks :tada:
