### ISSUE TITLE
Misaligned tab title

### ISSUE THREAD

**Issue by SeaDve** [rafaelmardojai/firefox-gnome-theme#182]
The title is aligned to the left instead of the center. Clicking the tab temporarily fixes it.

![1606626052760-min](https://user-images.githubusercontent.com/64297935/100533870-2384c200-3244-11eb-9112-390974f2abd6.gif)

**Comment by rafaelmardojai** [comment]
Mmh, I think I have seen that bug. But I don't remember why I couldn't fix it.

**Comment by rafaelmardojai** [comment]
Is this still reproducible? Tabs code has changed a lot, so probably it got fixed.

**Comment by SeaDve** [comment]
I haven't seen it for a long time. Or maybe I did, but didn't noticed
