### ISSUE TITLE
Install script won't work if a profile has a space in its name

### ISSUE THREAD

**Issue by furtarball** [rafaelmardojai/firefox-gnome-theme#185]
For example, if the name is abcdef.Default User, it treats "abcdef.Default" and "User" as separate directories, which obviously will not work. I'm sure this happens because of how bash creates arrays by splitting strings using spaces as delimiters – scripts/install.sh, line 76:
`PROFILES_PATHS=($(grep -E "^Path=" "${PROFILES_FILE}" | cut -d "=" -f2-))`
The command in parentheses returns:
```
abcdef.User One
ghijkl.User Two
```
and $PROFILES_PATHS gets created as a four-element array: 0. abcdef.User, 1. One, 2. ghijkl.User, 3. Two.
I've already tried enclosing every line of that output in quotation marks or escaping spaces using sed, but bash doesn't seem to care.
I hope this detailed explanation helped, because personally I'm out of ideas.

**Comment by rafaelmardojai** [comment]
@dyegoaurelio I think you worked on this part of the script, any ideas?

**Comment by dyegoaurelio** [comment]
I dint expect that having space on profile names was a possibility

**Comment by dyegoaurelio** [comment]
working with shell can be annoying but I came up with a solution, I'll make a pr later

**Comment by dyegoaurelio** [comment]
@furtarball check if its working for you now

**Comment by furtarball** [comment]
@dyegoaurelio It still doesn't. If the profile name is "abcdef.Default User", it only tries to write to "abcdef.Default", completely forgetting about the "User" part.

> I dint expect that having space on profile names was a possibility

The name it proposes when creating a new one contains a space.

**Comment by dyegoaurelio** [comment]
Now the only problem is actually with the ```grep``` command
it is breaking when find a space
we just need to tinker with it a bit to get **all lines** containing ```PATH=``` even if have spaces

**Comment by dyegoaurelio** [comment]
which is here
https://github.com/dyegoaurelio/firefox-gnome-theme/blob/e3abc56393b6bb897430f20076b1750d0df25b1c/scripts/install.sh#L76

**Comment by furtarball** [comment]
Still does the same thing for me.

**Comment by dyegoaurelio** [comment]
You need to clone my fork and checkout to curl-improvement, which is the PR I'm pushing these changes 
(#178)

Then if you add this bellow line 76 from installation script
`
PROFILES_PATHS='Path=abcdef.User OnePath=ghijkl.User Two'
`
You'll be able to see that, as mentioned above, the script is processing correctly the paths.
We only need to grep including spaces.

**Comment by furtarball** [comment]
> You need to clone my fork and checkout to curl-improvement

I did exactly this.
> Then if you add this bellow line 76 from installation script […]

That's right! But the script still refuses to work with what it reads from profiles.ini. I removed everything from ~/.mozilla/firefox, ran firefox -p, created a new profile called Default User, yet still –
```
Profiles file found
Installing Theme on i73oszqf.Default
```

**Comment by dyegoaurelio** [comment]
Fixed `grep` command
It's working now :)

**Comment by furtarball** [comment]
Ok, your fix works, thank you!
