### ISSUE TITLE
Blurry icons on CSD

### ISSUE THREAD

**Issue by shoveln** [rafaelmardojai/firefox-gnome-theme#186]
After a clean installation of Pop!_OS, the icons on the CSD bar appear blurry and the navigation buttons are very faded. Re-installing the theme and clearing the cache in `.cache/mozilla/firefox` didn't resolve it. 

Screenshots at 200% zoom:
![Screenshot from 2020-12-16 22-19-23](https://user-images.githubusercontent.com/58153076/102443654-e151d380-3fec-11eb-9c0b-b24c029ccaba.png)

![Screenshot from 2020-12-16 22-19-46](https://user-images.githubusercontent.com/58153076/102443657-e2830080-3fec-11eb-96cb-09469d6b48a9.png)

The effect is more noticeable at 100% zoom: 
![Screenshot from 2020-12-16 22-21-44](https://user-images.githubusercontent.com/58153076/102443747-1827e980-3fed-11eb-9d7b-98a6dd759acf.png)

**Comment by rafaelmardojai** [comment]
Do you have `svg.context-properties.content.enabled` set to `true` in `about:config`?

**Comment by shoveln** [comment]
I did, but toggling it off didn't seem to change anything.

**Comment by rafaelmardojai** [comment]
You need that preference set to `true` to get the bundled SVG icons working. 

But looking your screenshots, looks like you're using the **System icons** optional feature, witch has an [known color issue](https://github.com/rafaelmardojai/firefox-gnome-theme#icons-color-broken-with-system-icons).

**Comment by shoveln** [comment]
I can confirm that setting system icons to `false` fixed the issue. I saw the known bug on the Readme, but assumed since the icons weren't just discolored that it was a different issue. Thanks for the help troubleshooting!
