### ISSUE TITLE
Search dropdown visual bug when it doesn't fit the screen

### ISSUE THREAD

**Issue by SeaDve** [rafaelmardojai/firefox-gnome-theme#188]
It applies to both normal and private window.

![image](https://user-images.githubusercontent.com/64297935/104168329-dc8c0e00-5438-11eb-9d71-98ca45e344d5.png)

The pin icon looks broken (it stays on the same location even scrolling), and maybe the scrollbar too?

**Comment by charlestsai1995** [comment]
I think a temporary fix would be to just increase the height of the result bar.
