### ISSUE TITLE
can't move new tab button in customization mode

### ISSUE THREAD

**Issue by fikrillah** [rafaelmardojai/firefox-gnome-theme#189]
let's cut to the case,

i want to make the new tab button placed next to home button like this:

![Cuplikan layar dari 2021-01-11 22-37-12](https://user-images.githubusercontent.com/48489341/104202849-03107000-545e-11eb-9075-6d2b8c17cf6f.png)

but when i try to move the button in customization mode, i can't move the new tab button because it's behind the overflow popup. like this:

![Cuplikan layar dari 2021-01-11 22-35-25](https://user-images.githubusercontent.com/48489341/104203203-74e8b980-545e-11eb-9128-268288c16a4f.png)

it  would be nice if i can drag the new tab button to my desired place after the theme is applied. because the only way to get the result like the first screenshot is to to move the new tab button before applying the theme...

thanks for awesome theme btw

**Comment by rafaelmardojai** [comment]
It's fixed in `master` since November, see [e9bbd4b4694c0706b007945436ed92ec2c7613e4].
