### ISSUE TITLE
Findbar searchbox's text isn't vertically aligned at the center

### ISSUE THREAD

**Issue by ubluish** [rafaelmardojai/firefox-gnome-theme#19]
Findbar searchbox's text isn't vertically aligned at the center
![Untitled](https://user-images.githubusercontent.com/21042432/60764193-429a1700-a085-11e9-855a-6d5525a3c747.png)

**Comment by ai** [comment]
I can confirm this on Fedora 30 (Russian locale, but I believe it doesn't depends on locale)
