### ISSUE TITLE
Manual instructions unclear and installer fails

### ISSUE THREAD

**Issue by StrangeRanger** [rafaelmardojai/firefox-gnome-theme#190]
I find the manual install instructions to be quite unclear. And when I install everything using the installer, I get this error `failed, lease check Firefox installation, unable to find profile.ini at`. `~/.mozilla/firefox` doesn't exist by default nor does the installer create it. Was this not designed to work on macOS?

**Comment by rafaelmardojai** [comment]
The script default paths are from linux, you need to find where your Firefox profiles are stored and pass it to the script using the `-f` flag.

You can find you profile folder going to `about:support` in Firefox, then in the _Application Basics_ table you need to find the _Profile Directory_ row and click _Open Directory_, then go to the upper directory witch is the Firefox data folder.

Then pass the path to the script:

```sh
./scripts/install.sh -f firefox/datadir/path
```
