### ISSUE TITLE
Dropdowns are truncated...

### ISSUE THREAD

**Issue by ghost** [rafaelmardojai/firefox-gnome-theme#195]
I have attached a screenshot of multi-account containers. I have a few more containers that are not shown and are inaccessible. The same happens with bitwarden.

![Screenshot from 2021-02-06 09-32-24](https://user-images.githubusercontent.com/5037324/107113369-d6822500-685e-11eb-9613-7c220e818cd5.png)

**Comment by juxuanu** [comment]
Similarly, the three dots button menu's contents get truncated on the right side.

![imatge](https://user-images.githubusercontent.com/24759034/114025198-2b4d1680-9875-11eb-83c0-76247b5481af.png)

**Comment by rafaelmardojai** [comment]
Popups max height were removed since b72aa1fe318d852565c1264a3e852236c16a3bd5.
