### ISSUE TITLE
html background is dark in extensions

### ISSUE THREAD

**Issue by 414owen** [rafaelmardojai/firefox-gnome-theme#198]
The unwritten rule is that web pages start off with a white background. This has been broken in firefox-gnome-theme, leading to some extensions looking like this...
![example](https://user-images.githubusercontent.com/1714287/107778018-79451280-6d3b-11eb-8a91-decb4a15a495.jpeg)

Don't get me wrong, I would love for have all my extensions to have dark backgrounds, however the problem here is that, as far as I know, there's no way for an extension to detect it that has a dark background. Unless I'm mistaken, even `getComputedStyle(document.documentElement).backgroundColor` will return `transparent`.

Maybe at some point pages will be able to opt-in to a vendor stylesheet that's adapted to `prefers-color-scheme`, but until then, would anyone mind if I fix this?

**Comment by rafaelmardojai** [comment]
Yeah, looks like something that we need to fix. 

If you can contribute, it will be very welcome, because I might take a while to fix this.
