### ISSUE TITLE
Improvements/Issues dump

### ISSUE THREAD

**Issue by lionirdeadman** [rafaelmardojai/firefox-gnome-theme#2]
Broken : 
- [x] Add Bookmark buttons look broken
- [x] Add Search engine option from address bar looks broken
- [ ] ~Extensions like feeds use dark font on dark backgrounds~
- [x] Volume button too close to X button
- [x] Bookmark animation is broken
- [x] Dropdown selected tab with blue line gets obscured when hovering

Improvements : 
- [ ] ~Scrollbar theming (it's not dark on dark mode and doesn't act like GTK programs)~
- [x] Find view could be changed to be more similar to Epiphany's and other gnome programs
- [x] Results Not connected to URL bar and no limit to height like Epiphany has
- [x] Certificate information theming
- [x] Permission request buttons theming
- [x] Download overview theming

I didn't create an issue for each since I thought it'd be be too much

**Comment by rafaelmardojai** [comment]
@lionirdeadman Thanks for reporting this. 
Broken stuff will be fixed this days.

Theming for FF popovers like download, site information, permission request, extension install, etc will come soon.
Scrollbar theming was tricky and more to mimic GNOME overlay scrolling, but i will try to fix it.

With *"Results Not connected to URL bar and no limit to height like Epiphany has"* do you mean what `matching-autocomplete-width.css` does?
With *"Find view"* do you mean the Find in page feature?

**Comment by lionirdeadman** [comment]
>With "Results Not connected to URL bar and no limit to height like Epiphany has" do you mean what matching-autocomplete-width.css does?

Yes, I use it but unfortunately if you added more search results (using browser.urlbar.maxRichResults) to replicate what Epiphany offers, then it just goes down and never stops to make it scrollable like Epiphany. Also, it aligns perfect with tabs in the theme while Epiphany doesn't have that small gap in between.

> With "Find view" do you mean the Find in page feature?
Yeah.

**Comment by rafaelmardojai** [comment]
What value do you have set in `browser.urlbar.maxRichResults`?

**Comment by lionirdeadman** [comment]
I have it set to an (absurd) 50. I'm unsure how many results Epiphany has.

**Comment by rafaelmardojai** [comment]
Try last commit. I added a max-height and scrollbar.

**Comment by lionirdeadman** [comment]
I would make that `30vh` instead of 80 is closer to what Epiphany has. Also, is it possible to move the view when the selected item is out of view? :thinking: 

Volume button issue isn't fixed unless you've not commited the change :p

**Comment by rafaelmardojai** [comment]
Please, check list progress and test latest commits. 
I'm moving Scrollbar theming to a new issue due to implementation difficulties.

**Comment by lionirdeadman** [comment]
> Find view could be changed to be more similar to Epiphany's and other gnome programs

Actually, I meant if it were up and centered although, the padding is nice.

And you didn't say if it were possible to move the view to the selected item in the address results, it'd be quite useful.

The other things though, yup, nicely done.

**Comment by rafaelmardojai** [comment]
> Actually, I meant if it were up and centered although, the padding is nice.

I centered it, but introduced some issues with the matches label, i will try something later.

> And you didn't say if it were possible to move the view to the selected item in the address results, it'd be quite useful.

Looks like it's not possible. Firefox don't expect scrolling there, so can be an upstream bug. No way to fix it with CSS.

**Comment by lionirdeadman** [comment]
>Looks like it's not possible. Firefox don't expect scrolling there, so can be an upstream bug. No way to fix it with CSS.

Yeah, makes sense, I'll open a bug then.

**Comment by rafaelmardojai** [comment]
@lionirdeadman Findbar is up and centered. Check last commit.

**Comment by lionirdeadman** [comment]
The count seems to be gone now and perhaps the "highlight all", "match Case" and such could be moved to the right? Otherwise, nice.

**Comment by rafaelmardojai** [comment]
Checkout last commit. ;)

**Comment by lionirdeadman** [comment]
Looks pretty good :ok_hand:

**Comment by rafaelmardojai** [comment]
Can you send me the link to install feeds extension?

**Comment by lionirdeadman** [comment]
There : https://addons.mozilla.org/en-US/firefox/addon/feed-preview/

Although, I'm sure applications which use the same mechanism are also affected.

**Comment by lionirdeadman** [comment]
It seems now that Feeds always shows as active with a white font. :thinking:

**Comment by rafaelmardojai** [comment]
Can you attach screenshot?

**Comment by lionirdeadman** [comment]
This is how it shows even though there's no feeds available, usually it had a slightly darker font.
![Screenshot-20190613130748-1280x1024](https://user-images.githubusercontent.com/39467792/59453073-1b7d5c00-8ddd-11e9-8c45-82aee6961e6c.png)

This is the original problem which happens when it can find a feed.
![Screenshot-20190613130825-1280x1024](https://user-images.githubusercontent.com/39467792/59453080-1e784c80-8ddd-11e9-9410-9a862855568f.png)

**Comment by rafaelmardojai** [comment]
Disabled button bug fixed.

Looks like Feeds don't implements regular Firefox popover. I can't get how it behaves. 
I'm going to install other extensions to test.

**Comment by rafaelmardojai** [comment]
I'm closing this issue. Main improvements/issues were implemented and fixed.
