### ISSUE TITLE
Unstyled DRM pop-up

### ISSUE THREAD

**Issue by kurogetsusai** [rafaelmardojai/firefox-gnome-theme#202]
Some web apps like Spotify use DRM in Firefox and then a DRM icon appears in the URL bar. It should also have a hover effect but it doesn't and when you click it, a pop up appears, but it looks pretty weird with the "Learn more" link on top of the text. It's pretty rare to see that part of the UI, so I'm guessing just no one noticed it before. A relatively easy way to reproduce it is to make a Spotify account and open Spotify's web player.

![2021-02-20 11:23:34](https://user-images.githubusercontent.com/9076473/108594249-c3984600-7370-11eb-9558-87bf18e9bb67.png)

P.S.
It's really nice to see you still keeping this project alive! :D I just came back to Firefox and started using this theme again. A lot of pleasant changes since I left. Good job! I'm sorry for disappearing and leaving you alone with this project. It's nice to see you again, Rafael!

**Comment by rafaelmardojai** [comment]
Those notification popups are hard to debug 😅, could you test the last commit?

> It's really nice to see you still keeping this project alive! :D I just came back to Firefox and started using this theme again. A lot of pleasant changes since I left. Good job! I'm sorry for disappearing and leaving you alone with this project. It's nice to see you again, Rafael!

I thought something happened to you, nice to see you around again!
