### ISSUE TITLE
Mysterious bar in fullscreen mode with Hide single tab

### ISSUE THREAD

**Issue by kurogetsusai** [rafaelmardojai/firefox-gnome-theme#203]
An empty bar appears under the header bar in fullscreen mode. It actually has 3 invisible icons on the right side. I'm assuming it might be some window controls that's normally in fullscreened Firefox? The bar only appears if "Hide single tab" is enabled.

Steps to reproduce:
1. Enable "Hide single tab" with `gnomeTheme.hideSingleTab`.
2. Open a window with just one tab.
3. Go to some website.
4. Press F11 to go to fullscreen.
5. Press Control-K to focus the URL bar while still in fullscreen mode.
6. ???
7. A mysterious seemingly empty bar appears.

![2021-02-20 11:24:55](https://user-images.githubusercontent.com/9076473/108594768-c9435b00-7373-11eb-9eac-39c38d0b2bbc.png)

**Comment by rafaelmardojai** [comment]
Mmmh, I can't reproduce.

It could be the window controls in the menu bar.
