### ISSUE TITLE
Yaru setting just looks like Adwaita

### ISSUE THREAD

**Issue by jmaris** [rafaelmardojai/firefox-gnome-theme#206]
Hi,

I tried the Yaru setting but it looks exactly like adwaita, on further analysis i found the yaru-dark.css and yaru-light.css files to be identical to the dark.css and light.css files.

Is something wrong on my side ?

**Comment by rafaelmardojai** [comment]
The Yaru theme currently only changes the accent colors.

**Comment by dap39** [comment]
It will be great to have a Yaru theme as it is in Nautilus:
![imagen](https://user-images.githubusercontent.com/18262487/117337742-082a7c80-ae9e-11eb-854a-69a7bb9cae4b.png)

**Comment by carlocastoldi** [comment]
Now, in firefox 93, changing
```
@import "colors/light.css";
@import "colors/dark.css";
```
to
```
@import "colors/light-yaru.css";
@import "colors/dark-yaru.css";
```
is buggy. I'm afraid this color scheme is outdated :\
![immagine](https://user-images.githubusercontent.com/34198340/136695004-416e536d-0c92-439a-a08d-6f0a42ff29fb.png)
