### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by maymage** [rafaelmardojai/firefox-gnome-theme#207]
Hi, 

so GNOME is moving towards rounded corners, see e.g. latest fractal, nautilus, geary

![bbb](https://user-images.githubusercontent.com/36572014/110100798-1b887100-7da3-11eb-884a-3f9cb13c6c59.png)

Of course some apps are still in the wood, e.g. settings, and some .. cough.. undermaintained .. cough .. still have sharp corners, e.g. totem.

Since I use Firefox with this theme daily, it would be nice, if it had rounded corners at the bottom too!

**Comment by kdwk** [comment]
Maybe this can help: https://github.com/owozsh/adwaita-rounded

It is a CSS file to make Gtk3 windows' corners rounded without using the proper Libhandy method. Could be used as a workaround until Gtk4 and libadwaita

**Comment by jannuary** [comment]
> Maybe this can help: https://github.com/owozsh/adwaita-rounded

First of all, that isn't as much of a fix but a bodge, since GTK3 doesn't clip the content when you round corners.

Secondly, that isn't particularly relevant to Firefox since it appears broken and glitchy even with that CSS tweak.

I've been able to tweak the border radius and take this screenshot, but moving the window causes visual glitches and I suspect there isn't much we can do about that without reaching upstream.
![image](https://user-images.githubusercontent.com/27908024/114386702-c585c500-9bbb-11eb-9320-9fcf7523869a.png)

**Comment by MichalLebeda** [comment]
@jannuary Moving window causes glitches anyway. Just try stock FF theme and check top corners when moving

**Comment by rafaelmardojai** [comment]
@jannuary Did you implement it directly with `userChrome.css`? In that case maybe we can add it as an optional feature.

**Comment by jannuary** [comment]
I suppose in the meantime, you can use [mutter-rounded](https://aur.archlinux.org/packages/mutter-rounded/) from the AUR to do this: 
![image](https://user-images.githubusercontent.com/27908024/134798402-1044aa5d-b58b-4914-a347-dcb5c317e813.png)

**Comment by jannuary** [comment]
Been playing with this today, and apparently widget.wayland.opaque-region.enabled = false removes the weird artefacting (exaggerated border-radius for illustration)

![Kooha-12-20-2021-15-45-30](https://user-images.githubusercontent.com/27908024/146738455-61ad84cf-e8cd-4b5e-95ab-02e62d75c3fa.gif)

**Comment by jannuary** [comment]
> Been playing with this today, and apparently widget.wayland.opaque-region.enabled = false removes the weird artefacting (exaggerated border-radius for illustration)

Hm, no, it's still janky - the actual window border isn't rounded

**Comment by Rend0e** [comment]
there's a gnome extension for rounded corners now: https://github.com/yilozt/rounded-window-corners

**Comment by AbrarSL** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1850827
Upstream work on rounded corners.

**Comment by juxuanu** [comment]
For reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1850827

**Comment by rafaelmardojai** [comment]
Upstream now has rounded bottom corners and the mentioned issue with the theme has been fixed in the `nightly` branch.
