### ISSUE TITLE
Close X wanders over Hamburger Menu

### ISSUE THREAD

**Issue by maymage** [rafaelmardojai/firefox-gnome-theme#208]
Hi, 

when the width of firefox becomes small, then the Close(X) moves over the Hamburger Menu.. 
But it's the only Header Bar element, which behaves badly.

See the screenshots below with such a situation (1) with a focus on the problem (2)

---

(1)

![ccc](https://user-images.githubusercontent.com/36572014/110101994-86867780-7da4-11eb-8144-5e9ffe42c48e.png)

---

(2)

![eee](https://user-images.githubusercontent.com/36572014/110102026-8dad8580-7da4-11eb-99b7-cc902689a29b.png)

**Comment by rafaelmardojai** [comment]
Thanks for reporting, this is a duplicated of #133.
