### ISSUE TITLE
Missing optoin to enable/disable colored URL bar in private browsing

### ISSUE THREAD

**Issue by johnfactotum** [rafaelmardojai/firefox-gnome-theme#21]
The option is referenced here: https://github.com/rafaelmardojai/firefox-gnome-theme/blob/9c4b43b72ba0ea121c0e45ad153d0ce7bd4634d4/userChrome.css#L13

The "next feature" referenced here was "Replace the private browsing indicator with a colored URL bar", but is currently missing.

**Comment by rafaelmardojai** [comment]
I will fix that line. Colored URL bar in private browsing is enable by default.

**Comment by johnfactotum** [comment]
Will you provide an option to disable it? Personally I find the colored URL bar a bit distracting. Or perhaps change it to something more subtle?

**Comment by rafaelmardojai** [comment]
GNOME Web use some blue on headerbar elements in private browsing, we can go that way.

**Comment by rafaelmardojai** [comment]
I have implemented an icon on headerbar background as private browsing indicator. Looks good to you?

![Captura de pantalla de 2019-07-08 12-22-02](https://user-images.githubusercontent.com/6210397/60829676-0a750000-a17b-11e9-91f4-291f0c7c6167.png)

**Comment by lionirdeadman** [comment]
This only appears in blank spaces and doesn't work when it has a small width as a result.

Is it possible to make it go through buttons and the search bar but with more transparency? This is what Epiphany does.

**Comment by rafaelmardojai** [comment]
I know, but that was the only way i find to put it there.
Let me look for a better implementation...

**Comment by rafaelmardojai** [comment]
Epiphany can do it right, because it has a static amount of buttons in headerbar.

**Comment by rafaelmardojai** [comment]
I can try to prevent it to hide when is on small width.
But, how many users running this theme are not using flex items on the sides of urlbar?
