### ISSUE TITLE
Use New Gtk Tabs

### ISSUE THREAD

**Issue by kdwk** [rafaelmardojai/firefox-gnome-theme#210]
https://blogs.gnome.org/alexm/2021/03/13/reinventing-tabs/

Gnome has reworked tabs and the latest Gnome Web on Gnome 40 has them. Since this theme aims to recreate the Gnome Web aesthetic on Firefox, it should follow this change.

**Comment by rafaelmardojai** [comment]
There's a WIP going on, see #200

**Comment by kdwk** [comment]
Got it

**Comment by rafaelmardojai** [comment]
The new tabs are now in the `beta` branch.

**Comment by jannuary** [comment]
This probably should be closed since it is merged into mainline now.
