### ISSUE TITLE
Change where the bookmarks bar appears

### ISSUE THREAD

**Issue by frandavid100** [rafaelmardojai/firefox-gnome-theme#211]
Hi,

When you open a new tab, the bookmarks bar appears on top of the tab list. Which in turn makes the tab list move up and down when you change tabs:

https://user-images.githubusercontent.com/694794/112871595-af5a0e00-90bf-11eb-9542-390754488c65.mp4

Could the bookmarks bar appear under the tabs list instead?

Thanks!

**Comment by rafaelmardojai** [comment]
This was reverted in [c98880eadaeed3cc9f2596b07a29bb0cf1a76e37]. Please use the `gnomeTheme.bookmarksToolbarUnderTabs` [optional preference](https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features) if you want this behavior back.
