### ISSUE TITLE
Question: can this theme be maintained with new proton design?

### ISSUE THREAD

**Issue by Chrysostomus** [rafaelmardojai/firefox-gnome-theme#213]
https://www.omgubuntu.co.uk/2021/02/try-firefox-proton-redesign-ubuntu

WIth the new design of firefox, can this theme still be maintained? I'm hoping the answer is yes, but I understand that the resources of the project are already strained.

**Comment by rafaelmardojai** [comment]
No worry, when the new design drops I will fix everything broken :)
