### ISSUE TITLE
Bookmarks Toolbar Appearance Settings Broken for Blank New Tab Page

### ISSUE THREAD

**Issue by bryce-carson** [rafaelmardojai/firefox-gnome-theme#214]
This was not broken a couple days ago, but now it is on my system. I was and am using 6e7922a3f161baab23d4451105af84de55c94472 on Firefox 87.

With the Bookmarks Toolbar initially set to hidden:

1. Use Library to _Show Bookmarks Toolbar_
2. Open a New Tab
3. Use the secondary mouse button (right- or alternative-click) to open the context menu of the toolbar, and in the Bookmarks Toolbar submenu select the 'Only Show on New Tab' radio button.

The toolbar then slides upwards, hiding, and is no longer visible on New Tabs or any page. In the Bookmarks menu of the  Library the setting has reverted to 'Never Show', as is implied by the relevant button again labelled with _Show Bookmarks Toolbar._

**Comment by bryce-carson** [comment]
In my about:config, **_browser.toolbars.bookmarks.visibility_** is set to **newtab**. Reverting this to **always** produces the expected behaviour _for that setting_ (always show the toolbar), and then closing about:config and using the toolbar context menu to change to _Only Show on New Tab_ reproduces the observed, improper behaviour.

**Comment by bryce-carson** [comment]
However, using the _Firefox Home_ new tab page produces the expected behaviour for New Tabs and the Bookmarks Toolbar visibility settings.

**Comment by rafaelmardojai** [comment]
Sorry for late response, But I have been trying to reproduce with not success since some time ago.
