### ISSUE TITLE
[Firefox - new Proton UI] Appearence for tabs broken

### ISSUE THREAD

**Issue by juxuanu** [rafaelmardojai/firefox-gnome-theme#215]
![image](https://user-images.githubusercontent.com/24759034/114175800-b04e3380-993a-11eb-877b-7ef2d32ae4ae.png)

New design landed in Nightly. This theme now needs rework for it.

**Comment by rafaelmardojai** [comment]
I will probably wait for it to land in stable or beta before fixing it.

**Comment by juxuanu** [comment]
Could you point me to the code where the tab design is?
I could try to work with it based on the WIP tab redesign in the other issue.
As another suggestion, maybe you could have a different branch for nightly so you can start working on it before it lands in stable

**Comment by rafaelmardojai** [comment]
The tabs code is in `/theme/parts/tabsbar.css`, but I will recommend to wait for beta at least, when Mozilla does this kind of changes, they keep changing things in Nightly. When it lands beta at least we know that the code is almost "final" and our fixes wouldn't break soon. 

For example when the megabar landed in Nightly, I tried to fix it there, but Mozilla devs changed the classes name and styles many time until beta. So let's be patient.

**Comment by adryd325** [comment]
The new proton theme was pushed to beta. I'd probably also hold off in case class names change again

**Comment by X-m7** [comment]
I just updated to Firefox 88 stable, and the tabs are now kinda broken like in the above screenshot (stretched close buttons and the tab titles no longer being centered). Below is what it looks like on my system, so not sure if it's a different bug.

![Screenshot from 2021-04-22 21-44-13](https://user-images.githubusercontent.com/18729369/115709219-4ad75980-a3b4-11eb-8c42-c06c88678923.png)

**Comment by rafaelmardojai** [comment]
> I just updated to Firefox 88 stable, and the tabs are now kinda broken like in the above screenshot (stretched close buttons and the tab titles no longer being centered). Below is what it looks like on my system, so not sure if it's a different bug.

@X-m7 It should be fixed now with [1a806e3].

**Comment by rafaelmardojai** [comment]
Today I will install beta and start to fixing this.

**Comment by rafaelmardojai** [comment]
Proton fixes landing on `beta` branch: https://github.com/rafaelmardojai/firefox-gnome-theme/tree/beta.

Current state:
![Captura de pantalla de 2021-04-22 23-14-31](https://user-images.githubusercontent.com/6210397/115817504-97289680-a3c0-11eb-9ac7-abd1849596c5.png)

Still a lot of thing to fix, but at least it doesn't look that broken.

**Comment by rafaelmardojai** [comment]
I'm closing this since tabs are looking good on Proton.
