### ISSUE TITLE
Not enough contrast between active / not-active tabs on dark theme

### ISSUE THREAD

**Issue by luispabon** [rafaelmardojai/firefox-gnome-theme#216]
As you can see, it's pretty hard to make out which tab is actually active:

![image](https://user-images.githubusercontent.com/6388823/115542560-4c136400-a298-11eb-9b04-9446a1563658.png)

Active tab needs way more contrast with not-active.

**Comment by rafaelmardojai** [comment]
Have you tried the **Active tab contrast** optional preference? 

This is an contrast issue from upstream Adwaita.

See: https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features

**Comment by luispabon** [comment]
Thank you, I hadn't. That worked fine. I'm closing this now.

**Comment by TheCultLeader666** [comment]
> This is an contrast issue from upstream Adwaita.
It seems that GNOME Web has better contrast than this theme by default, shouldn't this theme try to mimic Web with Adwaita?

**Comment by rafaelmardojai** [comment]
@TheCultLeader666 it looks the same for me.

GNOME Web:
![Captura de pantalla de 2021-06-06 17-08-43](https://user-images.githubusercontent.com/6210397/120941774-2e844780-c6ea-11eb-9044-d2225caa1e01.png)
This theme:
![Captura de pantalla de 2021-06-06 17-10-00](https://user-images.githubusercontent.com/6210397/120941776-2fb57480-c6ea-11eb-9715-8d97a08574d3.png)

**Comment by TheCultLeader666** [comment]
> @TheCultLeader666 it looks the same for me.
> 
> GNOME Web:
> ![Captura de pantalla de 2021-06-06 17-08-43](https://user-images.githubusercontent.com/6210397/120941774-2e844780-c6ea-11eb-9044-d2225caa1e01.png)
> This theme:
> ![Captura de pantalla de 2021-06-06 17-10-00](https://user-images.githubusercontent.com/6210397/120941776-2fb57480-c6ea-11eb-9715-8d97a08574d3.png)

Yes, for light mode, but in dark mode the contrast is slightly better in Web.
Web:
![image](https://user-images.githubusercontent.com/65368815/120942368-04497e80-c718-11eb-8a69-15367111b6b2.png)
This theme: 
![image](https://user-images.githubusercontent.com/65368815/120942396-335ff000-c718-11eb-8982-790b31f4498a.png)

**Comment by rafaelmardojai** [comment]
Yeah thanks for noticing it. Should be using upstream colors now [0743046].
(https://gitlab.gnome.org/GNOME/libhandy/-/blob/master/src/themes/Adwaita-dark.css#L267)
