### ISSUE TITLE
Broken Tab design in Firefox 88

### ISSUE THREAD

**Issue by ai** [rafaelmardojai/firefox-gnome-theme#217]
Thanks for the amazing theme, which pleasure my eyes every day.

Unfortunately, the recent Firefox 88 broke the tab style. The tab title is not aligned to the center and the close button is not square.

![Screenshot from 2021-04-22 07-42-47](https://user-images.githubusercontent.com/19343/115708852-80416000-a33e-11eb-883f-e39897380da5.png)

**Comment by rafaelmardojai** [comment]
Yep, I'm working on this today!

**Comment by ai** [comment]
And container tab is also broken (just to be sure that I reported about everything 😅)

![Screenshot from 2021-04-22 07-46-56](https://user-images.githubusercontent.com/19343/115709230-f645c700-a33e-11eb-9c2f-f1e318eeef86.png)

**Comment by rafaelmardojai** [comment]
@ai can you check [1a806e3] fixes it?

**Comment by ai** [comment]
Yeap, now it works perfectly. Thanks for a quick fix.
