### ISSUE TITLE
Window inactive issues

### ISSUE THREAD

**Issue by misuchivu** [rafaelmardojai/firefox-gnome-theme#22]
Latest Firefox on Wayland. Fedora. When dragging headerbar the window chrome becomes unfocused.

**Comment by rafaelmardojai** [comment]
Firefox adds pseudo class `:-moz-window-inactive` when window is dragged. I haven't found a way to avoid it.

**Comment by RocketMan** [comment]
> I have submitted a patch upstream: https://phabricator.services.mozilla.com/D50445

FYI, the patch has landed in Firefox 72.  https://phabricator.services.mozilla.com/D51307

The patch is less ambitious than the original patch, but resolves the issue of :-moz-window-inactive in the csd titlebar.  Thus, effective Firefox 72, the firefox-gnome-theme should work as expected, with no artifacts during dragging.

**Comment by rafaelmardojai** [comment]
It's working awesome. Thanks for working on this!
