### ISSUE TITLE
Since last update, icons are always black

### ISSUE THREAD

**Issue by ferlanero** [rafaelmardojai/firefox-gnome-theme#225]
Since last update, icons are always black even in Adwaita dark, where it's supposed to be white
![Captura de pantalla de 2021-05-11 00-33-42](https://user-images.githubusercontent.com/1192395/117734292-73a08100-b1f3-11eb-9e75-3dca8eddf000.png)

**Comment by ferlanero** [comment]
This behavior already occurred in last beta too.

**Comment by ferlanero** [comment]
Ah! That 's my fault I had  `svg.context-properties.content.enabled` set to `false` Thanks for your help.

**Comment by ferlanero** [comment]
When I set `svg.context-properties.content.enabled` to `true` everything looks as expected in the dark mode
![Captura de pantalla de 2021-05-11 01-10-16](https://user-images.githubusercontent.com/1192395/117735517-e01c7f80-b1f5-11eb-8d67-f40a33db3f9b.png)

**Comment by rafaelmardojai** [comment]
Yeah, this is needed to be able to recolor the custom icons. Feel free to close if it's working fine.

**Comment by ferlanero** [comment]
> Yeah, this is needed to be able to recolor the custom icons. Feel free to close if it's working fine.

Don't you think it could be a good idea to add this information to main page? If someone use Adwaita black theme, icons are showing wrong in Firefox with Firefox-Gnome-Theme

**Comment by rafaelmardojai** [comment]
Yeah I have to update the README. 

But we ship a user config file (`configuration/user.js`) that is symliked to the one in the Firefox user profile when you use the installation script. That's why I said that maybe the config file symlink is failing.

**Comment by rafaelmardojai** [comment]
I have added some info about it on the README. 

https://github.com/rafaelmardojai/firefox-gnome-theme#required-firefox-preferences
