### ISSUE TITLE
Random black artifacts around hamburger menu on Wayland

### ISSUE THREAD

**Issue by ghost** [rafaelmardojai/firefox-gnome-theme#23]
![Screenshot from 2019-07-09 09-56-15](https://user-images.githubusercontent.com/52562923/60866089-1d95d780-a230-11e9-9109-2cd36fa092f8.png)

There's no pattern related to their appearance:
- usually happens when opening the menu for the first time on a page
- doesn't happen on all pages

**Comment by rafaelmardojai** [comment]
It is a glitch related to shadows.
