### ISSUE TITLE
Show page loading with `gnomeTheme.hideSingleTab` enabled

### ISSUE THREAD

**Issue by aunetx** [rafaelmardojai/firefox-gnome-theme#231]
When feature `gnomeTheme.hideSingleTab` is activated, we can't see the blue loading bar under the tab (which is normally show when there are multiple tabs).

The best thing to fix it would be to show page loading indicator under the main header bar, if and only if this feature is activated.

**Comment by rafaelmardojai** [comment]
What do you mean with "blue loading bar under the tab"? I only see a bouncing ball in the favicon.

> The best thing to fix it would be to show page loading indicator under the main header bar, if and only if this feature is activated.

That is hard if not impossible to do with CSS.

**Comment by rafaelmardojai** [comment]
Also to my knowledge there's no way to know that there's a single tab outside that tab, that's why I haven't be able yo fix #88.

**Comment by aunetx** [comment]
Hmm, weird... Do you use adwaita? I will screencast it tomorrow to show you

And yeah, it will be impossible to do in css then... And what do you think about putting this loading bar in the header (like epiphany does if I remember correctly)? Is it doable in css?

If you think it may be a good idea, I will try to work on it -- but I don't have any knowledge in Firefox theming for the moment tbh :)

**Comment by aunetx** [comment]
Yeah, you're right, it's only a bouncing ball sorry... Would it be possible to have the same behaviour as epiphany with CSS?
And where is this loading icon situated in the code? I just searched, but did not find it...

**Comment by rafaelmardojai** [comment]
> Would it be possible to have the same behaviour as epiphany with CSS?

Don't seems to be a way to know if the current tab is loading from the `nav-var` (headerbar) or the `urlbar`. And if we foun a way it would be a undetermined progress bar (block bounces back and forth) because we wouldn't have a way to know the loading progress.

> And where is this loading icon situated in the code?

The Firefox tab loading icon?

**Comment by Tomoghno** [comment]
> When feature `gnomeTheme.hideSingleTab` is activated, we can't see the blue loading bar under the tab (which is normally show when there are multiple tabs).
> 
> The best thing to fix it would be to show page loading indicator under the main header bar, if and only if this feature is activated.

How to enable `gnomeTheme.hideSingleTab` feature
