### ISSUE TITLE
Match theme with GTK4/libadwaita

### ISSUE THREAD

**Issue by SeaDve** [rafaelmardojai/firefox-gnome-theme#235]
GTK4 buttons are noticeably flatter, and popovers has different styles

**Comment by rafaelmardojai** [comment]
This should be made behind a preference since the GTK3 -> GTK4 apps migration will be slow.

Even GNOME Web will be GTK3 for a while.

**Comment by TheCultLeader666** [comment]
would this be the proper issue/place to report issues for the libadwaita branch?

**Comment by rafaelmardojai** [comment]
> would this be the proper issue/place to report issues for the libadwaita branch?

Yep, it's fine. 

Just take in account that it's a WIP branch that has been progressed by contributors. I will finish and merge it to `master` when using GNOME 42, so when Fedora 36 gets released around April.

**Comment by TheCultLeader666** [comment]
the libadwaita branch looks pretty good so far to me here on gnomeos nightly, the only things I've noticed is the corner radius of the window, strange contrast in the searchbar popup, and the lack of a dark variant.

**Comment by TheCultLeader666** [comment]
additionally, the private window is still old adwaita

**Comment by DeadMozay** [comment]
I noticed that if you apply the firefox-gnome-theme libadwaita theme, then when you start firefox in the window manager (not only in firefox), the minimize and maximize buttons are activated, and you can no longer disable them either through tweak tools or through dconf, only restarting the PC, after turning on the buttons, there is no until you start firefox, is it just me?
![изображение](https://user-images.githubusercontent.com/39763483/150509670-af568740-9d66-4461-9062-49418b8da4b4.png)

**Comment by duartec3000** [comment]
Hi Everyone!
First a big thank you to the developer for making such an awesome theme.
I just installed v100 and Firefox remains with the normal "GTK3 theme" nothing like the screenshots posted on the main github page.
Do we need to change a pref somewhere to get the libadwaita version? or maybe download the theme in the Beta branch? I saw the screenshots and thought it was already in the main branch but maybe I'm wrong.
Thank you so much for any help you can provide!

**Comment by duartec3000** [comment]
@rafaelmardojai thank you so much for the quick reply, I have installed manually from master everything is working great so far.
Many thanks for the time you invested in this project, it's looking very good!
