### ISSUE TITLE
Tab title misalignment

### ISSUE THREAD

**Issue by SilverMarcs** [rafaelmardojai/firefox-gnome-theme#238]
![image](https://user-images.githubusercontent.com/77480421/120078416-50217580-c0d1-11eb-801e-518dd8e2e4ef.png)

Firefox v88 
Theme on stable branch

The tab names are aligned to the left. Center should be the intended behavior.

**Comment by rafaelmardojai** [comment]
Are you sure you are using the latest version? This should be fixed.

You should read `Firefox GNOME theme v88` in the bottom right corner of the customization mode.

**Comment by SilverMarcs** [comment]
Bottom left corner yes it says Firefox GNOME theme v88. It automatically fixed itself after a while though

**Comment by rafaelmardojai** [comment]
Lol, yeah, bottom left 😅. 

Right, maybe it was some random thing. Where you editing Firefox styles?, sometimes things can break and a restart fix it.

In any case, I'm closing this, feel free to reopen if this happens again.
