### ISSUE TITLE
Enabling system icons is bugged when using dark theme icon set

### ISSUE THREAD

**Issue by sith-on-mars** [rafaelmardojai/firefox-gnome-theme#239]
I have enabled `gnomeTheme.systemIcons` in `about:config`. I discovered that whenever I enabled a icon theme with dark mode support, Firefox Gnome theme couldn't recognise dark theme icon and the icons in Firefox Gnome look "greyish". For example, I use Papirus-Dark icon set and here is how it looks when I enable `gnomeTheme.systemIcons`:

![image](https://user-images.githubusercontent.com/37974764/120147460-33bb3100-c1d6-11eb-994b-589d4425116d.png)

Interestingly, if I used icon set which has no dark theme, like Adwaita, or icon set which has light theme, like Papirus-Light, the problem described above ceases to exist.

**Comment by rafaelmardojai** [comment]
This is a know bug advised on the feature description https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features.

See: https://github.com/rafaelmardojai/firefox-gnome-theme#icons-color-broken-with-system-icons
