### ISSUE TITLE
Empty space at the right side of tab bar

### ISSUE THREAD

**Issue by F3nd0** [rafaelmardojai/firefox-gnome-theme#24]
There's an empty space to the right of the tabs at all times, which doesn't seem to serve a purpose and makes the tab bar look uneven.

![A screenshot depicting the issue.](https://coinsh.red/ipfs/QmUSNF3VijFZwYwQX9xvpsYZXEwBSB3xK3Fe7NjxhQJReK)

The space does not seemingly represent an element which could be removed via ‘Customize…’ However, it does shrink to a smaller length when the window's width decreases significantly (to 400px or so).

I'm running [GNU Icecat 60.7.2](https://www.gnu.org/software/gnuzilla/) (freed & tweaked Firefox), installed with the package manager [GNU Guix](http://guix.gnu.org/) on [Parabola GNU+Linux-libre](https://www.parabola.nu/) (freed Arch). I suppose the issue might stem from my somewhat odd setup, but am not sure. Please let me know if I can do anything to investigate further!

**Comment by rafaelmardojai** [comment]
I have installed Icecat, and also CSD window buttons looks broken. CSD fixes for Firefox 60 coming.

**Comment by rafaelmardojai** [comment]
Please test last commit.

**Comment by F3nd0** [comment]
The space is now gone; it looks great, thanks!
