### ISSUE TITLE
checkout instructions fail

### ISSUE THREAD

**Issue by pguedes** [rafaelmardojai/firefox-gnome-theme#245]
The git repo path on the instructions fail for me. 

Removing the leading `/` fixes it.

![image](https://user-images.githubusercontent.com/507107/120772670-72275780-c518-11eb-88c4-58a325f2b2f5.png)

not sure if this is a fish shell specific thing (i'm on fish)

**Comment by rafaelmardojai** [comment]
It works fine for me with the `/`. But I don't mind removing it.
