### ISSUE TITLE
Some trivial visual issues

### ISSUE THREAD

**Issue by SeaDve** [rafaelmardojai/firefox-gnome-theme#246]
These things are just very trivial enhancement to be more consistent, just want to mention

------------------

![image](https://user-images.githubusercontent.com/64297935/120883188-569e7880-c60e-11eb-8298-cbd9e7cd2bca.png)

above: firefox with gnome-theme
below: ephy

The buttons are a few pixel smaller with the theme compared to adwaita.

------------------

![image](https://user-images.githubusercontent.com/64297935/120883386-64083280-c60f-11eb-9c14-c1289e7e2ecc.png)

I think it would be better to copy an icon in gtkentry wherein it will just recolor the icon on hover. like this in ephy:

![image](https://user-images.githubusercontent.com/64297935/120883897-7899fa00-c612-11eb-942e-23b374a3366d.png)

--------------------

Forgot to add this on the previous issue regarding with 89

![image](https://user-images.githubusercontent.com/64297935/120886154-185d8500-c61f-11eb-97d8-26b4033400bd.png)

**Comment by rafaelmardojai** [comment]
Thanks for caching these!

> The buttons are a few pixel smaller with the theme compared to adwaita.

Yeah, looks like GTK increased the buttons distance by `1px`. Fixed.

> I think it would be better to copy an icon in gtkentry wherein it will just recolor the icon on hover. like this in ephy:

Yeah, I through a bout this too. Fixed.

> Forgot to add this on the previous issue regarding with 89

Fixed.

**Comment by SeaDve** [comment]
thanks for quick fix!

**Comment by SeaDve** [comment]
I did a git pull and I noticed that isn't it to button size, instead of the spacing. Here's how it looks like on latest commits on master:
![image](https://user-images.githubusercontent.com/64297935/120893668-0d1e4f80-c647-11eb-8c2d-539672871b97.png)

above: ephy
below: firefox with gnome-theme

**Comment by rafaelmardojai** [comment]
Should be fixed now.
