### ISSUE TITLE
pinned tab favicons are offset to the right

### ISSUE THREAD

**Issue by TheCultLeader666** [rafaelmardojai/firefox-gnome-theme#248]
It seems that the favicons of pinned tabs are off-center, as shown in this screenshot:
![image](https://user-images.githubusercontent.com/65368815/120926237-95decf00-c6cb-11eb-8c9d-e166638abb12.png)
The problem is especially noticeable when the tab shows the notification dot.

**Comment by rafaelmardojai** [comment]
Are you sure you are using the latest version? It looks centered to me:
![Captura de pantalla de 2021-06-06 17-14-21](https://user-images.githubusercontent.com/6210397/120941894-f3364880-c6ea-11eb-9422-8146d2c69560.png)
