### ISSUE TITLE
Select options in the page are centered

### ISSUE THREAD

**Issue by garrett** [rafaelmardojai/firefox-gnome-theme#255]
When using https://cockpit-project.org/ (Linux server administration via a web based UI) in Firefox, I noticed that native select options are centered.

In Firefox 89.0.1 without firefox-gnome-theme:

![Screenshot from 2021-06-23 09-10-08](https://user-images.githubusercontent.com/10246/123052705-6a661f00-d403-11eb-815b-fcea9073a2c8.png)

In Firefox 89.0.1 with firefox-gnome-theme:

![Screenshot from 2021-06-23 09-09-26](https://user-images.githubusercontent.com/10246/123052744-73ef8700-d403-11eb-95ee-7568a6ec53fa.png)

PatternFly, which Cockpit uses, has a "form select" widget, which is a wrapper for the native form select element @ https://www.patternfly.org/v4/components/form-select

You can see the issue on that PatternFly example component page.

**Comment by garrett** [comment]
This is on tag `v89`, git commit: 25ec8678d885c105535e30710eabebb0600fd722 `(Tabsbar: Fix close button auto hide)`.

**Comment by garrett** [comment]
This line is applied to the select widget:

https://github.com/rafaelmardojai/firefox-gnome-theme/blob/v89/theme/parts/buttons.css#L96

As everything else is a class or id, it must be applying the CSS to the `menulist` element.

**Comment by garrett** [comment]
The changes were all introduced in git commit ad4f92a9, which introduced menulist styling. 

Reverting the commit fixes the dropdown alignment here. I'm not sure what the intent was and what else is affected, however, so a simple revert might just break something else. So far, I haven't encountered anything out of the ordinary.

**Comment by rafaelmardojai** [comment]
Without ad4f92a9 menulist buttons will be unthemed (e.g. controls in the permissions popup).

Making a separate selectors list for the text buttons that require `text-align: center` could be a work around.
