### ISSUE TITLE
Inactive tab style change when fullscreened

### ISSUE THREAD

**Issue by SeaDve** [rafaelmardojai/firefox-gnome-theme#257]
Before fullscreen:
![image](https://user-images.githubusercontent.com/64297935/123532484-f9df3b00-d73f-11eb-9bda-a262cd79c62e.png)

---

Fullscreened:
![image](https://user-images.githubusercontent.com/64297935/123532510-3f9c0380-d740-11eb-990e-7a6f21bbb22f.png)

**Comment by rafaelmardojai** [comment]
Should be fixed.

I also have seen that tabs don't change background on hover when fullscreened, but that's another issue.
