### ISSUE TITLE
Tabs in the middle of a toolbar/headerbar break the whole Tab UI Metaphor

### ISSUE THREAD

**Issue by duartec3000** [rafaelmardojai/firefox-gnome-theme#259]
Tab UI Metaphor is to work like a Folder with lots of tabs that separate pages.

After #211 we now have the Tabs row in the middle of the interface when Bookmarks Toolbar is enabled, this makes the access to the Tabs much more difficult, confusing and break the UI Metaphor of Tabs that need to be touching the Pages they belong to.

I hope you consider reverting this change as per #223 as people that don't like their tabs moving down when they open a new tab can just make the toolbar permanent as it seems much worse in Usability to have the tabs in the middle than to have the tabs move a row down only when you open a new tab.

Thank you for your consideration

**Comment by rafaelmardojai** [comment]
Yeah, is true, I didn't really care because I have the bookmarks bar always hidden. But now looking that this is a controversial change, I will revert it, as the previous state seems the sane one. Then I will provide a optional preference to move the bookmarks bar under the tabs.
