### ISSUE TITLE
Bookmarks' text is light on light background.

### ISSUE THREAD

**Issue by KarkanAlzwayed** [rafaelmardojai/firefox-gnome-theme#262]
The bookmark's text is light on light background and is very hard to see. This also applies to the "facebook container" icon(if you look at my extensions on the top right, you'd see a barely visible icon, that is the one). See screenshot, please.
Thanks

![firefox](https://user-images.githubusercontent.com/49320606/128787436-89740a35-967a-497f-b970-1aebe9be4511.png)

**Comment by rafaelmardojai** [comment]
Hmm, I cant reproduce. Maybe you have the Firefox dark theme enabled instead of the system one? Are you using a different theme on host than Adwaita?

**Comment by KarkanAlzwayed** [comment]
My bad, I just found out that I don't have "system theme" enable on firefox itself. It was just a simple conflict. Sorry about that. I will close this issue.
Thanks
