### ISSUE TITLE
Minimize the window by middle-click

### ISSUE THREAD

**Issue by msadeqhe** [rafaelmardojai/firefox-gnome-theme#263]
Is it possible to minimize the window by pressing middle-click on the blank area of the header bar?

I changed middle-click behavior in GNOME Tweaks, all programs respect that but Firefox doesn't care about it.

**Comment by rafaelmardojai** [comment]
If vanilla Firefox doesn't respect that, then it's a Firefox issue. Nothing we can do with CSS.
