### ISSUE TITLE
Find buttons doesn't have icons

### ISSUE THREAD

**Issue by msadeqhe** [rafaelmardojai/firefox-gnome-theme#264]
I did `auto-install.sh` and also I tried Manual Installation, but when I press Ctrl+F, the buttons doesn't have icons:

![Untitled](https://user-images.githubusercontent.com/8925601/129392956-f7bd39e6-1ea8-42d6-b227-4498a5dae752.jpg)

OS: Debian 11 (bullseye)
Desktop: GNOME 3.38.2
Firefox version: 88.0.1

**Comment by Vistaus** [comment]
I can reproduce this in 95.0 beta. In fact, I don't see any buttons next to the arrows at all as full text is displayed instead.
