### ISSUE TITLE
Context submenu does not display if it does not fit within right-edge of screen

### ISSUE THREAD

**Issue by Dreamsorcerer** [rafaelmardojai/firefox-gnome-theme#265]
I've been plagued with this issue for months, thinking it was a bug in Firefox, but it only seems to occur with this theme enabled:
https://bugzilla.mozilla.org/show_bug.cgi?id=1685409

Steps to reproduce:

Right-click context menu, hover over a submenu item (e.g. 'send page to device').

Actual results:

Submenu will not display unless it fits within the dimensions of the screen, resulting in awkward situations where I have to find some way to be able to right-click the content from the left side of the window in order to access it.

Expected results:

Menu should display without issues the same as other GTK applications (for example Gedit).

**Comment by Dreamsorcerer** [comment]
That's unfortunate, seems like most distros are moving (or have already) to Wayland by default.

**Comment by rafaelmardojai** [comment]
Yeah, I'm waiting for Fedora to officially support Wayland + Nvidia privative drivers.

**Comment by shdwchn10** [comment]
I can reproduce that on Fedora Silverblue 34

**Comment by Dreamsorcerer** [comment]
Just noticed this seems to be fixed for me now (Firefox 97).
