### ISSUE TITLE
Blank panels

### ISSUE THREAD

**Issue by Dreamsorcerer** [rafaelmardojai/firefox-gnome-theme#266]
Something that started happening fairly recently (after updating to Firefox 90 maybe). When a notification bar appears (like "Firefox prevented a popup"), often after closing it or similar, a blank space is left instead of the upper bars reorganising.

This can usually be got rid of by changing tabs or similar, which seems to force a complete redraw or something.

**Comment by losuler** [comment]
I just want to add that I have the same issue and changing tabs didn't work, whereas moving the tab to a new window got rid of it.

**Comment by Dreamsorcerer** [comment]
I've actually found that I can remove it by clicking at the right end of the panel, which is, I assume, where the close button would be.

**Comment by KushagraKarira** [comment]
![Screenshot from 2021-10-03 18-37-08](https://user-images.githubusercontent.com/36698785/135755086-eaa48630-b77e-4c91-95e3-0df40e317696.png)
Sample image.

**Comment by losuler** [comment]
> I've actually found that I can remove it by clicking at the right end of the panel, which is, I assume, where the close button would be.

This only seems to work with some banners (e.g. the popup blocked one), whereas it doesn't work with the enable DRM banner.
