### ISSUE TITLE
Hamburger menu: 'Sign in' button clashes with 'Sync and save data'

### ISSUE THREAD

**Issue by Mel34** [rafaelmardojai/firefox-gnome-theme#272]
![Screenshot from 2021-09-01 13-03-26](https://user-images.githubusercontent.com/13254332/131614854-c4110f61-f7d6-4fd8-a2a3-92b60739a8ad.png)

**Comment by Pacman99** [comment]
I'm also experiencing this

![image](https://user-images.githubusercontent.com/16345849/133345057-d833f247-2e8d-462b-bf0d-8487a9c62675.png)
