### ISSUE TITLE
Only show theme when system theme is selected? 

### ISSUE THREAD

**Issue by Chrysostomus** [rafaelmardojai/firefox-gnome-theme#277]
Would it be technically possible to have this theme apply only if the system theme option is selected in Firefox settings? We (Manjaro linux, gnome edition) are currently shipping this theme enabled by default, and since Firefox asks about the theme on the first run, it would be better for user experience if that setting actually did something.

I can probably implement something like this by having a startup script that polls Firefox settings and triggers if there is any change there, but you can imagine how hacky that would be.

**Comment by rafaelmardojai** [comment]
The `:root:not(:-moz-lwtheme)` selector could work for that, but we will need to put it before every selector. If we were using some CSS  preprocessor, this type of things could be easier.

If we had some media query would be ideal, but I don't think it's the case.

**Comment by rafaelmardojai** [comment]
Actually now I think that having the option to force a different color scheme than the system one is a desirable feature. So I will keep the current behavior.
