### ISSUE TITLE
Suggestion: Add the theme to the firefoxcss-store 

### ISSUE THREAD

**Issue by 31j** [rafaelmardojai/firefox-gnome-theme#281]
This is completely optional, but I think it would be nice to have the theme on [here](https://firefoxcss-store.github.io/)

This would make the theme  more accessible / visible to someone browsing r/FirefoxCSS

**Comment by rafaelmardojai** [comment]
PR sent: https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/pull/110

**Comment by andreasgrafen** [comment]
This is a great theme; great to see it being added to the list.
I've accepted the PR and now it's [out there](https://firefoxcss-store.github.io/) for world to find! ♡

**Comment by rafaelmardojai** [comment]
Thanks for the kind words!
