### ISSUE TITLE
Hide single tab is not respected when tabs are hidden. 

### ISSUE THREAD

**Issue by 31j** [rafaelmardojai/firefox-gnome-theme#282]
Unsure if this is intended behaviour, however in my use case it ideally shouldn't be this way. 

Steps to reproduce:

1. Install an extension that hides tabs, I personally use [this](https://addons.mozilla.org/en-US/firefox/addon/sidebery/) extension. Specifically with the "hide tabs from other panels" feature enabled. 
2. Have only one tab "open" while all other tabs are hidden, this tab will be displayed despite having all others hidden 

As I said before, I completely understand if this is intended behaviour (as the drop-down to view hidden tabs is on the tab bar), but in my specific use case with sideberry I'd much prefer having them truly hidden OR at the very least the drop down for hidden tabs moved to the main bar instead of the tab bar. 

Thank you for making this theme! It truly is a great theme

**Comment by rafaelmardojai** [comment]
Yeah, it doesn't work if you have other elements on the tabsbar, and sadly Firefox doesn't allow you to move the all tabs button to other place.

**Comment by 31j** [comment]
Alright, thank you for explaining. I guess for now this issue should be closed unless something changes on Firefox's end
