### ISSUE TITLE
Permissions popover needs styling

### ISSUE THREAD

**Issue by juxuanu** [rafaelmardojai/firefox-gnome-theme#286]
- The horizontal bar I think shouldn't be visible
- The (x) buttons need padding on the right

![imatge](https://user-images.githubusercontent.com/24759034/134438974-c08affbc-062f-4636-9fad-6065017f77bd.png)

**Comment by rafaelmardojai** [comment]
Thanks for reporting! 
Yeah, a lot of things are broken right now. I haven't had time to release fixes for 91 nor 92. I hope I can fix them before 93 is out.

**Comment by 3ship** [comment]
Just for posterity:

All popovers on the left side of the address bar (permissions, website information, privacy options) need padding on the right:

![screencap-20210930213432-513x189](https://user-images.githubusercontent.com/47889681/135524475-5f10d3f0-71a0-4023-bae9-b677bc536a3b.png)
![screencap-20210930215119-422x196](https://user-images.githubusercontent.com/47889681/135524536-396556cc-02be-4083-8dd8-fe31e1a6464c.png)
![screencap-20210930215056-423x541](https://user-images.githubusercontent.com/47889681/135525417-88070adc-dd0b-44d8-96fd-97635dca809b.png)

- "Add this site to your bookmarks" menu

On the right end of the address bar the menu for adding bookmarks looks like it needs padding on all sides:
![screencap-20210930214200-332x596](https://user-images.githubusercontent.com/47889681/135525610-61e004ad-420f-4948-8202-64da5e5dcccd.png)

- "Hidden tabs" menu

When you click on the "List all tabs" overflow menu on the tab bar and go to the sub-menu "Hidden tabs", entries will have the wrong color around their corners when you hover over them (both dark and light mode):
![screencap-20210930213843-363x106](https://user-images.githubusercontent.com/47889681/135526805-5c52f8d8-37af-43fc-9501-d8af5eb79ed0.png)
(I believe the "Hidden tabs" sub-menu only appears, if you use tab management add-ons e.g. Panorama Tab Groups)

- "Bookmarks menu"

1. Add the "bookmarks menu" icon to your toolbar
2. Open the bookmarks menu
3. Hover back and forth between items in the menu

There's subtle flicker or lag when switching from one menu entry to another. I don't experience this in any other menu.

Thanks for your work by the way. This theme looks amazing!
