### ISSUE TITLE
Some cases need to use gnome theme arrow

### ISSUE THREAD

**Issue by ubluish** [rafaelmardojai/firefox-gnome-theme#29]
- History Sidebar
![1](https://user-images.githubusercontent.com/21042432/61007252-a87bec80-a36c-11e9-9216-1b6ae16df00e.png)

- Bookmark manager window
![2](https://user-images.githubusercontent.com/21042432/61007300-c77a7e80-a36c-11e9-8384-aaf02e588f2c.png)

- Bookmarking new page
![3](https://user-images.githubusercontent.com/21042432/61007326-d7925e00-a36c-11e9-9d0e-c194d6a45484.png)

**Comment by rafaelmardojai** [comment]
I can't debug/inspect Firefox Library window. But maybe i can search in Firefox source code.

**Comment by rafaelmardojai** [comment]
I'm fixing sidebar history view button and adding gnome icons to tree views in general.

About library window buttons, it's hard to debug, but also it will be dropped soon in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1554144. So is a wontfix for it.
