### ISSUE TITLE
Zoom +/- buttons aren't centered in hamburger menu

### ISSUE THREAD

**Issue by bbhtt** [rafaelmardojai/firefox-gnome-theme#291]
I'm running current master of the theme and FF Nightly 95.0a1. Not sure if this is a Nightly only issue...

![screenshot](https://user-images.githubusercontent.com/62639087/137333218-9d17665b-1b8a-41b8-9cb8-189ad908a545.png)

**Comment by aadilayub** [comment]
With the release of `94`, this is no longer a Nightly issue.

**Comment by winkelnp** [comment]
can confirm, this is happening in my `94.0.1` as well
