### ISSUE TITLE
New Tab button like in Epiphany

### ISSUE THREAD

**Issue by CleoMenezes** [rafaelmardojai/firefox-gnome-theme#293]
The New Tab button in Epiphany is on the left-hand side next to the load button. It would be pretty cool if it came as a default

Epiphany
![image](https://user-images.githubusercontent.com/54215258/137665814-1a419e74-7633-4f72-9b6c-d70137ee6587.png)
Example
![image](https://user-images.githubusercontent.com/54215258/137665880-b26b8f1f-07b3-41b6-8a91-dedeb65d2f09.png)

**Comment by KushagraKarira** [comment]
did you enable 'gnomeTheme.systemIcons'

**Comment by rafaelmardojai** [comment]
This is not possible, you need to manually move it in the Customize Toolbar option.
