### ISSUE TITLE
how to move titlebar close button like screenshot in readme?

### ISSUE THREAD

**Issue by kevariable** [rafaelmardojai/firefox-gnome-theme#294]
![image](https://user-images.githubusercontent.com/56016477/138574582-2b5c9c95-9a05-4830-800a-3d4f10474636.png)

Thanks in advance, i am new in gnone

**Comment by winkelnp** [comment]
You should be able to go into "customise toolbar" in your hamburger menu (under "more tools") and deselect the "title bar" checkbox at the bottom of the screen.

**Comment by kevariable** [comment]
> You should be able to go into "customise toolbar" in your hamburger menu (under "more tools") and deselect the "title bar" checkbox at the bottom of the screen.

Thanka tl reply, but it's already unchecked

**Comment by rafaelmardojai** [comment]
Could you confirm that this works as expected with default Firefox?

**Comment by kevariable** [comment]
> Could you confirm that this works as expected with default Firefox?

Is it not like expected, i am use Arch linux with gnome 4.0 with latest firefox and seems like the close toolbar not same as readme

**Comment by rafaelmardojai** [comment]
I mean if this:

> You should be able to go into "customise toolbar" in your hamburger menu (under "more tools") and deselect the "title bar" checkbox at the bottom of the screen.

works in Firefox without the theme installed.

**Comment by kevariable** [comment]
> I mean if this:
> 
> > You should be able to go into "customise toolbar" in your hamburger menu (under "more tools") and deselect the "title bar" checkbox at the bottom of the screen.
> 
> works in Firefox without the theme installed.

Not work, just reduce the contrast of header

**Comment by rafaelmardojai** [comment]
Then it's a Firefox issue.

**Comment by kevariable** [comment]
Alright, thanks to replied
