### ISSUE TITLE
beta branch behind master?

### ISSUE THREAD

**Issue by TheCultLeader666** [rafaelmardojai/firefox-gnome-theme#295]
Beta branch is supposed to be in sync with beta versions of Firefox, but somehow is behind master in terms of commits (old adwaita icons, etc.)

**Comment by rafaelmardojai** [comment]
Yeah, I usually sync it when I commit but those last changes that you mentioned where contributed in PRs. 

I haven't had time to work on this lately, I was moving and had other real world duties :p. But probably next weekend I will be able to commit some fixes, I use this daily and some bugs are annoying me really hard 😅

**Comment by rafaelmardojai** [comment]
Done!
