### ISSUE TITLE
Distribute patches

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/firefox-gnome-theme#30]
I think this is the way to go for easy installation.
New repo should be created to this purpose, and keep this repo as CSS source and theme-hack. (I'm also considering switch to sass/less, for a easy code maintenance and generate a single css file)

I have no idea about patching/packaging, so i'm asking for:
- Figure out what needs to be put where.
- ~Name proposals, we should rebrand Firefox to distribute it.~
- Package maintainers, to distribute css patches.

**Comment by lionirdeadman** [comment]
I think that's a terrible idea. We really don't want to deal with people's security. Please reconsider.

**Comment by rafaelmardojai** [comment]
@lionirdeadman I now, but thinking in flatpak, it will compile from Firefox source (https://github.com/mozilla/gecko-dev) and only apply css patches.

**Comment by rafaelmardojai** [comment]
There is a way distro packages can patch existing apps/packages like firefox?

**Comment by alerque** [comment]
No! You don't want to be the one packaging and distributing a browser. Take it from somebody who has done it. The security implications and occasion need for speedy releases is not something that should be considered just to monkey patch a UI theme. If it can be done as an addon package sure (and as I mentioned elsewhere I might even help make that happen), but don't build and distribute the browser itself.

**Comment by alerque** [comment]
What distro packages can do varies by distro, but in general they can usually place additional content but not remove or modify system files installed by other packages. The question is does Firefox have a place to put this thing it will find on the system the way it does in a user's profile folder?

**Comment by rafaelmardojai** [comment]
Mmm, in that way, the installation script is the "easiest" installation methoth we can get.

**Comment by rafaelmardojai** [comment]
Hey please test

**Comment by alerque** [comment]
Instead of closing this can we re-purpose the issue for looking into distribution as an add-on package (not extension, but a bolt on addition to the system Firefox package)?

Looking the [list of everything installed by the Firefox package](https://termbin.com/bovv) of particular note is the `/usr/lib/firefox/browser/chrome/` directory. Would it work to just stuff the files from this repository in there instead of the user's profile directory?

**Comment by alerque** [comment]
Unfortunately a quick test shows you can't just stuff the same files in there. Maybe they need to be called something other than "userChrome" to be read from there? Does anybody know where developer documents for what paths do get read for this kind of thing are?

**Comment by rafaelmardojai** [comment]
No idea, i only know all Firefox CSS/Icons are called from `/browser/omni.ja`.
