### ISSUE TITLE
Blank permission icon is being dispalyed

### ISSUE THREAD

**Issue by bbhtt** [rafaelmardojai/firefox-gnome-theme#300]
A blank permission icon is being displayed when the website itself didn't request any permission:

![Screenshot](https://user-images.githubusercontent.com/62639087/142612960-52750fcc-1a40-479c-b239-12bce0a742dd.png)

Steps to reproduce:

1. Have one tab with the permission icon for example "Block Audio and Video" in youtube.com (set auto-play to block audio and video in privacy and security settings of Firefox beforehand for this to work)
2. Have another tab open with example.com (might take a refresh or two)
3. The permission icon is being displayed in the example.com tab when it didn't request anything

The black icon is carried over to every tab opened afterwards, for example:

![image](https://user-images.githubusercontent.com/62639087/142865801-85ea10da-8c43-463e-ac3b-21db91f2b436.png)

Theme version: Master edfa268d49651060fd5652dcb64364251f0f2111
Firefox Nightly: 96.0a1 buildID: 20211122093912

Doesn't happen in a clean profile or in a profile with theme removed.

**Comment by rafaelmardojai** [comment]
I can´t reproduce this in Firefox 94.

**Comment by bbhtt** [comment]
You are correct, I just checked with 94 and the issue is not reproducible there with the theme. Looks like it's a nightly-only issue at the moment.

**Comment by bbhtt** [comment]
I can reproduce this now on 96.0.1

**Comment by bbhtt** [comment]
Seems that the issue is gone...

Tested with 

Theme. https://github.com/rafaelmardojai/firefox-gnome-theme/commit/e8f93b9b3456c13356f17aae7c8abb99195d12ec
FF. 101.0a1 (2022-04-14)

Closing. Thanks!
