### ISSUE TITLE
Out of place "Sign in" button

### ISSUE THREAD

**Issue by evansan** [rafaelmardojai/firefox-gnome-theme#301]
OS: Arch Linux
Firefox Version: 94.0.2-2 from official arch repo

![Screenshot from 2021-11-25 00-22-41](https://user-images.githubusercontent.com/2133205/143384344-35e99d50-0b62-4b65-a248-00806f05618b.png)

**Comment by rafaelmardojai** [comment]
This should be fixed in current master branch. You sure are running latest version?

**Comment by evansan** [comment]
my bad, confirm it's fixed, have to rerun the install scripts.
