### ISSUE TITLE
Weird border around bookmark menu

### ISSUE THREAD

**Issue by Titaniumtown** [rafaelmardojai/firefox-gnome-theme#303]
When viewing a bookmark folder, this strange border appears around the contents of said folder: 
![Screenshot from 2021-11-29 00-54-08](https://user-images.githubusercontent.com/11786225/143815981-475a3b7f-4d77-445c-b3fe-e9a859afd1c3.png)

Edit: this also seems to appear around the right-click menu, among others.

**Comment by Titaniumtown** [comment]
Nevermind, this is a duplicate of #273

**Comment by rafaelmardojai** [comment]
No, this is a different issue.

**Comment by Titaniumtown** [comment]
oh? ok. it seemed like a similar effect.

**Comment by rafaelmardojai** [comment]
Yeah, kinda similar, but this one is only affecting bookmarks menus. Also the other issue about context menus should be already fixed, I need to close that ticket.

**Comment by Titaniumtown** [comment]
Issue fixed. Thanks!
