### ISSUE TITLE
Border around password boxes

### ISSUE THREAD

**Issue by Titaniumtown** [rafaelmardojai/firefox-gnome-theme#304]
With the autofill for passwords and usernames, a border appears around those popups, similar to #303

Firefox nightly 96
Gnome Shell 41.1

**Comment by Titaniumtown** [comment]
@rafaelmardojai is there documentation of firefox theming? I would love to try and help by solving and PRing these issues myself.

**Comment by rafaelmardojai** [comment]
> is there documentation of firefox theming? I would love to try and help by solving and PRing these issues myself.

Not really, only what it's said in the README: https://github.com/rafaelmardojai/firefox-gnome-theme#development

So you need to start inspecting Firefox and figure out how things work.

**Comment by Titaniumtown** [comment]
Hm ok. I'll try and figure that out. Thanks!

**Comment by juxuanu** [comment]
This happens on Firefox stable (95.0)

**Comment by rafaelmardojai** [comment]
I have reverted the theming of the auto complete popup.

Firefox is using the [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) everywhere now ([which can't be accessed with userChrome.css](https://bugzilla.mozilla.org/show_bug.cgi?id=1575507)), I had be able to work around it in some places like menus but in this case I haven't be able to.
