### ISSUE TITLE
Window decorations don't display properly

### ISSUE THREAD

**Issue by Titaniumtown** [rafaelmardojai/firefox-gnome-theme#305]
Window decorations don't display how they should in Epiphany/Gnome Web. The Close, Maximize, and minimize buttons just show dots instead of the proper icons.

Firefox Nightly 96: 
![image](https://user-images.githubusercontent.com/11786225/143890900-89bfcb05-b16f-44eb-a7fc-e617bb1b8acb.png)

Epiphany/Gnome Web: 
![image](https://user-images.githubusercontent.com/11786225/143890792-b6d062e6-646e-439c-bc23-69f3655f3dc6.png)

**Comment by PixsaOJ** [comment]
If I choose Dark theme, I get default window buttons. When I pick anything else, like system theme, I get these dots.

Is it possible to use GTK theme I already have? Like Layan solid dark?

**Comment by nv95** [comment]
Just switch to the system theme in firefox settings

**Comment by rafaelmardojai** [comment]
Just updated to 96 and it works fine with the system theme enabled in firefox settings (what it's actually a theme requirement).

So I will update `user.js` to have `user_pref("extensions.activeThemeID", "default-theme@mozilla.org");`. And also add info about it in the README.

**Comment by jayofdoom** [comment]
@rafaelmardojai So, interestingly, I'm having a version of this problem.

- My minimize/close/maximize buttons are dots when "Dark" is the selected theme
- When "System" is the selected theme, they appear more correctly, but I'm using adiwaita-dark for my gnome desktop so this is not correct.

I'm not sure what the right way is to get both dark mode, and working window decorations.

**Comment by jayofdoom** [comment]
I fixed my described issue by:
- Using system theme
- Setting `ui.systemUsesDarkTheme` to integer `1` in about:config
