### ISSUE TITLE
Excess padding around context menus and the bookmarks menu as of FF95

### ISSUE THREAD

**Issue by 3ship** [rafaelmardojai/firefox-gnome-theme#308]
As the title says, every context menu I could find now has excess padding. The highlight when hovering over menu entries no longer extends to the left and right border of the context menu.

Apart from the context menus, there's also the bookmarks menu, i.e. the star symbol you can drag onto the toolbar. The padding envelops the menu including the arrow. And unlike the other dropdown menus on the toolbar, the bookmarks menu is out of position.

**Comment by rafaelmardojai** [comment]
Yep, seems to be the same as this one: https://github.com/rafaelmardojai/firefox-gnome-theme/issues/273#issuecomment-990634920
