### ISSUE TITLE
Firefox Libadwaita theme

### ISSUE THREAD

**Issue by CleoMenezes** [rafaelmardojai/firefox-gnome-theme#309]
I was playing around with the code a bit and I found it quite interesting how it can look like this. I hope I can see the Libadwaita version soon.

Thanks for the amazing job and I hope maybe I can even help (whatever I can as I'm not that advanced at this lol)
![image](https://user-images.githubusercontent.com/54215258/146651257-4f432a12-a8b8-46d4-8256-148e2ded0544.png)

**Comment by rafaelmardojai** [comment]
That looks nice! Any help would be welcome.

I'm planing to work on this when GNOME 42 is out, since maintaining this changes behind a preference wouldn't be possible with the time I have available right now.

This request is begin tracked here: #235.

**Comment by CleoMenezes** [comment]
Excellent. I'll be watching when you create another branch for that or something. I want to try to help.

**Comment by CleoMenezes** [comment]
Just sharing more about it.
https://github.com/CleoMenezes/firefox-gnome-theme

https://user-images.githubusercontent.com/54215258/146661550-881f5b52-726f-4473-82f5-37546cb991cc.mp4
