### ISSUE TITLE
Theme variants behavior

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/firefox-gnome-theme#31]
I have discover the `@media (prefers-color-scheme: dark/light)` media query. So now we have a way to detect if host theme is light or dark when default theme is selected in Firefox.

Should we keep support for Firefox light/dark theme selector? (`:-moz-lwtheme` and `:-moz-lwtheme-brighttext` pseudo classes)

**Comment by lionirdeadman** [comment]
That sounds like a pretty good idea.

**Comment by rafaelmardojai** [comment]
What i do not know, is if someone will want to have light Firefox while using dark Adwaita, or vice versa.

**Comment by lionirdeadman** [comment]
That's still possible using `ui.systemUsesDarkTheme` in about:config (using a string, 1 is dark, 0 is light)

**Comment by rafaelmardojai** [comment]
That preference is not present in my system.

**Comment by lionirdeadman** [comment]
You need to create it

**Comment by rafaelmardojai** [comment]
Don't seems to do anything.

**Comment by lionirdeadman** [comment]
It seems they broke that about:config item recently, I can't get it to work now either...

**Comment by Roboe** [comment]
https://github.com/rafaelmardojai/firefox-gnome-theme/commit/97af89c78eadaf20bfa5be803ef002898b32be7d broke Firefox for ESR users ([Debian](https://packages.debian.org/buster/firefox-esr)).

Firefox ESR is currently in 60.8.0.esr. Next ESR release (68.0.2esr) will support `prefers-color-scheme`, which is expected to arrive for everyone in two cycles (12 weeks), see graphic [here](https://www.mozilla.org/en-US/firefox/organizations/#faq)).

Reverting the commit works for me, but I wanted to inform you.

**Comment by lionirdeadman** [comment]
Right now we don't support ESR officially, only the latest Firefox. 

Perhaps we should make a branch which reverts that commit for an ESR branch right now and kill that once the next ESR comes out since it's not really something we want to have the burden of for the moment. (By we, I really mean Rafael because I don't do much other than bug reports)

**Comment by rafaelmardojai** [comment]
Now theme defaults to light theme, so only dark variant support should be broken in FF60. Better than nothing.

**Comment by Roboe** [comment]
Ok. I'll keep my reverted-commits tree since I want a dark theme, but that should fix it for newcomers. Though an explicit "defaults to light theme" comment for the 60 (which is the currently preferred, not the "old" one) would be more informative.

Thank you! :)

**Comment by rafaelmardojai** [comment]
README updated.

**Comment by 73** [comment]
Hi all,
I heard you are looking for someone that would like to force the dark variant while using bright Adwaita as a system default. Well, I was trying to do that and found this issue. 

I tried setting the dark variant in the Firefox settings:
![image](https://user-images.githubusercontent.com/529346/97427537-fd9e9180-1914-11eb-9404-d52e04198cb5.png)
However, the top control elements stayed bright. It does work, when I change the system default in the Tweak Tool.

Is there a way to force a dark variant that survives a `git pull` to update?

Thank you so much btw. You made my Firefox so pretty.

**Comment by 73** [comment]
@rafaelmardojai do you know a way to set a dark theme variant while keeping the bright system default?

**Comment by rafaelmardojai** [comment]
Hmm, maybe launching firefox with `GTK_THEME=Adwaita:dark`?

**Comment by 73** [comment]
> Hmm, maybe launching firefox with `GTK_THEME=Adwaita:dark`?

Sure. That works. It is a little unpractical though. Changing the environment variable on an URI handler is not trivial since it is called not only from one place. I thought maybe there was a way to trick the the theme to believe the variable would be set.
