### ISSUE TITLE
Double shadow/border on autocomplete menu

### ISSUE THREAD

**Issue by ai** [rafaelmardojai/firefox-gnome-theme#312]
A way to reproduce:

1. Open any page with text fields with autocomplete. For instance, [`type=email` demo page](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_email).
2. Put focus to text field and press `↓` to see autocomplete menu
3. Menu will have 2 borders and 2 shadows

![Снимок экрана от 2021-12-19 15-42-42](https://user-images.githubusercontent.com/19343/146675305-4f8fa35a-bafd-4b4a-9f55-a26b623c85eb.png)

Firefox 95 & Fedora 35

**Comment by rafaelmardojai** [comment]
Duplicated of #304
