### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/firefox-gnome-theme#32]
Please test WIP installation script.

`bash <(curl -s https://raw.githubusercontent.com/rafaelmardojai/firefox-gnome-theme/master/scripts/install.sh)`

It optionally accepts flags: 
- -f $firefox_folder (Sets custom Firefox folder)
- -p $profile_folder (Sets custom profile folder)
- -g (Auto enable GNOMISH extra features `hide-single-tab.css` & `matching-autocomplete-width.css`)

For example this will work for flatpak and icecat:
`bash <(curl -s https://raw.githubusercontent.com/rafaelmardojai/firefox-gnome-theme/master/scripts/install.sh) -f ~/.var/app/org.mozilla.FirefoxNightly/.mozilla/firefox/`

`bash <(curl -s https://raw.githubusercontent.com/rafaelmardojai/firefox-gnome-theme/master/scripts/install.sh) -f ~/.mozilla/icecat/`

**Comment by lionirdeadman** [comment]
Let's not encourage copy-pasting and running scripts stored online this way, I propose recommending :

```
git clone https://github.com/rafaelmardojai/firefox-gnome-theme/
./scripts/install.sh
```

(The script currently won't work this way but that can be changed)

It should also allow easier modification and testing of forks rather than always modifying the script

**Comment by rafaelmardojai** [comment]
> Let's not encourage copy-pasting and running scripts stored online this way

I know, it's just for fast testing.

> It should also allow easier modification and testing of forks rather than always modifying the script


Maybe we can provide two different scripts... I want the `chrome` folder to be a git repo, so user can update with `git pull origin master`.

The script also needs a way to install in all profiles.

**Comment by lionirdeadman** [comment]
Currently I just have a userChrome.css pointing to the one in my firefox-gnome-theme folder which is just a git clone with the things I want uncommented. I believe we can do the same thing.

**Comment by rafaelmardojai** [comment]
Checkout last changes to script.

**Comment by lionirdeadman** [comment]
Just tried it, perhaps we should put our examples of things to put in customChrome as presented in userChrome?

Also, again, git cloning shouldn't be done since it's both a waste of bandwidth and also means that the script needs to be edited in all forks and that all changes that want to be applied first need to done in a git repository.

**Comment by rafaelmardojai** [comment]
So we just use `cp` to copy theme in profile?

**Comment by rafaelmardojai** [comment]
```sh
git clone https://github.com/rafaelmardojai/firefox-gnome-theme/ && cd firefox-gnome-theme
./scripts/install.sh -g
```
Should do the trick.

**Comment by lionirdeadman** [comment]
Yep, that sounds better.

**Comment by rafaelmardojai** [comment]
Installation script is usable now, closing.
