### ISSUE TITLE
Provide packaging

### ISSUE THREAD

**Issue by bdaase** [rafaelmardojai/firefox-gnome-theme#322]
Even though the installation instructions are quite simple, for the ease of use and more publicity, it would be nice if packaging for different distributions could be provided. I would be especially interested in a Fedora package/Copr.

**Comment by K4LCIFER** [comment]
Aggreed. I'm not sure about other distributions, as I have never dealt with them, but creating a package for the AUR shouldn't be too difficult. I wouldn't mind doing that at some point.

**Comment by rafaelmardojai** [comment]
You could do something similar to what Manjaro community did:

https://gitlab.manjaro.org/Chrysostomus/firefox-gnome-theme-maia
https://gitlab.manjaro.org/packages/community/themes/firefox-gnome-theme-maia

But doesn't seems very practical IMO. Creating packages for something that get installed on an app user data folder is complicated.

**Comment by JaneSmith** [comment]
Is it possible for it be set up as a Flatpak add-on for the Firefox Flatpak on Flathub? I've seen a few other apps with add-ons available, for example the Gimp Flatpak has a bunch of third-party plugins as installable add-ons.

**Comment by rafaelmardojai** [comment]
> Is it possible for it be set up as a Flatpak add-on for the Firefox Flatpak on Flathub? I've seen a few other apps with add-ons available, for example the Gimp Flatpak has a bunch of third-party plugins as installable add-ons.

Not really, the main problem is that Firefox's `customChrome.css` is a per profile feature, so you can't set a generic Flatpak extensions endpoint.

**Comment by azmeuk** [comment]
Have you considered submitting the theme directly to the firefox themes database?
https://addons.mozilla.org/en-US/developers/addon/submit/distribution

**Comment by rafaelmardojai** [comment]
@azmeuk Currently there's no way with extensions to inject custom CSS the way `userChrome.css` does.

There's only [this thing](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme_experiment) that can be explored in the future, see #353.
