### ISSUE TITLE
FF96 - transparent bookmarks menu and missing arrow on toolbar menus

### ISSUE THREAD

**Issue by 3ship** [rafaelmardojai/firefox-gnome-theme#324]
Firefox 96 seems to have introduced a small batch of new issues:

1. All menus on the toolbar are missing the arrow pointing at the toolbar button. Example screenshot of burger menu:

![Example screenshot burger menu](https://user-images.githubusercontent.com/47889681/149214695-f9b768db-2785-4c2e-8a63-3e7c52d63cc7.png)

2. The bookmarks menu is now entirely transparent:

![bookmarks menu](https://user-images.githubusercontent.com/47889681/149215197-495b5d00-bd8d-49c1-aecc-cc014ccf0c3b.png)

**Comment by ulipo** [comment]
Confirmed here, I am unable to take a screenshot of the transparent menu but I ran in the same issue.

**Comment by rafaelmardojai** [comment]
> All menus on the toolbar are missing the arrow pointing at the toolbar button. Example screenshot of burger menu:

Firefox as stopped using arrow-boxes, so I need to figure out away to add the arrow, maybe using pseudo-elements.

**Comment by ulipo** [comment]
As a temporary workaround, to get back some menu background it's enough to comment out the following line in theme/parts/popup.css:
```
.menupopup-arrowscrollbox {
/*	background: none !important;*/   <-- COMMENT THIS LINE
	box-shadow: none !important;
	border: 0 !important;
	padding: 0 !important;
	margin: 0 !important;
}
```

**Comment by ceiphr** [comment]
+1 Love the theme! I hope this gets resolved.

**Comment by rafaelmardojai** [comment]
The arrow doesn't seem fixable for now, Anything else is fixed already.
