### ISSUE TITLE
Bug with firefox double click in hamburgur menu.

### ISSUE THREAD

**Issue by Tomoghno** [rafaelmardojai/firefox-gnome-theme#329]
https://user-images.githubusercontent.com/57741324/149673497-cca241b7-25bf-409e-94a7-141d00a3cd5e.mp4

**Comment by rafaelmardojai** [comment]
Hmm, can't reproduce here. Sure this doesn't happen with vanilla firefox? Also, are you using Wayland?

**Comment by rafaelmardojai** [comment]
I'm using Wayland now, but I can't reproduce this. Could someone confirm?
