### ISSUE TITLE
3 dots in the top right of the window where the minimize, maximize, and close buttons should be

### ISSUE THREAD

**Issue by K4LCIFER** [rafaelmardojai/firefox-gnome-theme#332]
As shown in the image below, there's 3 dots in place of where the usual minimize, maximize, and close buttons usually would be:
![image](https://user-images.githubusercontent.com/7829231/149679941-f1be2690-9b17-432d-a23f-fa943acb077e.png)
The buttons functions work as expected (the close button closes, the maximize button maximizes, and the minimize button minimizes), but grapically, they are broken.

**Comment by rafaelmardojai** [comment]
See #305.
