### ISSUE TITLE
Formatting issues with small window sizes

### ISSUE THREAD

**Issue by mdartmann** [rafaelmardojai/firefox-gnome-theme#333]
When split due to small window size, the search engine list ("This time, search with...") in the bottom of the address bar is a bit glitchy.
(tested on latest commit)
![Glitchy search engine list screenshot](https://user-images.githubusercontent.com/76077644/149726547-f5b1d017-e1c7-4a5c-8b5e-fc228d26bcf6.png)

**Comment by mdartmann** [comment]
I found another issue: Also on a small screen size, the settings hamburger menu button overlaps with the minimize button when it's enabled.
![Screenshot from 2022-01-18 08-14-28](https://user-images.githubusercontent.com/76077644/149888828-5b3ee2be-f381-4a27-a34b-9afef9b80834.png)

**Comment by rafaelmardojai** [comment]
The first issue could be fixed by removing the linked style from the buttons.

The second one it's a duplicated of #133.

**Comment by mdartmann** [comment]
Sorry for the dup.
This theme is awesome and I'd like to help more, but I've never worked with themes or UI code in general, so I can't open a PR in good conscience.

**Comment by rafaelmardojai** [comment]
>  This theme is awesome and I'd like to help more, but I've never worked with themes or UI code in general, so I can't open a PR in good conscience.

No problem. I just was writing down the possible approach to fix the issue.

**Comment by rafaelmardojai** [comment]
Closing in favor of #133.
