### ISSUE TITLE
Change to how containers are represented

### ISSUE THREAD

**Issue by VandrerenErik** [rafaelmardojai/firefox-gnome-theme#337]
Hello there, I've modified the code so the contained tabs look like seen below as I consider this more representative of a container instead of the dot you currently use which is most commonly used to represent notifications.

My question is, shall I make a pull request out of this? I don't know if you are interested in this change.
![image](https://user-images.githubusercontent.com/54407345/150646508-18fc3993-ae2c-461c-9e0d-3f9f9f0127c8.png)

**Comment by rafaelmardojai** [comment]
Sorry for the delay.

I agree that the current design might be confusing, but I don't think this solution matches with the Adwaita style. I think we can explore the solutions further.

**Comment by VandrerenErik** [comment]
I actually with you, I recently dropped my change in favour of one made by a friend of mine. His solution is way nicer to the eye and even though it is not something we've seen in gnome I think it is more than acceptable.

![image](https://user-images.githubusercontent.com/54407345/151704850-f45b7af7-fe87-4e06-809e-391085652092.png)

**Comment by mishnea** [comment]
I put the changes VandrerenErik mentioned in [this repo](https://github.com/mishnea/firefox-gnome-tweaks). Right now they are in the `customChome.css` file but if you like the changes, I can change it to include them in the theme and make a PR.

**Comment by rafaelmardojai** [comment]
> I agree with you, I recently dropped my change in favour of one made by a friend of mine. His solution is way nicer to the eye and even though it is not something we've seen in Gnome I think it is more than acceptable.

This definitely looks better, through it looks very similar to the "needs attention" style of Adwaita tabs that I plan to implement at some point:
![tabs-unread](https://user-images.githubusercontent.com/6210397/151833316-f57ca21b-a5f1-4f62-bc2f-95626f788b8e.png)

I have been experimenting with applying a tone-down color background to the tabs, what do you think?

![Captura de pantalla de 2022-01-31 12-36-11](https://user-images.githubusercontent.com/6210397/151844224-2a7f8030-5c4c-4d3d-bcf4-e305ae5369a4.png)

**Comment by VandrerenErik** [comment]
I don't dislike the tone-down background on tab. But I still prefer @mishnea version, I don't think it is that similar to "needs attention"

**Comment by CleoMenezesJr** [comment]
Libadwaita has a new tab, I believe it solves these problems. Later, if Rafael agrees, we will be trying to implement something like this.
![image](https://user-images.githubusercontent.com/54215258/162586866-6d70d9c8-3294-407e-975f-433dbcd5fb64.png)
![image](https://user-images.githubusercontent.com/54215258/162586871-5678e90e-3306-4320-91db-918f0bf537d2.png)
