### ISSUE TITLE
Muting pinned tabs

### ISSUE THREAD

**Issue by VandrerenErik** [rafaelmardojai/firefox-gnome-theme#338]
Muting a pinned tab is impossible and the mute icon is also intrusive/disruptive.

**Comment by rafaelmardojai** [comment]
It looks like this for me:

![Captura de pantalla de 2022-01-31 12-39-18](https://user-images.githubusercontent.com/6210397/151844539-1e0dc968-d134-4909-9456-2e00f7dfc353.png)

And works fine, how it looks for you?

**Comment by VandrerenErik** [comment]
I have this already tweaked and working. I can check again the code without any modifications later on.

**Comment by bdaase** [comment]
Could we make the icon a bit smaller though? It's very hard to click the tab because you always hit the mute symbol...

**Comment by rafaelmardojai** [comment]
> Could we make the icon a bit smaller though? It's very hard to click the tab because you always hit the mute symbol...

True, I will try to reduce the size. Right now it's 16px because it the optimal size for rendering the icon pixel wise.
