### ISSUE TITLE
maia, settings dropdown has incorrect padding/alignment

### ISSUE THREAD

**Issue by iitalics** [rafaelmardojai/firefox-gnome-theme#342]
The settings dropdown menu has obviously incorrect padding issues. 
![Screenshot from 2022-02-02 14-24-56](https://user-images.githubusercontent.com/1772927/152223974-2fd9017e-5b21-4561-b2a4-b6ebc9df7c45.png)

As you can see there is no padding on the edges of this menu or within the buttons, and various components are not aligned correctly (e.g. the `+`/`-` icons).

I am using a relatively new Manjaro install which comes with gnome theme maia:
```
firefox-gnome-theme-maia                     [Installed] 20210918-1   community 
    Adwaita theme with maia highlight color for Firefox
firefox                                      [Installed] 96.0.3-0.1   extra 
    Standalone web browser from mozilla.org
```

**Comment by rafaelmardojai** [comment]
I will guess that maia isn't up to date with the latest changes of the theme.

**Comment by Chrysostomus** [comment]
Okay, it has now been updated. Sorry for such a delay, it took me a good while to notice this!
