### ISSUE TITLE
Private mode not adjusted for libadwaita variant

### ISSUE THREAD

**Issue by the-Mitu** [rafaelmardojai/firefox-gnome-theme#343]
![image](https://user-images.githubusercontent.com/3919854/153433042-b18541a3-33e1-4e1b-af0c-6dd831c22180.png)

For libadwaita variant I see what looks like the same as for the default variant – buttons with borders etc. I would expect borderless buttons etc.

**Comment by CleoMenezesJr** [comment]
Take a look now.

**Comment by the-Mitu** [comment]
Definitely better now, thanks! :)
