### ISSUE TITLE
Can you test the future (libadwaita) version (gtk4) with this theme ?

### ISSUE THREAD

**Issue by BirdInFire** [rafaelmardojai/firefox-gnome-theme#351]
i have found a theme that enable GTk3 app to look like GTK4 with libadwaita, can you use it too when you try the next version (now in beta ?).

https://github.com/lassekongo83/adw-gtk3

This theme can maybe help you to fix thing into the beta (but at least if you can fix the fact that the theme (in the fedora 35) does not really like a non adwaita dark version).

the only think that visually break in my eye when forcing dark mode in firefox/librewolf is the close button (and reduce / maximize) if you have enabled them.

**Comment by CleoMenezesJr** [comment]
Theme customization for Firefox is quite a part of the system theme, for example I was using this adw-gtk3 theme; if moz-apparence is set to none, it even adds the system close button, which in this case would be this theme, but not all users could be using this theme, so it was necessary to create the button from scratch.
One of the things this theme helps is the window borders which help integrate Firefox with firefox-gnome-theme.
