### ISSUE TITLE
Window control buttons are very small

### ISSUE THREAD

**Issue by Kirottu** [rafaelmardojai/firefox-gnome-theme#355]
That is about it, this happens on LibreWolf 98.0.2. Otherwise this seems to be working very well. I am on the beta branch.

Here is a screenshot of this:
![image](https://user-images.githubusercontent.com/56396750/161430481-5697afe8-b973-4a6d-b2e7-dd1b0b64a205.png)

**Comment by CleoMenezesJr** [comment]
This problem is known, I particularly don't know what it could be, but if you go to Firefox settings switch to any theme and go back to System Theme, it works normally again.

**Comment by kabessao** [comment]
Can confirm that the comment above works, it seems to be some compatibility issue with themes in general. Just set set the theme to "System Default" that the issue is solved.

**Comment by rafaelmardojai** [comment]
I guess we could add user_pref("extensions.activeThemeID", "default-theme@mozilla.org"); to configuration/user.js as a possible solution.
