### ISSUE TITLE
Dropping gnome-icons.css

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/firefox-gnome-theme#36]
Soon GNOME icons will be included in theme as SVG to fix #8. And Adwaita icon theme will be "hardcoded".

So `gnome-icons.css` main functionality will be included by default.

But I'm considering create `system-icons.css`, with similar functionality, for the ones not using Adwaita icons and want to use their system icon theme. But facing `moz-icon://stock/` issues.

**Comment by lionirdeadman** [comment]
Why would the code using the SVG not be simply put in gnome-icons.css?

**Comment by rafaelmardojai** [comment]
`gnome-icons.css` was out of "core" because it was partially broken, the SVG implementation will not.
So no reason to continue out. Or do you think most people prefer default Firefox icons?

**Comment by lionirdeadman** [comment]
Ah, I see. I never knew it was partially broken. Then sure, I don't see a problem

**Comment by lionirdeadman** [comment]
This seems to give a lot of icons a dark color :/

**Comment by rafaelmardojai** [comment]
:/ Screenshot?

**Comment by lionirdeadman** [comment]
![Screenshot-20190716210255-1279x45](https://user-images.githubusercontent.com/39467792/61339735-20cf2b80-a80d-11e9-911f-36a78854aee2.png)
 :/

**Comment by rafaelmardojai** [comment]
Are you using `system-icons.css` or default?

**Comment by lionirdeadman** [comment]
Default although my customChrome.css has 

```@import "theme/hide-single-tab.css";
@import "theme/matching-autocomplete-width.css";
@import "theme/hide-single-tab.css";
@import "theme/matching-autocomplete-width.css";
@import "theme/hide-single-tab.css";
@import "theme/matching-autocomplete-width.css";
@import "theme/gnome-icons.css"
````
(Duplication caused by the script, should probably fix that unless we tell users to update the git from the profile dir instead of using the script all the time)

**Comment by lionirdeadman** [comment]
Adding system-icons.css fixed it.

**Comment by rafaelmardojai** [comment]
> Adding system-icons.css fixed it.

No, it should work without it. But anyways now is fixed, a colon was missing xD

**Comment by rafaelmardojai** [comment]
We should add a `update` script.

**Comment by lionirdeadman** [comment]
An update script can't really work without duplication.

**Comment by rafaelmardojai** [comment]
Why? It only should run `git pull origin master` and maybe remove profile cache if needed.

**Comment by rafaelmardojai** [comment]
It will not work for forks, but will make the work for regular users.

**Comment by lionirdeadman** [comment]
Because the update script itself can't be updated

Let's say, I have a copy in ~/Downloads which I use to update, this update script can never be updated unless we update (with git pull) both the ~/Downloads copy *and* the profile directory's copy.

**Comment by rafaelmardojai** [comment]
What about creating the `gnomish-optional-features.css` file?
```css
@import "theme/hide-single-tab.css"; 
@import "theme/matching-autocomplete-width.css";
```

Then check with `grep` if `@import "gnomish-optional-features.css";` exists in `customChrome.css` before adding it.

Also check if `firefox-gnome-theme` exists, en delete it before coping.
