### ISSUE TITLE
Show tab title in url bar when tabs are hidden

### ISSUE THREAD

**Issue by marcel2789** [rafaelmardojai/firefox-gnome-theme#360]
This optional feature would only work with `gnomeTheme.hideSingleTab` enabled.
It would look like this:
![image](https://user-images.githubusercontent.com/50751553/163364879-85e4e716-af06-4391-abb4-2917d28e4d62.png)
If you click on the url bar, the url would appear again.
![image](https://user-images.githubusercontent.com/50751553/163364995-2c7adf0f-42a5-43c7-aa56-a28f6caaf603.png)
If 2 tabs or more are open, it would show the url again.
![image](https://user-images.githubusercontent.com/50751553/163365112-a683af45-7861-4444-941d-e2dc8b47e221.png)

I'm aware that isn't how it works in Epiphany, but it would be a cool little feature to add.

**Comment by CleoMenezesJr** [comment]
Even with gnome Theme.hide Single Tab how do I make this happen?

**Comment by rafaelmardojai** [comment]
This isn't possible without JS being involved. So if you want this, you will need to create an extension.

**Comment by marcel2789** [comment]
Thanks for the response. I'll look more into how to create an extension.

**Comment by rafaelmardojai** [comment]
> Thanks for the response. I'll look more into how to create an extension.

Nice! Feel free to share it here if you get to it.
