### ISSUE TITLE
screenshot.png is of the GTK3 version.

### ISSUE THREAD

**Issue by starship-boi** [rafaelmardojai/firefox-gnome-theme#362]

**Comment by rafaelmardojai** [comment]
And the current stable theme is mimicking GTK3.

**Comment by starship-boi** [comment]
But I'm talking about the libadwaita branch. The libadwaita branch has a screenshot of the GTK3 version; the exact same screenshot as the stable version. I thought that the libadwaita branch already looked at least somewhat different.

**Comment by starship-boi** [comment]
Sounds good. Should I close this issue or keep it open as a reminder to update the screenshots eventually?
Also, this is a great tool, keep up the good work :smile:.

**Comment by CleoMenezesJr** [comment]
There are visual fixes that still need to improve to have this. But we are not that far from that.
