### ISSUE TITLE
Search engine text in search bar is a bit unreadable

### ISSUE THREAD

**Issue by mizzunet** [rafaelmardojai/firefox-gnome-theme#363]
![image](https://user-images.githubusercontent.com/10193999/163766797-e0a0f4ad-629a-43b2-ae67-c19f48690931.png)

Isn't it better to have some light colour?

**Comment by mizzunet** [comment]
`#urlbar-search-mode-indicator-title`

**Comment by rafaelmardojai** [comment]
Update to follow the Adwaita [tagged entries mock up](https://gitlab.gnome.org/Teams/Design/os-mockups/-/blob/master/tagged-entries/tagged-entries.png).

![Captura desde 2022-05-22 10-26-09](https://user-images.githubusercontent.com/6210397/169703172-3e9fa3d8-fc9f-4b75-9dbb-e69570765515.png)

**Comment by rafaelmardojai** [comment]
I guess we could add `user_pref("extensions.activeThemeID", "default-theme@mozilla.org");` to `configuration/user.js` as a possible solution.
