### ISSUE TITLE
Bookmark folder icons have poor visibility with dark theme

### ISSUE THREAD

**Issue by bbhtt** [rafaelmardojai/firefox-gnome-theme#364]
The dark on dark harms visibility in my opinion:

![image](https://user-images.githubusercontent.com/62639087/163820296-cbfc1dd7-157e-4e45-801d-18fd2b2d8045.png)

Maybe it would be better to switch them to Gnome 42 folder colour in Nautilus: blue (if doable)...

![image](https://user-images.githubusercontent.com/62639087/163820553-3eaf64be-8690-415d-94a2-e3f2ef6fa79a.png)

Or the default white outline:

![image](https://user-images.githubusercontent.com/62639087/163821451-ea266aa8-40b0-4a9f-a40c-0eecffa31bbd.png)

**Comment by rafaelmardojai** [comment]
Actually, they should be white in dark theme, so seems like something is broken.

**Comment by bbhtt** [comment]
With the new Adwaita style they now look like this: 

![image](https://user-images.githubusercontent.com/62639087/170030301-12862a1a-c2dd-413b-a35b-3963fd381197.png)

**Comment by rafaelmardojai** [comment]
> With the new Adwaita style they now look like this:

Yeah, that's the new folder icon from GNOME.

The thing is that I still can't reproduce the issue:
![Captura desde 2022-05-24 07-50-44](https://user-images.githubusercontent.com/6210397/170039149-143f3da4-f0d3-484f-9c4c-31ebf81928e9.png)

Could you give us more info about your setup? Also, this is the only icon that shows up black right?

**Comment by bbhtt** [comment]
What do you mean by setup? I'm on GNOME 42 Wayland, theme is Adwaita and using Firefox Nightly. I think I saw the same issue in release but I can check again.

These are theme related prefs I have:

```
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);    
user_pref("svg.context-properties.content.enabled", true;                  
user_pref("gnomeTheme.hideSingleTab", true);                               
user_pref("gnomeTheme.activeTabContrast", true);                           
user_pref("gnomeTheme.hideWebrtcIndicator", true);                          
user_pref("gnomeTheme.bookmarksToolbarUnderTabs", true);         
```

**Comment by bbhtt** [comment]
Yea same thing in Firefox release as well 100.1

**Comment by bbhtt** [comment]
Ah yea I found the issue. My user.js had a syntax error `user_pref("svg.context-properties.content.enabled", true;` didn't have a closing `)`, so that pref was never being turned on. Without that enabled, the icons turn black, turning it on fixed it.

Sorry for not checking it earlier. And thanks!
