### ISSUE TITLE
Update banner text is misaligned

### ISSUE THREAD

**Issue by bbhtt** [rafaelmardojai/firefox-gnome-theme#365]
![Screenshot from 2022-04-21 18-17-01](https://user-images.githubusercontent.com/62639087/164461600-53dd534a-0590-4343-819d-dbfd1850b98d.png)

It's a bit closer to the top edge of the banner than the bottom and aligned to the left. I think it should be centered or moved more to the left to match rest of the items in the hamburger menu? 

FF Nightly 101.0a1 (2022-04-20)
Theme. master/https://github.com/rafaelmardojai/firefox-gnome-theme/commit/e8f93b9b3456c13356f17aae7c8abb99195d12ec

**Comment by CleoMenezesJr** [comment]
I really can't identify where this is.

**Comment by bbhtt** [comment]
Perhaps it is a bit clear in the new theme style

![image](https://user-images.githubusercontent.com/62639087/170032688-9ccb9b88-79ed-4530-bbec-30be00ab6079.png)

> I really can't identify where this is.

Do you mean where the banner appears?
