### ISSUE TITLE
(libadwaita branch) bookmarks toolbar not colour matched

### ISSUE THREAD

**Issue by winkelnp** [rafaelmardojai/firefox-gnome-theme#367]
You most likely know about this, but I couldn't find anything about this, so I thought an issue/feature request would be in order.

In both light and dark modes the bookmarks toolbar is not yet colour matched to the stylesheet of libadwaita.

Dark mode:
![dark mode](https://user-images.githubusercontent.com/68015877/166076873-cb8ec5c9-3a7c-461d-a6d7-29d34828afff.png)
Light mode:
![light mode](https://user-images.githubusercontent.com/68015877/166076992-f33fb8e8-8a14-4de6-995a-f0f02a5842d7.png)

**Comment by CleoMenezesJr** [comment]
Thanks for letting me know. The Libadwaita version is still WIP, some things still need some love and others still haven't been touched, bookmarks is one of them.

**Comment by winkelnp** [comment]
You're probably already aware, but hovering over a bookmark in the light mode bookmark toolbar does not give the highlight like the elements in the main top bar.

**Comment by CleoMenezesJr** [comment]
Thanks, I think I forgot to send some commits. See now how it is.
