### ISSUE TITLE
Tab resize and place behaviour

### ISSUE THREAD

**Issue by mthomos** [rafaelmardojai/firefox-gnome-theme#37]
Can you keep the default tab resize and place behaviour ? The whole of resizing and moving tabs is frustating

**Comment by lionirdeadman** [comment]
Epiphany has recently done this (and they're not sure if they want to keep it if I remember correctly) but Firefox doesn't resize until the cursor is removed from the tab area so it's not been a problem to me. Unsure if we should follow.
