### ISSUE TITLE
make the tab bar hidden when theres only 1 tab like in gnome web

### ISSUE THREAD

**Issue by OldWorldOrdr** [rafaelmardojai/firefox-gnome-theme#374]
and move the new tab button next to the refresh button (also like gnome web)

**Comment by rafaelmardojai** [comment]
Checkout https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features, we have a optional preference for that. And you have to manually move the new tab button.

**Comment by OldWorldOrdr** [comment]
@rafaelmardojai thanks so much!!!
