### ISSUE TITLE
[Libadwaita] Mimic the GTK 4 context menu.

### ISSUE THREAD

**Issue by CleoMenezesJr** [rafaelmardojai/firefox-gnome-theme#377]
![image](https://user-images.githubusercontent.com/54215258/168944808-aa09e908-b687-4112-a54b-d2ff7eb7575e.png)

How it should look like:

![image](https://user-images.githubusercontent.com/54215258/168945105-3b99ec8a-f1d5-4e6f-bb8d-ddb45dd79e7e.png)

**Comment by rafaelmardojai** [comment]
We also will need to update the checkbox/radio icons that are displayed in context menus.

**Comment by rafaelmardojai** [comment]
> Is it possible to modify context menus to behave like GTK4 ones? For example, on bookmarks folders you get the classic way of navigating through it (new menu opens on a folder), but on GTK4 the whole context menu shifts to the left and the new menu replaces the old one.
> 
> The same way it works on the Firefox account context menu.

Not really, not with just CSS. 

Only the Firefox panels (popovers) have that behavior. But maybe someone could ask them to repeat that in the menus.
