### ISSUE TITLE
Container colors calls more attention than active tab color indication

### ISSUE THREAD

**Issue by semente** [rafaelmardojai/firefox-gnome-theme#38]
I find hard to find the active tab in the tabs bar because it is obfuscated by the container colors which is larger and brighter. 

![2019-07-13-094712_1074x580_scrot](https://user-images.githubusercontent.com/29862/61171831-7802a100-a56c-11e9-9ea3-19adf45f3487.png)

**Comment by rafaelmardojai** [comment]
I open to suggestions. We just change it to less brighter colors? Or we can implement a new design?

**Comment by lionirdeadman** [comment]
We can't change the colors unless we pass a filter over them but it would defeat the purpose of customizable container colors since they'd be modified by us afterwards.

A new design might be worth thinking about.

**Comment by rafaelmardojai** [comment]
Firefox has a class per container color (for example `identity-color-blue`), and set color with  ` --identity-tab-color` variable, so changing colors is easy.

**Comment by rafaelmardojai** [comment]
Dropping some options...
![Captura de pantalla de 2019-07-13 17-23-36](https://user-images.githubusercontent.com/6210397/61177617-78685f80-a59f-11e9-8fb9-46d90e2534d8.png)
![Captura de pantalla de 2019-07-13 18-50-09](https://user-images.githubusercontent.com/6210397/61177618-78685f80-a59f-11e9-81ab-d5c9f7a00638.png)

**Comment by lionirdeadman** [comment]
The second option most likely doesn't work with tabs with no icon and I personally prefer the first option.

Would it be possible to put the colored circle on the top-right of the icon? (not bottom-right since that is sometimes used for notifications)

**Comment by rafaelmardojai** [comment]
Like this?
![Captura de pantalla de 2019-07-13 20-37-42](https://user-images.githubusercontent.com/6210397/61178226-385ca900-a5ae-11e9-9bb6-28e9a5441a01.png)

**Comment by lionirdeadman** [comment]
Yup, exactly!, that looks pretty good to me.

**Comment by semente** [comment]
Awesome! Thanks!
