### ISSUE TITLE
Bookmark star menu has no padding

### ISSUE THREAD

**Issue by winkelnp** [rafaelmardojai/firefox-gnome-theme#381]
Title. 

Here are some images:
Dark:
![Screenshot from 2022-05-19 20-38-45](https://user-images.githubusercontent.com/68015877/169388864-d8d491f8-23bb-4cd3-b58d-047d2b919588.png)

Light:
![Screenshot from 2022-05-19 20-40-35](https://user-images.githubusercontent.com/68015877/169389198-275e73f7-3d5a-4019-ae64-b9e2041f3fb6.png)

On another note, the text on the "go back" button in light mode seems to stay light...

**Comment by rafaelmardojai** [comment]
Yeah, I'm aware of this.

I'm doing some small progress everyday (a bit busy with work). But next thing will be definitely this.
