### ISSUE TITLE
Active tab visibility very low due to the low contrast

### ISSUE THREAD

**Issue by saligari** [rafaelmardojai/firefox-gnome-theme#383]
Hello,

Thanks for your work on this theme, really appreciate it. My one issue, is that I can't easily tell which tab is active.

~~I don't know if you're using set colors for the background or transparent black for inactive tabs like libadwaita does, however the results are different:~~

~~Libadwaita in light, has #ebebeb for background tabs & #f5f5f5 for active, whereas this theme has #e1e1e1 for background and #ebebeb for active.~~

~~Perhaps because you're using a different grey bg for firefox (#ebebeb instead of #f5f5f5 which I see gnome-text-editor uses).~~ 

Anyway, libadwaita is changing: 

![imagen](https://user-images.githubusercontent.com/14283056/169503022-391a4ef4-d66b-4652-a9d3-010fd32a180c.png)

![imagen](https://user-images.githubusercontent.com/14283056/169503084-a70ff1e5-8ee8-4d59-8420-3ba75250f9e2.png)

probably resulting in better contrast.

**Comment by rafaelmardojai** [comment]
We have the `gnomeTheme.activeTabContrast` optional feature (https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features), though I haven't tested in the libadwaita update, so maybe needs some fixing.

About this new tabs style, it's planned, but after it reaches a libadwaita stable release.
