### ISSUE TITLE
[Libadwaita] Save/edit bookmark menu looks wrong

### ISSUE THREAD

**Issue by proninyaroslav** [rafaelmardojai/firefox-gnome-theme#386]
Here is what I found (latest `beta` branch):
![2022-05-21 20-46-20](https://user-images.githubusercontent.com/7840559/169663504-f1088793-e080-4e2c-a4cb-72e2f782595e.png)
 - No padding
 - Wrong text color of the `Remove bookmark` button
 - Strange looking dropdown arrows
 - `New folder` button doesn't have libadwaita style (screenshot below)

![New folder](https://user-images.githubusercontent.com/7840559/169663559-61c921b1-a93d-467f-9f9a-08c4edf1d91b.png)

**Comment by proninyaroslav** [comment]
Sorry, I got this on the master branch and it seems that part of the problem is solved. The following problems remain:
 - Strange looking dropdown arrows
 - `New folder` button doesn't have libadwaita style

**Comment by CleoMenezesJr** [comment]
The Bookmark was fixed:
![image](https://user-images.githubusercontent.com/54215258/169672574-e48d43cc-4f9b-4f3b-8f85-f11e2fe8f927.png)

> New folder button doesn't have libadwaita style (screenshot below)

Personally, I haven't tried to customize it yet, but I believe that Rafael has some reason to be like that.

> Wrong arrows

Quite weird. This arrow is not used in the theme, have you tried deleting the folder and re-installing F-G-T from scratch?

> Wrong search bar padding

This has not yet been touched, but we are aware.

**Comment by rafaelmardojai** [comment]
Sorry, forgot to rebase beta, should be update now.


>     Strange looking dropdown arrows
>     New folder button doesn't have libadwaita style

Fixed.


> There are also problems in the bookmarks menu:

This is he Library window, so opened a new issue (#387).
