### ISSUE TITLE
Scrollbar theming is broken/bugged in some places

### ISSUE THREAD

**Issue by lionirdeadman** [rafaelmardojai/firefox-gnome-theme#39]
- [ ] ~Sidebar is always "hovered"~
- [x] Bookmarks/Library has a darker scrollbar resulting in low visibility of it, it also looks skinnier.

**Comment by rafaelmardojai** [comment]
> Sidebar is always "hovered"

Scrollbar theming is not applied in sidebar. I need to find a way.

> Bookmarks/Library has a darker scrollbar resulting in low visibility of it, it also looks skinnier.

Please provide screenshot.

**Comment by rafaelmardojai** [comment]
I see. In general looks like pop-ups scrollbars are broken.

**Comment by tominventisbe** [comment]
Just came here to mention the same: if you have an overlay in a page with a higher z-index than where a scrollbar is, the scrollbar below will show on top of the overlay.

I also experience an oddity where if you move your cursor right as far as possible (and the window is maximized on GNOME), and then move the mouse up and down between the part that contains the slider and the part that is empty, the scrollbar flickers:

![peekKXFJ4Z](https://user-images.githubusercontent.com/11189195/61219241-17ae6380-a714-11e9-99b8-32519615af8e.gif)

Finally, not sure if this is possible in Firefox, but the original GNOME scrollbar animation is animated with a very fast animation, which makes it less abrupt:

![peekUV6Z4Z](https://user-images.githubusercontent.com/11189195/61219358-56441e00-a714-11e9-8117-1be72c5dc91d.gif)

**Comment by rafaelmardojai** [comment]
>  if you have an overlay in a page with a higher z-index than where a scrollbar is, the scrollbar below will show on top of the overlay.

Can you try sey `layout.css.moz-document.content.enabled` to `true` in the `about:config` settings?

**Comment by tominventisbe** [comment]
I tried changing it and restarting Firefox, but it didn't seem to help.

**Comment by rafaelmardojai** [comment]
Looks like everything is fixed now.
You probably will need to remove you profile folder inside `~/.cache/mozilla/firefox/` before re-opening Firefox to see the changes  (This won't erase your settings, sessions, etc...).

About Sidebar, it's impossible to fix, `:hover` doesn't work right in `hbox` scrollbars.

**Comment by lionirdeadman** [comment]
That animation works in pop-up but not in webview, it kinda stutters, I've deleted the cache.

**Comment by rafaelmardojai** [comment]
It also stutters to me, the interesting thing is that it only happens with document root scrollbars...
But when i tried to record it to show the difference, in the record all looks good. 🤔

![Peek 15-07-2019 17-36](https://user-images.githubusercontent.com/6210397/61253884-33bc0000-a728-11e9-9f12-a52545360172.gif)

Probably related to `z-index: 2147483647;` needed for root scrollbars to work.

**Comment by tominventisbe** [comment]
Can confirm that the commits fix the issue with scrollbars in overlays 🎉 .

The animation looks fairly accurate, too, which is nice.

I occasionally get the stutter mentioned by @rafaelmardojai too, as well as the original issue where the scrollbar flickers when the window is maximized and you move the mouse to the far right, though it doesn't seem to happen for all scrollbars; it does on GitHub, for example, but not one of my own projects, which may be because the scrollbar there is inside the page and not for the entire page (it doesn't span the entire viewport vertically).

**Comment by lionirdeadman** [comment]
Just noticed but if there's a scrollbar *and* a resize element then it can go crazy when hovering over the resizing element. (You can try this in Github issues)

**Comment by rafaelmardojai** [comment]
Not related to `z-index: 2147483647;`, it also happens with `z-index: 1;`.

**Comment by rafaelmardojai** [comment]
Looks like some Firefox animation render bug with root scrollbars...

**Comment by tominventisbe** [comment]
It does appear to be some kind of Firefox bug. It is almost as if Firefox does not register the mouse if it is at the far right edge of the screen and it is maximized.

Does anyone happen to have a Firefox bug that can be tracked?

**Comment by lionirdeadman** [comment]
@tominventisbe The problem is we need to find the equivalent in non-themed Firefox for it to be a valid to them AFAIK since userChrome.css is not supported by them which is why no upstream bug was made for any of our bugs labelled upstream.

**Comment by tominventisbe** [comment]
Ah, I see, thanks for letting me know.

If the problem was some kind of "hover state not triggered on scrollbars for last horizontal pixel", which would also apply to non-themed Firefox, you would have been able to fob it off on Bugzilla as a genuine bug report 😄.

**Comment by rafaelmardojai** [comment]
Looks like scrollbars theming stopped to work in FF 71+

**Comment by rafaelmardojai** [comment]
Scrollbars theming moved to https://github.com/rafaelmardojai/firefox-gnome-scrollbars
