### ISSUE TITLE
sidebar in newtab page is translucent

### ISSUE THREAD

**Issue by soppyMann** [rafaelmardojai/firefox-gnome-theme#391]
![Screenshot from 2022-05-23 18-36-20](https://user-images.githubusercontent.com/65861874/169857120-f6b04f55-0b41-431b-94b0-f25b2f9b9d74.png)

this is happening with the latest commit https://github.com/rafaelmardojai/firefox-gnome-theme/commit/c8ad4341c15e152eac479e22d75babfe928c22de

on FF developer edition 101.0b9

**Comment by TomBursch** [comment]
My bad, did not realize the button background color is this transparent
