### ISSUE TITLE
Strange looking close button

### ISSUE THREAD

**Issue by hrqmonteiro** [rafaelmardojai/firefox-gnome-theme#394]
![Screenshot from 2022-05-25 22-25-15](https://user-images.githubusercontent.com/17055027/170395991-3e5cb64d-32cf-4e79-aac3-51d60e9d2685.png)

Is this supposed to look like this? (I'm on Fedora 36, Gnome 42)

**Comment by rafaelmardojai** [comment]
Probably a duplicated of #355.

Are you using the default/system theme in Firefox? This issue usually happens when you don't.

**Comment by rafaelmardojai** [comment]
> Are you using the default/system theme in Firefox? This issue usually happens when you don't.

This still stands as a general recommendation, but just pushed a fix for this.
