### ISSUE TITLE
[Libadwaita] "Choose an app to open the link" dialog looks wrong

### ISSUE THREAD

**Issue by proninyaroslav** [rafaelmardojai/firefox-gnome-theme#395]
Tested on `master` branch.
![2022-05-27 18-50-52](https://user-images.githubusercontent.com/7840559/170735253-593e32da-39b0-4d0e-a70a-6151008cacd8.png)
![2022-05-27 18-50-59](https://user-images.githubusercontent.com/7840559/170735255-c3b14cff-9c17-454b-a7d0-e7286c3cd771.png)
1. The positive button looks as inactive, even though it's not.
2. No app icons on the start side (maybe it's a Firefox bug, I don't remember exactly)
3. Selection appears to be clipped

**Comment by rafaelmardojai** [comment]
Yeah, I'm aware of this, dialogs are broken in general right now,
