### ISSUE TITLE
Bookmarks tags suggestion lists are not correct place

### ISSUE THREAD

**Issue by queeup** [rafaelmardojai/firefox-gnome-theme#397]
![Ekran Görüntüsü - 2022-05-28 20-08-09](https://user-images.githubusercontent.com/87835/170837007-cae9398a-84a1-410b-b6d1-4a70ad09e365.png)

**Comment by rafaelmardojai** [comment]
It looks right for me. Could you test with the latest theme version?
![Captura desde 2022-07-28 11-23-48](https://user-images.githubusercontent.com/6210397/181589009-0013c557-6836-4650-95e6-59e3255446f4.png)

**Comment by queeup** [comment]
I will test it next week and inform you.

**Comment by queeup** [comment]
It's working correct atm. Thank you.
