### ISSUE TITLE
Adapt to new Libadwaita active tab style

### ISSUE THREAD

**Issue by octowaddle** [rafaelmardojai/firefox-gnome-theme#398]
Recently, Libadwaita changed the way the active tab is highlighted and this theme should adapt it.
This is a screenshot of the GNOME Web GTK4/Libadwaita port with the new style:

![GNOME Web GTK4/Libadwaita Port with the new active tab style](https://user-images.githubusercontent.com/77749247/171996029-a7c48458-43f7-47ae-ba35-60beee2c2cc0.png)

**Comment by proninyaroslav** [comment]
I agree, it looks more contrasting. Sometimes I confuse active tab.

**Comment by rafaelmardojai** [comment]
It's planned, but for what I know, this haven't reached a stable release yet.

**Comment by p-mitana** [comment]
I'll add something to this:

![image](https://user-images.githubusercontent.com/3919854/186649813-8523cd2e-4a40-4b91-8166-d76cb00354c7.png)

Which tab is currently active? It's not easy to tell and the left one is not – I just use the Facebook Container extension.

The new design might need a different approach to marking contexts. My suggestion is the gradiented highlight from the bottom of the tab (full width of the tab). A rounded rectangle of the active tab would land over it – either opaque or semi-transparent. Even if it was opaque, the contexted border around will still be visible. Additionally it won't interfere with the mark on a tab that wants my attention.

**Comment by k-kirill** [comment]
GNOME 43 has been released with the new tab style in Files, Console, etc and it is been updated in openSUSE Tumbleweed, so please consider implementing it.

**Comment by rafaelmardojai** [comment]
> GNOME 43 has been released with the new tab style in Files, Console, etc and it is been updated in openSUSE Tumbleweed, so please consider implementing it. P.S. Thanks for maintaining the theme.

I usually make the changes when they arrive to Fedora stable, because that's when they bother me. But will try to find the time to fix this early since this is a highly requested thing.

**Comment by rafaelmardojai** [comment]
Progress is being done in the [`libadwaita-1.2`](https://github.com/rafaelmardojai/firefox-gnome-theme/tree/libadwaita-1.2) branch.
