### ISSUE TITLE
Bookmarks and History have a much longer pop-up compared to Library's

### ISSUE THREAD

**Issue by lionirdeadman** [rafaelmardojai/firefox-gnome-theme#40]
Title says it at all.

**Comment by rafaelmardojai** [comment]
Screenshot? I don't get it.

**Comment by lionirdeadman** [comment]
Library :
![Screenshot-Library](https://user-images.githubusercontent.com/39467792/61179882-2bee4580-a5da-11e9-97de-5be8131b735f.png)

Bookmarks : 
![Screenshot-Bookmarks](https://user-images.githubusercontent.com/39467792/61179883-2bee4580-a5da-11e9-9de3-88c5860e7f6e.png)

**Comment by rafaelmardojai** [comment]
That isn't Firefox default behavior?

**Comment by lionirdeadman** [comment]
It is default behaviour, do we want to follow this though?

**Comment by rafaelmardojai** [comment]
Something like this should do the trick?
```css
panel[type=arrow] {
	max-height: 80vh !important;
}
```

**Comment by lionirdeadman** [comment]
I'm unsure if this is the same as the library panel but if so, yeah?

**Comment by rafaelmardojai** [comment]
It will prevent all popups from growing to much.

**Comment by lionirdeadman** [comment]
There's still a small difference between both but it looks much better with that.

**Comment by rafaelmardojai** [comment]
I know, looks like there's Firefox javascript involved in popups subviews height calculating. So that's the best we can do with CSS. But i think a large GTK popover subview will behave similar to Firefox.
