### ISSUE TITLE
Sharp corners after updating to Firefox 101

### ISSUE THREAD

**Issue by belenos** [rafaelmardojai/firefox-gnome-theme#400]
![Screenshot from 2022-06-04 12-34-44](https://user-images.githubusercontent.com/1954831/172013336-8e9e996e-eb76-4151-ba68-2e450ff5d7b4.png)

I'm using the adwaita version of the gnome theme, on Wayland, layers.acceleration.force-enabled set to true. After updating to Firefox 101, this week, I've got these sharp corners.

I've even tried a new Firefox profile (the screenshot above). The default theme looks fine, but after installing the Gnome theme again, the sharp corners come back.

**Comment by proninyaroslav** [comment]
I'm seeing something similar in Fedora 36 and Firefox 101 on the `master` branch. I see sharp corners in a very short moment of time when I go from window maximize mode. But after the animation ends, the corners disappear.

**Comment by rafaelmardojai** [comment]
This is a known bug, have you tried some of the[ posibles solutions](https://github.com/rafaelmardojai/firefox-gnome-theme#csd-have-sharp-corners)?

**Comment by belenos** [comment]
Yes. None of the solutions listed works on Firefox 101 or newer for me (Arch Linux/Wayland). Reverting to Firefox 100 fixes it, but that's not really a fix lol.

**Comment by belenos** [comment]
Problem persists on Firefox 107, fresh install of EndeavourOS/Arch Linux with Gnome 43.1 on Wayland, even with layers.acceleration.force-enabled set to true. Very annoying. 
![Screenshot from 2022-11-23 09-10-27](https://user-images.githubusercontent.com/1954831/203545105-4d29539d-e3ea-47dc-a3d4-b17f650497a9.png)

I've tried alternative themes as well, to see if something changes. Doesn't make a difference. 
![Screenshot from 2022-11-23 09-19-20](https://user-images.githubusercontent.com/1954831/203545546-c4837126-9820-4451-9a5d-4bd5ee29d54b.png)

The About window looks alright tho. 
![Screenshot from 2022-11-23 09-23-02](https://user-images.githubusercontent.com/1954831/203546026-14c6e857-49bb-4c1b-9806-88a135206f82.png)

**Comment by rafaelmardojai** [comment]
> Problem persists on Firefox 107, fresh install of EndeavourOS/Arch Linux with Gnome 43.1 on Wayland, even with layers.acceleration.force-enabled set to true. Very annoying.

I have the same setup but on Fedora, and the borders looks rounded. I don't have `layers.acceleration.force-enabled ` set.

![Captura desde 2022-11-23 08-56-17](https://user-images.githubusercontent.com/6210397/203564744-9b13dfb3-459d-4619-99d8-6b362a658375.png)


> I've tried alternative themes as well, to see if something changes. Doesn't make a difference.

This has nothing to do with themes, it's a bug with Firefox not making the window transparent.

> The About window looks alright tho.

Yeah, that's expected, that window will use the system titlebar.

**Comment by rafaelmardojai** [comment]
Could you confirm if this also happens to you with Firefox vanilla?

**Comment by laech** [comment]
I can confirm this happens under Ubuntu 22.10 as well with Firefox 107 and this theme (default Firefox themes don't have this problem), a workaround is to use https://extensions.gnome.org/extension/5237/rounded-window-corners/ on top of this to get rid of the corners.

**Comment by belenos** [comment]
> I can confirm this happens under Ubuntu 22.10 as well with Firefox 107 and this theme (default Firefox themes don't have this problem), a workaround is to use https://extensions.gnome.org/extension/5237/rounded-window-corners/ on top of this to get rid of the corners.

This does fix it. Thank you!

**Comment by cewbdex** [comment]
Is this still an issue? Works fine on my Fedora 39.
