### ISSUE TITLE
Visual feedback when page is loading in single tab mode

### ISSUE THREAD

**Issue by tcsiqueira** [rafaelmardojai/firefox-gnome-theme#404]
When we are not using Firefox with multiple tabs, there is no visual feedback when a website is loading. For multiple tabs, we can see the website icon switch to a "loading icon".

It would be nice if there is some element showing that the page is in "loading state".

**Comment by im-viriv** [comment]
Gnome Web implements a loading bar under the Address bar but i suppose adding a spinner in the Address bar also works if making a loading bar is too much of a hassle or simply not possible

**Comment by rafaelmardojai** [comment]
Duplicated of #231.
