### ISSUE TITLE
Compatible with Firefox 102?

### ISSUE THREAD

**Issue by NotCoolKiwi** [rafaelmardojai/firefox-gnome-theme#409]
Is this compatible with Firefox 102? It's breaking quite a few custom CSS, as you can see on r/FirefoxCSS. I would like to know if this is going to work before I update, since it isn't a vulnerability ATM, thank you!

**Comment by rafaelmardojai** [comment]
Yeah, I'm running `master` in 102 and haven't noticed anything broken yet.

**Comment by NotCoolKiwi** [comment]
Thank you! It's working for me as well.
