### ISSUE TITLE
There should be a gap here.

### ISSUE THREAD

**Issue by Fatih20** [rafaelmardojai/firefox-gnome-theme#41]
![Screenshot-20190714155740-391x473](https://user-images.githubusercontent.com/51940383/61181407-5975d600-a650-11e9-8cc9-f134f8bf15ce.png)
THe gap between the title on the title bar and the buttons is non-existent and it's not pleasing.

**Comment by rafaelmardojai** [comment]
That's Firefox native titlebar. Please report to Mojave theme.
