### ISSUE TITLE
Decrease padding on Firefox Account button

### ISSUE THREAD

**Issue by polyjitter** [rafaelmardojai/firefox-gnome-theme#411]
Currently, the Firefox Account button uses the same padding as every other button. This leads to it looking very small, as it is a full color avatar. It would be nice to have that padding reduced, and perhaps a custom hover shape provided.

![image](https://user-images.githubusercontent.com/18127936/177021967-8aae7881-fffa-48d7-ae83-47fdf261ddf8.png)

**Comment by rafaelmardojai** [comment]
Yeah, I guess we should decrease the padding a bit to get something similar to what Fractal has:
![Captura desde 2022-07-03 11-45-05](https://user-images.githubusercontent.com/6210397/177049343-836059e4-d32b-4e55-be70-72fe8ca34052.png)
