### ISSUE TITLE
GTK3 icons

### ISSUE THREAD

**Issue by marcinjahn** [rafaelmardojai/firefox-gnome-theme#413]
I just installed the theme with the one-liner, as shown in the repo README. Here's the result:

![image](https://user-images.githubusercontent.com/10273406/177206789-656d9275-1da1-4c1d-93c7-31e8724c74f5.png)

The icons are GTK-3 style, not libadwaita. Why is that? I have adw-gtk3-dark enabled in Gnome Tweaks for legacy apps, and it works properly in apps like Nautilus or Terminal.
I enabled the setting that hides the tabbar when just one tab is there. It looks weird in my case.

What's wrong?

**Comment by rafaelmardojai** [comment]
> I just installed the theme with the one-liner, as shown in the repo README. Here's the result:

Those icons are the same from GTK4. If you mean the theme appearance, yes, the one-liner command installs the last stable version of the theme, and that last version is following the GTK3 style. If you use the `master` version you will get the GTK4/libadwaita version (I'm probably releasing the new version today).

> I have adw-gtk3-dark enabled in Gnome Tweaks for legacy apps

This theme has nothing to do with your installed GTK theme. We recreate the whole GNOME apps appearance in CSS.

>  I enabled the setting that hides the tabbar when just one tab is there. It looks weird in my case.

The README clearly says:

> Note: You should move the new tab button somewhere else for this to work, because by default it is on the tab bar too. See https://github.com/rafaelmardojai/firefox-gnome-theme/issues/54.
