### ISSUE TITLE
Bookmark bar very bright

### ISSUE THREAD

**Issue by Tealk** [rafaelmardojai/firefox-gnome-theme#415]
Hello,

I find that the brightness of the bookmarks bar is too high.

![image](https://user-images.githubusercontent.com/12276250/178142111-18e61f9e-9558-4aa5-ae20-d043a900c8f8.png)

**Comment by CleoMenezesJr** [comment]
Fixed in this commit: https://github.com/rafaelmardojai/firefox-gnome-theme/commit/17ba7abded290499bf49a927460b61711f627382
