### ISSUE TITLE
remark selected tab

### ISSUE THREAD

**Issue by jgato** [rafaelmardojai/firefox-gnome-theme#416]
Is there any way of making selected tab more remarked above the others? Now it is only changes the colour a little. For me it is a little confusing. I am using Multi-account containers, so it is distinguished by colours, but, I dont get used to. 

![image](https://user-images.githubusercontent.com/3435696/178217394-1982786a-7515-48db-832c-afae4f13dd01.png)

![image](https://user-images.githubusercontent.com/3435696/178218723-9ea49afb-36a3-4ea1-a436-38bad54afe4b.png)

**Comment by rafaelmardojai** [comment]
For now you can use `gnomeTheme.activeTabContrast` to improve that. And probably when #398 is implemented things will be better.
