### ISSUE TITLE
The Close Tab Button Looks Ugly

### ISSUE THREAD

**Issue by Fatih20** [rafaelmardojai/firefox-gnome-theme#42]
![Screenshot-20190715051421-138x124](https://user-images.githubusercontent.com/51940383/61190002-ae046a00-a6bf-11e9-89fb-dd42db181f38.png)
The Close Tab button doesn't look good. The rectangle that shows up when the cursor hover over the button should be smaller and shouldn't border with the tab.
![firefox-gnome-theme Close Tab](https://user-images.githubusercontent.com/51940383/61190102-07b96400-a6c1-11e9-9a71-c7dcf514c01d.png)

**Comment by rafaelmardojai** [comment]
Can't reproduce in Firefox 68 or Firefox 70.

**Comment by Fatih20** [comment]
But this isn't a bug. I'm saying that the looks of the close tab button when the cursor hover over it, could be improved.

**Comment by lionirdeadman** [comment]
Yes, it doesn't look like this to me nor Rafael so it's a bug. This isn't intended behaviour.

**Comment by Fatih20** [comment]
How does it look like to you? Screenshots? I'll check it when I got home.

**Comment by rafaelmardojai** [comment]
![Captura de pantalla de 2019-07-14 18-20-51](https://user-images.githubusercontent.com/6210397/61190582-3523f480-a664-11e9-9a21-06c11279b055.png)

**Comment by Fatih20** [comment]
I'm using 68. Yeah, it's really weird.

**Comment by rafaelmardojai** [comment]
You don't have any extra CSS code?

**Comment by johnfactotum** [comment]
This happens when UI density is set to "touch" (`browser.uidensity` set to `2`)
