### ISSUE TITLE
Full Screen Indicator Theming

### ISSUE THREAD

**Issue by The-L3mur** [rafaelmardojai/firefox-gnome-theme#421]
The full screen indicator that shows up in places such as YouTube when you, well, enter full screen, is still the default Firefox one, and it feels quite out of place (to be honest, it feels out of place with stock Firefox as well).

![image](https://user-images.githubusercontent.com/30356285/180123118-847d2d7b-395b-4ce6-a51f-489bf577e849.png)

I suggest that it be themed to be more in line with the rest of the theme and Adwaita styling.

**Comment by CleoMenezesJr** [comment]
Working on it.
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/54215258/695fe732-4894-4096-8fc2-eb2697c31c5a)

**Comment by emansom** [comment]
@CleoMenezesJr Doesn't look particularly great with the light theme:

![Schermafdruk van 2023-05-29 16-22-41](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/981494/94ae157a-2b10-408e-8fbe-817673f6e8a8)

**Comment by CleoMenezesJr** [comment]
> @CleoMenezesJr Doesn't look particularly great with the light theme:
> 
> ![Schermafdruk van 2023-05-29 16-22-41](https://user-images.githubusercontent.com/981494/241752242-94ae157a-2b10-408e-8fbe-817673f6e8a8.png)

It's a known issue. I'll fix it later and send you a fix.

**Comment by rafaelmardojai** [comment]
@CleoMenezesJr Had some free time so pushed a fix.

**Comment by emansom** [comment]
With latest git, the middle most text is still a little unreadable but much better though. 👍🏻 

![Schermafdruk van 2023-05-29 20-09-47](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/981494/1f5b061d-9689-4a74-a3d4-9b6ac276de00)

**Comment by rafaelmardojai** [comment]
This is how it looks mimicking the  Adwaita Toast/osd styling:

![Captura desde 2023-05-29 14-02-49](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/77c1874f-f460-43d4-85ed-717e62bc30c1)

Opinions?

**Comment by CleoMenezesJr** [comment]
> This is how it looks mimicking the  Adwaita Toast/osd styling:
> 
> ![Captura desde 2023-05-29 14-02-49](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/77c1874f-f460-43d4-85ed-717e62bc30c1)
> 
> Opinions?
> 

LGTM
