### ISSUE TITLE
Material You extension

### ISSUE THREAD

**Issue by julianfairfax** [rafaelmardojai/firefox-gnome-theme#429]
It would be nice if this theme supported https://github.com/avanishsubbiah/material-you-theme. The top bar and the context menus aren't themed with Material You as they would be if it did.

**Comment by PoorPocketsMcNewHold** [comment]
Duplicate with #408. This extension just modify the libadwaita colorscheme according to the wallpaper. It's not an external theming API or something.

**Comment by julianfairfax** [comment]
> Duplicate with #408. This extension just modify the libadwaita colorscheme according to the wallpaper. It's not an external theming API or something.

Well yes, but it would be nice if this theme was abled to be themed by the extension as the regular Firefox theme is.

**Comment by rafaelmardojai** [comment]
If Firefox it's getting the colors is because it generates some colors from your GTK theme, but I don't plan to use those colors because are limited and don't will allow me to perfectly match Adwaita.
