### ISSUE TITLE
[Feature request] Gruvbox color scheme

### ISSUE THREAD

**Issue by werdahias** [rafaelmardojai/firefox-gnome-theme#430]
I really like you theme. I would like an version of this theme with the Gruvbox color palette. Please consider implementing this.

Cheers

**Comment by aspizu** [comment]
the Gradience app allows changing the colorscheme of other apps and this theme.

**Comment by rafaelmardojai** [comment]
This is out-of scope for the theme. You can alternatively use Gradience app to tweak the theme.
