### ISSUE TITLE
libadwaita tabs don't look like this

### ISSUE THREAD

**Issue by notthewave** [rafaelmardojai/firefox-gnome-theme#432]
![image](https://user-images.githubusercontent.com/74874782/184557657-f3ac39c0-5b0f-4907-a1bd-1c99c4e4cab2.png)

that's how they look.

Might be nice to do the Monterey thing with them: having the tabs in the headerbar. (probably not part of gnome HIG)

**Comment by rafaelmardojai** [comment]
> that's how they look.

That's how they look in libadwaita 1.2 that will be released along GNOME 43, not current stable.

Also duplicated of #398.
