### ISSUE TITLE
[Feature request] improvement in the new tab button

### ISSUE THREAD

**Issue by ruizlenato** [rafaelmardojai/firefox-gnome-theme#435]
New tab button could be the same as in Gnome Web.
Example: 
![image](https://user-images.githubusercontent.com/49354525/186808365-81452c74-112a-4bf0-b9ae-ffcad7fdf8d6.png)

**Comment by majjejjam** [comment]
That's an old version of the new tab icon. The current one _does_ look like the one present in this theme.

If you open Adwaita Demo (or any other updated GNOME app with tabs) you'll see:

![bild](https://user-images.githubusercontent.com/58899295/194273786-35de4893-4415-456a-b4ee-b6bc0093b539.png)

**Comment by rafaelmardojai** [comment]
That's right, we're using the latest version of that icon in the `adwaita-icon-theme`.

**Comment by ruizlenato** [comment]
> 

I was referring to the position of the icon actually

**Comment by ruizlenato** [comment]
> That's an old version of the new tab icon. The current one _does_ look like the one present in this theme.
> 
> If you open Adwaita Demo (or any other updated GNOME app with tabs) you'll see:
> 
> ![bild](https://user-images.githubusercontent.com/58899295/194273786-35de4893-4415-456a-b4ee-b6bc0093b539.png)

I was referring to the position of the icon actually

**Comment by rafaelmardojai** [comment]
> I was referring to the position of the icon actually

You can move it manually. The only way to have that by default would be to force a fixed layout with the `user.js` config file, but that's not desirable IMO.
