### ISSUE TITLE
Private window has an extra bar in Nightly

### ISSUE THREAD

**Issue by bbhtt** [rafaelmardojai/firefox-gnome-theme#436]
Looks like this was introduced recently on Nightly 106 (26-08-2022).

![image](https://user-images.githubusercontent.com/62639087/186948038-9c8ef000-180d-4c26-843d-be32f6827053.png)

https://bugzilla.mozilla.org/show_bug.cgi?id=1751481

**Comment by gtsiam** [comment]
Make that stable. Firefox 106 got released today.

**Comment by fliperama00** [comment]
I don't know if I should open a new issue, but after the v133 update, I got the "Private Window" bar back. Am I missing something?

**Comment by rafaelmardojai** [comment]
@fliperama00 It was already fixed here c1d082e. The problem is that I noticed this after doing the `v133` release, so the fix it's only in the `master` branch. I will probably do a `v133.1` ralease this week.
