### ISSUE TITLE
[GNOME] Window buttons overlap each other when the window size is minimized

### ISSUE THREAD

**Issue by proninyaroslav** [rafaelmardojai/firefox-gnome-theme#439]
**Theme version:** master
**GNOME version:** 42.4

If I minimize the window size to the smallest possible size, then the system buttons (close, minimize, and maximize) overlaps the browser window buttons:

![2022-09-13 10-36-23](https://user-images.githubusercontent.com/7840559/189840380-29ce28da-7912-4b64-8b68-0c96d47ba8b3.png)

I'm using the GNOME Tweak Tool to enable extra buttons (minimize and maximize), but it happens even when I use only the default window close button:

![2022-09-13 10-41-34](https://user-images.githubusercontent.com/7840559/189840933-822bc9f4-1d8e-40b8-9470-c43db5e4f123.png)

There is no issues with Firefox stock theme.

**Comment by CleoMenezesJr** [comment]
Effectively it is necessary some love when the proportion of the windows is a little smaller.

**Comment by rafaelmardojai** [comment]
Duplicated of #133.
