### ISSUE TITLE
"List all tabs" button is invisible

### ISSUE THREAD

**Issue by pedrofleck** [rafaelmardojai/firefox-gnome-theme#44]
The icon to list all tabs is missing when using Adwaita icons provided by the theme. I installed using the install script and the "-g" option. It looks like [this](https://i.imgur.com/y9H5EPk.png).

**Comment by rafaelmardojai** [comment]
Caused by hack for scrollbars to work. Now should be fixed.

**Comment by rafaelmardojai** [comment]
Note: this doesn't happen in Nightly 70.

**Comment by pedrofleck** [comment]
Just tested here and it's indeed fixed. Thanks!
