### ISSUE TITLE
icons with ` gnomeTheme.systemIcons` enabled are not recolored

### ISSUE THREAD

**Issue by aspizu** [rafaelmardojai/firefox-gnome-theme#444]

**Comment by rafaelmardojai** [comment]
Those are bitmap icons, so that's not possible.

**Comment by aspizu** [comment]
provide a script to copy and edit system icon svg files into the theme

**Comment by rafaelmardojai** [comment]
> provide a script to copy and edit system icon svg files into the theme

I guess that would be nice for the users wanting to integrate the theme with their custom icon theme, bud sadly I lack the time.

But I would be happy to include that script if someone contributes it.
