### ISSUE TITLE
all overview/context menus are grey

### ISSUE THREAD

**Issue by nanopone** [rafaelmardojai/firefox-gnome-theme#445]
not sure if this is the fault of the theme or gradience.

![image](https://user-images.githubusercontent.com/49787675/193050882-57e12572-d2b1-47f8-946e-224f294201dd.png)

**Comment by rafaelmardojai** [comment]
I can't reproduce this, could you give more info like your Firefox version?

**Comment by Veelhiem** [comment]
Hi, I'm also experiencing this same bug. This is the case for all context menus.

I'm on Fedora 36 (using Wayland on AMD) and the Firefox version is 105.0.2.

**Comment by rafaelmardojai** [comment]
Please then report it to Gradience, I can't reproduce this.

**Comment by CleoMenezesJr** [comment]
This bug is not related to FGT. Please report this in Gradience's repo.
