### ISSUE TITLE
[Question] Do i propose Vertical Tab PR

### ISSUE THREAD

**Issue by ghost** [rafaelmardojai/firefox-gnome-theme#446]
i actually have merged a popular CSS from firefox, and tweaked it to make it work with this theme : 
part/vertical-tab.css

and the feature (optional) hidden behind a flag : gnomeTheme.verticalTab (who also hide the tab from the normal theme).

So i ask here it's you are interested to merge it (and i do a PR) (like that you can fix some issue in CSS or thing that you don't like in my simple merging of the two themes) or you don't (and i don't do a PR).

I do propose since the goal is to match epiphany (gnome-web) theme and since they don't have this feature i'm not sure you will want it.

It do require the extension tab center reborn (also have the css for the extension, but since many guy ask this feature on brave, many use it on r/firefox-css, it's why i propose this here).

I only have fixed the r/firefox-css who broke the close button on your theme and remove some useless code i have seen, nothing more so it may have some useless css code in it i don't have seen or minor glitch i don't have seen (on very big screen or very little screen).

There is one bug that i don't have actually fixed it's on private tab by default extension not load and so tab are hidden, i don't have fixed it since i nearly never use private tab since my firefox forget nearly everything by default.

Edit : 
Screenshot 1 : 
![image](https://user-images.githubusercontent.com/42673166/193148337-9203733f-7c14-48ba-adc3-508a0a302b11.png)

Screenshot 2 : 
![image](https://user-images.githubusercontent.com/42673166/193148375-edf113ab-a3d6-46bf-bc76-633e68c96f76.png)

**Comment by rafaelmardojai** [comment]
Hey, Sorry for late response.

> I do propose since the goal is to match epiphany (gnome-web) theme and since they don't have this feature i'm not sure you will want it.

You're right, the theme goal is to match the Adwaita design, and vertical tabs isn't a patter of it. And since it requieres an extension, it makes me doubt if I want this on core.

I guess maybe this can be part of some kind of "extensions integration"? I also use some extensions like Simple Tab Groups that could have theming in the future.
