### ISSUE TITLE
Missing System Buttons After Sign-in to Firefox Account on Manjaro Gnome Edition

### ISSUE THREAD

**Issue by djmoore711** [rafaelmardojai/firefox-gnome-theme#448]
I have tried this on three fresh installs of Manjaro Gnome Edition. Everything is fine with the Firefox Gnome theme off of a fresh installation of Manjaro Gnome Edition. Then I sign in, Firefox begins to synchronize all of my settings, and the minimize, maximize, and close button turn into dots. 

If I sign out of my Firefox account and remove all add-ons, the buttons do not reappear. If I create a new account on the system and login to that new account, the buttons are back in the Firefox Gnome theme--until I sign in to my Firefox account in that browser. Then, they are gone again.

It is often, when I click sign in on my Firefox account, I can see the buttons turn into dots in real time.

I want to help troubleshoot this issue, but I am not sure how or where to start.

[Link to Example Image](https://imgur.com/a/YoW5q0U)

**Comment by rafaelmardojai** [comment]
Are you using the default/system theme on Firefox settings?

**Comment by forest2code** [comment]
> 

after change default theme, buttons come back
thx!

**Comment by forest2code** [comment]
@rafaelmardojai  after changing to default theme, buttons come back
thx!
