### ISSUE TITLE
Some missing details in the Private Window

### ISSUE THREAD

**Issue by CleoMenezesJr** [rafaelmardojai/firefox-gnome-theme#452]
- [ ] The tabsbar should be hidden when there is the option to hide it when there is only one tab:
- - ![image](https://user-images.githubusercontent.com/54215258/194878870-ac0de8df-c218-4722-a916-90fc30d4af68.png)

- [ ] Wrong colors in the tabs both active and on hover:
- - ![image](https://user-images.githubusercontent.com/54215258/194879625-85f6601d-597d-466e-937b-0e2b89d63aea.png)

**Comment by rafaelmardojai** [comment]
>  The tabsbar should be hidden when there is the option to hide it when there is only one tab:

#436

**Comment by CleoMenezesJr** [comment]
> Container tabs are also not very readable. Why not color the background with the color you're using for the text instead, kind of like it was before?

The tabs seem to be always active when has a background color. I'm thinking alternatives, but for now, coloring the text was the best option.

**Comment by rafaelmardojai** [comment]
Suggestions are welcome. Maybe we can tweak the colors to get better readability? But background is a non-go because it makes hard to distinguish which tab is selected.

**Comment by CleoMenezesJr** [comment]
I thought of putting some shadow in the text for now, but it didn't please me much. Maybe using the Need Attention trait, but it is on top with the color of the container. Let's make some experiments
