### ISSUE TITLE
Tabbar overflow graphic misplaced

### ISSUE THREAD

**Issue by folknor** [rafaelmardojai/firefox-gnome-theme#454]
Hi!

Thanks again for all your awesome work, I've used the theme since the beginning :1st_place_medal: 

For some reason I can't upload the image to show the issue, Github just tells me "something went really wrong, and we can't process that file" even with PNG or JPEG.

Let me just file this and attempt to put it in a comment!

**Comment by folknor** [comment]
![Untitled](https://user-images.githubusercontent.com/233791/195316229-0ececa48-ec6b-4ca0-9d5b-802e0ef88641.jpg)

**Comment by folknor** [comment]
Hopefully the issue is self-evident from that image. Let me know if you need additional information! Thanks!

**Comment by rafaelmardojai** [comment]
Version? I can't reproduce this on 105 stable.

**Comment by folknor** [comment]
Ah, my bad I should have specified - yes of course it is on Nightly.

**Comment by rafaelmardojai** [comment]
Thanks. We have a few beta/nightly issues right now, will see if I find some time to fix those in the `beta` branch.

**Comment by eilx** [comment]
Also reporting this on release v105.1, seems to only happen when the arrows aren't disabled

Overflow on left:
![Screenshot from 2022-10-21 19-07-35](https://user-images.githubusercontent.com/74159071/197261736-1c59a8a3-9ef0-4c91-be51-0197abdfd6a6.png)

Overflow on right:
![Screenshot from 2022-10-21 19-07-08](https://user-images.githubusercontent.com/74159071/197261737-1f2d6b81-34de-4ca8-a78f-fb0e206faa6f.png)
