### ISSUE TITLE
Possible inclusion of a preference toggle for disabling single tab active highlighting. 

### ISSUE THREAD

**Issue by katanaBadger** [rafaelmardojai/firefox-gnome-theme#457]
Hope you are keeping well!

As someone who prefers keeping the tab bar visible at all times to keep consistency without letting pages jump up and down when opening and closing, I feel that the active tab highlight should be disabled only when there's a single tab open. At the moment to my eye, it doesn't look right when the tab occupies the entire width of the browser.

Could this please perhaps be delegated as an additional toggle if possible?

Thank you for keeping the theme updated to Adwaita's standards, it continues to look stunning!

**Comment by rafaelmardojai** [comment]
You can enable the `gnomeTheme.hideSingleTab` pref. See how: https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features
