### ISSUE TITLE
Overflow too early on selected / hovered tab

### ISSUE THREAD

**Issue by BirdInFire** [rafaelmardojai/firefox-gnome-theme#458]
Am i the only one to have an overflow showing on a 6 letter long title on selected / hovered tab ?

I use the last version on firefox wayland (flatpak).
the only settings (removed all other to try to debug myself) : gnomeTheme.hideSingleTab.

Screenshot : 
![image](https://user-images.githubusercontent.com/42673166/195737349-dc94378e-1cf7-4428-8e3e-7886410777db.png)

**Comment by rafaelmardojai** [comment]
This is fixed on master, please update.
