### ISSUE TITLE
Firefox 106

### ISSUE THREAD

**Issue by julianfairfax** [rafaelmardojai/firefox-gnome-theme#462]
Hiding the tab bar with only one tab open doesn't work on Firefox 106.

![image](https://user-images.githubusercontent.com/43753131/196554207-7e897cba-fb1a-4687-b727-6c554347c0c2.png)

It has little tab search button that cannot be removed.

![image](https://user-images.githubusercontent.com/43753131/196554287-14649d66-f22d-45ec-a5c6-ee4884fdd7ae.png)

A fix would bring me joy. Thank you for developing this theme!

**Comment by rafaelmardojai** [comment]
Duplicated of #433.
