### ISSUE TITLE
Enormous new tab icon

### ISSUE THREAD

**Issue by ZechariahB** [rafaelmardojai/firefox-gnome-theme#463]
When you have too many tabs open, the new tab icon will appear with an enormous icon. All tabs expand vertically to accommodate for this. You can also cause this by adding other items via "customize toolbar...". They too will exhibit the same behavior. This issue occurs in all versions of firefox-gnome-theme past v100 as far as I know and likely exists in much earlier versions as well.

To assist with replication: (It might not matter anyways)
`gnomeTheme.systemIcons` is set to true

![Screenshot from 2022-10-19 20-34-32](https://user-images.githubusercontent.com/84613764/196830533-8919080a-94b7-4061-a53b-d5e294c86061.png)

**Comment by rafaelmardojai** [comment]
> To assist with replication: (It might not matter anyways) gnomeTheme.systemIcons is set to true

Actually it matters, and only happens with `gnomeTheme.systemIcons`.
