### ISSUE TITLE
Headerbar 'more tools' button too large on firefox-nightly 108.0a1

### ISSUE THREAD

**Issue by Sinasta** [rafaelmardojai/firefox-gnome-theme#467]
I don't really understand what is causing this issue but the header-bar is unusable because it is covered by one big button: 'More Tools' on Firefox-Nightly 108.0a1
![Screenshot from 2022-10-24 10-52-48](https://user-images.githubusercontent.com/64699866/197488073-df461bcb-2b66-4b10-a706-305fd067e84d.png)

**Comment by CleoMenezesJr** [comment]
Does this happen in version 106?

**Comment by Sinasta** [comment]
No the issue is not happening in 106. I just wanted to report for the latest nightly but i can close the issue aswell if this is expected behaviour

**Comment by lowgos** [comment]
I reproduce too, reverting to default theme in the meantime.

**Comment by Mantas-2155X** [comment]
I have this as well. 
As a temporary workaround you can comment out the following lines to fix some issues:
- [oversized more tools button in header bar](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/master/theme/parts/popups.css#L162)
- [oversized zoom button in application menu](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/master/theme/parts/popups.css#L161)
- [oversized bookmark buttons](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/master/theme/parts/popups.css#L166)

**Comment by TheKrafter** [comment]
I had this issue on 108.0, but fixed after a reinstall
