### ISSUE TITLE
the tab label Overlaps with the close button when the its width is close to the width of the tab itself

### ISSUE THREAD

**Issue by azab246** [rafaelmardojai/firefox-gnome-theme#469]
small issue
idk if i can explain it properly
While tabs are being compressed when more are opened
when a tab with a name that is almost the same as the width from which the name shading begins causes it to overlap with the close button
![Screenshot from 2022-10-29 00-54-48](https://user-images.githubusercontent.com/99084207/198748336-0b6d44dd-a51e-4ebe-9d3b-7821a25dbbd3.png)
![Screenshot from 2022-10-29 01-03-39](https://user-images.githubusercontent.com/99084207/198748553-fa6c8247-ed2b-46c3-b375-1fe4072f63eb.png)
instead of :
![Screenshot from 2022-10-29 01-01-51](https://user-images.githubusercontent.com/99084207/198748429-a492f6b5-57de-4ef7-b9f6-fac85a15bd8c.png)

i only have "Hide single tab" feature enabled and other than that its on default

**Comment by rafaelmardojai** [comment]
This is a known issue in the current stable version (usually installed through the curled script).

This should be already fixed on master branch.

**Comment by azab246** [comment]
thats good to know
ill close this then
thanks!
