### ISSUE TITLE
color too dark in bookmark bar and menu bar

### ISSUE THREAD

**Issue by MaxBrandtner** [rafaelmardojai/firefox-gnome-theme#470]
I love your project, but in my humble opinion the menu bar and bookmark bar background color is too dark. In terms of coloring it doesn't make a lot of sense either as it goes from grey to darker back to the original grey. (If you disagree explaining how I can edit the css to give it the same grey color as the tabbar would work as well)

**Comment by CleoMenezesJr** [comment]
Particularly, both the menu bar and the bookmark are things I never visit, and I inevitably wouldn't stop to fix them until I saw this issue. I believe that @rafaelmardojai  shares the same problem. lmao
