### ISSUE TITLE
search bar is not red when no match is found

### ISSUE THREAD

**Issue by p00f** [rafaelmardojai/firefox-gnome-theme#474]
The search bar does not turn red when no match is found

Nightly without gnome theme
![image](https://user-images.githubusercontent.com/36493671/199970569-5b434304-3d44-4c1f-a026-eadff2b4801c.png)

Stable with gnome theme
![image](https://user-images.githubusercontent.com/36493671/199970413-fcd0827b-0805-437b-a259-657632b02c7a.png)

I'm using the AUR package as of https://github.com/rafaelmardojai/firefox-gnome-theme/commit/c976b692341951462d0a849239fbc86d47f548b1

**Comment by CleoMenezesJr** [comment]
@rafaelmardojai, the behavior in Epiphany is that the magnifying glass icon turns into a disgruntled emoji, however, Firefox does not have this icon sign.
Firefox already warns that it was not found with text ![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/54215258/c0b417ab-b926-43dd-ae52-ff344e4c6431), I don't know if it's necessary to paint the background to signal this, but if we decide to do something like this, an idea could be to change the color of the outline:
[Screencast from 2023-05-15 02-14-57.webm](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/54215258/3387d4b2-9e04-4226-af0e-8c7436d861a3)
_of course not this color_

What's your opinion? Leaving it as is is also a good option in my opinion.

**Comment by CleoMenezesJr** [comment]
Well, I just saw that there is a tentative solution in this PR: https://github.com/rafaelmardojai/firefox-gnome-theme/pull/407/files#diff-5dffed67d7ec703ebce827efa89ec07a17dac02b7a2ccc5045303c26f431ebb3R3
There are then 3 options.
