### ISSUE TITLE
Cannot switch back from new tab manager when single tab is open

### ISSUE THREAD

**Issue by ArtyIF** [rafaelmardojai/firefox-gnome-theme#475]
When opening the new tab manager, when one tab is open, the only way to switch back is to open a new tab.

Steps to replicate:

1. Enable `gnomeTheme.hideSingleTab`
2. Move the Firefox View button away from the tab bar
3. Have one tab open
4. Click the Firefox View button, it should open
5. Click the Firefox View button again

Expected result: Firefox View will close. Alternatively, as a workaround, the tab bar should stay visible when Firefox View is open

Actual result: Nothing happens. The only way to close it is to Ctrl-Tab to a different tab or to create a new tab, which is counter-intuitive when the View button is not on the tab bar

**Comment by rafaelmardojai** [comment]
I'm pretty sure that there's no way to know that Firefox View is open from the tabs CSS.

This is one of the reasons why  `gnomeTheme.hideSingleTab` is an opt-feature and not a core style of the theme. It can cause issues in the Firefox workflow.

I guess you could try to ask Firefox devs to make the Firefox View button behave like a toggle.
