### ISSUE TITLE
Fullscreen exit icon stays when entering YouTube fullscreen mode

### ISSUE THREAD

**Issue by ArtyIF** [rafaelmardojai/firefox-gnome-theme#476]
See top right corner of the screenshot below

![image](https://user-images.githubusercontent.com/8017858/200037385-43bb7b8f-773a-4c4f-96dc-9d70e813d54f.png)

**Comment by CleoMenezesJr** [comment]
Thanks for reporting. Now in version 107 I can reproduce this bug.
