### ISSUE TITLE
Tab title moves left when hovering over it

### ISSUE THREAD

**Issue by marcinjahn** [rafaelmardojai/firefox-gnome-theme#477]
The title says it all. The recording below explains it even better:

https://user-images.githubusercontent.com/10273406/200180239-2ca0e76f-5b0b-416b-84c0-ed6dbc0a5337.mp4

I believe that the title should stay in place when I hover the tab.

**Comment by rafaelmardojai** [comment]
Yes, this has been around for some time. Somehow, sometimes Firefox's tab text overflowing gets bugged and this happens. (Usually when it restores an old session)

Basically the theme has a hacky way to properly place the close button when the tab has text overflowing, and in some cases Firefox is setting the `[textoverflow]` attr when the tab content is actually floating, causing the hack to be seen when it shouldn't.
