### ISSUE TITLE
Different active tab colors

### ISSUE THREAD

**Issue by semente** [rafaelmardojai/firefox-gnome-theme#48]
For some reason, the active tab color is different for certain tabs (couldn't identify a pattern yet). At the first image below, it is good but at the second one it is hard to identify the active tab. 

![2019-07-17-174551_582x347_scrot](https://user-images.githubusercontent.com/29862/61410660-2f344a80-a8d4-11e9-8114-3e4b72ecef95.png)
![2019-07-17-174528_752x449_scrot](https://user-images.githubusercontent.com/29862/61410661-2f344a80-a8d4-11e9-8d61-8e7e13a0d553.png)

**Comment by rafaelmardojai** [comment]
Actually i think are the same color, but there is some optical effect caused when the webview background is light...

**Comment by semente** [comment]
You are right.

Well, at least on dark theme I find hard to find the tab on light pages. My vision is not the best. But it is not a big deal.

**Comment by rafaelmardojai** [comment]
I just added a new optional feature for better contrast in active tabs.
https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features
