### ISSUE TITLE
Window buttons should have a fade in hover effect

### ISSUE THREAD

**Issue by demirdegerli** [rafaelmardojai/firefox-gnome-theme#485]
Top: Firefox GNOME Theme
Down: GNOME Software

[Screencast from 2022-11-15 13:49:04.webm](https://user-images.githubusercontent.com/67432156/201901395-542518e8-3ef7-41e8-a76c-5e4c6ba44761.webm)

**Comment by CleoMenezesJr** [comment]
It's work in progress :)

[Screencast from 2022-11-17 22-05-39.webm](https://user-images.githubusercontent.com/54215258/202602319-0802719e-d646-4917-b8d2-ae53fc9e2267.webm)

**Comment by CleoMenezesJr** [comment]
https://github.com/rafaelmardojai/firefox-gnome-theme/commit/bb437abe08f5fdb7469eebd389ce6085aeb3d0b1
