### ISSUE TITLE
Accept answer in "make an AUR package" discussion

### ISSUE THREAD

**Issue by emansom** [rafaelmardojai/firefox-gnome-theme#488]
### Discussed in https://github.com/rafaelmardojai/firefox-gnome-theme/discussions/242

Please flag as solved 🥺

**Comment by CleoMenezesJr** [comment]
Your comment is already marked as answer.

**Comment by emansom** [comment]
> Your comment is already marked as the answer.

It is now! Thanks @rafaelmardojai 🤗

**Comment by CleoMenezesJr** [comment]
> > Your comment is already marked as the answer.
> 
> It is now! Thanks @rafaelmardojai 🤗

Great!

**Comment by rafaelmardojai** [comment]
I had to convert the discussion to a question because regular discussion can't be marked as resolved 😅
