### ISSUE TITLE
Weird flickering in tab bar when hovered over the close tab button

### ISSUE THREAD

**Issue by a2chan** [rafaelmardojai/firefox-gnome-theme#49]
![ezgif-1-5c8055e5236e](https://user-images.githubusercontent.com/46082775/61442867-00ff4b00-a966-11e9-889a-69f92cd95643.gif)

**Comment by lionirdeadman** [comment]
What version of Firefox is this and it seems you have either modified the theme or not updated it in a while since the "list all tabs" pop-over icon is not a gnome one but rather the mozilla one.

**Comment by a2chan** [comment]
Firefox is version 68.0 and I cloned it directly from GitHub yesterday which I believe must be the latest version.

**Comment by rafaelmardojai** [comment]
Looks like you are using a modification from https://github.com/vinceliuice/Mojave-gtk-theme/.
Please report a issue there, or ask Mojave maintainer to update to latest changes from this repo.
I can't reproduce this bug.
