### ISSUE TITLE
Use normal width tabs option makes tabs too small

### ISSUE THREAD

**Issue by somepaulo** [rafaelmardojai/firefox-gnome-theme#493]
Probably a legacy form older code, but the `/* OPTIONAL: Use normal width tabs */` code in `tabsbar.css` has `--tab-min-width: 76px !important;` while everywhere else this is set to `--tab-min-width: 131px !important;`.

**Comment by rafaelmardojai** [comment]
This is intentional, vanilla Firefox tabs have `76px` min-width. Maybe this size can be recalculated a bit since our tabs have more horizontal padding. 

`131px` is the min-width of libadwaita tabs.

**Comment by somepaulo** [comment]
If the theme is trying to mimic libadwaita, then the tabs' `min-width` should be set to `131px` in all cases, IMHO.

If this setting is meant to go down to Firefox's settings, then it should probably be named something different, because currently it's supposed to not allow tabs to expand the whole width of the window, but doesn't say the minimum size will get smaller than if you don't enable this option.

On a separate note, since about a month ago this setting overrides whatever I set in `about:config` in `browser.tabs.tabMinWidth`, which didn't happen before.

**Comment by rafaelmardojai** [comment]
> If the theme is trying to mimic libadwaita, then the tabs' min-width should be set to 131px in all cases, IMHO.

If you want to fully mimic libadwaita don't enable `gnomeTheme.normalWidthTabs`.

> On a separate note, since about a month ago this setting overrides whatever I set in about:config in browser.tabs.tabMinWidth, which didn't happen before.

True, since we're manually resetting `--tab-min-width` to is original value. Changing it to `--tab-min-width: inherit` should make `browser.tabs.tabMinWidth` work again when `gnomeTheme.normalWidthTabs` is enabled. 

Will commit that.
