### ISSUE TITLE
Maximizing window with tabs as headerbar results in buggy toolbar

### ISSUE THREAD

**Issue by TylerMS887** [rafaelmardojai/firefox-gnome-theme#494]
When maximizing the Firefox window, I get a toolbar that looks bugged out:

![image](https://user-images.githubusercontent.com/115214762/202895325-6849996e-12ec-4568-9921-1a97def96df7.png)

It's supposed to be without the spacing at the end of the toolbar:
![image](https://user-images.githubusercontent.com/115214762/202895368-254ba787-9f43-48d8-bfe2-efdc8df620d6.png)

This appears to not be usual behaviour and is a bug.

Running Fedora 36, Firefox 106, GNOME 42.

**UPDATE:** Upgraded to Fedora 37, GNOME 43.

**Comment by CleoMenezesJr** [comment]
Please, while using Firefox 106, use FGT release 106.
Firefox 107 there were several changes that caused bugs in FGT, the changes that are in the master branch are for the next release of Firefox 107.

**Comment by rafaelmardojai** [comment]
CC @Commenter25
