### ISSUE TITLE
"Hide single tab" feature seems to be broken for pinned tabs in v106

### ISSUE THREAD

**Issue by RozeFound** [rafaelmardojai/firefox-gnome-theme#498]
I'm not sure if this is intended or not, so I file a bug.

### To reproduce:
1. Install latest version of firefox with latest version of theme
2. Enable "Hide single tab" feature
3. Open 2 tabs, pin one, close the second
4. Enjoy almost empty tab bar

**Comment by rafaelmardojai** [comment]
Yes, it's intended. That's how libadwaita tabs behave.
