### ISSUE TITLE
Tab Center Reborn doesn't shrink size properly

### ISSUE THREAD

**Issue by not-a-dev-stein** [rafaelmardojai/firefox-gnome-theme#506]
I've been one of the not few that mixed firefox-gnome-theme with ff-vertical-tabs for a long time, so I was glad to see it being integrated into the theme itself, but currently it looks broken on v107 (on Fedora RPM version, haven't tested on Flathub, but I don't expect it to be related to that), as it doesn't shrink to size properly when not on focus, and glitching when the cursor is close to its huge border.

[Gravação de tela de 2022-12-07 09-52-48.webm](https://user-images.githubusercontent.com/63420929/206184822-e2f84f9c-4329-4af9-b4a4-ae91b3d80208.webm)

**Comment by marc0x1** [comment]
I also got the same bug with the Flathub version

**Comment by rafaelmardojai** [comment]
CC @BirdInFire
