### ISSUE TITLE
Top bar doesn't hide in fullscreen mode

### ISSUE THREAD

**Issue by unomi-zan** [rafaelmardojai/firefox-gnome-theme#509]
Using the F11 key to toggle fullscreen mode doesn't hide the Adress bar and the tab bar.

**Comment by rafaelmardojai** [comment]
Works fine for me, could you give more info about your setup?

**Comment by unomi-zan** [comment]
### Theme specific flags I've enabled
`gnomeTheme.hideSingleTab`
`gnomeTheme.bookmarksToolbarUnderTabs`
`gnomeTheme.normalWidthTabs`

### Firefox version
- 108, 107
  
### Gnome Theme version
- 108, 107

### Disabling all the extensions also didn't help.

### My setup
![image](https://user-images.githubusercontent.com/79187956/208227987-43cc24f9-691c-4521-9765-5ffa40a79b22.png)

### Video Example
[Screencast from 2022-12-17 11-51-52.webm](https://user-images.githubusercontent.com/79187956/208228047-52bce7a3-d41b-4757-a37f-597ac3af641c.webm)

### Please guide me if I need to give more information.

**Comment by unomi-zan** [comment]
NVM, I figured out what was wrong. I didn't tick the option to hide the toolbar.
![image](https://user-images.githubusercontent.com/79187956/208228468-ff5d7db4-2de8-42ec-84ca-25d9c75d83f0.png)
