### ISSUE TITLE
Partly invisible when decreasing window size through some shortcut/button when paired with Rounded Window Corners extension

### ISSUE THREAD

**Issue by EddoWagt** [rafaelmardojai/firefox-gnome-theme#512]
Okay, so this issue is very specific, but an issue nonetheless.

If you are using the gnome extension "Rounded Window Corners" and have this Firefox theme enabled,
the window becomes partly invisible if you decrease the window size through some kind of tool, like the maximise button or gTile for example. If you manually resize it won't happen and when you manually resize after it happens, it fixes itself.

This can be fixed by adding an exception to the Rounded Window Corners extension, but then you can't have nice rounded corners at the bottom of the window.

![image](https://user-images.githubusercontent.com/64751823/207667968-f3691cce-eafe-4bb8-a86a-258272b0f9cc.png)
![image](https://user-images.githubusercontent.com/64751823/207668255-a854c71b-ab3b-4319-b192-7bd00e88b66b.png)

**Comment by rafaelmardojai** [comment]
@CleoMenezesJr  Do you use this extension? Could you reproduce?

**Comment by CleoMenezesJr** [comment]
Yes, I use it and there really is this bug, but it's not related to us. It is an already reported bug of the extension.

**Comment by CleoMenezesJr** [comment]
@EddoWagt, this bug is from the extension and not the theme. There is already an open issue about this in their repository: https://github.com/yilozt/rounded-window-corners/issues/100

**Comment by EddoWagt** [comment]
Thank you, didn't notice the bug without FGT, so I assumed it was related. I appreciate the link!
