### ISSUE TITLE
Headerbar too large in Firefox 108 

### ISSUE THREAD

**Issue by emansom** [rafaelmardojai/firefox-gnome-theme#514]
The headerbar now appears too large in Firefox 108.

![Schermafdruk van 2022-12-15 21-13-40](https://user-images.githubusercontent.com/981494/207957958-13b7143e-84d3-4874-8590-9077206fa18f.png)

**Comment by emansom** [comment]
Possibly related to #467 and missing padding fixes in PR #513 (see commit https://github.com/witalihirsch/Mono-firefox-theme/commit/caceed5c37909306266f97ab4a484c90a6d6d57b)

**Comment by juxuanu** [comment]
This is also an issue: 
![image](https://user-images.githubusercontent.com/24759034/208059527-618d3ad9-9ae3-4ad7-9464-6451ea619aaa.png)

The hover background is cropped
