### ISSUE TITLE
navigation button with tabsAsHeaderbar

### ISSUE THREAD

**Issue by RedCommand** [rafaelmardojai/firefox-gnome-theme#517]
Hello.
First of all, many thanks for the project!

As a feature, do you think it will be possible to have the navigation buttons (back, forward and refresh) in the header bar when using `gnomeTheme.tabsAsHeaderbar` ? Currently, the navigation button is with the search bar and there is a gap before the tabs.

![image](https://user-images.githubusercontent.com/50780743/208079838-9b561f42-36ab-4299-a2e1-f7c0e00eee58.png)

**Comment by rafaelmardojai** [comment]
You can move toolbar icons to the tabbar when you customize toolbars, but unfortunately Firefox doesn't allow to move the navigation buttons.
