### ISSUE TITLE
Tab bar and toolbar broken in Firefox 108

### ISSUE THREAD

**Issue by h5law** [rafaelmardojai/firefox-gnome-theme#518]
![image](https://user-images.githubusercontent.com/53987565/208087181-1514e117-e0dc-4db0-89ca-a9e48f72f505.png)

The tab bar is being overridden by the "Firefox View" button at the top, the URL bar is tiny  and the more tools section produces a very strange dropdown.

**Comment by maymage** [comment]
Confirmed.. I'm on firefox 108 from flathub and just reinstalled with the curl script.

**Comment by insidemordecai** [comment]
Issue #504 was closed as fixed but after reinstalling the theme using the curled script I still get the same layout issue.

**Comment by rickdkk** [comment]
Same issue here. Thought it was a FF issue at first and did a `dnf reinstall firefox` and which didn't help.

**Comment by rafaelmardojai** [comment]
> Issue https://github.com/rafaelmardojai/firefox-gnome-theme/issues/504 was closed as fixed but after reinstalling the theme using the curled script I still get the same layout issue.

Curled script needs a tagged release.

**Comment by rafaelmardojai** [comment]
Duplicated of #504
