### ISSUE TITLE
Inconsistent tab alignment when playing audio

### ISSUE THREAD

**Issue by nwallace** [rafaelmardojai/firefox-gnome-theme#52]
First of all, thank you for the theme! I love it.

I noticed an inconsistency when you have a tab that is sharing your webcam. Definitely not a critical bug -- everything works fine -- but it threw me off for a split second.

Here's what the tab looks like when the tab is focused: (text is centered, all is well)
![screenshot_2019-07-18-12:34:08](https://user-images.githubusercontent.com/1614172/61479524-a5c75b80-a959-11e9-904e-aae8cf4e3037.png)

And here's what the tab looks like when it's unfocused: (text is left-aligned, unlike other tabs)
![screenshot_2019-07-18-12:34:29](https://user-images.githubusercontent.com/1614172/61479658-e2935280-a959-11e9-9cf5-752c189c4d70.png)

I'd expect the text to remain centered when the tab is unfocused, but it becomes left-aligned.

**Comment by nwallace** [comment]
Hm, this behavior doesn't seem to be consistent. After closing and re-opening my browser, the tab content when unfocused and sharing video was center-aligned as expected. If I can suss out what might have been the difference, I'll post back here.

**Comment by nwallace** [comment]
Looks like it has to do with the fact that the tab is playing sound -- not the camera sharing

Sharing video in far left tab, second tab has no audio (neither have focus):
![image](https://user-images.githubusercontent.com/1614172/61568321-6592d680-aa48-11e9-8479-c175c3105e8c.png)

Still sharing video in far left tab, but now second tab is playing audio (still neither have focus):
![image](https://user-images.githubusercontent.com/1614172/61568335-72172f00-aa48-11e9-8dcd-f8f3d299eff7.png)

**Comment by rafaelmardojai** [comment]
I can't reproduce it in Nightly, i will try later with stable 68.

**Comment by rafaelmardojai** [comment]
@nwallace still the same?
