### ISSUE TITLE
[BUG] wrong bookmark bar colour when not in focus & lines between bookmark bar, search bar, and tab bar

### ISSUE THREAD

**Issue by MaxBrandtner** [rafaelmardojai/firefox-gnome-theme#521]
**Describe the bug**
when unfocusing the color of the bookmark bar background colour

**To Reproduce**
1. Unfocus firefox
2. See error

**Expected behavior**
same bookmark bar colour as the rest of the topbar
no black lines between bookmark bar, searchbar, tabbar

**Desktop (please complete the following information):**
 - OS: linux - debian
 - Browser firefox
 - Version 108

**Comment by rafaelmardojai** [comment]
Fixed the background miss mach.

About the black lines, if you mean these toolbars separators, they are intended.
![Captura desde 2022-12-17 22-43-02](https://user-images.githubusercontent.com/6210397/208280297-82191aec-8aaf-4346-9b8c-99734a876fc5.png)
