### ISSUE TITLE
[BUG] Tab Bar color doesn't match with the title bar in Private Window

### ISSUE THREAD

**Issue by unomi-zan** [rafaelmardojai/firefox-gnome-theme#523]
### 
### Light Theme
![image](https://user-images.githubusercontent.com/79187956/208249999-cc2fa466-6076-4eb6-aa4e-a5c3c0cf9cc7.png)

### Dark theme
![image](https://user-images.githubusercontent.com/79187956/208250017-4513ec8a-7a69-4b90-8f6b-39e3a3247d43.png)

### Desktop
- OS: Fedora 37
- Browser firefox
- Version 108

**Comment by rafaelmardojai** [comment]
Can't reproduce. Looks like this for me:
![Captura desde 2022-12-17 22-17-47](https://user-images.githubusercontent.com/6210397/208279685-7ba55a69-7ff1-4cb5-84b9-0de48fb567c3.png)

**Comment by unomi-zan** [comment]
Tweaked around some settings and found out that it seems to be caused when the title bar is enabled.

### Title Bar enabled
![image](https://user-images.githubusercontent.com/79187956/208286111-6d9a379b-6d3b-45aa-87e0-e405fd71abda.png)

### Title Bar disabled
![image](https://user-images.githubusercontent.com/79187956/208286066-47d7e4d3-2770-4f4b-b1c2-897ccb0aabfd.png)
