### ISSUE TITLE
[BUG] Like everything is messed up

### ISSUE THREAD

**Issue by TheKrafter** [rafaelmardojai/firefox-gnome-theme#525]
**Describe the bug**
the top bar and tab bar area is all messed up.
Cannot see bookmarks, extensions, open tabs, etc.

**To Reproduce**
1. Open firefox
2. it's messed up

**Expected behavior**
It to all appear as it has since install

**Screenshots**
![Screenshot](https://raw.githubusercontent.com/TheKrafter/thekrafter.github.io/main/files/Screenshot%20from%202022-12-17%2012-40-19.png)

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Browser firefox
 - Version 108.0

**Additional context**
It was working fine yesterday, had it update and shut down last night, and now its broken.

**Comment by emansom** [comment]
Duplicate. #504

**Comment by TheKrafter** [comment]
sorry!
