### ISSUE TITLE
Releasing headerbar buttons after dragging the window activates actions for those buttons

### ISSUE THREAD

**Issue by misuchivu** [rafaelmardojai/firefox-gnome-theme#53]
If you drag the window by grabbing some buttons like refresh, back, forward, home, new tab etc and then release the buttons, the action related to the button is activated, e.g. the page refreshes or the window is closed (if the close button is dragged).

**Comment by rafaelmardojai** [comment]
Mmm interesting, this behavior is new. It seems that in the end I will have to remove this feature.

**Comment by rafaelmardojai** [comment]
Looks like it's working fine again, can you confirm?

**Comment by misuchivu** [comment]
Nop. Still the same problem. Updated with latest commits.
