### ISSUE TITLE
Search input in library is not centered

### ISSUE THREAD

**Issue by emansom** [rafaelmardojai/firefox-gnome-theme#530]
**Describe the bug**
The search input in the library is not centered.

**To Reproduce**
1. Open the Firefox menu
2. Click on 'History'
3. Click on 'Manage History'
4. Observe the search input being off center

**Expected behavior**
The search input being centered.

**Screenshots**
![Schermafdruk van 2022-12-19 16-47-03](https://user-images.githubusercontent.com/981494/208466117-77524a7a-d2b3-4ebb-91ba-eac93c71120a.png)

**Setup information**
 - OS: Arch
 - Installation method: AUR
 - Firefox version: 108
 - Theme version: master git branch
 - Optional features enabled: irrelevant

**Comment by rafaelmardojai** [comment]
Duplicated of  #387.
