### ISSUE TITLE
no icons

### ISSUE THREAD

**Issue by edsonblwolf** [rafaelmardojai/firefox-gnome-theme#536]
After I installed it, it looked like this, without icons.
[https://i.imgur.com/2VTMgIB.png](url)
[https://i.imgur.com/LqfRHtp.png](url)

**Comment by williamd5** [comment]
This looks like an issue with fonts. The icons that are usually displayed at these places use a font which replaces letters/special characters or even full words (like with Google Material icons, seen in the Translate screenshot) with an icon.

**Comment by rafaelmardojai** [comment]
This can hardly be an issue with the theme, please report again if you are still this issue with the theme installed only.
