### ISSUE TITLE
Master password dialogue looks wrong. 

### ISSUE THREAD

**Issue by lightonflux** [rafaelmardojai/firefox-gnome-theme#537]
**Describe the bug**
![grafik](https://user-images.githubusercontent.com/1377943/209992588-760b2692-97cc-4896-ac2b-967ac2c21e00.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Have Firefox 108.0.1  (Flatpak)
2. Invoke master password dialogue
3. Look at it.

**Expected behavior**

Dialogue window should look like adwaita dialogue.

**Setup information**
 - OS:  Fedora
 - Installation method: flatpak
 - Firefox version:  108.0.1 
 - Theme version: master

**Comment by rafaelmardojai** [comment]
Sadly these kind of Firefox dialogs can't be improved further. (Fixed a bit the padding)

**Comment by lightonflux** [comment]
![grafik](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/1377943/970311b6-6f50-4c27-a6d5-2c66261a721a)
Looks much better now. Thanks a lot!
