### ISSUE TITLE
Close tab button to left version [Feature]

### ISSUE THREAD

**Issue by ghabit** [rafaelmardojai/firefox-gnome-theme#538]
**Is your feature request related to a problem? Please describe.**
For users, who are using close window at left side of window, can be close tab button moved to the left somehow?

**Describe the solution you'd like**
It can be done as done in gnome web

**Describe alternatives you've considered**
As alternative it can be done as mac os safari is done

**Additional context**
Now I have close button moved to the left of window, and close tab buttons positioned at the 
![Screenshot from 2022-12-30 23-43-26](https://user-images.githubusercontent.com/70936/210110423-44794266-de81-46ed-a6a1-87e838b790b6.png)
right, it's killing me via my OCD.

**Comment by lullabyist** [comment]
I don't see why this can't be made an optional feature. It's been requested enough times now (#275, #503). If I made a PR would it be accepted?

**Comment by rafaelmardojai** [comment]
@lullabyist The tabs alignment CSS is a bit complicated, and I'm not investing my time on that, but if you want to try out and implement this, yes I will accept a PR with an opt feature for this.

**Comment by ghabit** [comment]
Can we at least keep this open, and maybe add help needed tag or something?

**Comment by svta-7125** [comment]
If your DE is GNOME, you can install gnome tweaks and change the button placements from there.

**Comment by pchmykh** [comment]
> If your DE is GNOME, you can install gnome tweaks and change the button placements from there.

Yes, but it doesn't affect Firefox tabs.

**Comment by rafaelmardojai** [comment]
The theme should now move the tab close button the left if window controls are the same.

**Comment by pchmykh** [comment]
> The theme should now move the tab close button the left if window controls are the same.

Thank you dear sir!

**Comment by svta-7125** [comment]
> > If your DE is GNOME, you can install gnome tweaks and change the button placements from there.
> 
> Yes, but it doesn't affect Firefox tabs.

That's since Firefox uses xorg by default. If you're using wayland, use flatseal and disable xorg/x11 so firefox opens with wayland.

**Comment by pchmykh** [comment]
> > > If your DE is GNOME, you can install gnome tweaks and change the button placements from there.
> > 
> > 
> > Yes, but it doesn't affect Firefox tabs.
> 
> That's since Firefox uses xorg by default. If you're using wayland, use flatseal and disable xorg/x11 so firefox opens with wayland.

Can you please tell what I'm doing wrong?

![Screenshot from 2023-10-04 19-44-11](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/125208381/7caa4a4c-386f-4844-a4a5-743238697925)
