### ISSUE TITLE
How to bring the window management icons back on mac?

### ISSUE THREAD

**Issue by kubai087** [rafaelmardojai/firefox-gnome-theme#539]
<img width="1550" alt="iShot_2022-12-31_20 04 02" src="https://user-images.githubusercontent.com/68949228/210136124-d2c21334-4105-40b4-8e0b-a0f4b6f7db45.png">

**Comment by rafaelmardojai** [comment]
The theme uses Firefox media queries that are only available on linux, and I'm not planning to add mac support unless someone else wants to implement it.
