### ISSUE TITLE
Hide the tab bar when only one tab that is open doesn't work

### ISSUE THREAD

**Issue by SeptianTux** [rafaelmardojai/firefox-gnome-theme#54]
![Screenshot_19-07-2019_17:10:32](https://user-images.githubusercontent.com/16522812/61528332-adb1f900-aa48-11e9-9e29-41ac921a7557.png)

I use Firefox 68.0 on Ubuntu 18.04

**Comment by ubluish** [comment]
Move the "New tab" button to the headerbar.

**Comment by SeptianTux** [comment]
It's work. I think it's a bug.

**Comment by abrac** [comment]
Hi. I also need help for this... How do you move the new tab button to the headerbar? It doesn't appear when I'm in the "Customize Firefox" page.

**Comment by rafaelmardojai** [comment]
@abrac Mmm, seems like the overflow menu is on top of the tabsbar. I need to fix that.

**Comment by abrac** [comment]
@rafaelmardojai Thanks! Your comment helped me find a workaround. 

For future visitors: Simply disable *Firefox-Gnome-Theme* by going to your Firefox profile's `userChrome.css` file, and commenting out the line 

```css
@import "firefox-gnome-theme/userChrome.css";
```

Reopen Firefox, and you will now be able to move the new tab icon to the toolbar. Now, uncomment the above line and reopen Firefox.

**Comment by bbabel** [comment]
I can confirm that this is fixed in latest version (dfa1bc5 on 26 Nov 2020). When you hit "Customize Firefox" the "New Tab" Button appears and you can drag it to the main bar.
