### ISSUE TITLE
Flexible spaces disappear when entering/exiting full screen video

### ISSUE THREAD

**Issue by Movisivi** [rafaelmardojai/firefox-gnome-theme#540]
Title. Depending on how many I have,  each time I full screen then exit, the spaces disappear one by one.   Rapidly pressing F on YouTube doesn't bring them back either., a browser restart fixes it halfway. Some comes back but others doesn't. Going into Customize Toolbar shows them as placed on the toolbar then exiting brings them both back.  Running Nightly 110

**Comment by rafaelmardojai** [comment]
Looks like duplicated of  #492. Are you using the master version of the theme?

**Comment by Movisivi** [comment]
Yes, is it fixed on beta?
