### ISSUE TITLE
System icons look like Window is out of focus

### ISSUE THREAD

**Issue by reihwald** [rafaelmardojai/firefox-gnome-theme#544]
**Describe the bug**
The icons of the browser are brighter than the ones on other native applications when enabling gnomeTheme.systemIcons on Ubuntu using the -t yaru theme.

**To Reproduce**
1. Install the latest version (as of writing this issue) using ./scripts/auto-install.sh -t yaru
2. Enable the gnomeTheme.systemIcons option
3. Set Ubuntu to the light theme

**Expected behavior**
I'd expect the icons to be the same color as on the rest of the applications

**Screenshots**
How Firefox looks:

![grafik](https://user-images.githubusercontent.com/56656499/212431309-d8fe80ad-6991-4d4b-a26b-5d2de8607180.png)

How other applications look:

![grafik](https://user-images.githubusercontent.com/56656499/212622681-09ee6d95-2960-4ea9-a163-d173a73b4103.png)

**Setup information**
 - OS: Ubuntu 22.10
 - Installation method: .deb
 - Firefox version: 109
 - Theme version: master 108.1
 - Optional features enabled: -yaru, gnomeTheme.hideSingleTab, gnomeTheme.systemIcons

**Comment by rafaelmardojai** [comment]
That's a known limitation of `gnomeTheme.systemIcons`. See https://github.com/rafaelmardojai/firefox-gnome-theme#icons-color-broken-with-system-icons.

**Comment by reihwald** [comment]
Am I doing something wrong? The color of the icons don't seem to change no matter what filter I apply
