### ISSUE TITLE
[Feature] Develop a userChrome CSS Theme for FireFoxPWA

### ISSUE THREAD

**Issue by quebexer** [rafaelmardojai/firefox-gnome-theme#547]
[FirefoxPWA](https://github.com/filips123/PWAsForFirefox) let's you install PWAs like if they were native apps. However, when you install them, they keep the original Firefox theme. I tried installing your Gnome Theme but it looks odd. See the picture below for comparison.

![Screenshot from 2023-01-20 15-01-17](https://user-images.githubusercontent.com/13590875/213817519-65fb357c-d61d-4929-9638-1878b57b0e3d.png)

**Comment by LSeelig** [comment]
I use a custom default profile so apps automatically use the native titlebar (the extensions button and permissions can still be accessed with ctrl-tab) but supporting firefoxpwas would mean right click menus, other ui elements, and maybe the more useful custom titlebars would integrate better.

**Comment by rafaelmardojai** [comment]
I use Fedora Silverblue and Flatpaked Firefox, and installing this extension to try to support it seems impossible. PRs will be very welcome if anyone actually using the extension can work on this.

**Comment by LSeelig** [comment]
I don't know if/how it can be done with a flatpak since I use the rpm Firefox on Fedora Workstation.

**Comment by rafaelmardojai** [comment]
If anyone has access to it and is willing develop support for this extension I'm open to PRs.

For now I'm closing as out of scope, since it's my policy for extension-support requests.
