### ISSUE TITLE
Broken browser resize and css ":hover"

### ISSUE THREAD

**Issue by ghost** [rafaelmardojai/firefox-gnome-theme#548]
**Describe the bug**
Broken browser resize and css ":hover". 
I can't see what i select on pages and in browser. :hover applies if I click only.
Also sometimes I can't resize window and if toggle maximize I see this (see additional screenshot).
This happens from time to time. Restarting browser fixes issue

**To Reproduce**
1. Install Theme
2. Use theme for some time
**Expected behavior**

**Screenshots**

**Setup information**
 - OS: Arch Linux
 - Installation method: git clone
 - Firefox version: 109
 - Theme version: master
 - Optional features enabled:
    gnomeTheme.bookmarksToolbarUnderTabs | true
    gnomeTheme.hideWebrtcIndicator | true
    gnomeTheme.normalWidthTabs | false
    gnomeTheme.systemIcons | true
    gnomeTheme.tabsAsHeaderbar | true

**Additional context**
![image](https://user-images.githubusercontent.com/8164054/213866525-0eb9b49a-9ba2-4c0a-bde1-80bef6aad45a.png)

**Comment by unc926** [comment]
I can confirm this.

toolbar icons sliding to right side ( passing flexible space )

all popup menus are broken. suddenly flashes and hiding.

text selection behaves as if using a combination of shift or ctrl.

not using any optional features

![tb](https://user-images.githubusercontent.com/30185386/216821145-cae6be52-2569-45bc-a53a-3f9134955f3a.png)
![tb2](https://user-images.githubusercontent.com/30185386/216821149-f12e4fed-8215-40f2-b429-3bcebc57a847.png)

**Comment by andretiagogr** [comment]
> Have you tested if this can reproduced without the theme?

It happened to me without the theme, so the issue must lie elsewhere.
