### ISSUE TITLE
[Feature] give gnome colors to firefox "about:" pages and popup dialogs

### ISSUE THREAD

**Issue by erlefloch** [rafaelmardojai/firefox-gnome-theme#549]
**Is your feature request related to a problem? Please describe.**
I feel that the default colors of firefox internal pages don't match with adwaita colors, especially with the dark theme on. 

**Describe the solution you'd like**
I would like the firefox gnome theme to change the default colors of firefox, on "`about:`" pages like `about:settings`, info pages like the "Secure Site Not Available" page, and on popup dialogs like the printing dialog.

**Describe alternatives you've considered**
Maybe it is possible to changing these settings manually in `about:config`, but it is hard to figure out what setting changes what feature. 

**Additional context**
screenshots:

![image](https://user-images.githubusercontent.com/90708860/214092968-9b809f3f-4cf9-4e47-977e-dc0974293eba.png)

![image](https://user-images.githubusercontent.com/90708860/214090752-b62e71c1-30d0-4c76-a9a4-b334057c761b.png)

![image](https://user-images.githubusercontent.com/90708860/214094234-41bc8ddd-7c31-40b9-b9d5-1941597a9fa2.png)

**Comment by rafaelmardojai** [comment]
Duplicated of #244.
