### ISSUE TITLE
Hiding single tab is not working in Nightly 111

### ISSUE THREAD

**Issue by bbhtt** [rafaelmardojai/firefox-gnome-theme#552]
**Describe the bug**

Single tab hiding is not working in Nightly 111

**To Reproduce**
1. Install latest Nightly 111 I'm using 2023-01-30
2. Enable hiding single tab as per Readme
3. Move the new tab button to the top bar
4. See that the tab is still displayed

**Expected behavior**

Tab should be hidden

**Screenshots**

![image](https://user-images.githubusercontent.com/62639087/216035963-f556ba18-80f6-4ec0-9c7f-6bc65007f428.png)

**Setup information**
 - OS: Arch Linux
 - Installation method: Flatpak
 - Firefox version: 111.0a1 (2023-01-30)
 - Theme version: master 78fb30118a58425a41ead035324c353828200112
 - Optional features enabled:
 
```
gnomeTheme.hideSingleTab
gnomeTheme.activeTabContrast
gnomeTheme.hideWebrtcIndicator
gnomeTheme.bookmarksToolbarUnderTabs
```

**Additional context**

It is working correctly on 109.0.1

**Comment by bbhtt** [comment]
There seems to be some new buttons to move between tabs, they disappear on hovering over the tab

![image](https://user-images.githubusercontent.com/62639087/216036266-38610722-78bd-4b0f-bc69-2c88a2fecfc2.png)

Also the tab manager button is being displayed with only 2 tabs? Shouldn't it be displayed when tabs overflow? I have the tabsmanager about:config pref turned off, so this is from this theme

**Comment by MatthewCash** [comment]
I am seeing the same behavior on Firefox Developer edition 110.0b6, although the tab manager and buttons do not show when the last tab is the active tab.

**Comment by RogerioTDS** [comment]
Same issue on Firefox 110 which just hit the official Arch repositories.

**Comment by rafaelmardojai** [comment]
Hmm so the `first-visible-tab` and `last-visible-tab` attributes are gone and the current CSS no longer works.

`:only-of-type` seems to do the work.

**Comment by rafaelmardojai** [comment]
> Hmm so the `first-visible-tab` and `last-visible-tab` attributes are gone and the current CSS no longer works.
> 
> `:only-of-type` seems to do the work.

This also seems to resolve #498, which is not how libadwaita behaves, but we don't have other option.

**Comment by maymage** [comment]
@rafaelmardojai 

Hi, I'on Firefox 110, current flatpak install, but the `hide-single-tab` still doesn't work, though updated and that seems to have worked 🙅‍♀️
