### ISSUE TITLE
Tab manager menu is missing container icons

### ISSUE THREAD

**Issue by bbhtt** [rafaelmardojai/firefox-gnome-theme#553]
**Describe the bug**

Tab manager menu is missing container icons

**To Reproduce**
1. Install latest Nightly 111 I'm using 2023-01-30
2.  Go to tabmanager menu> New container tab
3. See that no container icons are displayed

**Expected behavior**
 
Container icons should be displayed

**Screenshots**

**Setup information**
 - OS: Arch Linux
 - Installation method: Flatpak
 - Firefox version: 111.0a1 (2023-01-30)
 - Theme version: master 78fb30118a58425a41ead035324c353828200112
 - Optional features enabled:
 
```
gnomeTheme.hideSingleTab
gnomeTheme.activeTabContrast
gnomeTheme.hideWebrtcIndicator
gnomeTheme.bookmarksToolbarUnderTabs
```

**Additional context**

Maybe this is Nightly only issue?

**Comment by rafaelmardojai** [comment]
@bbhtt Is this still an issue? Icons looks fine for me.

**Comment by bbhtt** [comment]
> @bbhtt Is this still an issue? Icons looks fine for me.

Yea it is still missing the icons in Nightly 115.0a1 (2023-05-12). Once you open enough tabs with the theme the tab manager menu appears > New container tab

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/62639087/0d4fb00c-0590-4f1d-b1b4-1d23b75c834f)
