### ISSUE TITLE
Tab panel shaking when two or more Tabs are open since updating to Firefox 110.0

### ISSUE THREAD

**Issue by githubtefo** [rafaelmardojai/firefox-gnome-theme#556]
**Describe the bug**
I just update to Firefox 110 and I start noticing that the Tabs are shaking occasionally when I have two or more open.
UPDATED: Maybe related to pin tabs; I just closed it and it doesn't seem to happen so far.
**To Reproduce**
1. Update Firefox.
2. Open two or more tabs.
3. You will see the issue.

**Expected behavior**
Not shaking tabs.
**Screenshots**
[Screencast from 02-11-2023 03:08:48 PM.webm](https://user-images.githubusercontent.com/11220103/218279081-f5141d23-c4d2-440b-b012-58d8873f6d63.webm)

**Setup information**
 - OS: [e.g. Fedora, Ubuntu] Ubuntu 22.04 LTS
 - Installation method: [e.g. rpm, flatpak] deb package
 - Firefox version: [e.g. 108] 110
 - Theme version: [e.g. v108, master, commit]  v108.1; UPDATED: also moved to v109 and same behavior.
 - Optional features enabled: [e.g. gnomeTheme.hideSingleTab] not that I remember.

**Additional context**

**Comment by IntoTheVoid-900** [comment]
I have also had this issue on the 110 Flatpak, I am using VanillaOS (a fork of Ubuntu)

**Comment by rafaelmardojai** [comment]
So for now we have lost tabs separators until I figure out a new implementation.

**Comment by githubtefo** [comment]
Looks great! Also, the HideSingleTab option starts working again!

**Comment by Inderix** [comment]
I'm still seeing this issue as of commit e3db36c, when I'm on the last tab in the tab strip it's fine, but opening my pinned tabs or any other tab will cause the shaking again. HideSingleTab isn't working for me either.

I'm using Firefox 110.0, Arch Linux x86_64, Firefox was installed via ``pacman``.

**Comment by rafaelmardojai** [comment]
> I'm still seeing this issue as of commit [e3db36c](https://github.com/rafaelmardojai/firefox-gnome-theme/commit/e3db36cba1ac9b710713d1b2c6a034e09493a5be), when I'm on the last tab in the tab strip it's fine, but opening my pinned tabs or any other tab will cause the shaking again. HideSingleTab isn't working for me either.
> 
> I'm using Firefox 110.0, Arch Linux x86_64, Firefox was installed via `pacman`.

You're describing the bug exactly how it was before the patch, and the fact that is fixed for others makes me wonder if you are really running the latest commits. Could you share some videos or screenshots? If you still see the tabs separators then you aren't running the latest commits.

**Comment by Inderix** [comment]
![image](https://user-images.githubusercontent.com/88416096/219431920-eec018d4-3bb0-4cea-b08f-526dfa29ba24.png)
Here's what my tab bar looks like at this moment, I'm on Wayland and I don't have the tools for screen recordings right now. 

When I updated, I deleted the ``chrome`` folder from ``~/.mozilla/firefox/jhpl18d7.default``, and re-ran the AIO command from the README. I'm rather new to theming Firefox to this extent, so now I believe I may have done something wrong.

**Comment by rafaelmardojai** [comment]
@Inderix  Usually Firefox stable profiles end with `.default-release`, the `.default` folder usually is jut a dummy one.  The best way to find out your Firefox profile folder is going to `about:support` in your address bar and look for the "Profile Directory" on that page.

**Comment by Inderix** [comment]
Thanks, seems like everything is working correctly now! Awesome work on this

**Comment by IntoTheVoid-900** [comment]
I am on the master branch now, and it's working perfectly, thanks! I do miss the look of the tab separators, but this is fully functional for my workflow and that's what matters. You should probably pin this issue, because the latest release doesn't include the fix and more people will have the issue when they update Firefox.
