### ISSUE TITLE
Extension pop-ups have inconsistent white background

### ISSUE THREAD

**Issue by xcffl** [rafaelmardojai/firefox-gnome-theme#56]
Pop-ups of extensions may have white background or background of other colors. Like this one:
![Popup](https://user-images.githubusercontent.com/2216902/61539001-09b95500-aa2a-11e9-87c4-3e67923688cb.png)

Is there any way to make the white gray, or crop the original popups instead of adding borders with round corners?

**Comment by rafaelmardojai** [comment]
Now popovers will use extension content background when is set with `--arrowpanel-background`. This will help.
