### ISSUE TITLE
Ability to change tab height

### ISSUE THREAD

**Issue by cardinalpepe** [rafaelmardojai/firefox-gnome-theme#561]
**Is your feature request related to a problem? Please describe.**

After installing these theme I noticed that the tab-bar is by default very large, I tried various css and whatnot but I cant figure out how make them less tall, this isn't really a bug or feature request, I just don't know where to ask.

**Describe the solution you'd like**
How to change tab size/height.

**Comment by rafaelmardojai** [comment]
The theme provides an [optional feature](https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features) (`gnomeTheme.normalWidthTabs`) to use the default Firefox tabs width.

About tabs height, we use the libadwaita tabs height, I don't plan to change that.

To change the tab box height (to 24px for example) you can use this CSS:
```css
tab > stack {
	height: 24px !important;
	min-height: 24px !important;
}
```
(The tab box has padding so the actual tabs will be smaller)

But if you have taller tabs than the ones visible on the theme screenshots, then it's a bug and attaching a screenshot might help.
