### ISSUE TITLE
Bookmark toolbar - show more bookmarks button

### ISSUE THREAD

**Issue by rammazzoti2000** [rafaelmardojai/firefox-gnome-theme#563]
**Describe the bug**

The `show more bookmarks` button is not vertically aligned with the rest of the bookmarks

**Screenshots**

![image](https://user-images.githubusercontent.com/3244654/222826708-6479e808-a3cb-481f-910a-26cce40f1f0e.png)

**Setup information**
 - OS: Fedora 37 Gnome 43
 - Installation method: `One command curled script`
 - Firefox version: 110 (64 bit)
 - Theme version: 110
 - Optional features enabled: `gnomeTheme.hideSingleTab`, `gnomeTheme.activeTabContrast`, `gnomeTheme.systemIcons`

**Comment by rafaelmardojai** [comment]
Looks like this for me:
![Captura desde 2023-03-26 18-19-09](https://user-images.githubusercontent.com/6210397/227811067-0c673e0c-eebf-4184-87fa-c46ae87aa1dc.png)

**Comment by rafaelmardojai** [comment]
Actually looks like an issue caused by `gnomeTheme.systemIcons`.
