### ISSUE TITLE
Space below the mailto dialog

### ISSUE THREAD

**Issue by ascpial** [rafaelmardojai/firefox-gnome-theme#564]
**Describe the bug**

There is a gap between the buttons and the end of the window in the mailto dialog.

**To Reproduce**

1. Go onto a website which proposes you to send emails
2. Send an email
3. In the dialog to choose the application in which to open the mail, there is the gap as follows:

**Expected behavior**

There should be no gap bellow the button, like other Adwaita dialog windows.

**Screenshots**

![image](https://user-images.githubusercontent.com/72463129/222926999-efa3ad13-f140-4a64-b87c-62e8da2b6898.png)

**Setup information**
 - OS: Fedora 37
 - Installation method: RPM
 - Firefox version: 110.0
 - Theme version: master ([acf52c4](https://github.com/rafaelmardojai/firefox-gnome-theme/commit/acf52c41f0c3a47fbc6b6e0cb7a899c76579e72d))

**Comment by rafaelmardojai** [comment]
Looks like a problem with Firefox's resizable dialogs, tried to make them look better.

**Comment by ascpial** [comment]
I checked it and it looks far better, thank you!
