### ISSUE TITLE
[Qestion] Alsking help about tab height 

### ISSUE THREAD

**Issue by Noob-linux-user** [rafaelmardojai/firefox-gnome-theme#567]
I don't know if this is the right place, but is there a way to reduce the padding between the tab and the URL bar? when I try to make the tab small by using
`.tabbrowser-tab {
  height: 15px !important;
  min-height: 15px !important;
  max-height: 15px !important;`

the padding is still there and the tab cuts some of the text.
Also, can we make a smooth transition while showing the tab bar when more than 1 tab is present?

**Comment by cardinalpepe** [comment]
asked this a while ago, the dev said "About tabs height, we use the libadwaita tabs height, I don't plan to change that.", no css I tried worked so I just got used to it over the span of a month.

**Comment by Noob-linux-user** [comment]
thanks for the reply. i feel like the margin is too much for the tab. I guess there isn't an easy fix
