### ISSUE TITLE
Show sidebars icon doesn’t look gnomish

### ISSUE THREAD

**Issue by ai** [rafaelmardojai/firefox-gnome-theme#57]
![Screenshot from 2019-07-19 11-52-40](https://user-images.githubusercontent.com/19343/61548509-dbcd1400-aa1b-11e9-911a-fb33323b332c.png)

Icon uses thin lines in contrast with other GNOME icons

![Screenshot from 2019-07-19 11-54-18](https://user-images.githubusercontent.com/19343/61548555-f4d5c500-aa1b-11e9-8572-9fc1d7100265.png)

**Comment by rafaelmardojai** [comment]
We're using the side panel icon from GNOME Builder.
There's no GNOME symbolic icon for sidebar.

**Comment by ai** [comment]
Thanks for the explanation. I think it is OK, now.

**Comment by rafaelmardojai** [comment]
Sidebar icon should be more GNOMISH now.
