### ISSUE TITLE
`List all tabs` button won't appear unless the tabs are "squeezed"

### ISSUE THREAD

**Issue by Ashvith10** [rafaelmardojai/firefox-gnome-theme#572]
**Describe the bug**
`List all tabs` won't appear unless there's enough tab to bring scroll

**To Reproduce**
1. Open Firefox, you'll see the `List all tabs` button hidden
2. Keep creating multiple tabs (more than 12 in my case), till the tabs don't grow any smaller and brings a scroll bar - `List all tabs` will be visible now.

**Expected behavior**
`List all tabs` should be visible all the time, irrespective of whether the breakpoint is reached or not.

**Screenshots**
Single tab, no scrollbar visible on tab section - no `List all tabs` button
![Screenshot from 2023-03-26 10-57-30](https://user-images.githubusercontent.com/113123021/227757158-54777694-c253-4a1b-8af2-e01462b57aa7.png)

Thirteen tabs open, scroll bar visible - `List all tabs` button is visible
![Screenshot from 2023-03-26 10-57-43](https://user-images.githubusercontent.com/113123021/227757160-ee09fb8a-e13e-4685-9c42-59da2bc87238.png)

**Setup information**
 - OS: Fedora 38
 - Installation method: RPM
 - Firefox version: 110
 - Theme version: v110
 - Optional features enabled: None

**Additional context**
-

**Comment by rafaelmardojai** [comment]
Actually, this is intentional to mimic GNOME web behavior.

This is the code if you want to remove it:

https://github.com/rafaelmardojai/firefox-gnome-theme/blob/18a4d21238be0adb941ad94d6ae6df5f16bfc5ca/theme/parts/tabsbar.css#L468-L474

**Comment by jianglai** [comment]
It doesn't look like the button shows up even when the tab width stops shrinking. Changing the CSS does make it visible all the time.

Can you make whether it shows up configurable in `about:config`?

**Comment by jianglai** [comment]
Actually, the [`browser.tabs.tabmanager.enabled`](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/59eee4080aa79a0671e98358f91ae1ef0c0806e1/theme/parts/tabsbar.css#L524) flag will make the button visible when the tabs overflow.

But I'd still prefer to have the option to make it visible all the time, just like stock Firefox.
