### ISSUE TITLE
Firefox GNOME Theme doesn't use system's custom GNOME theme

### ISSUE THREAD

**Issue by aitor-gomila** [rafaelmardojai/firefox-gnome-theme#575]
**Describe the bug**
I use Elementary OS 7, which is based upon ubuntu and gnome. The default browser is GNOME Web, it looks great, is more-or-less privacy-focused, and blends well with the OS.

The problem is that it uses safari, which sucks because I can't even access Github.

So I installed firefox through the flatpak with the intention to use this theme and I thought it would fit well. but apparently it uses adwaita and the built in gnome icons.

**To Reproduce**

1. Use a distribution that isn't default GNOME (e.g. Ubuntu, elementaryOS...) It can be a virtual machine
2. Download firefox (important!! via flatpak)
3. Get this theme: open about:profiles, open directory of current profile, clone repository, use flatpak installation script
4. Firefox will use gnome default icons and default adwaita theme, even if the distribution uses another theme

**Expected behavior**

**Screenshots**
Firefox on Elementary with firefox-gnome-theme

![image](https://user-images.githubusercontent.com/46191980/227901605-f78247ff-63ff-4813-8828-c40e1071ffb8.png)

GNOME Web on elementary

![image](https://user-images.githubusercontent.com/46191980/227901777-b5fb0c5a-859f-488b-a436-eb6b8f537438.png)

**Setup information**
 - OS: Elementary OS 7 (ubuntu 22.04 LTS)
 - Installation method: Flatpak
 - Firefox version: 111.0.1
 - Theme version: master (1cf5df7)
 - Optional features enabled: 

**Additional context**
I can work on this issue if you point out how to do it

**Comment by emansom** [comment]
This theme is for Adwaita/GNOME, not Granite/Pantheon. Consider using [this theme](https://github.com/Zonnev/elementaryos-firefox-theme) instead.

**Comment by aitor-gomila** [comment]
Thanks!

**Comment by rafaelmardojai** [comment]
Just to make things clear, this theme is just CSS trying to mimic GNOME's Adwaita. Any other theme must be manually implemented too.
