### ISSUE TITLE
Hover highlight in unified extension menu is misaligned in Nightly 113

### ISSUE THREAD

**Issue by bbhtt** [rafaelmardojai/firefox-gnome-theme#579]
**Describe the bug**

**To Reproduce**

1. Go to unified extension menu
2. Hover over an extension cogwheel

**Expected behavior**

Aligned properly

**Screenshots**

![image](https://user-images.githubusercontent.com/62639087/228707432-f86bd5ca-ce90-46a5-88cf-760319910ea7.png)

**Setup information**
 - OS: Arch Linux
 - Installation method: Flatpak
 - Firefox version: 113.0a1 (2023-03-28)
 - Theme version: beta b95cf7962b2f18e7c04aff6f0e0d02e147725a0e
 - Optional features enabled:
 
```
gnomeTheme.hideSingleTab
gnomeTheme.activeTabContrast
gnomeTheme.hideWebrtcIndicator
```

**Additional context**

Working correctly with stable Firefox

![image](https://user-images.githubusercontent.com/62639087/228708213-91f9fd50-35c1-418f-89be-fa00c0ba5d87.png)

**Comment by rafaelmardojai** [comment]
Also fixed by [efd69a3ef5d8ea7007ab923229b4c41faf26c9b5]
