### ISSUE TITLE
Searchbar's button overlap with the search entry

### ISSUE THREAD

**Issue by Cogitri** [rafaelmardojai/firefox-gnome-theme#58]
This only happens when I make the window smaller (as in, not have it take up the entire workspace)
![Screenshot from 2019-07-21 01-47-07](https://user-images.githubusercontent.com/8766773/61585356-c3fbaa00-ab59-11e9-8662-3cc9a0188970.png)

Here's a webm of the thing:

[Peek 2019-07-21 01-49.zip](https://github.com/rafaelmardojai/firefox-gnome-theme/files/3414080/Peek.2019-07-21.01-49.zip)

**Comment by rafaelmardojai** [comment]
This is supposed to be fixed since [bab8951]. Your copy of the theme is up to date?

**Comment by Cogitri** [comment]
Yes, just updated, but let me check again

**Comment by Cogitri** [comment]
Hm, my profile's chrome/firefox-gnome-theme folder is at commit a9b0de3224d699b770f9a9ffad825e2ada1f1b25, which should be the latest one

**Comment by lionirdeadman** [comment]
What version of firefox?

**Comment by Cogitri** [comment]
68.0

**Comment by rafaelmardojai** [comment]
Still the same?

**Comment by Cogitri** [comment]
Pulled again and it seems to work now, thank you for this great theme :)
