### ISSUE TITLE
Dialogue buttons are misaligned in Nightly 113

### ISSUE THREAD

**Issue by bbhtt** [rafaelmardojai/firefox-gnome-theme#581]
**Describe the bug**

**To Reproduce**

1. Go to Site information dropdown (the lock symbol in address bar)
2. Click on "Clar cookies and site data"
3. See that buttons are misaligned in the dialogue box

**Expected behavior**

Properly aligned

**Screenshots**

![image](https://user-images.githubusercontent.com/62639087/229016194-245127d5-eea0-4189-b33c-542f343d52b7.png)

**Setup information**
 - OS: Arch Linux
 - Installation method: Flatpak
 - Firefox version: 113.0a1 (2023-03-28) 
 - Theme version: master 0cc285b
 - Optional features enabled: 

```
gnomeTheme.hideSingleTab
gnomeTheme.activeTabContrast
gnomeTheme.hideWebrtcIndicator
```

**Additional context**

N/A

**Comment by bjornpijnacker** [comment]
Can reproduce on Firefox 111.0.1
![image](https://user-images.githubusercontent.com/35508080/230771643-066795dc-1901-45d8-8618-47f53d506a1b.png)

**Comment by rafaelmardojai** [comment]
If you resize the dialog, everything looks fine. I guess I can try to reduce the top padding so buttons can fit.
