### ISSUE TITLE
Close window button turns red on hover when dark theme is enabled in firefox settings

### ISSUE THREAD

**Issue by untermensch** [rafaelmardojai/firefox-gnome-theme#583]
**Describe the bug**

The window close button turns red (#d60022) on hover, if FF theme is set to dark.

**To Reproduce**

1. Go ti FF settings > Themes > Enable dark theme
2. Hover mouse over the close window button in top right
3. Button turns red.

**Expected behavior**

Button turns light grey.

**Screenshots**

![image](https://user-images.githubusercontent.com/35326326/229271753-3d841575-a5df-4423-8f91-fcaf2eb2f77f.png)

**Setup information**
 - OS: VanillaOS 22.10
 - Installation method: Flatpak
 - Firefox version: 111.0.1 (64-bit)
 - Theme version: v111
 - Optional features enabled: none

**Comment by rafaelmardojai** [comment]
Yes, currently the theme only officially supports the "system" Firefox theme since I don't have time to test against the others.

**Comment by rafaelmardojai** [comment]
> Yes, currently the theme only officially supports the "system" Firefox theme since I don't have time to test against the others.

This is stated at the end of this section of the README: https://github.com/rafaelmardojai/firefox-gnome-theme#required-firefox-preferences

**Comment by rafaelmardojai** [comment]
Looks like Firefox now allows our theme to  force a different theme than the system one. So I will start supporting them.

Removed the warning from README.
