### ISSUE TITLE
Add this theme to FirefoxCSS-store

### ISSUE THREAD

**Issue by Neikon** [rafaelmardojai/firefox-gnome-theme#586]
User [Zabooby](https://github.com/Zabooby) has asked us to include this theme in [firefoxcss.-store](https://firefoxcss-store.github.io/), can we do it?

Link to issue: https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/issues/175

**Comment by rafaelmardojai** [comment]
This theme was included more than a year ago: https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io/pull/110
