### ISSUE TITLE
Error entering profile folder?

### ISSUE THREAD

**Issue by amivaleo** [rafaelmardojai/firefox-gnome-theme#59]
Hi!

This is what I get when I try to run the install.sh script for my firefox 68.0 on Fedora:

"./install.sh: line 26: cd: too many arguments
Error entering profile folder."

How to fix this? I would love to use this "theme"... :(

**Comment by rafaelmardojai** [comment]
This happen when the script cant find any profile folder in standard firefox folder `~/.mozilla/firefox`.

Can you go to `about:support` in Firefox. Then: search for "Profile Directory". And paste the route here?.

**Comment by amivaleo** [comment]
Sure.

Here it is:

"/home/jimmy/.mozilla/firefox/bxqax3fp.default-release"

**Comment by amivaleo** [comment]
I tried:

`$ ./install.sh -p bxqax3fp.default-release`

It doesn't complain, but firefox gui doesn't change.

**Comment by rafaelmardojai** [comment]
I just seen `cd: too many arguments`,  run `./install.sh -p bxqax3fp.default-release`.

**Comment by rafaelmardojai** [comment]
> It doesn't complain, but firefox gui doesn't change.

Have you restarted Firefox?

**Comment by amivaleo** [comment]
> > It doesn't complain, but firefox gui doesn't change.
> 
> Have you restarted Firefox?

Yes. I also gave "killall firefox". Still the same.

**Comment by rafaelmardojai** [comment]
No errors in command line?

**Comment by rafaelmardojai** [comment]
Probably the script have no symlinked the `user.js` file that sets `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`. 
Otherwise you can set it in `about:config`.

**Comment by amivaleo** [comment]
I deleted the contents of ~/.mozilla/firefox an tried again.

Everything looks fine:

```
$ ./install.sh -p y0bj8bsb.default-release
Installing theme in /home/jimmy/.mozilla/firefox/y0bj8bsb.default-release
Coping repo in /home/jimmy/.mozilla/firefox/y0bj8bsb.default-release/chrome
Set configuration user.js file
Done.
```

**Comment by amivaleo** [comment]
> toolkit.legacyUserProfileCustomizations.stylesheets

It's set to "true":

![Schermata da 2019-07-21 14-55-04](https://user-images.githubusercontent.com/24316547/61591477-93525980-abc7-11e9-8b2b-b200f3644f1b.png)

Still no gnome-like gui. 🤔

**Comment by rafaelmardojai** [comment]
`y0bj8bsb.default-release` is your new profile?

**Comment by amivaleo** [comment]
Yes sir!

![Schermata da 2019-07-21 15-28-42](https://user-images.githubusercontent.com/24316547/61591893-3d33e500-abcc-11e9-99e9-ec0498aef3b9.png)

**Comment by rafaelmardojai** [comment]
If you go to `/home/jimmy/.mozilla/firefox/y0bj8bsb.default-release/chrome`, what is inside `userChrome.css`?

**Comment by amivaleo** [comment]
Ah-ha!

That's the issue!

The content of that file is this single line `@import "firefox-gnome-theme/userChrome.css";`

BUT! I cloned the repo in a hidden folder: `.firefox-gnome-theme`

I fixed this by adding the dot "." to the import line.

Thank you! :)

**Comment by gcantieni** [comment]
Hi thanks for solving this! For me it was solved by your second step: finding the name of my profile directory by going to `about:support` and pasting it after the install script:
```
./scripts/install -p <profile-name excluding directory path>.default-release
```
Works like a charm!
