### ISSUE TITLE
Support the new look (libadwaita 1.4). [Feature]

### ISSUE THREAD

**Issue by knokelmaat** [rafaelmardojai/firefox-gnome-theme#599]
**Is your feature request related to a problem? Please describe.**

A recent Libadwaita update (1.4) introduced a few new widgets, for example [AdwToolbarView](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.ToolbarView.html). With this come changes of the style compared to previous versions. An example for GNOME Web (Epiphany):

![image](https://user-images.githubusercontent.com/31448397/233068437-0eea04e0-0723-49e4-aa1e-cb0e4d8cd63c.png "GNOME Web 43.1+")

![image](https://user-images.githubusercontent.com/31448397/233066981-730795de-ae78-448c-a96a-8515291c27be.png "GNOME Web Nightly")

**Describe the solution you'd like**

Update the firefox-gnome-theme to this new style.

**Describe alternatives you've considered**

Keeping the old style, but this would look outdated amongst the other libadwaita apps (Web, Files, Music, Settings etc.).

**Additional context**

The new style is already present in GNOME OS nightly, I don't know when these will be appearing in distros (possibly already in 44, otherwise in 45)

**Comment by rafaelmardojai** [comment]
Yeah, is planned for when the new libadwaita version is released.

**Comment by Exalm** [comment]
(ephy on that screenshot is _not_ using toolbar view)

**Comment by BirdInFire** [comment]
> Yeah, is planned for when the new libadwaita version is released.

when you make it can you ping me like that i can update the color of the config for the vertical tab to mach to potential color change.

**Comment by HuyHung1408** [comment]
Are there any specific line to edit that part from grey to white? I'm not an expert in css but I can tweaking around.
