### ISSUE TITLE
Findbar content alignment

### ISSUE THREAD

**Issue by ubluish** [rafaelmardojai/firefox-gnome-theme#6]
Textbox and next & previous buttons are not aligned as you can see, buttons are higher than textbox

![Untitled](https://user-images.githubusercontent.com/21042432/59967521-64df5100-952b-11e9-8843-c56ec1023e27.png)

**Comment by rafaelmardojai** [comment]
I can't reproduce it, but i have tried something, can you test last changes?

**Comment by ubluish** [comment]
It works fine now but searchbox text aligned top not centered
![Untitled](https://user-images.githubusercontent.com/21042432/59977382-c5749980-95d0-11e9-8526-cdb53745f608.png)
