### ISSUE TITLE
Quick find bar input field jumps right after matches are found

### ISSUE THREAD

**Issue by tominventisbe** [rafaelmardojai/firefox-gnome-theme#60]
There is a special "Quick find" bar that is hidden behind the "/" key that you can use to not only find matches, but also immediately open them by pressing the return key. It looks virtually identical to the normal find bar you can open with _Ctrl+F_.

The input field on this bar doesn't appear to be centered yet and, when matches are found, Firefox displays something like "x of y matches" to the left of the input field, which causes the input field to jump to somewhere off-center to the right.

Not a priority bug, but just wanted to let you know.

**Comment by lionirdeadman** [comment]
Worth noting it can't be accessed from Github because they override the shortcut.

**Comment by tominventisbe** [comment]
Indeed, I noticed the same and didn't mention it, but I see now that I probably should have 😄.
