### ISSUE TITLE
Buttons overlap with the searchbar

### ISSUE THREAD

**Issue by enzosanchezewe** [rafaelmardojai/firefox-gnome-theme#602]
**Describe the bug**
When firefox is really narrow, buttons overlap with the searchbar.

**To Reproduce**
1. Open firefox
2. Shrink the window to a vertical rectangle
4. There are two buttons overlapping (three line menu and one that allows you to use the buttons that were hidden because of the size)

**Expected behavior**
Allow the searchbar to shrink more

**Screenshots**
![imagen](https://user-images.githubusercontent.com/62959641/233868152-c2443b3b-819a-4be5-bbb2-6d49298a1aad.png)
![imagen](https://user-images.githubusercontent.com/62959641/233868176-95480091-a20d-4877-9ffe-74618ec3ff02.png)

**Setup information**
 - OS: Manjaro
 - Installation method: pacman/pamac. Manjaro's official repo (extra)
 - Firefox version: 112.0
 - Theme version: master
 - Optional features enabled: gnomeTheme.hideSingleTab ; gnomeTheme.bookmarksToolbarUnderTabs ; gnomeTheme.hideWebrtcIndicator ; gnomeTheme.hideUnifiedExtensions

**Additional context**
No extensions.
My laptop is really small, it has a 1366x768 screen.
I'm running gnome 43.4.
Removing the spacing doesn't solve the issue.

**Comment by rafaelmardojai** [comment]
Duplicated of #133.
