### ISSUE TITLE
[Feature] Ability to change Windows button to the default system one

### ISSUE THREAD

**Issue by Noob-linux-user** [rafaelmardojai/firefox-gnome-theme#604]
The windows control button. close, minimize, and maximize are always in the adwita, 

It would be nice to have the default button instead of adwita one

**Comment by CleoMenezesJr** [comment]
Thanks for the suggestion, but this theme is made to _follow latest GNOME Adwaita style_. And as the description says _This is a bunch of CSS code to make Firefox look closer to GNOME's native apps_, it would be out of scope to maintain something like that.
