### ISSUE TITLE
gnomeTheme.hideSingleTab bug when Firefox View is clicked

### ISSUE THREAD

**Issue by uneassisedeBATARD** [rafaelmardojai/firefox-gnome-theme#605]
When I click on Firefox View, even when there is only one tab and the "gnomeTheme.hideSingleTab" feature is set to true as bollean, the taskbar appear and can't be hide.

**To Reproduce**
1. Open Firefox with "gnomeTheme.hideSingleTab" set to true as bollean.
2. Go to Firefox View.
3. See the bug.

**Expected behavior**
The taskbar, when I exit the Firefox View, should disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/115212708/235293820-7757ee04-8652-4250-9d1e-9e0c1860c6ea.png)
![image](https://user-images.githubusercontent.com/115212708/235293832-2f20246d-4ebf-415e-86b6-c0a4441f61d8.png)

**Setup information**
 - OS: Fedora Workstation 38
 - Installation method: Firefox pre-installed, theme by the curl command (curl -s -o- https://raw.githubusercontent.com/rafaelmardojai/firefox-gnome-theme/master/scripts/install-by-curl.sh | bash)
 - Firefox version: 112.0.1 (64 bits)
 - Theme version: v112
 - Optional features enabled: gnomeTheme.hideSingleTab ; gnomeTheme.bookmarksToolbarUnderTabs ; gnomeTheme.symbolicTabIcons

**Comment by rafaelmardojai** [comment]
Sadly this isn't fixable.

When you open Firefox View it will append a hidden tab to the tabsbar that never get removed afterwards. Meaning that the `tab:only-of-type` selector doesn't work any more.

This is a limitation of `gnomeTheme.hideSingleTab`, for example if you use some tabs manager extensions that hidden tabs (like Simple Tabs Group) it will also don't work. This is one of the reasons why it's an optional feature and not a default feature of the theme.

**Comment by piousdeer** [comment]
I'll add that a workaround is to close the Firefox View tab via Ctrl+W.
