### ISSUE TITLE
[Feature] Remove black seperator between tabs and URL bar to match Epiphany(Gnome Web)

### ISSUE THREAD

**Issue by JayaswalPrateek** [rafaelmardojai/firefox-gnome-theme#607]
**Is your feature request related to a problem? Please describe.**
Current style is inconsistent with org.gnome.Epiphany 

**Describe the solution you'd like**
change color from black to #303030 or change separator width to 0 (preferrable)

**Describe alternatives you've considered**
None

**Additional context**
![Screenshot from 2023-05-02 19-27-00](https://user-images.githubusercontent.com/104377054/235689398-5ea1f450-b70b-4895-bff0-16672d187081.png)

**Comment by rafaelmardojai** [comment]
This is how it looks current Epiphany stable (44.2):
![Captura desde 2023-05-02 10-27-22](https://user-images.githubusercontent.com/6210397/235712595-641003dd-fd3d-4f5d-a76f-d54f8f66d6be.png)

You're probably using some devel version, if so, it's a duplicated of  #599.
