### ISSUE TITLE
Tab text is not centered in Firefox 113

### ISSUE THREAD

**Issue by githubtefo** [rafaelmardojai/firefox-gnome-theme#609]
**Describe the bug**
Tab text is not centered in the beta version.

**To Reproduce**
Install the new branch of the beta version in Firefox v113.

**Expected behavior**
Tab text should be centered but it is aligned to the left.

**Screenshots**
**![Uploading** image.png…]()

**Setup information**
 - OS:Ubuntu 22.04 LTS
 - Installation method: git clone
 -  - Firefox version: 113.0
 - Theme version: beta branch
 - Optional features enabled:
gnomeTheme.hideSingleTab	true	
gnomeTheme.normalWidthTabs	false	
gnomeTheme.systemIcons	true

**Additional context**
Not sure if I should report a bug from beta versions... I am sorry if I should not and just disregard it and close it.

**Comment by rafaelmardojai** [comment]
> This seems to happen with the release version (113.0) as well on Arch Linux

Sure, it was reported when 113 was i in beta.

**Comment by rafaelmardojai** [comment]
For now it looks like this:
![Captura desde 2023-05-09 20-00-16](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/19eab1e6-a5b8-41a7-b913-e441a3e9bd2d)

Text centered and favicon on the left. I can't seem to be able to center both, and I'm lacking time to investigate further.

**Comment by vinceliuice** [comment]
Try this:
```
.tab-label {
	margin-inline: 0 !important;
}

.tab-label-container {
	min-width: 0 !important;
	max-width: min-content !important;
}
```

**Comment by Ashdemai** [comment]
> Try this:
> 
> ```
> .tab-label {
> 	margin-inline: 0 !important;
> }
> 
> .tab-label-container {
> 	min-width: 0 !important;
> 	max-width: min-content !important;
> }
> ```

I tried your code and it does indeed center the tab icons with the text. Nice!

**Comment by rafaelmardojai** [comment]
> Try this:
> 
> ```
> .tab-label {
> 	margin-inline: 0 !important;
> }
> 
> .tab-label-container {
> 	min-width: 0 !important;
> 	max-width: min-content !important;
> }
> ```

Thanks for the hint. Totally forgot about `min-content`.
