### ISSUE TITLE
[Feature] Colorful private windows

### ISSUE THREAD

**Issue by suwermave** [rafaelmardojai/firefox-gnome-theme#611]
**Is your feature request related to a problem? Please describe.**
Unthemed Firefox private mode window has violet shade.

**Describe the solution you'd like**
Why not to bring color to private windows!

**Additional context**
Look how it was done in elementary

![theme-odin-new](https://user-images.githubusercontent.com/50447661/236679853-f2cfc06c-f5be-4bca-ba4b-b74968b27a24.png)

**Comment by suwermave** [comment]
If it is not desired to be default to be as close to Gnome Web as possible, then this can at least be an option

**Comment by rafaelmardojai** [comment]
I might change the color from blue to purple, so it has more Firefox identity, but it will look like any other libadwaita app with colored headerbar, so no gradients.

**Comment by suwermave** [comment]
That would be LIT 🔥🔥🔥
More consistent with purple firefox background when in private mode.
