### ISSUE TITLE
New tab broken with gnomeTheme.systemIcons

### ISSUE THREAD

**Issue by Tealk** [rafaelmardojai/firefox-gnome-theme#622]
**Describe the bug**

If the scroll option is active for too many tabs, the tab line height increases and the new tab icon becomes huge

**To Reproduce**

1. Open many Tabs

**Screenshots**

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/12276250/0345e44c-280d-4a2b-a6f1-d7c2fcdc8805)

**Setup information**
 - OS: Arch
 - Installation method: manual
 - Firefox version: 113.0
 - Theme version: master

**Comment by rafaelmardojai** [comment]
Looks fine for me:
![Captura desde 2023-05-10 12-42-11](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/c519f51e-
3e9e-4baa-b5e1-3aedab3c8de6)

**Comment by Tealk** [comment]
I can reporduce it, what would help you to understand the bug?
