### ISSUE TITLE
Tab bar on top

### ISSUE THREAD

**Issue by NettoHikari** [rafaelmardojai/firefox-gnome-theme#623]
**Describe the bug**
Since today, the tab bar is displayed above the address bar in LibreWolf, even though gnomeTheme.tabsAsHeaderbar **isn't** set.

**To Reproduce**
1. Update to the lastest master code.
2. Tab bar moves to top.

**Expected behavior**
Tab bar should be underneath address bar.

**Screenshots**
![grafik](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/8510368/ad624429-a887-47b1-b58f-88049b17b684)

**Setup information**
 - OS: Arch Linux
 - Installation method: Flatpak
 - Firefox version: LibreWolf 112.0.2-1
 - Theme version: master
 - Optional features enabled: gnomeTheme.hideWebrtcIndicator

**Comment by rafaelmardojai** [comment]
This looks like Firefox 113 before the latest patches. You sure that you're running the latest master version?

**Comment by NettoHikari** [comment]
Hi! Thanks for your answer. As far as I'm aware, I'm using the latest master version.

![grafik](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/8510368/ead98f46-df27-40ab-ab1e-9facb55486ee)
![grafik](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/8510368/976dabba-b973-4fc0-920a-b0b6efbef434)

Everything worked fine until this morning after I updated my system. I use Arch Linux and I have a pacman hook that updates the GNOME theme for Firefox to the latest version (it just runs "git pull origin master" on the right folder). It's worked fine like this for a long time.

**Comment by rafaelmardojai** [comment]
> Edit: I'm probably just stupid. Might this be because I'm still on LibreWolf 112? The Flatpak hasn't been updated yet.

Probably, try using the v112 git tag.

**Comment by NettoHikari** [comment]
That worked, thanks. I just didn't think twice.

Thanks for your work and have a nice day!
