### ISSUE TITLE
Tabs act the headerbar, event though gnomeTheme.tabsAsHeaderbar is set to false

### ISSUE THREAD

**Issue by AndryCake** [rafaelmardojai/firefox-gnome-theme#624]
**Describe the bug**
The tabs still show at the top of the page, as the headerbar even though `gnomeTheme.tabsAsHeaderbar` is set to `false`

**To Reproduce**

1. Remove `chrome` folder from the profile folder
2. Run the `firefox-gnome-theme` install script
3. Go to `about:config`
4. Make sure `gnomeTheme.tabsAsHeaderbar` is set to `false`
5. Open Firefox

**Expected behavior**
The tabs should be below the find bar and the find bar should act as the headerbar

**Screenshots**
https://imgur.com/a/LAUIt1c

**Setup information**
 - OS: NixOS
 - Installation method: `nixpkgs` (in `configuration.nix`)
 - Firefox version: 113.0
 - Theme version: `master`
 - Optional features enabled: None (in fact, `gnomeTheme.tabsAsHeaderbar` is disabled)

**Edit**
It worked before (yesterday at the time of writing)

**Comment by maymage** [comment]
Also in absence of the `gnomeTheme.tabsAsHeaderbar` the same is true: the tabs are above the headerbar. 

* Firefox 113.0 from Flathub 
* Firefox theme from master

The theme installation output shows correct installation.

**Comment by raul-lezameta** [comment]
Same problem for me, unfortunately (Firefox 113.0 on Arch).
Also, the window controls are missing.

**Comment by maymage** [comment]
@rafaelmardojai 

As I said.. I am on master - updated the theme just 4 hours ago. Installation went fine, firefox is 113.

**Comment by rafaelmardojai** [comment]
> As I said.. I am on master - updated the theme just 4 hours ago. Installation went fine, firefox is 113.
> 
> Also I confirm, that the window controls are missing: that's the close button for me.
> 
> Edit: and just to be sure: reinstalled, theme goes to my profile, logged out and in again. Still the same.

Sure, but then I can't reproduce the issue. Also I was assuming that because the screenshots looks exactly like Firefox 113 before I fixed it.

This is how it looks for me:
![Captura desde 2023-05-11 07-50-46](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/e371bcb7-494e-4e4e-9004-ae3e736d2546)

Also this has nothing to do with `gnomeTheme.tabsAsHeaderbar`, this issue is caused because Firefox 113 changed the CSS properties used to reorder things, so without the fixes it goes back to the normal toolbars order.

**Comment by rafaelmardojai** [comment]
@maymage Does this part of `chrome/firefox-gnome-theme/theme/parts/toolbox.css` in your profile folder looks like this?

![Captura desde 2023-05-11 07-56-02](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/c8a8d39a-c7ad-45ed-8622-32ebd77e17b1)

**Comment by andreacocci95** [comment]
I have the same problem on 113. The problem is on one command curled script that take the last release instead of the master branch. So, can you create a new release for this fix? Thanks.

**Comment by maymage** [comment]
@rafaelmardojai 

Yeah, sorry my fault. Like @andreacocci95  I assumed, that the curl command would install master. 

Doing as you said `git clone` the master brunch and running the `./ ... . sh` makes things work. 

Sorry for the disturbance!

**Comment by AndryCake** [comment]
I see that this has been closed already (even though I did not yet reply to @rafaelmardojai's replies), but (for anyone finding this in the future) what fixed my problem was redownloading and reinstalling `firefox-gnome-theme`.

**Comment by bmreading** [comment]
Sure, but isn't this still an issue if the curl command is not working? Should we expect that to not use the master version?

**Comment by rafaelmardojai** [comment]
> Sure, but isn't this still an issue if the curl command is not working? Should we expect that to not use the master version?

The curl command installs the latest tagged version of the theme, not master, it was written intentionally like that.

In the readme is stated:

> It will download the latest version of the theme and run the auto installation script for you.

Maybe I should rephrase that to make it clear that it install the latest "stable" version of the theme.

But anyway, I tagged `v113` today so it should work just fine now.

**Comment by alerque** [comment]
I'm not convinced this is as fixed as this issue suggests. I have several machines that I've been using this on and updating in regularly for years. I've pulled the latest version of this repo (now tagged v113) that includes the commits mentioning this, but my systems have all flipped to tabs-on-top as they updated to FF113. Something else must need poking besides just having the latest theme files in places.
