### ISSUE TITLE
no titles in sidebar in v113

### ISSUE THREAD

**Issue by paolocalosso** [rafaelmardojai/firefox-gnome-theme#625]
**Describe the bug**
after updating to v113 i cannot see titles in sidebar when it is open. i'm using a customized theme based on firefox-gnome-theme and [colloid-gtk-theme for firefox by vinceliuice](https://github.com/vinceliuice/Colloid-gtk-theme/tree/main/src/other/firefox) which is also based on firefox-gnome-theme so i'm not sure if i'm in the right place

**To Reproduce**

1. ctrl+b to open sidebar
2. titles in sidebar are not shown

**Expected behavior**
titles in sidebar should be visible, at least they were until v112

**Screenshots**
![Schermata del 2023-05-11 12-55-24](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/5927377/5a7c48f0-d9a9-422e-9797-83210dcb15f8)

![Schermata del 2023-05-11 13-11-12](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/5927377/abf104c3-e217-4212-b944-ce52cd5983ce)

**Setup information**
 - OS: ubuntu 23.04
 - Firefox version: 113
 - Theme version: customized by me based on colloid-gtk-theme by vinceliuice based on firefox-gnome-theme 
 - Optional features enabled: 

thank you for your wonderful work!

**Comment by paolocalosso** [comment]
sorry, missed that fix. thanks again!

**Comment by andreacocci95** [comment]
I have the same issue. I update the theme with the one command curled script. I see that it take the last release and not the code on master branch. Can you create a release for that? Thanks.
