### ISSUE TITLE
Wierd new tab icon behaviour when using system icons

### ISSUE THREAD

**Issue by saikat0511** [rafaelmardojai/firefox-gnome-theme#627]
**Describe the bug**
When the tab bar overflows the new tab icon changes and grows in size. This only happens when new tab button is placed inside the tab bar. It seems initially the system icon is not being used, and when it loads the icon after overflow its of wrong size. 

I have enabled system icons and using papirus icon theme.

**Screenshots**
![Screencast from 2023-05-13 02-55-49](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/57610828/60616063-ddb8-4ae5-aefc-1a1d91c8b856)

**Comment by CleoMenezesJr** [comment]
Did you make any tweaks to the CSS? Colors don't seem to be FGM's default. Btw, I can't reproduce the issue on Firefox 113.

**Comment by saikat0511** [comment]
No tweaks, just installed FGM with curl script and enabled bookmarks under tabs and systems icons.

**Comment by rafaelmardojai** [comment]
Duplicated of  #622.
