### ISSUE TITLE
Gap in left corner on `gnomeTheme.tabsAsHeaderbar`

### ISSUE THREAD

**Issue by ai** [rafaelmardojai/firefox-gnome-theme#628]
**Describe the bug**

When I enable `gnomeTheme.tabsAsHeaderbar` on Fedora (with close button on the right side) tabs has a small gap on the left side.

**To Reproduce**
1. Install extensions
2. Enable `tabsAsHeaderbar`
3. Restart

**Expected behavior**

No gap

**Screenshots**

![Captura desde 2023-05-13 06-01-55](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/19343/699c051d-c30c-4698-8860-3c5f3a756f3b)

**Setup information**
 - OS: Fedora 38
 - Installation method: RPM
 - Firefox version: 113
 - Theme version: `master` b940693
 - Optional features enabled:

![Captura desde 2023-05-13 06-07-48](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/19343/c054bfb7-9262-453d-8447-8d14ff4d396c)

**Comment by hmpfkafka** [comment]
try setting browser.tabs.firefox-view to false

**Comment by ai** [comment]
@hmpfkafka nope, that’s didn’t help

**Comment by rafaelmardojai** [comment]
Padding is intentional to have draggable area. Code here: https://github.com/rafaelmardojai/firefox-gnome-theme/blob/master/theme/parts/tabsbar.css#L557

**Comment by ai** [comment]
Thanks! I fixed it by adding to `chrome/userChrome.css`

```css
@supports -moz-bool-pref("gnomeTheme.tabsAsHeaderbar") {
  :root[tabsintitlebar] #TabsToolbar .toolbar-items {
    padding: 0;
  }
}
```

I don’t need draggable area since Firefox UI has plenty small areas to drag (but it may not be obvious for other users).

**Comment by rafaelmardojai** [comment]
Nice.

Closing since no further changes were requested.
