### ISSUE TITLE
Tabs are forced above the address bar

### ISSUE THREAD

**Issue by 7system7** [rafaelmardojai/firefox-gnome-theme#631]
**Describe the bug**
I have a problem w/ the tabs. They are forced to be above the addressbar in only one machine. 
I tried these:
 - change the `browser.tabs.drawInTitlebar` to **false**
 - change the `gnomeTheme.tabsAsHeaderbar` to **false**
 - remove the `~/.mozilla` dir and create a clean install
 - try the auto-install script, the AUR way and the manual way
 
My theme settings files currently:
```bash
chrome
├── firefox-gnome-theme -> /usr/lib/firefox-gnome-theme
├── userChrome.css
└── userContent.css
user.js -> chrome/firefox-gnome-theme/configuration/user.js
```

**Maybe it is not a bug, but I do not know what I have missed. Help me pls!**

**To Reproduce**
Install this theme any way.

**Expected behavior**
The tabs are below the addressbar by-default.

**Screenshots**
![Screenshot from 2023-05-14 10-48-42](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/3964568/eb7d2e82-784e-4758-ab6c-6b7da04d94ed)

**Setup information**
 - OS: [I use Arch btw](https://img.ifunny.co/images/52d8243147037d8ca6f3e420a9c79c793eb4e2b42a553912f9bf555d8b35d9ef_1.jpg)
 - Installation method: Manual, auto-scripts and AUR
 - Firefox version: 112.0.2-2
 - Theme version: 113.r0.gb940693-1
 - Optional features enabled: -

**Additional context**
-

**Comment by rafaelmardojai** [comment]
You shouldn't be using the v113 of the theme with Firefox 112. Update your Firefox or try using downloading the v112 git tag of the theme.

**Comment by 7system7** [comment]
Omg! Yes, I had an upgrade, after that, it worked! Thank you! :partying_face:
