### ISSUE TITLE
Ellipsis on context menus?

### ISSUE THREAD

**Issue by alosarjos** [rafaelmardojai/firefox-gnome-theme#632]
**Describe the bug**
I think this ellipsis thing is news, and used to show the whole text

**To Reproduce**
In Spanish (In my case), right click on a tab and some elements from the context menu will show the ellipsis

**Expected behavior**
Show the full text

**Screenshots**
![imagen](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/29999427/30d53802-dd3f-4352-be39-8f23027876b5)

**Setup information**
 - OS: Arch Linux
 - Installation method: Pacman
 - Firefox version: 113.0.1
 - Theme version: d9c7f13

**Comment by rafaelmardojai** [comment]
Probably a Firefox 113 thing. Could you confirm if is happening without the theme?

**Comment by alosarjos** [comment]
The ellipsis seems to be put by upstream, but the theme is making it show more

![Captura desde 2023-05-18 08-33-27](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/29999427/1495b44a-39f7-4657-a718-25ef464414df)


![Captura desde 2023-05-18 08-33-59](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/29999427/13eb0f5c-7b23-4141-a965-0a0c0dd46a10)

**Comment by Ashdemai** [comment]
Can confirm it happens to my context menus as well. You should probably increase the limit maybe?
