### ISSUE TITLE
Highlight entry looks weird with touch density enabled

### ISSUE THREAD

**Issue by Oranko** [rafaelmardojai/firefox-gnome-theme#633]
**Describe the bug**
Entry Highlight in touch density looks weird because of different colors with different heights

**To Reproduce**

1. Customize Toolbar
2. Select density to touch mode
3. Click on urlbar
4. Hover over any entry or start typing a fresh entry in the search bar
5. Look at the grey highlight or the blue highlight

**Expected behavior**
The highlight should consistent

**Screenshots**
![Screenshot from 2023-05-17 00-20-30](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/65071540/5d9ba024-6132-4b55-8a60-82d753410ac1)
![Screenshot from 2023-05-17 00-20-40](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/65071540/4a52015c-3bda-49ba-9d0b-ba3f57f6720f)

**Setup information**
 - OS: 
 - Installation method: 
 - Firefox version: 
 - Theme version: 
 - Optional features enabled:

**Comment by rafaelmardojai** [comment]
I never test against touch density so in practice is unsupported, any reason to use it?

**Comment by Oranko** [comment]
Ah yes, touch density makes everything a bit spaced out so the overall look become a bit more cleaner, and just in general looks very good

**Comment by rafaelmardojai** [comment]
This seems to be fixed by 2139a1abf834468498ab08675b4e067583c7717a.
