### ISSUE TITLE
Missing icons in the toolbar

### ISSUE THREAD

**Issue by luiz734** [rafaelmardojai/firefox-gnome-theme#635]
**Describe the bug**
There are missing icons in the toolbar. The buttons are present and functional, but there are no icons.

**To Reproduce**
1. Install the package from AUR with the package version 112.r0.g9b88fd9

**Expected behavior**
All icons should be visible in the toolbar.

**Screenshots**
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/44483575/3dee7566-6011-4b22-af28-b49512d9f8f2)

**Setup information**
 - OS: Arch
 - Installation method: AUR
 - Firefox version: 113.0.1
 - Theme version: master
 - Optional features enabled: gnomeTheme.closeOnlySelectedTabs, hideSingleTab, hideWebrtcIndicator, gnomeTheme.systemIcons
 
 **Additional context**
Three icons are missing: Open new tab, Reload page and Go forward (numbered 1, 2, and 3, respectively). I noticed this issue after the latest update.

**Comment by rafaelmardojai** [comment]
Do you have `svg.context-properties.content.enabled` se to true?

**Comment by The-L3mur** [comment]
The issue seems to be caused by commit e3eef6ee3144593525ab63b4255e26b40f504e6a. Reverting the change it made fixes the issue for me.

**Comment by luiz734** [comment]
> The issue seems to be caused by commit [e3eef6e](https://github.com/rafaelmardojai/firefox-gnome-theme/commit/e3eef6ee3144593525ab63b4255e26b40f504e6a). Reverting the change it made fixes the issue for me.

I can confirm that reverting to commit ed0272a275927a903c52bb21d3765b29866a1e53 fixed the issue.
