### ISSUE TITLE
Device name gets truncated in "Send Link to Device" menu

### ISSUE THREAD

**Issue by unomi-zan** [rafaelmardojai/firefox-gnome-theme#636]
**Describe the bug**

Just as the description says

**To Reproduce**

1. Right click on any link or tab
2. Select "Send Link to Device"
3. The device name gets truncated no matter how short the name is

**Expected behavior**

The device name should not get cut off

**Screenshots**

### Firefox Gnome Theme

![Screenshot from 2023-05-26 19-02-53](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/79187956/eab3fd30-0fa1-401f-8497-c212becdca96)

### Vanilla Firefox

![Vanilla Firefox](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/79187956/ba7bb73d-948c-4b63-86ee-d435c17b09f8)

**Setup information**
 - Firefox version: 113.0.1
 - Theme version: master

**Comment by rafaelmardojai** [comment]
I can't reproduce, things like this should have been fixed by 91982b5e777a47def02aa34b423c3511803ebc43. You sure that you are running that commit?

**Comment by unomi-zan** [comment]
It seems I wasn't using master. I thought the one liner curl script would automatically install the master branch.
Installed again by cloning the repo and everything is fine now.
