### ISSUE TITLE
Search results are left-aligned

### ISSUE THREAD

**Issue by lionirdeadman** [rafaelmardojai/firefox-gnome-theme#64]
On 70.0a1 (2019-08-02) (64-bit) which is available as flatpak has search results left-aligned. Unsure why but it's a thing.

**Comment by rafaelmardojai** [comment]
Yeah, Firefox reworked the urlbar results.
I already fixed this, but I'm looking a way this fix doesn't break FF68.

**Comment by lionirdeadman** [comment]
Can you give something I can pop into userChrome.css while you figure it out? It's been nagging me since :p

**Comment by rafaelmardojai** [comment]
Fixed. But there's a small bug with `--item-padding-start` that makes `#urlbar-results` smaller sometimes.
