### ISSUE TITLE
`gnomeTheme.tabsAsHeaderbar` doesn't work (FF Nightly 115.0a1 2023-06-04 build)

### ISSUE THREAD

**Issue by qwertychouskie** [rafaelmardojai/firefox-gnome-theme#640]
I just updated my copy of this theme in hopes that it would fix the missing minimize/maximize/close buttons.  Although it did, it also broke `gnomeTheme.tabsAsHeaderbar`.

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/13989090/8a3d308e-3f16-44de-a763-d9cb357e7cb2)

**Comment by Wiget454** [comment]
Does not work in stable 115.0
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/122064539/1bf9b763-8f1d-40b4-af5c-ce2eb26e2f18)

**Comment by rafaelmardojai** [comment]
It was caused when was `gnomeTheme.bookmarksToolbarUnderTabs` enabled. Please next time use the bug template and provide the features you have enabled. That way bug fixing is easier.
