### ISSUE TITLE
[Feature] Add options to hide border between tabs and URL bar

### ISSUE THREAD

**Issue by ai** [rafaelmardojai/firefox-gnome-theme#641]
**Is your feature request related to a problem? Please describe.**

I think we spend too much vertical space between tabs and URL bar. For instance by removing border and second gap we can make everything cleaner.

![Captura desde 2023-06-09 19-09-04](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/19343/519901a6-8ad1-4041-9759-05318c8e7713)

**Describe the solution you'd like**

I understand that we are copying other GNOME app design, so it is OK to have an option or maybe a snippet for CSS file.

**Comment by ai** [comment]
There is a border-less UI mockup in GNOME, so it is official

https://gitlab.gnome.org/Teams/Design/os-mockups/-/blob/master/tabs/tabs-borderless.png

![tabs-borderless](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/19343/767a6768-3aca-4384-84e0-ebb86f5af547)

Also, it was mentioned [in GNOME blog](https://blogs.gnome.org/alexm/2023/06/15/rethinking-adaptivity/)

![toolbar-view](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/19343/7a79126d-bfef-4993-8312-0157ca4cb72c)

**Comment by ai** [comment]
And Epiphany was moved to the same border-less tabs

![88ecac160231bf07a115a9240c4d9738bb92956e](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/19343/7a1fac39-a05e-4d58-bb91-a21c13731c16)

**Comment by rafaelmardojai** [comment]
Yeah. This issue possibly should be closed in favor of #599.
