### ISSUE TITLE
Readme should also say to remove user.js when uninstalling

### ISSUE THREAD

**Issue by IvoryJam** [rafaelmardojai/firefox-gnome-theme#643]
**Describe the bug**
After following the uninstall steps, just removing the "chrome" folder, some settings cannot be set in Firefox afterwards. Notably the density. 

**To Reproduce**
1. Install firefox-gnome-theme
2. Uninstall firefox-gnome-theme by removing chrome folder from the readme
3. Set the density
4. restart Firefox

**Expected behavior**
Readme should mention to removing user.js (or editing) along with removing chrome folder

**Setup information**
 - OS: Fedora
 - Installation method: Flatpak
 - Firefox version:114.0.2 
 - Theme version: Master
 - Optional features enabled: gnomeTheme.hideSingleTab 

**Additional context**

**Comment by rafaelmardojai** [comment]
True, initially `user.js` was just a symlink to the one inside the chrome folder. But recently we updated the script to just insert the preferences to the file, so it can work nicely with user previous values.

We need to reflect than change on the README.
