### ISSUE TITLE
Dark theme even with light adw-gtk3

### ISSUE THREAD

**Issue by saculo** [rafaelmardojai/firefox-gnome-theme#645]
**Describe the bug**
I have installed theme for firefox browser, but it is defaulted to the dark one. I have used curl script to do that. But my theme config is configured to get light theme.
**Screenshots**
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/37440952/f5d5f803-a6cf-40c5-a95c-e59b3524735d)

**Setup information**
 - OS: Fedora 38
 - Installation method: CURL script
 - Firefox version: 114.0.2

**Comment by rafaelmardojai** [comment]
Have you checked if you have the dark theme enabled in Firefox? `Menu > Addons and themes -> Themes`

**Comment by saculo** [comment]
Well, I was totally blind that I have missed some "custom" theme being enabled, thanks you... I would probably check that one hundred times and I would miss it again.
