### ISSUE TITLE
Unnecessary separation line in the website permission area

### ISSUE THREAD

**Issue by erlefloch** [rafaelmardojai/firefox-gnome-theme#654]
**Describe the bug**

A line at the bottom of the permissions lists for websites.

**To Reproduce**

Use Firefox 116 with the v116 theme.
1. Go to a website with granted permissions (notifications, camera...)
2. Click on the permissions icon
4. See a line at the bottom of the list of granted permissions

**Expected behavior**

~This line seems new in Firefox 116, and~ It would look nicer without it.

**Screenshots**

![new line in 116, regression](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/90708860/3ff962bb-1c15-4e82-b511-4be1420ffc41)

**Setup information**
 - OS: Fedora
 - Installation method: Flatpak from Flathub
 - Firefox version: 116
 - Theme version: 116
 - Optional features enabled: hideWebrtcIndicator, normalWidthTabs, tabsAsHeaderbar

**Comment by rafaelmardojai** [comment]
That has been there for a long time to my knowledge, and if I remember correctly, is unfixable because Firefox as a weird UI structure there, of course it could be fixed by removing the "list" style used there.

Will try to revisit this to see if can be fixed.

**Comment by erlefloch** [comment]
oh ok! I only realized it recently. 
Thanks !
