### ISSUE TITLE
Incorrect bookmarks bar layout

### ISSUE THREAD

**Issue by Koitharu** [rafaelmardojai/firefox-gnome-theme#655]
**Describe the bug**
At latest versions of firefox-developer-edition bookmarks bar looks ugly

**To Reproduce**
Enable bookmarks bar

**Expected behavior**
None

**Screenshots**
![изображение](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/8948226/94674c8c-1c0f-4de9-ad98-10aec134a117)

**Setup information**
 - OS: Arch
 - Installation method: [firefox-gnome-theme-git](https://aur.archlinux.org/packages/firefox-gnome-theme-git) from AUR
 - Firefox version: firefox-developer-edition 117
 - Theme version: latest at issue creation date
 - Optional features enabled: hideSingleTab, bookmarksToolbarUnderTabs

**Additional context**
None

**Comment by Kneemund** [comment]
This bug only occurs when setting the bookmarks tab to only show on new tab pages. If you set it to be always visible, it is sized correctly.

**Comment by rafaelmardojai** [comment]
Fixed on master.
