### ISSUE TITLE
Incorrect icon for starred/bookmarked pages

### ISSUE THREAD

**Issue by lheinke** [rafaelmardojai/firefox-gnome-theme#656]
The currently used symbol for a bookmarked page appears as a yellow star. This does not match the filled star icon that is used in for example Nautilus/Gnome Files. The empty star symbol, however, matches the normal Gnome symbol. 

![Screenshot from 2023-08-17 19-03-33](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/39367795/415e7986-410b-4665-a2c3-1a034f70a460)
![Screenshot from 2023-08-17 19-03-44](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/39367795/c90c92e9-1452-4e9c-a7d2-14f98c85d002)

**Setup information**
 - OS: Fedora
 - Installation method: RPM
 - Firefox version: 116.0
 - Theme version: v116

**Comment by rafaelmardojai** [comment]
The yellow star comes from GNOME Web:

![Captura desde 2023-08-17 14-39-31](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/a3923718-3068-43a8-b315-c75119a891f1)

Although I have noticed that we're using an outdated icon, the new one is more rounded.

**Comment by lheinke** [comment]
I guess then it comes down to a matter of preference. The yellow icon is easier to see and if the goal is to be as consistent as possible with Gnome Web, rather than other Gnome Core applications, this certainly makes sense. 

Personally, I have to say that I find the yellow color very distracting. It is much more visible than the indication that a page is bookmarked needs to be.
