### ISSUE TITLE
Checkboxes are broken on some websites

### ISSUE THREAD

**Issue by rijenkii** [rafaelmardojai/firefox-gnome-theme#657]
**Describe the bug**

This theme seems to break checkboxes in Figma, see screenshots.

**To Reproduce**

1. Open a Figma file
2. Press "F" and click on the canvas (Add a "frame").
3. Look in the right sidebar.

**Expected behavior**
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/5338332/8f0ac061-e9a0-4058-a9d0-907dca8986f0)

**Screenshots**

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/5338332/af45fc17-d57e-42ab-a764-9c44335db4e5)
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/5338332/e7637f6c-a0a0-4c6b-8f32-3db7ea48c0c3)

**Setup information**
 - OS: Artix Linux
 - Installation method: By hand
 - Firefox version: 116.0.3
 - Theme version: v116
 - Optional features enabled: None

**Comment by rijenkii** [comment]
Checkboxes are also broken in Kimai.

**To reproduce**
1. Open https://demo.kimai.org/en_US/profile/admin/prefs
2. Log in with credentials `admin` / `password`.
3. Scroll down

**Expected behavior**
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/5338332/32b79edf-52f3-4f7d-ac31-f89d2f7b1484)

**Screenshots**
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/5338332/7e5c9c9f-425e-44b5-8e39-cded232ecb1d)

**Comment by rijenkii** [comment]
Also, **all** bootstrap checkboxes are broken:
 https://getbootstrap.com/docs/5.3/forms/checks-radios/

**Comment by rijenkii** [comment]
Commenting out this block fixed checkboxes on websites and in devtools:
https://github.com/rafaelmardojai/firefox-gnome-theme/blob/08884fb6be1c74a81f5e0a35a81c3f219e109028/theme/parts/controls.css#L7-L30

**Comment by rafaelmardojai** [comment]
Hmm, this is weird, this CSS shouldn’t affect the webview.

The bootstrap  checkboxes look fine to me btw.

**Comment by rafaelmardojai** [comment]
Also devtools are unaffected for me.

**Comment by rafaelmardojai** [comment]
Anyway, I can't reproduce the issue, but the offender must be `input[type="checkbox"]` and Firefox seems to only be using the `checkbox` element on its UI so we can remove that selector safely.

 (The `input[type="checkbox"]` selector came from my Thudnerbird theme from were I initially implemented checkboxes theming)

**Comment by rijenkii** [comment]
> Hmm, this is weird, this CSS shouldn’t affect the webview.
>
> The bootstrap checkboxes look fine to me btw.

Agree, really weird. Not sure what's wrong with my browser then -- disabling extensions did nothing.

> Also devtools are unaffected for me.

For the history, my devtools look like this when checkboxes are uncommented.
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/5338332/0895373d-cffc-4b12-ab0e-9594f754ba6a)

**Comment by rijenkii** [comment]
Oh, I found out what was wrong.

I imported `userChrome.css` in `userContent.css`:
```
rijenkii@RijenkiiBook ~/.m/f/9/chrome> cat userContent.css 
@import "firefox-gnome-theme/userChrome.css";
```

**Comment by rijenkii** [comment]
Closing then, sorry for bothering!
