### ISSUE TITLE
Double Seperator Lines in Firefox 116

### ISSUE THREAD

**Issue by MaxBrandtner** [rafaelmardojai/firefox-gnome-theme#658]
**Describe the bug**
Double lines, where there should only be one(see image)

**To Reproduce**
right click in the web content section.

**Expected behavior**
One Line

**Screenshots**
![Screenshot from 2023-08-25 09-10-43](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/110912574/b73df20f-469f-4af9-9ce4-1be39688d05a)

**Setup information**
 - OS: Arch
 - Installation method: Flatpak
 - Firefox version: 116
 - Theme version: v116
 - Optional features enabled:

**Comment by rafaelmardojai** [comment]
Duplicated of #646. Sure you're using the latest version?

**Comment by KUPOinyourWINDOW** [comment]
yeah I can confirm this issue is fixed in the newest version of this theme

**Comment by MaxBrandtner** [comment]
Just looked in the chrome directory and when rerunning the auto-install script it apparently created a new directory firefox-gnome-theme-116 instead of replacing firefox-gnome-theme
