### ISSUE TITLE
Bookmarks bar is clipping on new tabs

### ISSUE THREAD

**Issue by Beryesa** [rafaelmardojai/firefox-gnome-theme#660]
**Describe the bug**
Bookmarks bar is clipping on v117 when selecting only show in new tabs

**To Reproduce**

1. Right click on bookmarks
2. Select only show in new tabs
3. Open a new tab
4. It clips

**Expected behavior**
It doesn't clip

**Screenshots**
Shown always
![resim](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/60751519/f13deba0-681b-4871-9748-3c85d9af3b20)

Shown on new tabs only
![resim](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/60751519/c485f0c1-3606-41d0-b080-a881c0af9880)

**Setup information**
 - OS: Fedora
 - Installation method: Flatpak
 - Firefox version: 117
 - Theme version: master

 - Optional features enabled:
    -  gnomeTheme.tabsAsHeaderbar 
    -  !gnomeTheme.normalWidthTabs 
    -  gnomeTheme.hideWebrtcIndicator

**Additional context**
No need of gnomeTheme.hideWebrtcIndicator any more with 117

**Comment by Titaniumtown** [comment]
I can reproduce this issue with Firefox 117 as well.

**Comment by Titaniumtown** [comment]
@rafaelmardojai this is not a beta/nightly, Firefox 117 has been released.

**Comment by rafaelmardojai** [comment]
@Titaniumtown Oh, looks like I'm out of the news. I will fix it as soon as the update arrives to me then.
