### ISSUE TITLE
New tab icon displays with incorrect transparency when window is unfocused

### ISSUE THREAD

**Issue by adueppen** [rafaelmardojai/firefox-gnome-theme#668]
**Describe the bug**
The icons for UI elements are displayed with reduced opacity when the window is unfocused, but this results in the 2 individual rectangles making up the plus in the new tab icon becoming visible with increased opacity where they overlap.

**To Reproduce**
1. Ensure the new tab button is visible.
2. Defocus the window

**Expected behavior**
The icon's opacity should be affected uniformly, being applied to the group and not the individual elements.

**Screenshots**
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6982070/ebfa1fba-557f-42a7-ad69-92619307295b)

**Setup information**
 - OS: Fedora 38
 - Installation method: RPM
 - Firefox version: 117
 - Theme version: master

**Comment by rafaelmardojai** [comment]
Good catch! Thanks for reporting.
