### ISSUE TITLE
Hardcode checkbox gnome-icon

### ISSUE THREAD

**Issue by ubluish** [rafaelmardojai/firefox-gnome-theme#67]
Hi Rafael,
I don't know if that is possible but can we hardcode checkbox icon because it looks blured and have a black border ?
![Untitled](https://user-images.githubusercontent.com/21042432/62825046-ca53d380-bba5-11e9-891f-44b24b0d9fb7.png)

**Comment by rafaelmardojai** [comment]
You mean like this?
![Captura de pantalla de 2019-08-10 20-03-38](https://user-images.githubusercontent.com/6210397/62828362-1f91e400-bbaa-11e9-83b4-31c1902035e6.png)

**Comment by ubluish** [comment]
> You mean like this?
> ![Captura de pantalla de 2019-08-10 20-03-38](https://user-images.githubusercontent.com/6210397/62828362-1f91e400-bbaa-11e9-83b4-31c1902035e6.png)

Yes, i think it looks way better this way. What do you think?
