### ISSUE TITLE
Incorrect width for Enhanced Tracking Protection button

### ISSUE THREAD

**Issue by handokota** [rafaelmardojai/firefox-gnome-theme#671]
**Describe the bug**

Incorrect width for Enhanced Tracking Protection button.

**To Reproduce**

1. Click on the protections icon.
2. See error.

**Expected behavior**

The button should use 100% width.

**Screenshots**

![Screenshot from 2023-09-26 17-35-51](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/64225391/d7259bec-7534-4a25-a495-aebf56b2ae88)

**Setup information**
 - OS: Arch Linux
 - Installation method: AUR
 - Firefox version: 118
 - Theme version: 117
 - Optional features enabled: `gnomeTheme.hideSingleTab`

**Comment by Titaniumtown** [comment]
@rafaelmardojai this is not a nightly/beta, this is an official release.

**Comment by rafaelmardojai** [comment]
Oh, so Firefox 118 is out and I'm not aware? 😅

**Comment by Titaniumtown** [comment]
Yes, it's on flathub and it was released a few days ago.
