### ISSUE TITLE
Black bar between tabs and address bar

### ISSUE THREAD

**Issue by OldWorldOrdr** [rafaelmardojai/firefox-gnome-theme#674]
**Describe the bug**
There is a small black bar between the tab bar and address bar

**To Reproduce**
1: open firefox, if hideSingleTab is on you will need to open another tab to show the tab bar

**Expected behavior**
no black bar, like it is in epiphany

**Screenshots**
![Screenshot from 2023-09-28 13-31-55](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/57970114/d94b3eac-fdac-4097-b8f2-d779e462493c)

**Setup information**
 - OS: Fedora 38 fully up to date
 - Installation method: Fedora repos
 - Firefox version: 117
 - Theme version: 5f531cf8aacfedd42ad43b4d891284ae326c6989
 - Optional features enabled: hideSingleTab, systemIcons, bookmarksToolbarUnderTabs

**Comment by OldWorldOrdr** [comment]
Just updated to 118 while writing this issue and its also a problem there

**Comment by rafaelmardojai** [comment]
This theme currently follows libadwaita 1.3 (GNOME 44) and that is how it looks. So this might be a duplicated of #599.

**Comment by rafaelmardojai** [comment]
You can check  #662 for progress.
