### ISSUE TITLE
Center - aligned URL on the title bar

### ISSUE THREAD

**Issue by svta-7125** [rafaelmardojai/firefox-gnome-theme#675]
Is it possible to add an option to centre align the URL on the URL bar like in Safari?

**Comment by Bhanuteja005** [comment]
Not sure it's exactly what you want, but Cmd & L will select & left align, same as if you'd clicked it - so you could do it as you're mousing towards it.

**Comment by rafaelmardojai** [comment]
I'm not planning to add that to the theme, but you can always add you custom styles along the theme.

Something like this should work:
```css
#urlbar-input {
    text-align: center !important;
}
```
