### ISSUE TITLE
[Feature] Accent colour

### ISSUE THREAD

**Issue by XanderLeaDaren** [rafaelmardojai/firefox-gnome-theme#676]
**Is your feature request related to a problem? Please describe.**
The accent colour is blue, even when the OS preferences are set to another colour, thus having Firefox behave differently from other applications.

**Describe the solution you'd like**
Find a way to get the OS’ accent colour, or either let the user choose it by editing a file.

**Additional context**
Blue accent colour is visible on selected menu list items, for checkboxes, radio buttons, line around fields, …

**Comment by rafaelmardojai** [comment]
The theme provides the `--gnome-accent-bg` and `--gnome-accent` CSS variables, you can change those variables in the sheets from `/firefox-gnome-theme/theme/colors`. 

Alternatively you can create the file `/firefox-gnome-theme/customChrome.css` that will survive updates and is automatically imported by the theme, there you can override the CSS variables:

```css
:root {
    --gnome-accent-bg: your-color !important;
    --gnome-accent: your-color !important;
}
```

When there is a standard way to define the accent colors on Linux desktops (there's already a xdp portal setting in the works) Firefox will probably support it and this theme use it. In the meantime there's no way to automatically get the custom accent colors implementation that any Linux desktop can have.
