### ISSUE TITLE
[Feature] Fullscreen Toolbar Overlap

### ISSUE THREAD

**Issue by jusqua** [rafaelmardojai/firefox-gnome-theme#677]
**Is your feature request related to a problem? Please describe.**
I have a laptop with a small screen size and I usually use the browser in fullscreen mode.
When the pointer moves in/out of navbar, its changes the viewport, forcing the current page to render again, and some webapps leaves a blank space at the bottom.

**Describe the solution you'd like**
The theme navbar should have the same behavior as epiphany it can be the default behavior or a separated feature like `gnomeTheme.fullscreenNavbarOverlap`.

**Describe alternatives you've considered**
I considered using [this](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_toolbox.css) "css hack" from `firefox-csshack` repo, but tinkered only for fullscreen mode.

**Additional context**
These are just a few screencasts to show how Epiphany and Firefox, respectively, behave.

[Epiphany fullscreen navbar overlap](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/62023311/c96edc6a-bd6d-48b4-a81b-a5263592cefe)

[Firefox fullscreen navbar pushdown content](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/62023311/9c7bb83e-0bd2-480f-a3b6-5a377992eb3e)

**Comment by CleoMenezesJr** [comment]
Not that hard to archive it. I've been trying to do something similar for a few minutes and the only problem I've found is that the tabbar didn't handle the hover behavior well.

[Screencast from 2023-12-09 01-21-35.webm](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/54215258/181dc5bf-1b9a-4cb9-a9ae-cc69f7a07196)
