### ISSUE TITLE
Search engine icons do not highlight with arrow keys

### ISSUE THREAD

**Issue by cewbdex** [rafaelmardojai/firefox-gnome-theme#682]
**Describe the bug**

When I type a query to address bar and want to use other search engine, I use arrows to navigate in the list. Text fields work fine, but the small icons a the bottom are not highlighted, as they would with mouse.

**To Reproduce**

1. Type something to search bar
2. Navigate up or down with arrow keys to the small icons

**Expected behavior**

Search engines get highlighted
**Screenshots**

![Snímek obrazovky z 2023-10-12 08-59-00](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/9021297/aefa320a-7ebd-4c62-be8e-20a551546f90)

**Setup information**
 - OS: Fedora
 - Installation method: Flatpak
 - Firefox version: 118
 - Theme version: master
 - Optional features enabled: 

**Additional context**

**Comment by renankogan** [comment]
#407 could fix this, but it has conflicts (since it does more than just fixing this bug)
 I manually modified my files here (only the modifications necessary to fix this bug), and it seems to fix
