### ISSUE TITLE
Firefox Beta 120.0b1 Has Broken Normal Width Tabs

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#685]
The about:config tweak (gnomeTheme.normalWidthTabs) to have tabs that don't extend the entire tab bar has broken and simply does not work anymore in the newest beta of Firefox (version 120)

**Comment by rafaelmardojai** [comment]
Done, can you test if works fine in the `beta` branch?

**Comment by KUPOinyourWINDOW** [comment]
Cam confirm it is fixed with beta branch now! ^-^

**Comment by pakosaan** [comment]
yes all tabs are moved to the left side with no space betweena and shows the  icon only.
