### ISSUE TITLE
hideSingleTab broken in Firefox v120

### ISSUE THREAD

**Issue by lj3954** [rafaelmardojai/firefox-gnome-theme#694]
**Describe the bug**
gnomeTheme.hideSingleTab does not have any effect in Firefox v120.0

**To Reproduce**

1. Set gnomeTheme.hideSingleTab to true
2. Open a window with 1 tab

**Expected behavior**
Tab list is hidden while a single tab is opened

**Screenshots**
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/33645555/a3afffca-4340-4a75-92c2-852cf1d41457)

**Setup information**
 - OS: Fedora 40 (Rawhide)
 - Installation method: RPM
 - Firefox version: 120.0
 - Theme version: master (1c32013)
 - Optional features enabled: gnomeTheme.hideSingleTab

**Additional context**
Firefox 120 Stable is not yet released, but this issue will likely persist.

**Comment by theodormoroianu** [comment]
I have the same issue (fedora 40, firefox 120), but in addition to `hideSingleTab` I found that `gnomeTheme.normalWidthTabs` and `gnomeTheme.bookmarksToolbarUnderTabs` do not work either. 

Deleting all install files and re-installing does not fix the issue.

**Comment by monwarez** [comment]
It is fixed in the beta branch for me: cd408d8e4de8bd514387366dda4fe0def6e43c16

**Comment by theodormoroianu** [comment]
> It is fixed in the beta branch for me: [cd408d8](https://github.com/rafaelmardojai/firefox-gnome-theme/commit/cd408d8e4de8bd514387366dda4fe0def6e43c16)

I can confirm this also fixes the issue for me.

**Comment by rafaelmardojai** [comment]
Yes, this is fixed in the beta branch. 

If you're using beta/nightly is always recommendable to use the corresponding branch of the theme.
