### ISSUE TITLE
Hide single tab not working on Firefox 120.0

### ISSUE THREAD

**Issue by ferlanero** [rafaelmardojai/firefox-gnome-theme#695]
**Describe the bug**
Hide single tab not working on Firefox 120.0

**To Reproduce**

1. Open Firefox 120.0
2. You'll see the tab even when only one is active

**Expected behavior**
When a single tab is used, it should not be shown

**Screenshots**
![Captura desde 2023-11-18 09-31-55](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/1192395/5ffb6858-30ad-43eb-840d-14c3e5783cd4)

**Setup information**
 - OS: Ubuntu 22.04.3
 - Installation method: DEB, [Official Mozilla launchpad repositoire](https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu/)
 - Firefox version: 120.0
 - Theme version: v119, master
 - Optional features enabled: gnomeTheme.hideSingleTab

**Additional context**
-

**Comment by rafaelmardojai** [comment]
Duplicated of #694, this is fixed in the beta branch.
