### ISSUE TITLE
missing gap in between tab bar and favourites bar

### ISSUE THREAD

**Issue by nanopone** [rafaelmardojai/firefox-gnome-theme#700]
**Describe the bug**
the margin between the tab and the favourites bar is non-existent. this looks fine normally, but if the colour of the favourites bar or tab bar is changed, it's very jarring. this is notably changed by gradience, which *technically* makes this a gradience problem, however almost literally any change to the colour scheme via gradience would show this problem. i, myself, am using the stock adwaita dark theme provided by gradience with only the accent colour changed, and this issue affects me. even though it is not noticeable by people using the stock theme, it is still there and in my opinion is still a problem.

**To Reproduce**

1. install the theme
2. using customChrome.css, change the colour of the favourites/tab bar. you can also use gradience
3. observe

**Expected behavior**
the gaps around the tabs should be uniform

**Screenshots**
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/49787675/123a24d2-372a-43bb-83c3-04e6770a0e77)

**Setup information**
 - OS: fedora workstation 39
 - Installation method: flatpak
 - Firefox version: 120.0
 - Theme version: v120
 - Optional features enabled: gnomeTheme.hideSingleTab, gnomeTheme.hideWebrtcIndicator

**Comment by nanopone** [comment]
update:
turns out this is *kind of* noticeable without any customChrome. take specific note of the separators for the favourites and the tabs. the gap between the favourites separator and the address bar is different than the gap between the tab separator and the favourites separator:
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/49787675/f35ec679-cb69-4f6d-992d-9f9de427399a)

**Comment by rafaelmardojai** [comment]
True, the bookmarks bar should have no top padding.

**Comment by nanopone** [comment]
> True, the bookmarks bar should have no top padding.

what? no. i'm saying there's no padding on the top of the tab bar where there should be. i'm not saying to remove the padding on the top of the bookmarks bar, that would just introduce yet another visual problem.

**Comment by rafaelmardojai** [comment]
> what? no. i'm saying there's no padding on the top of the tab bar where there should be. i'm not saying to remove the padding on the top of the bookmarks bar, that would just introduce yet another visual problem.

Well, with the GNOME 45 style you're supposed to have a single color background in the whole top toolbars without divisions.

For example here you have the theme and GNOME Web bellow:
![Captura desde 2023-11-21 17-37-47](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/f9bd7c2a-a5d2-4957-b757-98a931192192)

![Captura desde 2023-11-21 17-38-04](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/5a5a3c6f-1c5a-4514-ae42-4ec286d0b03f)

**Comment by rafaelmardojai** [comment]
If the problem is that when you apply different background colors, you see the non-existent top padding of toolbars below the header bar, that's not supported. They don't have top padding to have the correct spacing like other GNOME applications. So I would suggest adding padding to them in your `customChrome.css` if you want to change the backgrounds.
