### ISSUE TITLE
(Firefox 121 Beta 1) Close Button Bug

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#701]
In the newest beta there's a very minor visual bug with the close button, it doesn't have a circle around it like other gnome apps until you hover the mouse over it.

![Screenshot from 2023-11-21 22-28-07](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/133521592/1944c863-dfe0-4420-94ea-cd7c8d7c91bd)

**Comment by rafaelmardojai** [comment]
Fixed on beta branch.
