### ISSUE TITLE
gnomeTheme.hideSingleTab is not working on FF 120

### ISSUE THREAD

**Issue by nixrunner** [rafaelmardojai/firefox-gnome-theme#703]
`gnomeTheme.hideSingleTab = true` is not working on Firefox 120 on Fedora 39.

**Comment by rafaelmardojai** [comment]
Firefox 120 broke the opt prefs selectors, but this is fixed in the latest version of the theme. Are you sure that you have update it?

**Comment by rafaelmardojai** [comment]
Also, duplicated of #694.

**Comment by nixrunner** [comment]
Oh, now I see it. Thanks.
