### ISSUE TITLE
[Vertical tab - Extension] Add an option to restore the new tab option in Tab Center Reborn

### ISSUE THREAD

**Issue by Froggy232** [rafaelmardojai/firefox-gnome-theme#705]
**Describe the bug**
If I recall correctly, a previous behaviour was to have the new tab button at the bottom of the tab center reborn panel. It was very coherent I think, and would like to know if it was possible to add a user.js entry to restore it on demand.
Also, in the actual default behaviour, there is still the (now empty) space where the new tab button was, I think it should be remove in the default behaviour. 

**To Reproduce**
1 - Install the theme with tab center reborn customization
2 - Apply the tab center reborn entry in user.js
3 - Check the default behaviour

**Expected behavior**
At the very least, there shouldn't be an empty white space at the bottom of the Tab Center Reborn panel.
If possible, add an option in the user.js to restore the new tab option in the bottom of the Tab Center Reborn panel.

**Setup information**
 - OS: Fedora Silverblue 39
 - Installation method: Flatpak
 - Firefox version: 120
 - Theme version: Master
 - Optional features enabled: Just "gnomeTheme.extensions.tabCenterReborn"

Thanks for your incredible work, your theme is really nice!

**Comment by rafaelmardojai** [comment]
CC @BirdInFire

**Comment by pakosaan** [comment]
yeah need a new tab button

**Comment by BirdInFire** [comment]
I will work on this soon, I actually have a big project I do for my work and I don't have time to work at all on something else, I will fix every problem liked to me very soon, sorry for the delay

**Comment by Froggy232** [comment]
Thanks you a lot, take all the time you want of course!

**Comment by BirdInFire** [comment]
have done a PR to fix it in your config right now locate in the custom theme of tab center reborn : 

#newtab {
     display:none;
 }

and replace it with : 

#newtab {
     width: 95%;
 }

**Comment by Froggy232** [comment]
Haha, thanks you a lot, it's absolutely perfect! Thanks you a lot, a thousand of times!
So, if I understand correctly it will be merged in the main branch? I don't need to keep a note of that change for future installation?
Thanks you again, so so much,
Have a happy Christmas!

**Comment by BirdInFire** [comment]
> Haha, thanks you a lot, it's absolutely perfect! Thanks you a lot, a thousand of times!
> 
> So, if I understand correctly it will be merged in the main branch? I don't need to keep a note of that change for future installation?
> 
> Thanks you again, so so much,
> 
> Have a happy Christmas!

Normally yes will be merged

**Comment by Froggy232** [comment]
Nice, thanks you again
