### ISSUE TITLE
[Question] How do i remove the seperator between content and tabbar

### ISSUE THREAD

**Issue by h14turkiye** [rafaelmardojai/firefox-gnome-theme#708]
![Screenshot from 2023-11-25 14-08-37](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/112547995/d0531142-c288-4079-bbdf-f522b51bb7ee)
I want to remove this 1px line, or make it transparent.

**Comment by CleoMenezesJr** [comment]
Just remove the border `border-bottom: none;`

https://github.com/rafaelmardojai/firefox-gnome-theme/blob/d2e6cfdd63651ae8168e5905d94138f406580dd6/theme/parts/toolbox.css#L11-L14
