### ISSUE TITLE
Everything works, except that the icon still using the usual Firefox icon.

### ISSUE THREAD

**Issue by eraiggna** [rafaelmardojai/firefox-gnome-theme#711]
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/107824524/219656a9-a8de-45f9-ac93-7ec36f258735)

Shouldn't be included in the change if I use the curl command? or am I missing something here?

Any pointer would be really appreciated.

**Comment by Titaniumtown** [comment]
What is wrong with the Firefox icon?

**Comment by rafaelmardojai** [comment]
No, we don't theme the Firefox icon and is not really planned. The theme do has an icon (the one in the README) but is just a "project icon", no meant to replace Firefox's.

**Comment by eraiggna** [comment]
> No, we don't theme the Firefox icon and is not really planned. The theme do has an icon (the one in the README) but is just a "project icon", no meant to replace Firefox's.

Oh I see. Thanks for the clarification!
