### ISSUE TITLE
Context Menu Icons Missing

### ISSUE THREAD

**Issue by colossalchicken** [rafaelmardojai/firefox-gnome-theme#712]
**Describe the bug**
The icons in the context menu appear to be missing for Firefox Nightly.

**Screenshots**
![context_menu](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/79541546/14cd3704-1c67-4b47-bb3c-1127cd234e1a)

**Setup information**
 - OS: Arch Linux
 - Installation method: AUR
 - Firefox version: 122
 - Theme version: 120

**Comment by rafaelmardojai** [comment]
Duplicated of #710.  It is already fixed, please use the beta or nightly theme branch.
