### ISSUE TITLE
[BUG] Right clicking on a spelling error is displayed incorrectly

### ISSUE THREAD

**Issue by ascpial** [rafaelmardojai/firefox-gnome-theme#713]
**Describe the bug**
If you right click on a spelling error at the bottom of the screen, the menu is shrunk and unusable.

Please not that while this issue happens reliably for a word, it can works normally on an other word.

**To Reproduce**

1. This has been seen on Discord
2. Type a text with a spelling mistake
3. Right click on it
4. If the menu is displayed correctly, maybe try putting more words and clicking on others.

**Expected behavior**
The menu is big enough to be used.

**Screenshots**

![Broken](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/72463129/eb4adf8e-c59e-462a-8972-c3676e445f8f)

![Working in the same setup](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/72463129/6b234081-70e5-4961-b734-b8366fa37aa5)

**Setup information**
 - OS: Fedora
 - Installation method: RPM
 - Firefox version: 120.0
 - Theme version: master
 - Optional features enabled: No

**Comment by CleoMenezesJr** [comment]
Can't reproduce on Firefox 120.0.1 and FGT Nightly branch.

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/54215258/d1bb77fb-f078-4e11-b7dd-ce3113482ad0)
