### ISSUE TITLE
the font seems smaller than vannilla firefox.

### ISSUE THREAD

**Issue by pakosaan** [rafaelmardojai/firefox-gnome-theme#718]
**Describe the bug**
Font or UI feel somewhat smaller than before

**Setup information**
 - OS: Fedora
 - Installation method: RPM
 - Firefox version: 120
 - Theme version: 120
 - Optional features enabled: default

**Additional context**
I feel the ui or text smaller than before and feels weired and little hard to look at. Any way to maintain like the previous without changing anything manually like changing font size

**Comment by rafaelmardojai** [comment]
I don't think we modify the font sizes in general, so not sure from where could come that difference.

I don't have time right now to roll back to vanilla and compare, will do that later.

**Comment by CleoMenezesJr** [comment]
Can't reproduce either. I'm using Firefox 120.0.1 and FGT Nightly branch by the way.
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/54215258/3dafd954-763d-4815-b669-ccf6d222490f)
Try to take a look on font section on Firefox config and compare if there's the same font size on both profiles.
