### ISSUE TITLE
transparent window

### ISSUE THREAD

**Issue by BatBlazar** [rafaelmardojai/firefox-gnome-theme#719]
**Describe the bug**

only transparent when the window is focused

**To Reproduce**
1. update to v120 using the curl command

**Expected behavior**

**Screenshots**

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/103957544/028f7f34-fda9-47b6-a1c1-380bba3b8598)

**Setup information**
 - OS: Arch
 - Installation method: AUR
 - Firefox version: 120.0.1
 - Theme version: v120
 - Optional features enabled: none

**Additional context**

script install output:
```
Firefox installation folder found
'profiles.ini' found in /home/operator/.mozilla/firefox
Finding all available profiles
Installing DEFAULT theme for njly5fyk.default profile.
Installing theme in /home/operator/.mozilla/firefox/njly5fyk.default
Copying repo in /home/operator/.mozilla/firefox/njly5fyk.default/chrome
No theme set, using default adwaita.
No theme set, using default adwaita.
Set configuration to user.js file
Done.
Installing DEFAULT theme for 51jc7qu0.default-release profile.
Installing theme in /home/operator/.mozilla/firefox/51jc7qu0.default-release
Copying repo in /home/operator/.mozilla/firefox/51jc7qu0.default-release/chrome
No theme set, using default adwaita.
No theme set, using default adwaita.
Set configuration to user.js file
Done.

```

**Comment by rafaelmardojai** [comment]
The bug is that the window is transparent right?

I can't reproduce that in my current Flatpak Firefox over Wayland.

**Comment by BatBlazar** [comment]
correct, my session is x11, i did a fresh install of firefox and i couldn't reproduce it either, closing this.
