### ISSUE TITLE
[wayland] Right-click menu rendering glitch when right-clicking on images & videos

### ISSUE THREAD

**Issue by rien333** [rafaelmardojai/firefox-gnome-theme#720]
**Describe the bug**
The right-click menu renders "oddly" whenever I right-click on an image or video (and perhaps more web elements). Specifically, it appears to not scale well, such that 1) text appears "squished", and 2) the highlighted menu options does not align with where my cursor actually is. Rather, the highlighted menu option is always above where my mouse cursor currently resides.  (**recording attached below**)

I can consistently reproduce this on image and video elements (such as the screen recording I've attached), but I'm pretty sure I've triggered this bugged context menu when clicking on other elements. For example, at the moment, I can trigger it reliably when I right-click on misspelled words!

Thanks for the excellent theme btw!

**To Reproduce**

1. Launch firefox using `MOZ_ENABLE_WAYLAND=1 firefox`
1. Go to [firefox-gnome-theme on github](https://github.com/rafaelmardojai/firefox-gnome-theme)
2. Right-click on the project logo or any other image.

**Expected behavior**
The right-click menu (or context menu, as it's sometimes called) should look and function the same, regardless of what kind of web element I click on. 

**Screenshots**

[Screencast from 2023-12-14 15-30-01.webm](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/10417027/c48cae9e-4fba-4ec0-a5b0-ae2ede3a85d2)

**Setup information**
 - OS: Arch linux
 - DE: Gnome (vanilla, Wayland, little extensions, scaling 2x, experimental scaling not enabled)
 - Installation method: AUR
 -  Firefox version: Mozilla Firefox 120.0.1
 - Theme version: 120-1 (so the aur tells me)
 - Optional features enabled: browser.gnome-search-provider.enabled, gnomeTheme.bookmarksToolbarUnderTabs, gnomeTheme.hideSingleTab, gnomeTheme.hideUnifiedExtensions, gnomeTheme.hideWebrtcIndicator

**Additional context**
1. I'm running firefox in pure wayland mode, if that matters (i.e. I have `  MOZ_ENABLE_WAYLAND=1` set in `~/.config/environment.d/vars.conf`). 

2. I cannot reproduce if I start firefox with `--safe-mode --profile /tmp/firefox-profile/`.  (which should disable the gnome theme)

**Comment by zbikk** [comment]
can't replicate, works fine for me

**Comment by rien333** [comment]
> can't replicate, works fine for me

Bummer! Are you running firefox in wayland mode as well? I just launched firefox using `MOZ_ENABLE_WAYLAND=0 firefox`, and in that case, I also **cannot** reproduce.  So, the problem seems to be related to `MOZ_ENABLE_WAYLAND=1`. 

I've updated the title of my issue to reflect this finding.

**Comment by rafaelmardojai** [comment]
I'm using Firefox Flatpak with Wayland and can't reproduce.

**Comment by rien333** [comment]
> I'm using Firefox Flatpak with Wayland and can't reproduce.

Running under wayland is not the same as running in wayland mode. By default, firefox will run as an xwayland application, unless you have set `MOZ_ENABLE_WAYLAND` to `1`. (this behavior is likely to change in future as wayland adaption grows)

So, the real question is what kind of value for `MOZ_ENABLE_WAYLAND` you (@rafaelmardojai ) are using, and whether that gets picked up by flatpack.

[From the arch wiki](https://wiki.archlinux.org/title/Firefox#Wayland):

> More recent versions of Firefox support opting into [Wayland](https://wiki.archlinux.org/title/Wayland) mode via an [environment variable](https://wiki.archlinux.org/title/Environment_variable).

```
$ MOZ_ENABLE_WAYLAND=1 firefox
```

**Comment by rafaelmardojai** [comment]
@rien333 I'm not using that env var but I have removed the `x11` permission from the Flatpak, and `about:support` states `wayland` as the window protocol.

But I can try setting the env var.

**Comment by rafaelmardojai** [comment]
I still can't reproduce with the env var set.

**Comment by rien333** [comment]
Hm, let me try with the flatpak version as well.

**Comment by rafaelmardojai** [comment]
Yeah I'm sure, the flatpak without `x11` nor `fallback-x11` permissions would simply crash because it doesn't has ways to display. 

Tried xprop and I can't target the Firefox window, so effectively it's Wayland.

**Comment by pol5xc** [comment]
I'm not sure if it is helpful but I was having a this same issues and in my case it seems like setting `widget.wayland.fractional-scale.enabled` to false might have fixed it.

**Comment by rien333** [comment]
> setting widget.wayland.fractional-scale.enabled to false might have fixed it.

This worked!! Thank you so much for pointing this out ☺️

Sorry for the noise, but I guess we learned something.
