### ISSUE TITLE
Borders are drawn outside of the window content

### ISSUE THREAD

**Issue by AbrarSL** [rafaelmardojai/firefox-gnome-theme#721]
**Describe the bug**

There's a difference in how Epiphany draws it's borders and how FF does it. Epiphany draws a translucent border on top of content and FF draws one around the window itself.

I'm not sure if this is even something that can be handled by the theme without any changes to FF itself. Could it perhaps be possible to just remove that border? There'd be no need to draw an overlay border the way Epiphany does.

**To Reproduce**

1. Go vala.dev or any site that is visually simple enough to make the problem obvious

**Expected behavior**

Firefox should not draw an outer border. If possible it should draw the window border on top of the web content.

**Screenshots**

![Firefox](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/69783006/d43d4916-0750-41ca-a624-5b60d96ed9d6)
Firefox

![Epiphany](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/69783006/885db03a-ffd0-436b-80df-b4ff9952cb6c)
Epiphany

**Setup information**
 - OS: Fedora Silverblue 39
 - Installation method: Flatpak
 - Firefox version: 120.0.1
 - Theme version: master
 - Optional features enabled: gnomeTheme.hideSingleTab

**Comment by rafaelmardojai** [comment]
Yeah is true, but I don't think we can manipulate the window borders from UserChrome :/
