### ISSUE TITLE
No bottom rounded corners when Nextcloud dashboard tab is active 

### ISSUE THREAD

**Issue by meybonomme** [rafaelmardojai/firefox-gnome-theme#723]
No bottom rounded corners when Nextcloud dashboard tab is active. With other sites (so far I know) bottom corners are rounded and no issues. You can test with this Nextcloud server: https://nch.pl

Here is screencast:
[Screencast from 2023-12-18 17-28-48.webm](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/147217565/3e8af3f7-4ceb-4b86-af8e-8c16fcbe5b6b)

**Comment by rafaelmardojai** [comment]
This also happens with vanilla Firefox, so not really related to this theme. We just enable `widget.gtk.rounded-bottom-corners.enabled` in the config file.
