### ISSUE TITLE
Firefox 122 Beta 1 Tab Bar Bug

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#727]
Fedora 39, Firefox 112 Beta 1 (Flatpak)
In the newest beta if you move the mouse over Firefox within Gnome Shell's activities the tab bar in Firefox becomes translucent... somehow?
EDIT: ONLY HAPPENS ON X11 AS OF FIREFOX 122
Screenshot attached, strange bug to describe.
![Screenshot from 2023-12-19 20-10-06](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/133521592/b1d1788e-b388-484f-8e0f-b47d8b57deca)

**Comment by CleoMenezesJr** [comment]
112 or 121? If so, 121.0? Are you on master branch? Is it reproducible on vanilla Firefox's profile?

**Comment by KUPOinyourWINDOW** [comment]
I'm on the newest beta build which is currently 122, sorry for the confusion, I hate these high build numbers >.< also interestingly this bug ONLY happens on X11, not on Wayland, but in previous versions it didn't happen on either.

**Comment by KUPOinyourWINDOW** [comment]
Not sure exactly when it was fixed because I've been away from Linux for a few weeks, but I updated the beta branch of the theme and no longer have this issue! With confirmation this issue can be closed c:

**Comment by rafaelmardojai** [comment]
Yes probably, I was going to ask if bdb708818cd867993cb4a6221afaefa45e75de8d fixes the issue, but totally forgot, it seems like it does.
