### ISSUE TITLE
Large context menus have broken scrolling

### ISSUE THREAD

**Issue by AbrarSL** [rafaelmardojai/firefox-gnome-theme#728]
**Describe the bug**

Clicking on an element that produces a long context menu (Image that is also a link) will produce a glitchy context menu. The number of items in the menu is too long and tries to scroll but the scroll mechanism seems broken.

**To Reproduce**

1. Go to flathub.org
2. Right click on an app icon that is just about low enough to have the context menu overflow the window

**Expected behavior**

Not be glitchy. Scroll properly the same way GTK4 popovers do.

**Screenshots**

![Example](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/69783006/7e56e5e6-1dd6-4b1f-9a2b-1f341627f0c5)

**Setup information**
 - OS: Fedora Silverblue 39
 - Installation method: Flatpak
 - Firefox version: 121
 - Theme version: master
 - Optional features enabled: gnomeTheme.hideSingleTab

**Comment by CleoMenezesJr** [comment]
Yeah, can reproduce since v120.

**Comment by Thorazin** [comment]
Yep, I started having this problem today and the only solution I can find so far is to uninstall the theme.

**Comment by CleoMenezesJr** [comment]
I'm a bit out of time to look into this right now, but messing around a bit with --panel-shadow-margin seems to remove the problem, so there is some margin that is conflicting with this.

**Comment by ulipo** [comment]
I have the same issue with bookmarks menu, it jumps around like un the screencast above.
The issue has been introduced with commit 32b535c , reseting to 54433bf makes it disappear.

**Comment by oktayacikalin** [comment]
The dirty workaround from @ilsubyeega works. Not pretty, but the context menu is usable again. Hope you'll figure it out.

**Comment by rafaelmardojai** [comment]
I'm back from vacations, will check it out soon.

The problem is caused by our tabbar scrolling special theming, and because Firefox uses shadow DOM here, it looks like we're affecting all the scroll boxes, including the menu ones.

**Comment by Thorazin** [comment]
Thank you for the fix. I do like this theme. I want to let you and others know though that the "One command install with curl" did not download the fixed files, however cloning the git and running the install script did and now it works.

**Comment by queeup** [comment]
Yea he will release new version then we can install this fix with curl. Because one command install is installing latest release version.
