### ISSUE TITLE
Quick and close dialog buttons not matching adwaita theme (e.g. red close button)

### ISSUE THREAD

**Issue by misuchivu** [rafaelmardojai/firefox-gnome-theme#73]
![Screenshot from 2019-08-12 21-33-22](https://user-images.githubusercontent.com/52562923/62889040-37539e80-bd49-11e9-83fe-e529d373e1f4.png)

**Comment by rafaelmardojai** [comment]
I don't know if `userChrome.css` works on dialogs. Also there's no way to inspect dialogs.

But I'm going to search in firefox source code to see what can i find.

**Comment by rafaelmardojai** [comment]
No way to make it work, i'm jus adding `.dialog-button` theming
