### ISSUE TITLE
Do not apply right tab separator when tab is selected

### ISSUE THREAD

**Issue by CleoMenezesJr** [rafaelmardojai/firefox-gnome-theme#731]
**Describe the bug**
Separators should only appear between unselected tabs that do not border any selected tab.

**Screenshots**
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/54215258/b3a6ae18-e982-49ad-a300-880d20a975b7)

**Comment by rafaelmardojai** [comment]
O is it on nightly/beta?
