### ISSUE TITLE
[Vertical tab - Extension] Feature request: disable animation

### ISSUE THREAD

**Issue by astrocaat** [rafaelmardojai/firefox-gnome-theme#737]
**Describe the bug**

It's not really a bug, but on my system the sliding animation when the vertical tab gets opened/closed is kinda choppy and unpleasant when there are many tabs opened. 
Is there any way to disable the animation? @BirdInFire 

**Setup information**
 - OS: ArchLinux
 - Installation method: AUR
 - Firefox version: 121
 - Theme version: master
 - Optional features enabled: vertical tab extension

**Comment by BirdInFire** [comment]
Yes in the extension settings you can

**Comment by BirdInFire** [comment]
i will check on that asap, I do not know I can properly set this up in a user friendly way tough :/

**Comment by BirdInFire** [comment]
I found a solution who is to enable a switch in about:config like always open is it good ?

**Comment by astrocaat** [comment]
sure!

-------- Original Message --------

**Comment by BirdInFire** [comment]
add this in the end of chrome > theme > extensions > tab-center-reborn.css

```
@media (-moz-bool-pref: "gnomeTheme.extensions.tabCenterReborn.animationDisabled") {
    #sidebar-box[sidebarcommand*="tabcenter"]:hover #sidebar,
    #sidebar-box[sidebarcommand*="tabcenter"]:hover {
        transition: none !important;
    }
    #sidebar-box[sidebarcommand*="tabcenter"]:not(:hover) #sidebar,
    #sidebar-box[sidebarcommand*="tabcenter"]:not(:hover) {
        animation-timing-function: linear;
        transition: none !important;
    }    
}
```

Save and add in about:config : 
gnomeTheme.extensions.tabCenterReborn.animationDisabled on true

do a PR

**Comment by astrocaat** [comment]
it works well. Thank you!

-------- Original Message --------
