### ISSUE TITLE
Add support for the Floorp browser

### ISSUE THREAD

**Issue by TheRsKing** [rafaelmardojai/firefox-gnome-theme#740]
Floorp browser support would be nice.

[Floorp](https://floorp.app/en/)

**Comment by rafaelmardojai** [comment]
Have you tried the theme on it? If it already works I can add its profiles path to the auto-install script as we do for LibreWolf, but I don't really plan to support specific styles for other browsers than Firefox.

**Comment by TheRsKing** [comment]
It didn't work right away, but I don't think it would need a completely new theme since the browser is really just firefox with a new sidebar and other features. The design is relatively the same.

**Comment by SVTA-OP** [comment]
Just heard about Floorp, its the ultimate firefox imo. Would love to see it support this theme, so far, the theme works by simply copying the theme files from firefox's chrome folder and making a similar folder in floorp's profile folder.

**Comment by SVTA-OP** [comment]
I have came up with a workaround. Posted a link to it below.

https://github.com/SVTA-OP/Floorp-GNOME-Theme

**Comment by rafaelmardojai** [comment]
I can add the Floorp profiles path to the auto-install script if you want, but as already stated I don't plan to maintain any specific styling for it.

@SVTA-OP the main install script accepts flags, so you could pass Floorp's profiles path to it. Assuming it is `~/.floorp`, it would be as follows:

```sh
./scripts/install.sh -f ~/.floorp
```

**Comment by TheRsKing** [comment]
somehow it's strange. the manual installation worked. but with the script it didn't work (i entered the file path that is displayed at about:support)

**Comment by ilovethensa** [comment]
would love floorp support
