### ISSUE TITLE
Tab bar transparent when unfocused (nightly)

### ISSUE THREAD

**Issue by notHaider** [rafaelmardojai/firefox-gnome-theme#741]
**Describe the bug**

On Firefox nightly, when the firefox window is unfocused the area where the tabs are displayed becomes transparent so that you can see for example the wallpaper behind it. the text and icons seem to become semi transparent as they are still visible. 

This behavior happens on the nightly and master branch 

**To Reproduce**

1. open firefox window (if you have the hide single tab feature on open a new tab so that the tab bar becomes visible)
2. open or click on a new window

**Expected behavior**

the tabs text and icons should get a little bit darker S

**Screenshots**

Correct behavior
![Screenshot from 2024-01-04 23-10-58](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/81862535/5dc11dd3-6111-48f9-9c7e-8a335f5755d4)

Wrong behavior
![Screenshot from 2024-01-04 23-11-14](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/81862535/fe546eac-81f4-445c-bca4-1499a70b3f5b)

**Setup information**
 - OS: Arch
 - Installation method: aur binary (firefox-nightly-bin)
 - Firefox version: 123.0a1 (2024-01-04) (64-bit
 - Theme version:  v121, nightly (sorry i am not sure what to put here im new to this)
 - Optional features enabled: none

**Additional context**

¯\_(ツ)_/¯

(english is not my native language so excuse me if there are any errors. This also the first time opening an Issue on github so I apologize if there are any mistakes i made)

**Comment by notHaider** [comment]
its on newest firefox main release 122.0 too

**Comment by rafaelmardojai** [comment]
Duplicated of #741, didn't notice early.
