### ISSUE TITLE
Overflowing bookmarks menu and right click context menu jitters

### ISSUE THREAD

**Issue by ZechariahB** [rafaelmardojai/firefox-gnome-theme#743]
**Describe the bug**
Firefox limits the size of menus according to the monitor's resolution and to show everything it shows arrows and allows scrolling. There seems to be conflicting CSS which causes jittering to occur while that is visible. 

**To Reproduce 1**
1. Add bookmarks inside a folder until both top and bottom is constrained by monitor resolution.
2. Move your mouse and hover over the folder, then over to the list of bookmarks.
3. You should see that contents inside jitter back and forth violently until mouse stops moving.

**To Reproduce 2**
1. Use a right click menu that has a lot of entries. If it is too small or you place it too far down, this will not occur.
2. Touch the bottom of the context menu with the bottom of the monitor.
3. You should also see that too jitters.

**Expected behavior**
Both described should not occur like Firefox without using theme.

**Setup information**
 - Firefox version: 121
 - Theme version: v121

Optional features:
- gnomeTheme.dragWindowHeaderbarButtons true
- gnomeTheme.hideWebrtcIndicator true
- gnomeTheme.normalWidthTabs true
- gnomeTheme.symbolicTabIcons true
- gnomeTheme.systemIcons true
- gnomeTheme.tabsAsHeaderbar false

**Comment by rafaelmardojai** [comment]
Possibly a duplicated of #728, can you confirm? Should be fixed on master.

**Comment by rafaelmardojai** [comment]
Tagged a new release, so you can also use the curl command to update.

**Comment by ZechariahB** [comment]
Seems to be indeed a dupe. I overlooked that.
