### ISSUE TITLE
Right click context menu flickering

### ISSUE THREAD

**Issue by luiz734** [rafaelmardojai/firefox-gnome-theme#745]
**Describe the bug**
The popup that opens when I right-click some links keeps scrolling up and down to quickly, making it impossible to click some options.

**To Reproduce**
1. Right-click on links in any page. 
2. Move the cursor up and down.

**Expected behavior**
The context menu should not flick.

[flick.webm](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/44483575/1def2010-609a-4575-aa6e-c369ed0265f2)

**Setup information**
 - OS: Arch 6.6.10-1-lts
 - Installation method: AUR
 - Firefox version: 121.0.1
 - Theme version: 112.r0.g9b88fd9-1
 - Optional features enabled: None

**Additional context**
- I noticed that the issue only happens when there is no space to show the full popup, requiring a vertical scroll. 
- I've checked that this only happens while using the theme. 
- Despite disabling extensions that could be the cause, such as Greasemonkey, the issue persists.

**Comment by rafaelmardojai** [comment]
Duplicated of #728. A v121.1 release of the theme was made fixing that regression.
