### ISSUE TITLE
Firefox 122 bookmark icon issue

### ISSUE THREAD

**Issue by Titaniumtown** [rafaelmardojai/firefox-gnome-theme#750]
**Describe the bug**
The checkmark on the bookmark creation dialog is not properly rendered

**To Reproduce**

1. Go to a webpage
2. Try to bookmark the page
3. View the "Show editor when saving" option

**Expected behavior**
The blue checkmark icon should look normal and not all glitchy

**Screenshots**
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/11786225/fee0771d-6bbd-496b-8a93-91a81ecab663)

**Setup information**
 - OS: Fedora
 - Installation method: Flatpak
 - Firefox version: 122
 - Theme version: eb7c43d11abc157f97d032018115c9f7b04ca4de
 - Optional features enabled: N/A

**Comment by iAweX** [comment]
Same in page search bar.

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/50710418/aa325020-a0ee-4322-80d3-7155a3c6368a)

OS: Debian 12
Installation method: Mozilla Debian Package
Firefox version: 122
Theme version: master
Optional features enabled: fixed tab width
