### ISSUE TITLE
Unable to install for Nightly

### ISSUE THREAD

**Issue by 5vr** [rafaelmardojai/firefox-gnome-theme#754]
**Describe the bug**
Unable to install for Nightly

**To Reproduce**

1. Have Nightly installed at /opt/firefox
2. In the profile directory, create chrome folder, clone the repo inside it and cd into it. Have a theme called `Adwaita-AMOLED`.
3. Give command `./scripts/install.sh -f /opt/firefox/ -t Adwaita-AMOLED`
4. See error `FAIL, please check Firefox installation, unable to find 'profile.ini' at /opt/firefox/.`

**Expected behavior**
It should have installed the theme with the theme provided in the `-t` argument.

**Screenshots**

**Setup information**
 - OS: Arch
 - Installation method: Manual, from https://www.mozilla.org/en-US/firefox/channel/desktop/
 - Firefox version: 124.0a1 (2024-01-30) (64-bit)
 - Theme version: master
 - Optional features enabled: `-f` `-t`

**Additional context**

**Comment by rafaelmardojai** [comment]
The `-f` flag is for the Firefox's profiles folder, usually `~/.mozilla/firefox` (default value of the script), also the `-t` flag only matters if the theme is supported by this theme (is listed in the flag description on README).
