### ISSUE TITLE
Firefox gnome theme doesn't respond to light/dark mode toggle

### ISSUE THREAD

**Issue by SVTA-OP** [rafaelmardojai/firefox-gnome-theme#757]
Firefox Gnome theme used to switch between light and dark mode, but now it just stays dark.  
I'm using Fedora 39, Wayland with firefox 122 as a flatpak.

**Comment by rafaelmardojai** [comment]
Do you have the `System theme — auto` theme enabled in `Menu` -> `Add-ons and themes` -> `Themes`?

**Comment by SVTA-OP** [comment]
Yes, I have it enabled.  
  
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/126323835/de390633-9b3f-4298-8130-d6a5efddf9c8)

**Comment by SVTA-OP** [comment]
I'm so forgetful. Anyway, I happened to notice that the GTK3 theme was set to adw-gtk3-dark instead of adw-gtk3. Switched it and now I can toggle light and dark modes. Thanks.
