### ISSUE TITLE
Tab previews are unstyled & break tab bar scrolling

### ISSUE THREAD

**Issue by AbrarSL** [rafaelmardojai/firefox-gnome-theme#758]
**Describe the bug**

The tab previews use the default FF colors and not the colors from the theme.
I wonder if there's anything else that could be followed from Epiphany? I'm not sure.

Edit: I found another more serious issue. When the preview card is visible tab bar scrolling doesn't work.

**To Reproduce**

1. Go to about:config
2. Enable the browser.tabs.cardPreview.enabled option to true
3. Hover over a loaded tab

**Screenshots**

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/69783006/4ca8d4b9-8533-48ca-8cc7-0f58b3e7d885)

**Setup information**
 - OS:  Fedora
 - Installation method:  Flatpak
 - Firefox version:  123
 - Theme version:  master
 - Optional features enabled:  gnomeTheme.hideSingleTab

**Comment by rafaelmardojai** [comment]
Firefox 129 with `browser.tabs.hoverPreview.enabled` seems to look fine.
