### ISSUE TITLE
Vertical lines are shown on webpages and in full-screen videos.

### ISSUE THREAD

**Issue by DeeBeeDouble** [rafaelmardojai/firefox-gnome-theme#760]
**Describe the bug**

When watching a video, there will be a (sometimes flashing) line at the timeline of the video. This same line can sometimes also be observed in other, seemingly random places. I've seen it on many different websites and even on the new tab homepage.

There is another similar line that always appears when a video is playing in full-screen.

**To Reproduce**
1. Go to https://youtube.com or any other site that plays a video.
2. Watch a video
3. Full-screen it
4. See the lines

**Expected behavior**

No visible lines

**Screencast demonstrating the issue**

[Screencast from 2024-03-01 22-24-09.webm](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/78625950/b761964c-e698-4ada-8724-8fe814934cf5)

**Setup information**
 - OS: Fedora silverblue
 - Installation method: LibreWolf, Flatpak
 - Firefox version: 123.0-1
 - Theme version: v122
 - Optional features enabled: none

**Additional context**
- The same issue also occurred on a different machine with a fresh silverblue and LibreWolf install.
- Started appearing after an update of the theme some time (~2 Months) ago.

**Comment by ThuHtooSan** [comment]
Same here. I thought it was because of some gnome extensions I installed but it doesn't appear in my native video player. So, this theme might be the culprit.

**Comment by rafaelmardojai** [comment]
Maybe related-to/same-as #744, but sadly I can't reproduce it.

**Comment by BirdInFire** [comment]
I tried to replicate it into my VM (UTM) on silver blue with no success.
IS it possible it's an hardware acceleration issue rather than a theme bug ?

**Comment by iansantosdev** [comment]
This happens when there are downloads in the queue.

**Comment by DeeBeeDouble** [comment]
> This happens when there are downloads in the queue.

Hmm for me it happens regardless even without downloads.

**Comment by DeeBeeDouble** [comment]
> I tried to replicate it into my VM (UTM) on silver blue with no success. IS it possible it's an hardware acceleration issue rather than a theme bug (if so maybe try the native firefox instead of the flatpak in my memory acceleration issue is one known bug of the flatpak edition of firefox) ?

How is that possible? I tried it on completely different hardware with no settings changed. All i did was install LibreWolf, install the theme and that's it.

Native and the flatpak Firefox versions do not suffer from that problem, so I assume it is caused by one of the many flags LibreWolf changed.

**Comment by ThuHtooSan** [comment]
I can confirm that the line appears only when the downloads icon is _visible_ and _in the header bar_. It doesn't appear when I put the downloads icon in the tab bar and bookmark toolbar.

**Comment by rafaelmardojai** [comment]
The downloads was enough to reproduce the bug, hopefully it should be fixed for the issue author too.

**Comment by DeeBeeDouble** [comment]
Sorry for the late response.
That did indeed fix the line in the top left corner; however, the other one remains.
In addition, I figured out that this one is in fact just the cursor (The one that appears when you type) that does not hide itself anymore.
