### ISSUE TITLE
Close Button Bug in 125 

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#767]
We've got a small bug in the newest Firefox 125 beta, the close button is large and when you hover over it, it highlights in a red colour.

![Screenshot from 2024-03-22 16-16-00](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/133521592/4fb29c1a-307b-473f-821b-b299bc47595e)

![Screenshot from 2024-03-22 16-16-34](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/133521592/763f539a-a316-4313-bb93-6645c2c4b72e)

**Comment by hex-developer** [comment]
I can confirm I have the same issue with Firefox Developer Edition. My solution was rolling back and disabling updates with a policy...

**Comment by githubtefo** [comment]
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/11220103/dfa81421-45fc-4ba7-b420-40423ab31145)
Similar issue on stable v125.0.

**Comment by TrixieUA** [comment]
Same issue here on stasble 125
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/98626846/c2d26ff3-a4a1-4104-9a4b-f6b329aff6ad)

**Comment by garrett** [comment]
A related aside: I filed an upstream issue about the icons being incorrect in Firefox. https://bugzilla.mozilla.org/show_bug.cgi?id=1891977

If they actually fix this someday, then it'll be less to override in the theme here (which would mean less that breaks between Firefox releases) — and Firefox would look less wrong by default on Linux too.

**Comment by hex-developer** [comment]
Great job @garrett! The images you attached highlight the problem very precisely! Let's see when (and if) it'll be fixed...

**Comment by tr1p0p** [comment]
Why closed this issue ? It's not fix on any release, the command to install bring this bug, and so people just... well, post another duplicate of this issue because, well, it's only fix on the master (but nobody just give instruction to install the theme from it, so, yeah).

So yeah, got this issue too, waiting for the new release, don't want to go to master branch..
