### ISSUE TITLE
After updating gnomeTheme.hideSingleTab no longer has any effect. 

### ISSUE THREAD

**Issue by xusiai** [rafaelmardojai/firefox-gnome-theme#768]
**Describe the bug**
After updating gnomeTheme.hideSingleTab no longer has any effect. 

**To Reproduce**
1. Set gnomeTheme.hideSingleTab to true
2. Launch Firefox.

**Expected behavior**
Tab ebar disappear when a single tab is open.

**Screenshots**
![2024-03-29T04:43:24,518625734+01:00](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/142084577/3f526b49-c982-40cb-a131-2d5354f139c6)

**Setup information**
 - OS: NixOS
 - Installation method: Manual
 - Firefox version: 115.8
 - Theme version: master
 - Optional features enabled: 

```
      "gnomeTheme.closeOnlySelectedTabs" = true;
      "gnomeTheme.symbolicTabIcons" = true;
      "gnomeTheme.hideWebrtcIndicator" = true;
      "gnomeTheme.hideSingleTab" = true;
```

**Additional context**
No tab or theme related addons installed.

**Comment by BirdInFire** [comment]
@xusiai  Firefox version: 115.8, you mean 125 ? or are you on the LTS version (I ask to replicate it and try to found witch css selector have broken)

**Comment by xusiai** [comment]
I am on 115.8 (Extended Support Release) - if it works on current (124?) then perhaps this will resolve itself.

**Comment by rafaelmardojai** [comment]
If you`re using Firefox 115 you probably want to stay in the `v115` git tag. The theme doesn't try to be backward compatible, so for older versions you must use specific releases.
