### ISSUE TITLE
round buttons matching new adwaita theme

### ISSUE THREAD

**Issue by misuchivu** [rafaelmardojai/firefox-gnome-theme#77]
Right now landed on Fedora 30 Stable, see screenshot.
Could be optional to be activated from css settings.
![Untitled](https://user-images.githubusercontent.com/52562923/64359242-9fc43180-d010-11e9-99ca-c2cd1fbdeab4.png)

**Comment by NettoHikari** [comment]
Please make it optional, if possible. I think, the round button is a step in the wrong direction made by the developers of the Adwaita theme.

**Comment by rafaelmardojai** [comment]
Fixed, added `rounded-title-buttons.css`.
