### ISSUE TITLE
URLBar suggestions is broken with 126

### ISSUE THREAD

**Issue by zapSNH** [rafaelmardojai/firefox-gnome-theme#771]
**Describe the bug**
The .urlbarView is covering the URLBar content. If I remove [this line](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/33015314c12190230295cff61ced148e0f7ffe1c/theme/parts/urlbar.css#L11), then the problem goes away.

**To Reproduce**
1. Have Firefox 126
2. Click on the URLBar
3. Error appears

**Expected behavior**
The URLBar isn't covered by .urlbarView.

**Screenshots**
![screenshot](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/134786889/2aef3828-2025-4cac-82c8-955879eb2ea0)

**Setup information**
 - OS: Fedora
 - Installation method: tarball (Firefox), git (theme)
 - Firefox version: 126 (2024-04-05)
 - Theme version: master
 - Optional features enabled: none

**Additional context**
Simply pushing .urlbarView down isn't enough since the text content of the URLBar doesn't show up.

**Comment by zzzsyyy** [comment]
It may be necessary to port this fix to the `beta` branch, as many people use the beta branch on `firefox-beta`

**Comment by paulvt** [comment]
I still have this issue with the `v126` checked out on Firefox 126.0.

And it is the same whether the `--urlbar-container-height` is 0px, 34px (as it is now) or 200px.

**Comment by thomasaull** [comment]
@paulvt Maybe try to check out the `master`. This works for me on Firefox Developer Edition which currently is in `v126`

**Comment by paulvt** [comment]
I already did, but `master` is only one commit ahead of `v126` and that is a `README.md` change (see 1efffca).
