### ISSUE TITLE
[Feature]Optional Folder For Yaru Icons in Ubuntu 

### ISSUE THREAD

**Issue by ochi12** [rafaelmardojai/firefox-gnome-theme#772]
Please Instead of gnomeTheme.symbolicTabIcons=true, Why not just give us an option to install Yaru for ubuntu because not all the icons just follow the system icons.

**Comment by rafaelmardojai** [comment]
Sorry but I don't completely understand the question, are you talking about `gnomeTheme.symbolicTabIcons` or `gnomeTheme.systemIcons`?

**Comment by ochi12** [comment]
yes the gnomeTheme.systemIcons lack. only the new tab, back, forward, close, minimize, maximize, app menu, refresh looks like ubuntu System Icons other than that, (eg. inside the search box, inside, menu drop down) the star icon, shield icon, lock icon still feel adawaita'sh. 
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/84390901/47ea9d3c-a7a0-4ddc-ba01-948e19ee75b4)

**Comment by ochi12** [comment]
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/84390901/4d61e7ce-5273-4e06-b7e5-360b77132291)
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/84390901/882ed75d-7721-44f9-a11b-44e9ba868613)
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/84390901/0f4b4d5e-e7f7-4c81-aa35-8d915f503eb8)
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/84390901/58bf4279-8e6c-4e3a-8523-e54210ab1405)

**Comment by ochi12** [comment]
I don't mind the gnomeTheme.symbolicTabIcons tho

**Comment by rafaelmardojai** [comment]
Here we're limited to the standard icons theme, you can try to check what icons from the Ubuntu theme are available in Firefox with `moz-icon://stock/icon-name-here?size=dialog` and extend `theme/system-icons.css` to use them.
