### ISSUE TITLE
Close button changed

### ISSUE THREAD

**Issue by lapor-kris** [rafaelmardojai/firefox-gnome-theme#776]
**Describe the bug**
Close button has changed and now looks odd.

**To Reproduce**
1. Update to Firefox 125
2. Open Firefox

**Expected behavior**
The close button should be the same style as ohter close buttons in Gnome.

**Screenshots**
![Zaslonska slika 2024-04-18 12-13-25](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/68855741/0d60fbb3-ffe5-41af-a14e-c4f700d2c921)

**Setup information**
 - OS: Fedora 39
 - Installation method:RPM
 - Firefox version: 125.0.0
 - Theme version: The one installed with "One command install with curl"
 - Optional features enabled: /

**Comment by KUPOinyourWINDOW** [comment]
As a workaround (not fix) you can switch the firefox theme to System instead of Light or Dark and it should go back to normal

**Comment by lapor-kris** [comment]
It already was on System. I changed from System to Light and back, but nothing changes.

**Comment by tobiulm** [comment]
Same here. It also affects the Minimize and Maximize Window Buttons
![grafik](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/37046617/95d41c21-45ac-4577-a4ab-e8a30c4bc089)
Setup:
Fedora 39
Firefox 125.0.0

**Comment by JimmyJichi** [comment]
Related to #767, after updating to the latest master branch, the titlebar buttons look normal when the system theme is used. However, when manually choosing the light or dark theme, the buttons are still bugged.

[Screencast from 2024-04-18 16-29-13.webm](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/14927497/d583bd35-ae60-41bc-8da8-483dfaef4dec)

**Comment by rafaelmardojai** [comment]
This actually is a duplicated of #767.

@JimmyJichi thanks for the catch! Should be fixed no.
