### ISSUE TITLE
Oversized window close button

### ISSUE THREAD

**Issue by TriVoxel** [rafaelmardojai/firefox-gnome-theme#777]
**Describe the bug**

The close button is too big

**To Reproduce**

1. Install latest theme
3. Open Firefox 125.0.1

**Expected behavior**

Normal close button

**Screenshots**

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/25536957/aa3b8ced-d727-47d3-b487-b1b47d3300b6)

**Setup information**
 - OS: Fedora Atomic 39 GNOME
 - Installation method: Flatpak (Flathub)
 - Firefox version: 125.0.1
 - Theme version: Latest using CURL from instructions
 - Optional features enabled: gnomeTheme.hideSingleTab

**Additional stuff**

Monitor is 1080p at a standard 1x scaling

**Comment by rafaelmardojai** [comment]
Duplicated of #767. 

It's already fixed on master branch, we're just missing a release for the curl command to work.
