### ISSUE TITLE
Search Suggestions Broken in 126

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#778]
Unfortunately we got another bug (Mozilla pls).
Searching in the address bar causes the search suggestions to cover the bar in the new beta.

![Screenshot from 2024-04-19 20-21-49](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/133521592/f6d3fed1-3478-4c76-83f3-a079993d56db)

**Comment by rafaelmardojai** [comment]
Duplicated of #771
