### ISSUE TITLE
New colored checkbox and radiobutton in GTK-3.24.11

### ISSUE THREAD

**Issue by ubluish** [rafaelmardojai/firefox-gnome-theme#78]
![radiobutton](https://user-images.githubusercontent.com/21042432/64503974-e09c9e80-d2cd-11e9-81a8-3e94a4ddd9c6.png) ![checkbox](https://user-images.githubusercontent.com/21042432/64503973-e0040800-d2cd-11e9-804e-18fd8cbf0af1.png)

Edit: I checked the checkbox inside menubar items still the same in Libreoffice, do you think we should keep it like that or change it to colored

**Libreoffice menubar item**
![1](https://user-images.githubusercontent.com/21042432/64504490-1a6ea480-d2d0-11e9-8534-88a3d44b5370.png) ![2](https://user-images.githubusercontent.com/21042432/64504493-22c6df80-d2d0-11e9-8fbb-c39b1269441e.png)

**Comment by rafaelmardojai** [comment]
I think we will keep it like that. Using non flat checkbox in menus look weird.
