### ISSUE TITLE
Twitter/Mastodon don't respect bottom rounded corners

### ISSUE THREAD

**Issue by phillipjprado** [rafaelmardojai/firefox-gnome-theme#780]
**Describe the bug**
If you navigate to Twitter or Mastodon, the bottom corners appear to break out of the browser's rounded corners, making them pointed.

**To Reproduce**

1. Go to twitter.com or many mastodon instances like infosec.exchange
2. Look at the bottom corners of the browser

**Expected behavior**
Browser corners should still stay rounded as per the theme's corner radius.

**Screenshots**
Twitter's bottom right corner:
![Screenshot from 2024-04-24 16-05-28](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/29846153/c3c12a84-e0ff-4c0b-a83f-ae05a58893b7)

Mastodon's bottom right corner:
![Screenshot from 2024-04-24 16-05-04](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/29846153/3dceb49c-0a87-46c5-b255-fbf19f7ca1ea)

**Setup information**
 - OS: Ubuntu 23.10
 - Installation method: Flatpak
 - Firefox version: 125.0.1 
 - Theme version: v124
 - Optional features enabled: gnomeTheme.hideSingleTab, gnomeTheme.systemIcons

**Additional context**
It doesn't matter if you change the Twitter theme to dark or light mode, the issue is still there. It's hit or miss which Mastodon instances are affected.

**Comment by rafaelmardojai** [comment]
Bottom rounded borders come from Firefox and still have some bugs/regressions. Nothing we can do.

https://bugzilla.mozilla.org/show_bug.cgi?id=1850827
