### ISSUE TITLE
[Vertical tab - Extension] Visual bug, Inconsistency

### ISSUE THREAD

**Issue by ataractic** [rafaelmardojai/firefox-gnome-theme#781]
**Describe the bug**
When using light theme on white-background websites, we can't see the edge of the vertical tab bar, which makes it really unaesthetically pleasing (see the screenshots).

**To Reproduce**
1. Install `firefox-gnome-theme` using curl script
2. Install `Tab Center Reborn` and copy its' `firefox-gnome-theme` styling from the repository
3. Go on GitHub, or any light background website
4. See the thing

**Expected behavior**
A 1px-wide separator should be present on the vertical tab bar edge to maintain visual consistency

**Screenshots**
![Firefox New Tab](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/141071073/bf83c905-b1e4-4f13-b03c-45423c1416ec)
![GitHub example](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/141071073/b6aa42a6-9f88-49e5-8ae0-ec367d72f2be)

**Setup information**
 - OS: Fedora 40
 - Installation method: Curl script without sudo
 - Firefox version: 125
 - Theme version: v125 / master branch for vertical tabs styling
 - Optional features enabled: `gnomeTheme.extensions.tabCenterReborn`, `gnomeTheme.hideSingleTab`, `gnomeTheme.hideWebrtcIndicator`
 

**Additional context**
Tested with and without `gnomeTheme.extensions.tabCenterReborn.alwaysOpen` and `gnomeTheme.extensions.tabCenterReborn.animationDisabled`

**Comment by BirdInFire** [comment]
@ataractic have made a PR to fix, in the meantime you can add this into : theme/extensions/tab-center-reborn.css and restart, 

Note : I have copied the way the browser draw the line under the header bar, so I will not change the color or the size / transparency (because by coping this code it will change too if Mozilla (or this theme) decide to modify the color in the variable).

```
#sidebar-box{
        border-right: 0.01px solid var(--chrome-content-separator-color) !important;
}
```
