### ISSUE TITLE
Firefox 126 search suggestions offset

### ISSUE THREAD

**Issue by sekurilabs** [rafaelmardojai/firefox-gnome-theme#786]
I understand it's early but I wanted to give you heads up on this issue. I've noticed a strange offset in FF 126 (released today) with URL bar suggestions dropdown:

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/1055788/a339f023-738f-4767-84ba-c4076c7ce411)

Edit: Actually it's not just offset but the text that you input in the url-bar is not visable until esc is pressed, and the looking glass icon is not visible. I guess Mozilla changed something with url bar and suggestions.

I have moved the box via userChrome.css a bit down using a urlbarView class. You can see the missing text and icon now:
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/1055788/99ad5edc-56f6-4dbc-a4bb-1bb86ac46560)

**Comment by githubtefo** [comment]
Same problem here. How should I solve it?

**Comment by rafaelmardojai** [comment]
This is a duplicated of #771, and should be already fixed in master branch. For the curl script you will need to wait for a new release of the theme.
