### ISSUE TITLE
URL suggestions overlaps address bar

### ISSUE THREAD

**Issue by arashm** [rafaelmardojai/firefox-gnome-theme#789]
**Describe the bug**
The URL suggestion overlaps the address bar in Firefox 126.

**To Reproduce**

1. Click on address bar
2. The suggested URLs overlaps with the address bar

**Expected behavior**
The suggestions should appear beneath the address bar

**Screenshots**
![Screenshot from 2024-05-15 15-05-17](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/849640/ef84714a-ef6c-42af-b6f1-176d0d6c3502)

**Setup information**
 - OS: ArchLinux
 - Installation method: Pacman
 - Firefox version: 126.0
 - Theme version: 125
 - Optional features enabled: none

**Additional context**
The only customization I have is following CSS to hide the tab bar. I tried removing it and restarted Firefox, but it didn't help with the issue.

```css
#TabsToolbar{ visibility: collapse !important }
```

**Comment by dylankird** [comment]
I have the same issue, even without any additional CSS or configurations.

**Comment by rafaelmardojai** [comment]
Duplicated of  #771, already fixed on master branch. Use it or wait for a theme release.
