### ISSUE TITLE
Urlbar corners are abit blury

### ISSUE THREAD

**Issue by ubluish** [rafaelmardojai/firefox-gnome-theme#79]
![Untitled](https://user-images.githubusercontent.com/21042432/64504798-b220c280-d2d1-11e9-8b2b-a3dcc6264362.png)

**Comment by rafaelmardojai** [comment]
That's a Firefox issue drawing the box-shadow. This is fixed in FF70+.
I'm going to remove the shadow for FF69.

**Comment by rafaelmardojai** [comment]
Fixed in [234a739]
