### ISSUE TITLE
URL Dropdown menu overlaps with the URL bar when installed via install-by-curl.sh

### ISSUE THREAD

**Issue by theodormoroianu** [rafaelmardojai/firefox-gnome-theme#791]
**Describe the bug**

The bug mentioned in #771 and #789 , marked as closed, still occurs on my machine, with the latest version of the extension and of Firefox when using the `install-by-curl.sh` method.

I removed and reinstalled the extension and the problem still occurs.

Reinstalling the extension by following the manual installation instead of the one liner (cloning the repo and running `auto-install.sh`) fixes the issue, so the `install-by-curl.sh` file is probably outdated.

**To Reproduce**

1. Install the `firefox-gnome-theme` extension.
2. Open Firefox.
3. Click on the URL bar.
4. The menu overlaps with the bar.

**Expected behavior**
The menu does not overlap with the bar.

**Screenshots**

![Screenshot from 2024-05-16 15-03-30](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/8684801/7832d636-52ce-415f-8b31-2c542b965037)

**Setup information**
 - OS: Fedora 40
 - Installation method: Flatpak
 - Firefox version: 126
 - Theme version: master
 - Optional features enabled: `bookmarksToolbarUnderTabs`, `hideSingleTab`, `normalWidthTabs`.

**Comment by rafaelmardojai** [comment]
Duplicated of #771.
