### ISSUE TITLE
Fix GNOME stack icons coloring issues

### ISSUE THREAD

**Issue by MLDamazigh** [rafaelmardojai/firefox-gnome-theme#8]
The headerbar buttons color need some improvements. they are greyed out. even with the dark theme enabled.

The headerbar buttons with light theme (they should be black like the reload button!!).
![image](https://user-images.githubusercontent.com/15183134/60515003-32bbb500-9cca-11e9-9873-7e53ed5bc6bb.png)                              ![image](https://user-images.githubusercontent.com/15183134/60515019-3a7b5980-9cca-11e9-8bd0-56e392cc5fb0.png)

The headerbar buttons with dark theme (they should be in white color!).
![image](https://user-images.githubusercontent.com/15183134/60515207-aa89df80-9cca-11e9-8a54-fd2096827efd.png)

**Comment by rafaelmardojai** [comment]
That's an issue when using GNOME stack icons with `moz-icon://stock/` on some systems. 
See https://github.com/rafaelmardojai/firefox-gnome-theme#icons-color-broken.

In a future i should bundle GNOME svg icons by my self to fix this.
