### ISSUE TITLE
URL bar popout covers URL bar

### ISSUE THREAD

**Issue by kbdragon** [rafaelmardojai/firefox-gnome-theme#802]
**Describe the bug**
As in title, the URL bar pop up covers the URL bar, making modifying or copying the URL difficult.
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/113253861/e6f7f5b3-050b-4414-904b-b7e5990a73d2)

Following [this thread](https://www.reddit.com/r/firefox/comments/1cs3g49/address_bar_suggestions_going_up_instead_of_down/), I isolated the issue to the 'chrome/firefox-gnome-theme/theme/parts/urlbar.css' file and commented out the following section as a temporary fix:

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/113253861/6a87a840-367d-4695-bd9c-79d65247ed1e)

**Comment by rafaelmardojai** [comment]
This looks like a duplicated of #771, and it's already fixed. Can you give info about your Firefox and theme version?

**Comment by rafaelmardojai** [comment]
If you right click the headebar (navbar) and go to Customize, can you confirm the theme version in the bottom corner?

![Captura desde 2024-06-10 12-12-56](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/9d1ffa61-915d-422d-9dd3-82a09c9932e2)

**Comment by kbdragon** [comment]
@rafaelmardojai 
I'm on v126 of the theme.
Firefox 126.0.1.
I tried updating the theme before I found the problem - no luck.

**Comment by rafaelmardojai** [comment]
Well, then sadly I can reproduce it for now.

**Comment by EddoWagt** [comment]
Okay strange, my theme wasn't updating even though the installer gave no errors. Had to delete the theme and reinstall, it's working for me now.

**Comment by TipsyTheCat** [comment]
reinstalling the theme does fix this
