### ISSUE TITLE
Issue with optional features

### ISSUE THREAD

**Issue by NichoGamerTv** [rafaelmardojai/firefox-gnome-theme#804]
I have it enabled but it doesn't work, there's probably bugged.

**To Reproduce**
Type link: about:config
Type: gnomeTheme.tabsAsHeaderbar
Set: boolean
Press: add button
Restart Firefox

It would put the tab bar on top, which it stays on the bottom of the header bar.

here's that it doesn't work:
![Screenshot from 2024-06-22 23-28-02](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/78816507/393dd0f4-99cb-4eec-9a47-58c8cb25ad01)

I have it enabled:
![Screenshot from 2024-06-22 23-30-01](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/78816507/6841625e-fc8d-451a-9b52-a447dab81867)

 - OS: Debian 12
 - Installation method: ESR
 - Firefox version: 115.12.0esr
 - Theme version: master
 - Optional features enabled: gnomeTheme.tabsAsHeaderbar

**Comment by NichoGamerTv** [comment]
quick update: i installed the flatpak version, and it works now

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/78816507/cf26a893-e448-4454-8f60-c104807341ef)

**Comment by rafaelmardojai** [comment]
When you use an older Firefox version you want to use the git tag of the theme for that specific version, the `master` branch only targets the latest version.

In this case, I believe around Firefox 120, they changed the way to get those settings in CSS and the theme adapted, so the `master' branch will not work with 115 in this regard.
