### ISSUE TITLE
Part of the Firefox browser‘s functional buttons overlap

### ISSUE THREAD

**Issue by Niko3C** [rafaelmardojai/firefox-gnome-theme#805]
<img width="960" alt="Snipaste_2024-06-24_14-14-39" src="https://github.com/rafaelmardojai/firefox-gnome-theme/assets/131971935/e24e766c-9aa1-4f9d-b1a0-b5a8476f7b6b">
I am currently using Firefox on windows 11 with version 127.0.1(64-bit).
Firefox on windows 11 with version:127.0.1(64-bit),the system zoom in/out buttons are overlapping with the extensions,more tools,and application menu three buttons. I tried to modify the css files by myself,but it didn't work.I see the effect picture from you have the close button,but no matter how i try,and the final result is not able to show the effect according to your demo.At present,my solution is to enable the title in the customize toolbar in order to use it normally.Is there any way to solve the problem in the next version? I hope you can see my bug feedback,and i am looking forward to your reply,thank you very much!

**Comment by rafaelmardojai** [comment]
The theme doesn't support Windows see #107, maybe we can reopen that issue.

**Comment by Niko3C** [comment]
You're right. If you have time, we can work together to solve this problem！！

**Comment by rafaelmardojai** [comment]
Sure, actually looking at your screenshots the theme seem to be working pretty good on Windows, the only problem is that for window controls positioning the theme uses some linux only media queries to determine how many buttons there are and if they are in the left or right. But for Windows we can just asume that we have three buttons on the right.

Can you test if this CSS code solves the problem?

```css
@media (-moz-platform: windows) {
	:root {
		--gnome-navbar-csd-offset: 117px;
	}
}
```

**Comment by Niko3C** [comment]
Thank you very much for your reply by using the method you gave I have successfully solved the problem.
Here are my screenshots for other windows  users:
<img width="960" alt="Snipaste_2024-06-27_20-10-03" src="https://github.com/rafaelmardojai/firefox-gnome-theme/assets/131971935/fb76e562-920d-43df-9c90-7de5c874e9e7">

**Comment by rafaelmardojai** [comment]
Since it's a trivial fix, I'm going to add it to the theme.

**Comment by Niko3C** [comment]
Thank you for your reply. I have already made the necessary changes to the Windows theme. If anyone else needs it, you can have them come to my repository to view the files I have uploaded
<img width="960" alt="Snipaste_2024-07-08_15-03-33" src="https://github.com/rafaelmardojai/firefox-gnome-theme/assets/131971935/41976479-7e1f-41d9-b00c-2909523136a0">

**Comment by Niko3C** [comment]
This is the URL of my project: https://github.com/Niko3C/firefox-gnome-theme_win11
