### ISSUE TITLE
[Feature] Always hide tab bar

### ISSUE THREAD

**Issue by michaelhthomas** [rafaelmardojai/firefox-gnome-theme#807]
**Is your feature request related to a problem? Please describe.**

When using a tabs sidebar plugin like [Sidebery](https://github.com/mbnuqw/sidebery), the tabs shown at the top of the screen are redundant.

**Describe the solution you'd like**

An `about:config` setting that allows hiding the tab bar regardless of the number of tabs open.

**Describe alternatives you've considered**

Adding additional css to always hide the tab bar.

**Additional context**

**Comment by sekurilabs** [comment]
That is not actually in the domain of these theme. Developer can't know which extension everyone has. To hide the horizontal tab bar use your own css (either in sidebery css or in your own userChrome.css):
/* hides the native tabs */
#TabsToolbar {
  visibility: collapse;
}

**Comment by rafaelmardojai** [comment]
@sekurilabs is right, you can add extra custom CSS when needed. I don't think that this is in the scope of the theme.
