### ISSUE TITLE
Thunderbird 128 not work.

### ISSUE THREAD

**Issue by a1ex-ak** [rafaelmardojai/firefox-gnome-theme#812]
Good afternoon 
I haven’t found how to make a bug report for an email client, but the theme doesn’t work in Thunderbird 128.

![Снимок экрана от 2024-07-12 09-21-26](https://github.com/user-attachments/assets/6f32ecd1-03ac-46e4-92bf-4ba634161d3f)

Tell me how to fix it?

![Снимок экрана от 2024-07-12 09-22-16](https://github.com/user-attachments/assets/4a4b5cfb-b3b2-497f-95f2-f2d6cdb04408)

**Comment by rafaelmardojai** [comment]
I'm aware of this and probably will fix in in the weekend, but sadly the Thunderbird is not officially released yet so it doesn't have a bug tracker. For now you can jump in our Matrix room to report any problem.

**Comment by a1ex-ak** [comment]
> I'm aware of this and probably will fix in in the weekend, but sadly the Thunderbird is not officially released yet so it doesn't have a bug tracker. For now you can jump in our Matrix room to report any problem.

but the flatpack version was updated independently and version 128 is already in the store

**Comment by rafaelmardojai** [comment]
@a1ex-ak Probably I didn't explain myself well. The theme is the one not officially released yet.

That why you can read this on its README:

> ### Warning:
> This theme is a work in progress.

But anyway, the most notorious Thunderbird breakages should be fixed now.

**Comment by a1ex-ak** [comment]
> @a1ex-ak Probably I didn't explain myself well. The theme is the one not officially released yet.
> 
> That why you can read this on its README:
> 
> > ### Warning:
> > This theme is a work in progress.
> 
> But anyway, the most notorious Thunderbird breakages should be fixed now.

Excuse me, but when can I try the beta version? )) I really like your work.

**Comment by a1ex-ak** [comment]
> @a1ex-ak Probably I didn't explain myself well. The theme is the one not officially released yet.
> 
> That why you can read this on its README:
> 
> > ### Warning:
> > This theme is a work in progress.
> 
> But anyway, the most notorious Thunderbird breakages should be fixed now.

Please forgive me, everything worked out for me)) I really like your work.
