### ISSUE TITLE
AUR deploy failed

### ISSUE THREAD

**Issue by FunctionalHacker** [rafaelmardojai/firefox-gnome-theme#814]
Hi, it seems the latest release action didn't run successfully. Can you try to re-run this action? https://github.com/rafaelmardojai/firefox-gnome-theme/actions/runs/9943414435

**Comment by FunctionalHacker** [comment]
If re-running it doesn't help I will have to investigate a bit more, but let's try that first.

**Comment by rafaelmardojai** [comment]
The problem seemed to be this one https://github.com/KSXGitHub/github-actions-deploy-aur/issues/39, and should be fixed by 179e73f. But I don't think I can re-run a "release" action with that fix without making a new release.

**Comment by FunctionalHacker** [comment]
Alright, didn't know that was the case for release actions. I have updated the AUR package manually now, next release should be okay by CI. Sorry for the noise
