### ISSUE TITLE
Private window indicator cut off

### ISSUE THREAD

**Issue by StellarSand** [rafaelmardojai/firefox-gnome-theme#816]
**Describe the bug**
In private window, the indicator icon is cut off in the headerbar.

**To Reproduce**

1. Open new private window
2. See cut off indicator (eye icon) in headerbar

**Expected behavior**

Indicator is not cut off.

**Screenshots**

| Dark | Light |
| -- | -- |
| ![dark_old](https://github.com/user-attachments/assets/5a2ffd80-4854-4ca9-97ef-9c84e1e257dc) | ![light_old](https://github.com/user-attachments/assets/d816aec7-c416-4fff-906a-6cde8c1d61c3) |

**Setup information**
 - OS: EndeavourOS
 - Installation method: via curl
 - Firefox version: 128.0
 - Theme version: v128
 - Optional features enabled: gnomeTheme.noThemedIcons (but even without this, the indicator is cut off)

**Additional context**

Submitted [PR#815](https://github.com/rafaelmardojai/firefox-gnome-theme/pull/815) to fix this.

**Comment by rafaelmardojai** [comment]
It's intentional, see GNOME Web:
![Captura desde 2024-07-17 18-22-26](https://github.com/user-attachments/assets/abf9c8f0-c75f-49d4-b03e-497ff41fc17c)

The only difference it's that the icons seems to have changed recently, we should update it.

**Comment by StellarSand** [comment]
Updated in PR#815

![private window](https://github.com/user-attachments/assets/321a408b-0bad-43bb-920c-eb197afc602c)

**Comment by rafaelmardojai** [comment]
@StellarSand it should be a bit bigger, if you see the GNOME Web screenshot, so it needs to be a bit cut off 😅.

**Comment by StellarSand** [comment]
Exactly like Gnome web now.

![private](https://github.com/user-attachments/assets/175a0ca9-695b-4ccd-8f65-d6bdc4354a0c)

**Comment by rafaelmardojai** [comment]
Merged. Thanks a lot for taking the time! Really appreciated.

**Comment by StellarSand** [comment]
Thanks for developing this theme. :)
