### ISSUE TITLE
[Feature] Adding instructions to use the AUR package with Flatpak

### ISSUE THREAD

**Issue by iro-miya** [rafaelmardojai/firefox-gnome-theme#817]
**Is your feature request related to a problem? Please describe.**

I figured out how to use the AUR package when Firefox is installed with Flatpak.

If I could, I would do a pull request to add the instructions to `INSTALL.md`, but that file seems to only be part of the AUR repository, so instead I'm opening an issue so you can add it.

**Describe the solution you'd like**

Make the following changes to `INSTALL.md`:

1. "Open directory" doesn't work on Flatpak. To install to Flatpak, user should manually cd to `~/.var/app/org.mozilla.firefox/.mozilla/firefox` and find the profile directory.

2. At some point, they need to run this command

```sh
sudo flatpak override org.mozilla.firefox --filesystem=host-os:ro
```

(replacing org.mozilla.firefox with whatever version of Firefox they use)

This is needed to expose `/usr` to Firefox so that it can get to the theme in `/usr/lib/firefox-gnome-theme`. This also exposes other system folders, but there isn't any other way to do it in Flatpak as far as I can tell. Folders are exposed as read-only to minimise permissions.

3. Finally the system folders will be mounted in `/run/host`, so when installing on Flatpak, step 5 needs to be this:

```sh
ln -s /run/host/usr/lib/firefox-gnome-theme firefox-gnome-theme
``` 

Otherwise, the installation procedure is the same.

I just did that and it totally works!

**Describe alternatives you've considered**
Maybe you could also make it so that `INSTALL.md` is copied from this repository so that changes can be made on GitHub in the future.

**Additional context**

**Comment by rafaelmardojai** [comment]
CC @FunctionalHacker

**Comment by rafaelmardojai** [comment]
Better please left a comment in the AUR package since I don't directly maintain the package.
