### ISSUE TITLE
Dropdowns borders getting darker every time you open it

### ISSUE THREAD

**Issue by ubluish** [rafaelmardojai/firefox-gnome-theme#82]
Distribution: Fedora Silverblue 31
GNOME: 3.34
GTK: 3.24.11
Theme Version: Latest git
_____________________
Dropdowns borders getting darker every time you open it as S/S shows:
**1** 
![1](https://user-images.githubusercontent.com/21042432/64931009-c9156680-d835-11e9-870b-456970a176d1.png) 
**2**
![2](https://user-images.githubusercontent.com/21042432/64931011-ce72b100-d835-11e9-8da1-809be60ddc68.png)
**3**
![3](https://user-images.githubusercontent.com/21042432/64931017-d599bf00-d835-11e9-9e62-e8f32c9c50c1.png)

**Comment by lionirdeadman** [comment]
This is on Wayland, isn't it? If so, it's a known bug we have no control over IIRC.

**Comment by ubluish** [comment]
yes, it's wayland

**Comment by rafaelmardojai** [comment]
#23
