### ISSUE TITLE
[Feature] Request for the script for MS windows users

### ISSUE THREAD

**Issue by asifahmad134** [rafaelmardojai/firefox-gnome-theme#825]
Please also include installation method for all users on MS Windows 11 for firefox and librefox

**Comment by rafaelmardojai** [comment]
The theme does have some CSS fixes for Windows, but I don't plan to officially support it.

**Comment by asifahmad134** [comment]
Hi!
Thanks for this awesome theme. And, I am very sorry for late reply

So, I think that recent UI changes in firefox and chrome are to
accommodate touchscreen users and without touchscreen users on the desktop
and laptops. Instead of putting efforts into making a separate UI for these
scenarios, they just ruined the UI.

Your awesome theme just fixes it all. I have applied the fix by using git
bash in windows 11, screenshots are enclosed. I think Win10/11 users will
benefit all. Just look at these enclosed screenshots. By making a script
for windows users will benefit them greatly. Also, as i used librefox, so i
have to do all the manual installation.
Best Regards

*Asif Ahmad*

**Comment by rafaelmardojai** [comment]
@asifahmad134 I can get that, but sadly I have limited time for this project and I don't use Windows nor is my area of expertise. But I probably would accept contributions in that direction.

**Comment by asifahmad134** [comment]
Ok, thanks for the reply.
Best Regards

*Asif Ahmad*
Ufone & WhatsApp:  +92 334 970 4081
