### ISSUE TITLE
Wrong Icons in Ubuntu

### ISSUE THREAD

**Issue by dasmaetthes** [rafaelmardojai/firefox-gnome-theme#827]
On default icons for close, minimize/maximize look bold ant not like Ubuntu Yaru ones.

![grafik](https://github.com/user-attachments/assets/a0f6e384-cd29-493d-8808-582db85652d5)

When set "gnomeTheme.systemIcons" to true, they have the style of Yaru Theme, but they have wrong color, some light gray and not dark/black.

![grafik](https://github.com/user-attachments/assets/fd7843c8-7e13-45f3-944b-5706470e2c1d)

That's how they should look like:
![grafik](https://github.com/user-attachments/assets/d71358b4-e1fa-4422-8a6b-b8afe614d1bc)

**Comment by emansom** [comment]
Looks like it defaults to the unfocused variants of the system icons?

**Comment by dasmaetthes** [comment]
Yes when other Windows's are unfocused the Icons look same.

**Comment by rafaelmardojai** [comment]
The readme makes clear that `gnomeTheme.systemIcons` has a color bug: https://github.com/rafaelmardojai/firefox-gnome-theme?tab=readme-ov-file#icons-color-broken-with-system-icons.

You can tweak the CSS to get the right color for you.
