### ISSUE TITLE
[Feature] Support zen-browser

### ISSUE THREAD

**Issue by sezaru** [rafaelmardojai/firefox-gnome-theme#829]
Zen browser is a new firefox-based browser with some pretty cool features like a vertical tab, privacy focus, workspaces, etc.

I was wondering if there is some plan to make this theme support Zen browser too.

**Comment by ruizlenato** [comment]
I think it would be nice if it looks like [ouch](https://git.sr.ht/~shrimple/ouch)

![image](https://github.com/user-attachments/assets/0b1d1d6e-31c5-46b7-8ab3-8f16157bfe56)

**Comment by rafaelmardojai** [comment]
Sadly I lack time and motivation for this. Also maintaining support for multiple browsers in a single code base sounds like a maintenance nightmare.

If someone wants to work on this I would recommend forking this theme patching on top.

**Comment by rappo** [comment]
FYI @ruizlenato @sezaru, installing with Zen support is as straightforward as 
`./scripts/install.sh -f ~/.zen`
