### ISSUE TITLE
Hamburger menu stops showing up

### ISSUE THREAD

**Issue by javiermon** [rafaelmardojai/firefox-gnome-theme#83]
Hi

Using gnome 3.34 and Firefox 69 under Wayland. If I open Firefox (window not maximized) click on the hamburger menu, resize the window and click again, the hamburger menu is not showing up.

Thanks!

**Comment by javiermon** [comment]
![bug](https://user-images.githubusercontent.com/1457038/65368608-43f4cd80-dbf8-11e9-8fc7-1d49d3518266.png)

**Comment by rafaelmardojai** [comment]
I can't solve/investigate Wayland related issues since i don't use it any more. 

Someone can confirm if it doesn't happen in default Firefox?

**Comment by javiermon** [comment]
It doesn't happen in the Gnome Xorg session, I will try to verify this on default Firefox running under Wayland.

**Comment by rafaelmardojai** [comment]
Any news?

**Comment by javiermon** [comment]
Sorry for the late response.

In default wayland firefox it doesn't happen, but the hamburguer menu is not placed properly under it's button when I go full screen. Maybe it's related to that. That seems like a bug in firefox wayland support.
![Screenshot from 2019-11-02 15-53-45](https://user-images.githubusercontent.com/1457038/68077915-a3aece80-fd89-11e9-8f51-8c0faa2dc10a.png)
![Screenshot from 2019-11-02 15-53-59](https://user-images.githubusercontent.com/1457038/68077916-a3aece80-fd89-11e9-8467-1788bc5bab60.png)

**Comment by maymage** [comment]
Seems to have been fixed under firefox 71.0

* Hamburger Menu works
* Overflow Menu works incl. opening extensions

**Comment by rafaelmardojai** [comment]
@maymage have you tested it on wayland?

**Comment by maymage** [comment]
@rafaelmardojai 
Yeah, sure. This is

Fedora 31
Mutter 3.34.1
Gnome-Shell 3.34.1
Firefox 71.0

on wayland.

**Comment by rafaelmardojai** [comment]
Nice, so i'm closing this.
