### ISSUE TITLE
a lot of space between bookmarks

### ISSUE THREAD

**Issue by duckaleuze** [rafaelmardojai/firefox-gnome-theme#833]
theme: 

![img-2024-09-28-18-47-50](https://github.com/user-attachments/assets/5004bac4-97a2-4465-9eff-b348174c08a8)

with no theme:

![img-2024-09-28-18-48-07](https://github.com/user-attachments/assets/281a95bf-ab9f-4255-aefb-237da69971d7)

see how there is much more space there, I feel it's much more useful and also aesthetic. I don't know anything about CSS or programming, but this is more of an opinion than a 'bug report' to know if this will be fixed at some point, as it's a bit uncomfortable since I'm really used to manage my browsing through bookmarks. btw great theme I'm loving it so far!

**Comment by rafaelmardojai** [comment]
Duplicated of #810
