### ISSUE TITLE
Display tab preview in the center of the tab

### ISSUE THREAD

**Issue by TheRsKing** [rafaelmardojai/firefox-gnome-theme#834]
**Is your feature request related to a problem? Please describe.**
no problem, just aesthetics

**Describe the solution you'd like**
it would be nicer if the tab preview was displayed in the center of each tab instead of always on the far left

**Additional context**
![image](https://github.com/user-attachments/assets/4ce666d4-d016-4ec4-83e1-704957bae6a7)

**Comment by rafaelmardojai** [comment]
Sadly I don't think this is possible to implement with CSS.

Panels position is controlled by Firefox UI code, and they handle edge positioning correctly so they don't get out of the window. Also if we try to reposition the preview with CSS we don't have any context like the tab width to do any calculations.

**Comment by TheRsKing** [comment]
Thanks anyways ;)
