### ISSUE TITLE
ff v131

### ISSUE THREAD

**Issue by iaacornus** [rafaelmardojai/firefox-gnome-theme#835]
there's quite a lot of new features, so the theme is quite broken

**Comment by rien333** [comment]
Works pretty well here, is there any specific examples?

**Comment by iaacornus** [comment]
well, its just polishness

![image](https://github.com/user-attachments/assets/b29deef1-9b71-42bc-8d6b-c3a90c907a42)

here, for example. the size of window buttons are larger

**Comment by iaacornus** [comment]
although other than these icons all seems to be fine

**Comment by iaacornus** [comment]
and yes, the zoom, before the update my zoom works perfectly fine on 120%, but after the update it is very big

**Comment by rafaelmardojai** [comment]
@iaacornus I can't reproduce the specific problems you're describing.  Your icons look blurry but that's not the case here.

Can you give more info about your sistem/firefox settings?

**Comment by iaacornus** [comment]
> @iaacornus I can't reproduce the specific problems you're describing.  Your icons look blurry but that's not the case here.
> 
> 
> 
> Can you give more info about your sistem/firefox settings?

yeah sorry about that, it seems like it was firefox's problem, it was fixed by my previous comment. sorry for bothering, anyway thank you for great work!
