### ISSUE TITLE
Firefox 132 Search Text Contrast Issue

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#836]
In the newest Firefox beta the search text within the titlebar that represents your search engine is too faded and doesn't contrast properly.
![Screenshot From 2024-10-01 15-56-16](https://github.com/user-attachments/assets/eae232cb-9833-42d7-a7b0-4e6737cad553)

**Comment by rafaelmardojai** [comment]
Fixed in `beta` branch.

I didn't increase it like it was before because noticed that the color was brighter than libadwaita's, but should have more contrast than mozilla's.
