### ISSUE TITLE
Pinned tabs not displayed properly on Firefox 131

### ISSUE THREAD

**Issue by elmagio** [rafaelmardojai/firefox-gnome-theme#838]
**Describe the bug**
The highlighted pinned tab seems to be cut off with one side not having properly rounded corners.

**To Reproduce**
1. Pin a tab
2. Highlight one of the pinned tabs
3. It appears cut off on one side

**Expected behavior**
The highlighted pinned tab should be symmetrical with rounded corners on all sides

**Screenshots**
![image](https://github.com/user-attachments/assets/59816e5c-70df-4a06-8367-d0af32eed93a)

**Setup information**
 - OS: Ubuntu 24.04
 - Installation method: Official DEB repo
 - Firefox version: 131
 - Theme version: v129
 - Optional features enabled: gnomeTheme.normalWidthTabs, gnomeTheme.swapTabClose, gnomeTheme.tabsAsHeaderbar

**Comment by rafaelmardojai** [comment]
Duplicated of #832, already fixed on master branch.

Will keep this open until I make a release.
