### ISSUE TITLE
Tab separator changes width when the last tab is created or closed

### ISSUE THREAD

**Issue by jianglai** [rafaelmardojai/firefox-gnome-theme#839]
**Describe the bug**
The vertical lines between tabs have a slightly smaller width, than then one that separates the last tab and the `+` new tab button.

As a result, when a new tab is created, the last tab's width suddenly increases (as the separator between it and the `+` button shrinks to become the separator between tabs). Similarly, when closing the last tab, separator grow in width, and the second-to-last tab suddenly shrinks in size as it becomes the last tab.

The effect is pretty subtle, but hopefully the screen recording that I provided should explain it.

I only tested this when using the stock Firefox layout, where tabs are on top and of equal size, and the `+` button is next to the last open tab.

**To Reproduce**
Click on the `+` button to create a new tab.
Or
Have at least two tabs open, and close the last tab.

**Expected behavior**
When creating a new tab, the last open tab's width doesn't change.
And
When closing the last tab, the second-to-last tab's width doesn't change.

**Screenshots**

https://github.com/user-attachments/assets/f4a6d6c9-e8b0-41db-b4f8-0ae880f15302

https://github.com/user-attachments/assets/140b3e36-c062-483b-b068-c79f9cd937bc

**Setup information**
 - OS: Arch
 - Installation method: AUR
 - Firefox version: 131.0
 - Theme version: v131
 - Optional features enabled: `gnomeTheme.normalWidthTabs`, `gnomeTheme.tabsAsHeaderbar`

**Comment by rafaelmardojai** [comment]
Hosnetly I can't see any separator.

**Comment by rafaelmardojai** [comment]
Ok, I think I now understand the issue 😅, the fix should be easy.

**Comment by jianglai** [comment]
Thanks! That did fix the issue. However I noticed something else quite subtle (but visually annoying), which I'm not sure is present or not before the fix.

When I have multiple tab open, closing the last tab works as expected, but closing one of the tabs in the middle cause the first tab's width to change. For example, in the video below, closing the third tab causes the first tab's width to increase a bit, and closing the (now) third tab again causes the first tab's width to decrease a bit.

https://github.com/user-attachments/assets/e0f3e06e-d216-48bb-93ff-b4b252ccc9d3

**Comment by rafaelmardojai** [comment]
Yes, looks like the Firefox tab closing mechanic doesn't expects the tab having `box-sizing: content-box;` for its calculations.

**Comment by jianglai** [comment]
Is there an easy fix for this? If not, it seems like the old behavior is better.

**Comment by rafaelmardojai** [comment]
> Is there an easy fix for this? If not, it seems like the old behavior is better.

Tried a few things but looks like is not posible, might be related to problems like #174 that happen when you mess with the tabs sizing. Will revert the previous fix.
