### ISSUE TITLE
[question] Packaging in multiuser environment

### ISSUE THREAD

**Issue by Chrysostomus** [rafaelmardojai/firefox-gnome-theme#84]
Hi!

I'd like to package your theme and use it by default in some Manjaro linux editions. However, I'm wondering if there is any possibility of installing it in the system location so that it would be automatically applied for new users. It would be simple enough to apply the theme with a autostart script, but I would prefer not to touch users $HOME with the package manager when the theme needs to be kept up to date.

So, my question is: is there a way to apply this theme on system level instead of user level? I realize that this is my problem as a packager and not your issue as developer, but I figured it would not hurt to ask.

**Comment by rafaelmardojai** [comment]
To mi knowledge, there's no way to system wide set `userChrome.css`.

**Comment by Chrysostomus** [comment]
Thank you! I think I'll have to use a symlink to a system folder then. Thanks for your time!
