### ISSUE TITLE
[BUG] Tab alignments are broken in right-to-left languages

### ISSUE THREAD

**Issue by largestgithubuseronearth** [rafaelmardojai/firefox-gnome-theme#847]
**Describe the bug**
When using right-to-left languages and the FGT, the Tab titles are too far to the left side of the tab width and the spinner widget is not visible. Additionally, the "refresh" blue swell that comes over a tab when it's finished loading is also misaligned.

**To Reproduce**

1. Have FGT installed
2. Open Firefox and go into Settings. In General, go to Languages, click the dropdown and "Search for more languages".
3. Click "Select Language to Add" and select any right-to-left language, then click Add. In this example, I'm using Persian ( فارسی ) but I tried a couple others and got the same issues.
4. Restart Firefox to see the error in the Tabs.

**Expected behavior**
When using a right-to-left language, the Tab titles would remain center-aligned, and the Tab loading spinner would be visible. 

**Video example**

https://github.com/user-attachments/assets/059f5dc2-abbd-4241-bd26-edfc5a9e91c8

**Setup information**

 - OS: Arch, Fedora 40
 - Installation method: Package manager, Flatpak
 - Firefox version: v131.0.3
 - Theme tag version: v131

**Additional context**
[The original issue I got for this](https://github.com/largestgithubuseronearth/addwater/issues/23)

**Comment by rafaelmardojai** [comment]
Yeah, I have never tested rtl langs and never cared about using the writing mode/directionality aware spacing/alignment CSS properties. In newer code I do try to used them, but for old code it may stay like that until I find some time.
