### ISSUE TITLE
Theme broken in Fiefox 71

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/firefox-gnome-theme#85]
Thanks Firefox 😒
![Captura de pantalla de 2019-10-03 09-15-13](https://user-images.githubusercontent.com/6210397/66138696-a9679780-e5c4-11e9-9f82-66f00a5e86cb.png)

**Comment by xcffl** [comment]
Basically it's for the introduction of Mega Bar, which merges the address bar and the dropdown menu. It might be a good idea to look better, but it seems not to be good-looking so far.

**Comment by rafaelmardojai** [comment]
[e0bcf20], [58083f2], and [fea172d] should fix the Mega Bar issues.

With [16120de] I'm experimenting attaching URL bar and results, similar to Mega Bar:
![Captura de pantalla de 2019-10-04 08-20-40](https://user-images.githubusercontent.com/6210397/66211330-7a632b80-e681-11e9-9c96-220c1913c6d2.png)
What are your thoughts?

**Comment by xcffl** [comment]
I think the Mega bar's idea is good (which means the blue border will highlight both the bar and the dropdown, the background color are merged, and they have some elevation).

It's just unclear weather enlarge the bar yields a nice experience.

**Comment by rafaelmardojai** [comment]
Yeah, I'm just trying to make it look GNOMISH.
Current master:
![Captura de pantalla de 2019-10-04 11-42-15](https://user-images.githubusercontent.com/6210397/66224837-80b2d100-e69c-11e9-8831-25c2ba301a64.png)

**Comment by rafaelmardojai** [comment]
I think i will keep it like that.
This only affects FF71 Mega Bar, so it will keep looking like GNOME Web in older versions.

**Comment by rafaelmardojai** [comment]
Broken again... I won't fix it until Firefox 71 reaches beta.

**Comment by rafaelmardojai** [comment]
Aside from  #91 and https://github.com/rafaelmardojai/firefox-gnome-theme/issues/39#issuecomment-549086822, this theme is usable in Firefox 71+
