### ISSUE TITLE
Mute tab icon is too large and seems off

### ISSUE THREAD

**Issue by gpolydoros** [rafaelmardojai/firefox-gnome-theme#855]
**Describe the bug**
The mute tab icon is too large and seems a bit off compared to the rest of the theme.

**To Reproduce**
1. Open a website that has sound
2. See the tab header

**Expected behavior**
The icon should match the rest of the theme.

**Screenshots**
![Screenshot From 2024-11-01 15-47-47](https://github.com/user-attachments/assets/9c6145fe-2d1a-4de4-909b-b16a091d9eea)

**Setup information**
 - OS: Fedora 41
 - Installation method: RPM
 - Firefox version: 132.0
 - Theme version: master
 - Optional features enabled: -

**Additional context**

**Comment by rafaelmardojai** [comment]
Duplicated of #837, already fixed in master branch.
