### ISSUE TITLE
[Feature] GNOME 47 Color Theme Support

### ISSUE THREAD

**Issue by CodedIsTaken** [rafaelmardojai/firefox-gnome-theme#856]
Hello, With GNOME 47's Features To theme your system and apps around a color, I'm requesting you support this gnome 47 color theming feature, additionally gnome web supports color theming too.

**Comment by rafaelmardojai** [comment]
For now you can just change the `--gnome-accent` CSS var in the theme.

**Comment by CodedIsTaken** [comment]
i forgot, i should've said accent color.
