### ISSUE TITLE
URL bar extends underneath icons

### ISSUE THREAD

**Issue by Codethulhu03** [rafaelmardojai/firefox-gnome-theme#858]
**Describe the bug**
The URL bar takes up the full width of the top bar and is overlapped by icons when focussed.

**To Reproduce**
Focus the URL bar.

**Expected behavior**
The URL bar might extend its width but not intersect with other elements.

**Setup information**
 - OS: OpenSuse Tumbleweed with Hyprland
 - Installation method: Auto-Install script
 - Firefox version: 133 (Developer Edition)
 - Theme version: v132,master
 - Optional features enabled: none (default basic installation)

**Additional context**
I can fix this behaviour by commenting the `#urlbar[breakout][breakout-extend]` section in `theme/parts/urlbar.css`

**Comment by rafaelmardojai** [comment]
Duplicated of #849. Already fixed in `beta` branch.
