### ISSUE TITLE
Audio playing icon ovberlap 

### ISSUE THREAD

**Issue by tanaybhomia** [rafaelmardojai/firefox-gnome-theme#859]
**Describe the bug**
The theme used to use the original gnome icon for youtube or other pages when playing media but I think after I updated to Firefox 131 their is a weird icon which overlaps the tab.  

**To Reproduce**
Just play anything on youtube or other websites which play a media.

**Expected behavior**
The original gnome base icon should be visible
**Screenshots**
The icon overlap
![image](https://github.com/user-attachments/assets/f969234f-1598-457d-beff-327dc2ed4599)
My firefox version
![image](https://github.com/user-attachments/assets/68baf8ee-ccc8-4338-be4d-a4420e0a4c7f)
My Extensions 
![image](https://github.com/user-attachments/assets/aea5ad98-5590-4919-b52a-0b0885d3d1d1)
Enabled Features 
![Screenshot 2024-11-07 at 18-19-34 Advanced Preferences](https://github.com/user-attachments/assets/0070e261-a471-4a56-b15f-1724e4ccf6ad)

**Setup information**
 - OS: Fedora 41
 - Installation method: The default installed version of firefox
 - Firefox version: 132
 - Theme version: master
 - Optional features enabled:

**Comment by rafaelmardojai** [comment]
Duplicated of #837.
