### ISSUE TITLE
[Feature] Could hideSingleTab override allTabsButton and hide the bar?

### ISSUE THREAD

**Issue by JaneSmith** [rafaelmardojai/firefox-gnome-theme#862]
Not sure if this counts as a bug or feature request. I'll file it as a feature request, since technically everything is working as advertised, but not really in an ideal way.

**Is your feature request related to a problem? Please describe.**

* hideSingleTab makes the entire tab bar disappear when only one tab exists. Great.
* allTabsButton makes the List All Tabs button appear. Great. This makes it so much easier to find tabs when there are more than a few open.
* But when both hideSingleTab and allTabsButton are enabled, and only one tab is open, you get a blank tab bar with the List All Tabs button on the side. The List All Tabs button is pointless as there's only one tab and you're already looking at it. The blank tab bar wastes space on the screen.

**Describe the solution you'd like**

I would like it so that if hideSingleTab is enabled, then allTabsButton will only show the List All Tabs button if there is more than one tab. If there is only one tab, then the entire tab bar (including the List All Tabs button) should disappear.

**Additional context**

Thanks for your hard work on this. I've been using this theme for so long, and it's such a fantastic addition for GNOME users.

**Comment by JaneSmith** [comment]
Thank you very much for implementing this, but I think there's a bug with it.

I'm using the latest version of firefox-gnome-theme as of this post, with the latest Firefox (133) from Flathub.

If I open a new window, the tab bar disappears as expected. If I open a second tab, the tab bar reappears. Now:

* If I close the right-most tab, the tab bar disappears as expected.
* But if I instead close the left-most tab, the tab bar stays visible.

So it seems the tab bar doesn't always get hidden, depending on the order in which tabs are closed.

**Comment by rafaelmardojai** [comment]
@JaneSmith Looks like some Firefox bug not updating some CSS state. If you resize the window to some smaller size or do a dummy change in the browser chrome inspector the tabsbar will collapse just fine.

Probably a side effect of the complex selector needed for this to work, because Firefox doesn't set any attribute in the tabsbar to indicate "only one tab visible".
