### ISSUE TITLE
Minimize, Maximize, Close Buttons are Gone, Search Bar when used expands more than it should.

### ISSUE THREAD

**Issue by astoko** [rafaelmardojai/firefox-gnome-theme#866]
**Describe the bug**
Minimize, Maximize, Close Buttons after installing the theme it bugs out and they are not visible.
Search Bar while in not use its all fine and good but when its clicked on/used it gets buggy and expands further than it should as it overlays some icons and its totally not intended behavior. 

**To Reproduce**
1. Open The Browser (First Screenshot)
2. Use the Search (Second Screenshot)

**Expected behavior**
1. To see Minimize, Maximize, Close Buttons and ability to use them.
2. Search to Stay in place while using it.

**Screenshots**
1.
![image](https://github.com/user-attachments/assets/ef2876f2-e61d-4dc5-b0a3-76fe2e1c7d9f)
2.
![image](https://github.com/user-attachments/assets/7b10d163-cd22-4776-be99-684f4b48ab2e) 

**Setup information**
 - OS: Arch Linux x86_64 / Kernel: Linux 6.12.1-arch1-1
 - Installation method: AUR
 - Firefox version: 133.0
 - Theme version: firefox-gnome-theme-132-1 (From AUR)
 - Optional features enabled: None? (Not sure to check that.. but i did check atleast about:config and i didnt see anything changed so..)

**Additional context**
I tried to refresh and install again everything and yet again it failed so i come to here to see if its just me or its an well known bug.. gotta love cutting edge latest version packages bugging out qwq (nw its all good, i just like a lot this theme hehe xD)

**Comment by rafaelmardojai** [comment]
Duplicated of #849. Already on master branch.

**Comment by astoko** [comment]
Oh, Thanks i didnt notice! sowwy!! :3 :heart:

**Comment by rafaelmardojai** [comment]
Let's keep it open until I do a release so people don't open more duplicates.

**Comment by bertini97** [comment]
On master my close button is gone. Anybody else?

**Comment by astoko** [comment]
If you want to keep using the theme and doing your work i suggesting **for now** use the menu bar so you can use the buttons.. thought its relatively pretty clunky looking and god its thicc boy but for now that is all we can do :P
![image](https://github.com/user-attachments/assets/6a27cb1d-c581-49ba-b834-2200e1ffda4e)
Just Right click on an empty space on the bar and click from the popup menu "Menu Bar" and its should appear fine!

**Comment by rafaelmardojai** [comment]
v133 released.

**Comment by astoko** [comment]
![image](https://github.com/user-attachments/assets/784fb791-f6ce-4664-ba26-65bf61ad3d57)
Yeeep its totally working also *t h e m e  c o l o r* YIPPEE!!
