### ISSUE TITLE
Address bar is shrinking when clicked

### ISSUE THREAD

**Issue by danielbmeireles** [rafaelmardojai/firefox-gnome-theme#868]
**Describe the bug**
The address bar is shrinking when clicked:

![image](https://github.com/user-attachments/assets/e96537dd-1c06-41fb-b833-b3b4d0ff63ca)

**Setup information**
 - OS: Fedora Workstation 41
 - Installation method: RPM
 - Firefox version: 132.0.1 (64-bit)
 - Theme version: master
 - Optional features enabled: no

**Additional context**
```
Installed packages
Name            : firefox
Epoch           : 0
Version         : 132.0.1
Release         : 2.fc41
Architecture    : x86_64
Installed size  : 226.9 MiB
Source          : firefox-132.0.1-2.fc41.src.rpm
From repository : updates
Summary         : Mozilla Firefox Web browser
URL             : https://www.mozilla.org/firefox/
License         : LicenseRef-Callaway-MPLv1.1 OR GPL-2.0-or-later OR LicenseRef-Callaway-LGPLv2+
Description     : Mozilla Firefox is an open-source web browser, designed for standards
                : compliance, performance and portability.
Vendor          : Fedora Project
```

**Comment by rafaelmardojai** [comment]
The `master` branch targeting Firefox 133. You need to update your Firefox or use the `v132` tag.
