### ISSUE TITLE
Search in url bar shrinks

### ISSUE THREAD

**Issue by selliot-linux** [rafaelmardojai/firefox-gnome-theme#869]
When searching in url bar the menu dropdown shrinks

**To Reproduce**
Install latest version in Firefox 132.0.1 in Fedora 41
**Expected behavior**
The search should remain the same size of the url bar
**Screenshots**
![Screenshot From 2024-11-28 18-18-48](https://github.com/user-attachments/assets/e753c82a-b11b-40b9-9b59-749bacf45ce1)
![Screenshot From 2024-11-28 18-19-12](https://github.com/user-attachments/assets/40e72685-cfa3-4474-8da2-b560dff18f34)

**Setup information**
 - OS: Fedora 41
 - Installation method: Curl method
 - Firefox version: 132.0.1
 - Theme version: 133

**Comment by rafaelmardojai** [comment]
Duplicated of #868. Again, the `master` branch is targeting Firefox 133. You need to update your Firefox or use the v132 tag.
