### ISSUE TITLE
Accent Colour Feature Not Working (Flatpak)

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#871]
I saw in the release notes that as of the new version of this theme it supports gnome accent colours but it isn't working for me at all with the Flatpak version of Firefox. I change the gnome accent theme and and the Firefox theme colour stays blue.

Am I missing something or is this a Flatpak sandbox related bug?

**Comment by rafaelmardojai** [comment]
It should just work if you're using Firefox 133. The theme only does calculations from the `AccentColor` CSS system-color provided by Firefox. 

I use the Flatpak version too and works fine, so not sure what could be not allowing Firefox get the accent color from the settings portal... Maybe an outdated portal version? But I guess that should also affect libadwaita apps, so no idea.

**Comment by KUPOinyourWINDOW** [comment]
I'm using Firefox 134 beta 3, and my actual distro is current Fedora 41 so everything should be up to date. I'm not sure if anything has changed in the new Firefox version that could be causing this.

I'll do a clean install of the theme and then edit this to see if that fixes it

**Comment by rafaelmardojai** [comment]
Could you test if it's working fine with Firefox 133 from flathub?

**Comment by KUPOinyourWINDOW** [comment]
![Accent Colour Firefox](https://github.com/user-attachments/assets/438ba500-138a-4476-a5bf-d28a39c824e9)
it isn't working in that version either for me

**Comment by rafaelmardojai** [comment]
Hmm, then I don't know what can be the problem. I'm also in Fedora 41 (Silverblue) and everything works.

Yesterday someone mentioned the same problem in the Matrix channel, so you're not alone.

I guess that if you enter here https://www.w3.org/Style/CSS/Test/CSS3/Color/current/html4/t040501-system-colors-a.htm, you get a blue background in ` This should have the text color and background color of highlighted items, if the operating system provides such colors` right?, it should be teal if Firefox is doing it's thing right.

**Comment by KUPOinyourWINDOW** [comment]
yep its blue on that site

**Comment by CleoMenezesJr** [comment]
Are you guys using [adw-gtk3](https://github.com/lassekongo83/adw-gtk3)? It overrides the accent colors

**Comment by KUPOinyourWINDOW** [comment]
> Are you guys using [adw-gtk3](https://github.com/lassekongo83/adw-gtk3)? It hardcode the accent colors overrides the selected one.

I am! Is there a way to resolve it 'cause I would like to not lose that theme (I can report it as an issue there too)

**Comment by CleoMenezesJr** [comment]
Closing as completed and change label to invalid since it's not about FGT.

**Comment by CleoMenezesJr** [comment]
>  ...I'd like to not live without the consistency that theme offers though so I'll report a bug report over there

Btw, I think this will be useful: https://github.com/lassekongo83/adw-gtk3/commit/a88950d8d66308606a6cbb0cfece91376213ad2d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L71

**Comment by gwuen** [comment]
There's also a Gnome extension which does the same thing automatically, I highly recommend it: https://github.com/NiffirgkcaJ/adw-gtk3-colorizer
