### ISSUE TITLE
Search bar is broken after recent Firefox update

### ISSUE THREAD

**Issue by 27228y** [rafaelmardojai/firefox-gnome-theme#872]
# After recent Firefox update the search bar overlaps the ui.

The close button is also missing.
The same thing happened to me on a different PC.

![Screenshot From 2024-12-01 17-40-21](https://github.com/user-attachments/assets/dddec9ed-550b-4aa3-b12c-cac9ed31e69c)

**Comment by rafaelmardojai** [comment]
Duplicated of  #849. Please update the theme.
