### ISSUE TITLE
Url bar broke after the update 

### ISSUE THREAD

**Issue by tanaybhomia** [rafaelmardojai/firefox-gnome-theme#873]
**Describe the bug**
- When Searching something from the URL it breaks and spans the whole width of the window 
![image](https://github.com/user-attachments/assets/b4013b4c-e250-45b2-8272-365f536a0174)

**Setup information**
 - OS: Fedora 
 - Installation method: Default installed version
 - Firefox version: 133
 - Theme version: Master

**Comment by EliDev05** [comment]
I have the same bug


**Setup information**

-     OS: Mint (with GNOME)
-     Installation method: Default installed version
-     Firefox version: 133
-     Theme version: Master

**Comment by lapor-kris** [comment]
Same here.
Setup information

    OS: Fedora
    Installation method: Via Addwater
    Firefox version: 133
    Theme version: Master

**Comment by rafaelmardojai** [comment]
This looks like a duplicated of #849.

Please double check you're in the latest version of the theme, you can check the version in the left bottom corner of the "Customize toolbar" view:

![Captura desde 2024-12-02 07-06-00](https://github.com/user-attachments/assets/643c24cd-38a2-4be4-9529-911e4e68a115)

**Comment by lapor-kris** [comment]
You are right. I was on v131. I forgot to restart the Firefox :facepalm: 
Now, everything works great. Thanks
