### ISSUE TITLE
Thick grey line under header bar when tabs are hidden

### ISSUE THREAD

**Issue by afraidofmusic** [rafaelmardojai/firefox-gnome-theme#88]
Using Firefox 70.0 in Arch Linux. There is a thick grey line under headerbar.

Firefox focused
![Screenshot from 2019-10-29 14-59-21](https://user-images.githubusercontent.com/25895258/67765583-8ca46f80-fa5d-11e9-9d41-e78c552e4f9a.png)
Firefox unfocused, Epiphany focused
![Screenshot from 2019-10-29 14-59-30](https://user-images.githubusercontent.com/25895258/67765605-962dd780-fa5d-11e9-87fd-fa6597f6d6b6.png)

**Comment by rafaelmardojai** [comment]
Yeah, that issue is commented in the code: https://github.com/rafaelmardojai/firefox-gnome-theme/blob/44a7b7bb9016421daaa6896de1cc4d1375ce7720/theme/hide-single-tab.css#L7

I will try to find a work around.

**Comment by tauin** [comment]
would 
`#navigator-toolbox { border: none !important;}` 
work?

**Comment by rafaelmardojai** [comment]
> would this work?

Not really, `#navigator-toolbox` already has no border. 

What we need is to hide the border from `#TabsToolbar` when there's only one tab. But currently the only way to detect that is from the same tab with `tab:only-of-type`.
