### ISSUE TITLE
New tab button highlights improperly on hover with tabsAsHeaderbar enabled

### ISSUE THREAD

**Issue by elmagio** [rafaelmardojai/firefox-gnome-theme#882]
**Describe the bug**

A small visual bug where the highlight on the new tab button takes up the entire height of the headerbar when gnomeTheme.tabsAsHeaderbar is enabled, which makes asymmetrical with the height of the tabs. See screenshots for example.

**Screenshots**

With tabsAsHeaderbar:

![Capture d’écran du 2024-12-17 14-26-52](https://github.com/user-attachments/assets/b03bba9e-d5a2-4a61-b41b-53bd1c35f06f)

Without:

![image](https://github.com/user-attachments/assets/7d427059-3e7c-44e6-9317-e3ff78368a93)

**Setup information**
 - OS: Ubuntu 24.10
 - Installation method: Official .deb
 - Firefox version: 133.0.3
 - Theme version: 133.1
 - Optional features enabled: gnomeTheme.normalWidthTabs, gnomeTheme.swapTabClose, gnomeTheme.tabsAsHeaderbar

**Comment by elmagio** [comment]
Now that I look at it from a bit closer it also seems like the new tab cross isn't aligned with the tab close button, still only with tabsAsHeaderbar.

**Comment by rafaelmardojai** [comment]
Thanks, seems like a regression of aa9b670.

**Comment by elmagio** [comment]
Nice, thanks for the quick fix !
