### ISSUE TITLE
Search Bar Shrinks when entering anything

### ISSUE THREAD

**Issue by klendite** [rafaelmardojai/firefox-gnome-theme#884]
**Describe the bug**

**To Reproduce**
Install theme via Flatpak on Firefox ESR
use the address/search bar

**Expected behavior**
Searchbar should not change size when entering anything

**Screenshots**
Before:
![image](https://github.com/user-attachments/assets/39e20826-f7ee-4c85-86e4-a5b03be4bcb8)
After:
![image](https://github.com/user-attachments/assets/b08c83f0-1651-452a-bb3f-7db881f383c0)

**Setup information**
 - OS: Fedora 41 Workstation
 - Installation method:Flatpak
 - Firefox version: 128.5.2esr (64-bit)
 - Theme version: beta
 - Optional features enabled: 
![image](https://github.com/user-attachments/assets/9a50c59b-36b5-4500-aa76-117367da8e3e)

**Comment by rafaelmardojai** [comment]
The `beta` branch targets the current Firefox Beta version, and the `master` branch the current stable version (133), if you're using `128 ESR` you must use the proper git tag for that version, `v128` in your case (I don't think AddWatter supports that at the moment so you'll need to install using the scripts).

**Comment by klendite** [comment]
Just tried, issue still persists for the v128 git tag.

**Comment by rafaelmardojai** [comment]
Hmm, that's weird. When you go to "Customize toolbar" in the navbar context menu, you can read `v128` in the bottom left corner?

**Comment by klendite** [comment]
ah it doesn't seems like it can't find the user.js file

![image](https://github.com/user-attachments/assets/d214e809-8449-4d9c-b98c-47036d7e7e23)

**Comment by klendite** [comment]
Update: Just did a manual install, no script, works
