### ISSUE TITLE
gnomeTheme.tabAlignLeft doesn't do anything

### ISSUE THREAD

**Issue by klendite** [rafaelmardojai/firefox-gnome-theme#885]
**Describe the bug**
It SHOULD cause the favicon and title of tabs align to the left, not middle. Meanwhile, no matter what I do it doesn't change anything

**To Reproduce**
1. Install Git Branch 128 onto Firefox ESR
2. Start Browsing
3.  Sometimes it is aligned to the right, or middle

**Expected behavior**
Something like this: 
![image](https://github.com/user-attachments/assets/6842bd08-c182-4df7-a209-45155277ec43)
![image](https://github.com/user-attachments/assets/af71e74f-156c-4294-953a-8e558e38be53)

But this happens:
![image](https://github.com/user-attachments/assets/7e05aa05-a6af-464a-841b-b62b972eb64b)

**Screenshots**
![image](https://github.com/user-attachments/assets/39c893d8-c459-42ee-954b-d3d8cdd045ec)
![image](https://github.com/user-attachments/assets/25f389e8-3714-422a-9d48-1117f5ac4559)

Version: 128
![image](https://github.com/user-attachments/assets/d045be7e-dad9-44ce-9120-ad25bc677cd9)

Enabled tabAlignLeft in about:config
![image](https://github.com/user-attachments/assets/500a54b6-f3c8-4d7e-9843-6afce03f8f6c)

**Setup information**
 - OS: Fedora 41 Worksation
 - Installation method: Manual 
 - Firefox version: 128 ESR
 - Theme version: Git Branch v128
 - Optional features enabled: 
![image](https://github.com/user-attachments/assets/768c487a-1492-4ff7-a8a6-00f7ea53e842)

**Additional context**
Was just browsing and noticed this.

**Comment by rafaelmardojai** [comment]
That preference was introduced in the version 132 of the theme.

I probably should document that in the README I guess.

**Comment by klendite** [comment]
ah, is there anyway i can add that preference into the older versions?

**Comment by rafaelmardojai** [comment]
I guess you can try to copy the CSS.

This is how it looks the implementation in `master`, but should be harder to port because it's using nested CSS: 
https://github.com/rafaelmardojai/firefox-gnome-theme/blob/6cbc3b6eceb4195edab67daecc8daa7347c84c27/theme/parts/tabsbar.css#L179-L183

So you can try to copy the one from the `v132` tag:
https://github.com/rafaelmardojai/firefox-gnome-theme/blob/823756d8ddd21cfd3a24a87dad402e490e0eb5ee/theme/parts/tabsbar.css#L577-L583

**Comment by klendite** [comment]
Got it thank you, works great :>
