### ISSUE TITLE
Add support for PWAsForFirefox extension

### ISSUE THREAD

**Issue by pyhofficial** [rafaelmardojai/firefox-gnome-theme#887]
I'm a big fan of your Firefox GNOME theme and I've been using it for a while now. I've recently started using the PWAsForFirefox extension (https://github.com/filips123/PWAsForFirefox) to install Progressive Web Apps as regular Firefox extensions.

I'm wondering if it would be possible to add support for this extension to your theme. I think it would be a great addition, as it would allow users to have a more consistent look and feel across all their installed web apps.

I'm happy to help with testing or providing any additional information that would be helpful.

Thank you for your time and consideration.

**Comment by rafaelmardojai** [comment]
This is a duplicated of #547.

Thanks for the words! Sadly I'm not able to run the extension in my setup and I also lack the time.
