### ISSUE TITLE
Close, Minimise and Full screen button gone in Linux, and address bar displays incorrectly

### ISSUE THREAD

**Issue by Nekothegamer** [rafaelmardojai/firefox-gnome-theme#890]
The close, minimise and full screen buttons completely disappeared inside Linux (in Gnome btw) 
![image](https://github.com/user-attachments/assets/0cfaff18-1cac-4445-b2ee-77a9ddc2fa1d)
And the address bar displays incorrectly
![image](https://github.com/user-attachments/assets/2156c6f8-35b4-4fe2-a268-cde70efec461)

**Comment by rafaelmardojai** [comment]
Looks like a duplicated of #849. You probably need to update your theme.

Please next time use the issue template.

**Comment by Nekothegamer** [comment]
but how do i update my theme?

**Comment by rafaelmardojai** [comment]
It depends on how you installed it. You might need to run again the one command install with curl, or make a `git pull` in your Firefox profile, or let [Add Water](https://flathub.org/apps/dev.qwery.AddWater) automatically update it.
