### ISSUE TITLE
hide-single-tab is not respected in full screen

### ISSUE THREAD

**Issue by nahuelwexd** [rafaelmardojai/firefox-gnome-theme#9]
![Captura de pantalla de 2019-07-03 16-25-24](https://user-images.githubusercontent.com/18204745/60619492-35440a80-9daf-11e9-8a9c-b5b1e4bd1354.png)

but I enabled `hide-single-tab`  
![Captura de pantalla de 2019-07-03 16-26-16](https://user-images.githubusercontent.com/18204745/60619544-4c82f800-9daf-11e9-951c-1100e500ab3b.png)

**Comment by rafaelmardojai** [comment]
Because it will break toolbar auto hide.
Anyway i will investigate some workaround.

**Comment by rafaelmardojai** [comment]
Looks like this is not happening any more. Ready to fix.
