### ISSUE TITLE
Firefox 71+ popups theming broken

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/firefox-gnome-theme#91]

**Comment by weeman1337** [comment]
@rafaelmardojai is this issue the same for selects and the context menus? I'm unable to screenshot it because they close when taking the screenshot :/

**Comment by rafaelmardojai** [comment]
@weeman1337 I don't have theming issues with selects or the context menus. Try to take a screenshot with timer, that should work.

**Comment by Slomo17** [comment]
Same Problem here with the popup of menus, no Problem with contex menu though.
Attached screenshot of how it is supposed to look like, and how it looks like on my system.
![screenshot](https://user-images.githubusercontent.com/14056946/71097521-61faab80-21b0-11ea-91dc-67cfbca5b485.png)
![Screenshot from 2019-12-18 16-00-47](https://user-images.githubusercontent.com/14056946/71097525-63c46f00-21b0-11ea-9f52-f16f4fa7ab2d.png)

**Comment by rafaelmardojai** [comment]
Yeah, I haven't found a fix yet. That's the reason why is labeled as `help wanted`.

**Comment by Slomo17** [comment]
> Yeah, I haven't found a fix yet. That's the reason why is labeled as `help wanted`.

Unfortunately i am not a developer, so all i can do to help ist testing.

**Comment by rafaelmardojai** [comment]
Looks like, FF is using shadow DOM in popups, so no styles from `userChrome.css` will work in them.
(https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM)

**Comment by rafaelmardojai** [comment]
Please, test latest commits. Popups theming should be working as expected.

**Comment by Slomo17** [comment]
Looks great, thank you very much

**Comment by rafaelmardojai** [comment]
Fixed.
