### ISSUE TITLE
Get error when install

### ISSUE THREAD

**Issue by han190** [rafaelmardojai/firefox-gnome-theme#94]
Hi, this is what I get when I run `./scripts/install.sh`
```
./scripts/install.sh: line 26: cd: too many arguments
Error entering profile folder.
```
It probably relates to the if statement in the shell script.

**Comment by rafaelmardojai** [comment]
It can occur when you have multiple Firefox profiles folders matching `*.default*`.

You can fix this by defining your Firefox profile folder name found in `about:support` with the `-p` flag. For example: `./scripts/install.sh -p e0j6yb0p.default-nightly`

https://github.com/rafaelmardojai/firefox-gnome-theme#script-options

**Comment by han190** [comment]
@rafaelmardojai It works. Thanks!

**Comment by sevenfivesixnine** [comment]
Hey I have the exact same issue. I use this command :

`./scripts/install.sh -p qo66jf7b.default-nightly`

I've tried suggested solution but it still wont work. When I go to the `about:support` page I can see this :

/home/workstationtwo/.mozilla/firefox-trunk/qo66jf7b.default-nightly

Within the "Profile Directory" column.

I'm running the newest version of Firefox Nightly 72.0.

Do you have any idea why is this happening? I really like your work and would really like to use it for my Firefox Nightly.

**Comment by rafaelmardojai** [comment]
@sevenfivesixnine the script search profiles in `~/.mozilla/firefox/` by default, and looks like your profile lives in `~/.mozilla/firefox-trunk/`. You should also use the `-f` flag to define a custom firefox folder path.

`./scripts/install.sh -f ~/.mozilla/firefox-trunk/ -p qo66jf7b.default-nightly`

**Comment by sevenfivesixnine** [comment]
Worked like a charm. I actually thought about that but then did something else and totally forgot about it. I'm an idiot. Thanks!
