### ISSUE TITLE
How can I extend width of rouned icons on the top menu?

### ISSUE THREAD

**Issue by sevenfivesixnine** [rafaelmardojai/firefox-gnome-theme#96]
Hey. I would like to change the look of the rounded icons in the top menu. They are shaped to "square with rounded corners". I would like to extend width of the rounding to make it look like rectangle. Would it be possible? What do I need to do to accomplish this? Sorry but I'm not as good as you in this...

**Comment by rafaelmardojai** [comment]
All the buttons stuff is located in `/theme/parts/buttons.css`.

The main styling is defined here:
https://github.com/rafaelmardojai/firefox-gnome-theme/blob/f0b617a1bc901f2a7559b9f568cacd85e54e33be/theme/parts/buttons.css#L39-L51

To change the width you should modify this line:
https://github.com/rafaelmardojai/firefox-gnome-theme/blob/f0b617a1bc901f2a7559b9f568cacd85e54e33be/theme/parts/buttons.css#L49

I hope that helps you.

**Comment by sevenfivesixnine** [comment]
> All the buttons stuff is located in `/theme/parts/buttons.css`.
> 
> The main styling is defined here:
> 
> https://github.com/rafaelmardojai/firefox-gnome-theme/blob/f0b617a1bc901f2a7559b9f568cacd85e54e33be/theme/parts/buttons.css#L39-L51
> 
> To change the width you should modify this line:
> 
> https://github.com/rafaelmardojai/firefox-gnome-theme/blob/f0b617a1bc901f2a7559b9f568cacd85e54e33be/theme/parts/buttons.css#L49
> 
> I hope that helps you.

**Comment by sevenfivesixnine** [comment]
Hey, thanks for wasting your time with me! It works exactly as I wanted. Good luck with future projects!
