### ISSUE TITLE
Closing Button Hover Shape

### ISSUE THREAD

**Issue by fweth** [rafaelmardojai/firefox-gnome-theme#98]
The shape around the window closing button, which becomes visible when hovering, changed in some recent GNOME version (I think 3.34) from round cornered square to circle, but it's still round cornered square in this theme.

**Comment by rafaelmardojai** [comment]
Right now you need to enable the `rounded-title-buttons.css` optional feature: https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features

**Comment by rafaelmardojai** [comment]
Duplicate of #77

**Comment by fweth** [comment]
Sorry for not having done my own research and thanks for the quick reaction!
